### ISSUE TITLE
Rename tag Exif.Canon.AFPrimaryPoint

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1001]
#981 adds recognition for Canon AutoFocus Metadata.  The tag "Exif.Canon.AFPrimaryPoint" records points that should be ignored by the AutoFocus.

The name AFPrimaryPoint was chosen to align with ExifTool Documentation.  https://sno.phy.queensu.ca/~phil/exiftool/TagNames/Canon.html

Suggestions (from @derselbst) for alternative names are "AFPointsDisabled" and "AFPointsUnusable"  If we agree on a change of tag name, this will be released in Exiv2 v0.27.4.  I don't want to delay Exiv2 v0.27.3 while this is discussed.

@boardhead Can you give us your opinion about this, please?

Here are Tom's notes about Canon AutoFocus Metadata.  https://github.com/Exiv2/exiv2/issues/981#issuecomment-524564157

**Comment by boardhead** [comment]
I don't understand where you are coming from.  ExifTool doesn't report a primary AF point for any of the sample images I could find in the referenced thread.

**Comment by clanmills** [comment]
Oh!  I wonder how I managed to make that up.

@derselbst Please propose your name change and I'll submit the PR.

**Comment by derselbst** [comment]
Ok, then I would propose to use `AFPointsUnusable`. From the repository root dir, this should do:

```bash
> find . -type f -exec sed -i 's/AFPrimaryPoint/AFPointsUnusable/g' {} +
> find . -type f -exec sed -i 's/AF\ Primary\ Point/Unusable\ AF\ Points/g' {} +
```

**Comment by clanmills** [comment]
Thanks.  I probably have to update something in the test suite.

I'll deal with this in the next few days when I escape from #1008.

**Comment by clanmills** [comment]
Submitted: #1010

**Comment by clanmills** [comment]
This has been dealt with and is already in the 0.27-maintenace branch.  No further action necessary.
