### ISSUE TITLE
Team Activity Tracking Tools

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#101]
Luis mentioned a "scrum board" tool.  Sure why not.

Before we moved to GitHub (at the end of April), I tracked everything in Redmine.  I have a python script (svn://dev.exiv2.org/svn/team/contrib/redmine/progress.py) to compute various metrics. http://dev.exiv2.org/news/2

We're now living in the world of GitHub and perhaps we should make Redmine read-only and start moving away from that.  For that matter, I also wonder if we should be shut down exiv2.org in 2018.

Suggestions welcome.

**Comment by piponazo** [comment]
I did not put too much attention in the existing things in redmine, but I would vote for centralise as much as possible the work on GitHub. If we are doing here the main development, people will create issues here and we should try to make here visible most of the information. 

For example, we can handle different projects, milestones and issues in GitHub. We also have now some sort of Continuous Integration with Travis-CI and AppVeyor. More things will come related to CI (run unit tests automatically, coverage tools, static analyzers, etc).

Let's see what is the opinion of other active collaborators ;)

**Comment by D4N** [comment]
I don't think exiv2.org should be shut down, it is a good thing to have a separate website where the source & documentation can be hosted. Also I think Github issues are not a good replacement for the forum.

I think we should use the tools GitHub gives us but not overly rely on it. Imho the CI should be still done by Jenkins as Travis & AppVeyor cannot build on all platforms that we support.

For the communication I'd actually prefer the good-ol' mailing list (I find it to be more of a persistent medium than a chat like slack and far better suited for a discussion).

**Comment by piponazo** [comment]
Let's close this issue then. We can discuss more about this in the team meeting if you want.

**Comment by clanmills** [comment]
I've put this "on the list" for discussion in England.  http://dev.exiv2.org/news/3
