### ISSUE TITLE
Two Nikon lenses still not detected

### ISSUE THREAD

**Issue by Jakuje** [Exiv2/exiv2#1014]
**Describe the bug**
I have some pictures using two lenses I had some years back and they seems to be still missing from the exiv2. I used the following `.exiv2`:
```
[nikon]
164=AF-S Nikkor 70-200mm f/2.8E FL ED VR
170=AF-S Nikkor 24-70mm f/2.8E ED VR
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Run exiv2 on the existing photos 
2. Lenses are not detected

The metadata from pictures:
```
$ exiv2 -pv --grep Lens DSC_0003.JPG
0x0083 Nikon3       LensType                    Byte        1  78
0x0084 Nikon3       Lens                        Rational    4  240/10 700/10 28/10 28/10
0x008b Nikon3       LensFStops                  Undefined   4  72 1 12 0
0x000c NikonLd3     LensIDNumber                Byte        1  170
0x000d NikonLd3     LensFStops                  Byte        1  72
```
and
```
$ exiv2 -pv --grep Lens DSC_0170.NEF
0x0083 Nikon3       LensType                    Byte        1  78
0x0084 Nikon3       Lens                        Rational    4  240/10 700/10 28/10 28/10
0x008b Nikon3       LensFStops                  Undefined   4  72 1 12 0
0x000c NikonLd3     LensIDNumber                Byte        1  170
0x000d NikonLd3     LensFStops                  Byte        1  72
```

**Expected behavior**
The lens should be detected.

**Desktop (please complete the following information):**
 - OS: Linux
 - Compiler & Version [Gcc 7.3, Clang-6, MSVC 2017]
 - Compilation mode and/or compiler flags

**Additional context**
I would be able to contribute the code, but it is not particularly clear to me how and what all values I am supposed to use in the `src/nikonmn_int.cpp` to get the correct behavior. So either point me how I should do or feel free to add the data. I can also provide images if necessary.

**Comment by clanmills** [comment]
Thanks for reporting this.  A couple of questions:

1) Have you added the lens definitions to ~/.exiv2?
2) Can you attach sample images, please.

The code in nikonmn_int.cpp was "bought it" from elsewhere (and credit given in the code).  I have occasionally added other lenses to that table.

However, can you answer my questions before we get into the details about to add a lens "permanently" (without using ~/.exiv2).  How to achieve that was discussed a few months ago and I'll hunt down that conversation for your information.

**Comment by Jakuje** [comment]
The first one is here:
[DSC_0003](https://user-images.githubusercontent.com/2694489/65994756-63131b00-e494-11e9-8358-f2dfe999f7cd.JPG)
The second example is NEF (not supported by github) so I uploaded it here:
https://jakuje.dta3.com/files/DSC_0161.NEF
I actually added the attached definitions in the `~/.exiv2` just today, but it did not seem to do the trick for the darktable (but I assume it might have this information cached in the sidecar files -- I did not investigate a lot).

If there is a better way to add the new lens, just let me know.

**Comment by clanmills** [comment]
Right.  The ~/.exiv2 code's working fine:
```
794 rmills@rmillsmbp:~/Downloads $ cat ~/.exiv2 
[nikon]
164=AF-S Nikkor 70-200mm f/2.8E FL ED VR
170=AF-S Nikkor 24-70mm f/2.8E ED VR
795 rmills@rmillsmbp:~/Downloads $ exiv2 -pa --grep lens/i 65994756-63131b00-e494-11e9-8358-f2dfe999f7cd.JPG 
Exif.Nikon3.LensType                         Byte        1  D G VR
Exif.Nikon3.Lens                             Rational    4  24-70mm F2.8
Exif.Nikon3.LensFStops                       Undefined   4  6
Exif.NikonLd3.LensIDNumber                   Byte        1  AF-S Nikkor 24-70mm f/2.8E ED VR
Exif.NikonLd3.LensFStops                     Byte        1  F6.0
796 rmills@rmillsmbp:~/Downloads $ exiv2 -pa --grep lens/i DSC_0161.NEF 
Exif.Nikon3.LensType                         Byte        1  D G VR
Exif.Nikon3.Lens                             Rational    4  70-200mm F2.8
Exif.Nikon3.LensFStops                       Undefined   4  6
Exif.NikonLd3.LensIDNumber                   Byte        1  AF-S Nikkor 70-200mm f/2.8E FL ED VR
Exif.NikonLd3.LensFStops                     Byte        1  F6.0
797 rmills@rmillsmbp:~/Downloads $ 
```

Why's it not working with darktable?  Perhaps you're using a version of darktable that uses an elderly version of the exiv2 library.  The ~/.exiv2 feature was added in Exiv2 v0.26 which as released in April 2017.  Use the utility `lsof` in Linux to see which library darktable has loaded.   I think you can use something like `$ lsof | grep -i darktable | grep -i exiv2` to see what's going on.

If darktable's using an elderly exiv2 (exiv2 v0.25 or earlier), you have two choices:

1) (Recommended) Upgrade darktable to a version that uses Exiv2 v0.26 or later.
2) (Not recommended) Get the exiv2 code being used (v0.25 or whatever), add your lens into src/nikonmn_int.cpp, build exiv2 and replace the exiv2 library (probably in /usr/local/lib).

In the 0.27.2 code in src/nikonmn_int.cpp, you'll see the entries:
```
// https://github.com/Exiv2/exiv2/issues/743
{0xc9,0x48,0x37,0x5c,0x24,0x24,0x4b,0x4e,0x01,0x00,0x00, "Sigma", "", "24-70mm F2,8 DG OS HSM Art"},
//
//  https://github.com/Exiv2/exiv2/issues/598 , https://github.com/Exiv2/exiv2/pull/891
{0xCF,0x47,0x5C,0x8E,0x31,0x3D,0xDF,0x0E,0x00,0x00,0x00, "Tamron", "A030", "SP 70-300mm F/4-5.6 Di VC USD"},
//
{0xf4,0x4c,0x7c,0x7c,0x2c,0x2c,0x4b,0x02,0x00,0x00,0x00, "Sigma", "", "APO MACRO 180mm F3.5 EX DG"},
```

You can find the discussions about those lenses and have a read.  We can talk further if you're still interested in adding your lens.

Adding the lens definition to ensure it's recognised without using ~/.exiv2 is an interesting project.  I'll be happy to help you to achieve that goal.

If darktable is using an elderly version of Exiv2 (such as v0.25), you'll be better to wait for a newer darktable.  When you start messing with installed shared objects you may inflict damage on other applications on your machine.

**Comment by Jakuje** [comment]
It looks like the Ubuntu (latest stable) is using the old exiv2 so I will have to wait some time (probably forever) before they will update:
```
$ exiv2 -V
exiv2 0.25 001900 (64 bit build)
```
Anyway, with the help of #743 I was able to put the lines together and build newer version, but it does not look like working for me on neither of the images. Do you see there some obvious issue in the following lines?

```
{0xA4,0x48,0x5C,0x80,0x24,0x24,0xCF,0x4E,0x01,0x00,0x00, "Nikon", "", "AF-S Nikkor 70-200mm f/2.8E FL ED VR"},
{0xAA,0x48,0x37,0x5C,0x24,0x24,0xC5,0x4E,0x01,0x00,0x00, "Nikon", "", "AF-S Nikkor 24-70mm f/2.8E ED VR"},
```
Here is the output of the required fields:
```
$ ./bin/exiv2 -pv --grep focal/i --grep lens/i --grep mcu/i DSC_0161.NEF"
0x920a Photo        FocalLength                 Rational    1  2000/10
0x0083 Nikon3       LensType                    Byte        1  78
0x0084 Nikon3       Lens                        Rational    4  700/10 2000/10 28/10 28/10
0x008b Nikon3       LensFStops                  Undefined   4  72 1 12 0
0x000b NikonLd3     FocalLength                 Byte        1  128
0x000c NikonLd3     LensIDNumber                Byte        1  164
0x000d NikonLd3     LensFStops                  Byte        1  72
0x000e NikonLd3     MinFocalLength              Byte        1  92
0x000f NikonLd3     MaxFocalLength              Byte        1  128
0x0010 NikonLd3     MaxApertureAtMinFocal       Byte        1  36
0x0011 NikonLd3     MaxApertureAtMaxFocal       Byte        1  36
0x0012 NikonLd3     MCUVersion                  Byte        1  207
0xa405 Photo        FocalLengthIn35mmFilm       Short       1  200
$ ./bin/exiv2 -pv --grep focal/i --grep lens/i --grep mcu/i DSC_0170.NEF
0x920a Photo        FocalLength                 Rational    1  700/10
0x0083 Nikon3       LensType                    Byte        1  78
0x0084 Nikon3       Lens                        Rational    4  240/10 700/10 28/10 28/10
0x008b Nikon3       LensFStops                  Undefined   4  72 1 12 0
0x000b NikonLd3     FocalLength                 Byte        1  92
0x000c NikonLd3     LensIDNumber                Byte        1  170
0x000d NikonLd3     LensFStops                  Byte        1  72
0x000e NikonLd3     MinFocalLength              Byte        1  55
0x000f NikonLd3     MaxFocalLength              Byte        1  92
0x0010 NikonLd3     MaxApertureAtMinFocal       Byte        1  36
0x0011 NikonLd3     MaxApertureAtMaxFocal       Byte        1  36
0x0012 NikonLd3     MCUVersion                  Byte        1  197
0xa405 Photo        FocalLengthIn35mmFilm       Short       1  70
```

**Comment by clanmills** [comment]
Ubuntu isn't keeping up very well with Exiv2 releases.  I will not criticise.  They have a wide spectrum of concerns on their platform.  Exiv2 has 100k lines of code.  They have 1000x more worries!

Thanks for your code snippet.  Is this something you're building/testing on current code?  For sure we're "on the same page".  There are about 11 fields to align to make this work.  I'll investigate your code tomorrow on our 0.27-maintenance branch with your test files.

I could also suggest that you adopt another Linux distribution.  However, I personally use Ubuntu, so I can't suggest an alternative.  I develop Exiv2 on MacOS-X and use Windows-10 and Ubuntu as necessary.  The Exiv2 CI/buildservers work on many platforms.

**Comment by Jakuje** [comment]
Yes, I tested with local build of `exiv2` on `master` branch with `cmake ./ && make` after the local modifications.

**Comment by clanmills** [comment]
Can you send me your code, please, as that gets me into sync with you.

For reasons which have nothing to do with this issue, I have decided to retire.  This is the final issue on which I will ever work for Exiv2.  When I get this fixed for you, you'll have to raise an issue to have it included in the code base.  I'm done after 12 years and 15,000 hours of effort.

**Comment by clanmills** [comment]
I've changed my mind.  I'm not willing to do any further work on anything concerning Exiv2.  You'll have to debug and fix this on your own.

**Comment by clanmills** [comment]
I've looked at this.  The lens is recognised by an earlier entry in the table.  I've modified the lens name by adding AAA, BBB, CCC, DDD to make it obvious that it has been selected.

```
872 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ bin/exiv2 -pa --grep lens/i ~/Downloads/65994756-63131b00-e494-11e9-8358-f2dfe999f7cd.JPG 
Exif.Nikon3.LensType                         Byte        1  D G VR
Exif.Nikon3.Lens                             Rational    4  24-70mm F2.8
Exif.Nikon3.LensFStops                       Undefined   4  6
Exif.NikonLd3.LensIDNumber                   Byte        1  Nikon CCC AF-S Nikkor 24-70mm f/2.8E ED VR
Exif.NikonLd3.LensFStops                     Byte        1  F6.0
873 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ bin/exiv2 -pa --grep lens/i ~/Downloads/DSC_0161.NEF 
Exif.Nikon3.LensType                         Byte        1  D G VR
Exif.Nikon3.Lens                             Rational    4  70-200mm F2.8
Exif.Nikon3.LensFStops                       Undefined   4  6
Exif.NikonLd3.LensIDNumber                   Byte        1  Nikon AAA AF-S Nikkor 70-200mm f/2.8E FL ED VR
Exif.NikonLd3.LensFStops                     Byte        1  F6.0
874 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

I've run the test suite with this change, and everything passes and I'm pleased to say it works.  So, I recommend simply changing the records to match your lens.

I'm getting old.  I haven't spotted the change you are requesting.  The current output the 0.27-maintenance branch looks fine:

```
170 = 0xAA 65994756-63131b00-e494-11e9-8358-f2dfe999f7cd.JPG
We have "AF-S Nikkor 24-70mm f/2.8E ED VR"
You're requesting "AF-S Nikkor 24-70mm f/2.8E ED VR"
```
What's the difference?

```
164 = 0xA4 DSC_0161.NEF
We have "AF-S Nikkor 70-200mm f/2.8E FL ED VR"
You're requesting "AF-S Nikkor 70-200mm f/2.8E FL ED VR"
```
What's the difference?

Here's my local change for debugging purposes.  When you know exactly what you'd like changed, please update this issue.  The best approach is to submit a PR with appropriate changes to the test suite.

I have retired.  Later today I'll submit code changes to the release/web-site and I'm done with Exiv2.

```
871 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ git diff
diff --git a/src/nikonmn_int.cpp b/src/nikonmn_int.cpp
index 0d212fb8..86be7da2 100644
--- a/src/nikonmn_int.cpp
+++ b/src/nikonmn_int.cpp
@@ -2092,8 +2092,8 @@ fmountlens[] = {
 {0xA8,0x48,0x8E,0x8E,0x30,0x30,0xC3,0x4E,0x01,0x00,0x01, "Nikon", "JAA342DA", "AF-S Nikkor 300mm f/4E PF ED VR"},
 {0xA8,0x48,0x8E,0x8E,0x30,0x30,0xC3,0x0E,0x01,0x00,0x01, "Nikon", "JAA342DA", "AF-S Nikkor 300mm f/4E PF ED VR"},
 {0xA9,0x4C,0x31,0x31,0x14,0x14,0xC4,0x06,0x01,0x00,0x01, "Nikon", "JAA138DA", "AF-S Nikkor 20mm f/1.8G ED"},
-{0xAA,0x48,0x37,0x5C,0x24,0x24,0xC5,0x4E,0x01,0x00,0x02, "Nikon", "JAA824DA", "AF-S Nikkor 24-70mm f/2.8E ED VR"},
-{0xAA,0x48,0x37,0x5C,0x24,0x24,0xC5,0x0E,0x01,0x00,0x02, "Nikon", "JAA824DA", "AF-S Nikkor 24-70mm f/2.8E ED VR"},
+{0xAA,0x48,0x37,0x5C,0x24,0x24,0xC5,0x4E,0x01,0x00,0x02, "Nikon", "JAA824DA", "CCC AF-S Nikkor 24-70mm f/2.8E ED VR"},
+{0xAA,0x48,0x37,0x5C,0x24,0x24,0xC5,0x0E,0x01,0x00,0x02, "Nikon", "JAA824DA", "DDD AF-S Nikkor 24-70mm f/2.8E ED VR"},
 {0xAB,0x3C,0xA0,0xA0,0x30,0x30,0xC6,0x4E,0x01,0x00,0x02, "Nikon", "JAA533DA", "AF-S Nikkor 500mm f/4E FL ED VR"},
 {0xAC,0x3C,0xA6,0xA6,0x30,0x30,0xC7,0x4E,0x01,0x00,0x02, "Nikon", "JAA534DA", "AF-S Nikkor 600mm f/4E FL ED VR"},
 {0xAD,0x48,0x28,0x60,0x24,0x30,0xC8,0x4E,0x01,0x00,0x02, "Nikon", "JAA825DA", "AF-S DX Nikkor 16-80mm f/2.8-4E ED VR"},
@@ -2106,8 +2106,8 @@ fmountlens[] = {
 {0xAF,0x4C,0x37,0x37,0x14,0x14,0xCC,0x06,0x01,0x00,0x03, "Nikon", "JAA139DA", "AF-S Nikkor 24mm f/1.8G ED"},
 {0xA3,0x38,0x5C,0x8E,0x34,0x40,0xCE,0x8E,0x01,0x00,0x03, "Nikon", "JAA829DA", "AF-P DX Nikkor 70-300mm f/4.5-6.3G ED VR"},
 {0xA3,0x38,0x5C,0x8E,0x34,0x40,0xCE,0x0E,0x01,0x00,0x03, "Nikon", "JAA828DA", "AF-P DX Nikkor 70-300mm f/4.5-6.3G ED"},
-{0xA4,0x48,0x5C,0x80,0x24,0x24,0xCF,0x4E,0x01,0x00,0x03, "Nikon", "JAA830DA", "AF-S Nikkor 70-200mm f/2.8E FL ED VR"},
-{0xA4,0x48,0x5C,0x80,0x24,0x24,0xCF,0x0E,0x01,0x00,0x03, "Nikon", "JAA830DA", "AF-S Nikkor 70-200mm f/2.8E FL ED VR"},
+{0xA4,0x48,0x5C,0x80,0x24,0x24,0xCF,0x4E,0x01,0x00,0x03, "Nikon", "JAA830DA", "AAA AF-S Nikkor 70-200mm f/2.8E FL ED VR"},
+{0xA4,0x48,0x5C,0x80,0x24,0x24,0xCF,0x0E,0x01,0x00,0x03, "Nikon", "JAA830DA", "BBB AF-S Nikkor 70-200mm f/2.8E FL ED VR"},
 {0xA5,0x54,0x6A,0x6A,0x0C,0x0C,0xD0,0x46,0x01,0x00,0x03, "Nikon", "JAA343DA", "AF-S Nikkor 105mm f/1.4E ED"},
 {0xA5,0x54,0x6A,0x6A,0x0C,0x0C,0xD0,0x06,0x01,0x00,0x03, "Nikon", "JAA343DA", "AF-S Nikkor 105mm f/1.4E ED"},
 {0xA6,0x48,0x2F,0x2F,0x30,0x30,0xD1,0x46,0x01,0x00,0x03, "Nikon", "JAA639DA", "PC Nikkor 19mm f/4E ED"},
872 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

**Comment by D4N** [comment]
Anyone who wishes to work on this: 
- take the patch from https://github.com/Exiv2/exiv2/issues/1014#issuecomment-538257876
- commit it and check what the testsuite does
- optionally: add a test for this using the files provided by @Jakuje in https://github.com/Exiv2/exiv2/issues/1014#issuecomment-537198975, strip them via `exiv2 ex $file` and create a regression test like the one in `tests/bugfixes/github/test_pr_992.py`.
