### ISSUE TITLE
Define a security process

### ISSUE THREAD

**Issue by D4N** [Exiv2/exiv2#1035]
_Originally posted by @cryptomilk in https://github.com/Exiv2/exiv2/issues/1018#issuecomment-539850488_

For fuzzing and also security related fixes it is important to have the process documented. You can use: https://www.libssh.org/development/security-process/

Write down which versions you support and communicate that. Example: https://wiki.samba.org/index.php/Samba_Release_Planning

This way you can always point people to your processes. The smaller the team the less versions you should have in maintenance mode.

I hope that helps.

**Comment by cryptomilk** [comment]
Also get CVEs through the Red Hat Security team, they also assist if something is considered a security issue or not.

**Comment by clanmills** [comment]
Done:  #1122.
