### ISSUE TITLE
Do you want to contribute?

### ISSUE THREAD

**Issue by D4N** [Exiv2/exiv2#1038]
Are you interested in contributing but don't know where to start? Ask here, in `#exiv2-chat` on matrix.org or on the discussion mailing list: https://lists.sr.ht/~d4n/exiv2-discussion.

Is the documentation about contributions lacking? Are you missing information? Please create new issues for that, so that we can fix them.

**Comment by clanmills** [comment]
I'm going to close this to reduce the number of open issues.  Very pleased to say after the dark days of mid-2020, there has been a wonderful increase in the number of contributors.    The following are acknowledged in the release notes for v0.27.4:

| Contributor  | Activity                                          |
|:--           |:--                                                |
| Alex         | Project Management                                |
| Arnold       | Keeps me honest!                                  |
| Christoph    | Nikon and Canon Support                           |
| David        | Help with legal investigation concerning bmff     |
| Freddie      | Fuji support                                      |
| Kevin        | Security fixes                                    |
| Leo          | New python test scripts                           |
| Leonardo     | Crowdin Localisation Support                      |
| Milo&scaron; | DNG, Exif 2.32, easyaccess support                |
| Peter K      | bmff code                                         |
| Peter S      | langAltValue.read() fix and helpful issue reports |
| pydera       | Security Fixes                                    |
