### ISSUE TITLE
Write some property, written to fail

### ISSUE THREAD

**Issue by night9951** [Exiv2/exiv2#1056]
write fail code

exifData["Exif.Image.XPAuthor"] = "SAHARA";
exifData["Exif.Image.XPTitle"] = " sssssssssssssss";
exifData["Exif.Image.XPComment"] = "dddddddddddddd";
exifData["Exif.Image.XPSubject"] = "fffffffffffffff";

write success code

exifData["Exif.Image.Model"] = "Test 1";      // AsciiValue
exifData["Exif.Image.Make"] =  "conan"  ;    // AsciiValue
exifData["Exif.Photo.UserComment"]= "charset=Ascii ssssssssss";

**Comment by clanmills** [comment]
I updated this issue yesterday.  How odd, my reply as disappeared!

These XP tags expect pairs of Bytes, not an ascii string:
```
$ taglist | grep XP
XPTitle,	40091,	0x9c9b,	Image,	Exif.Image.XPTitle,	Byte,	Title tag used by Windows, encoded in UCS2
XPComment,	40092,	0x9c9c,	Image,	Exif.Image.XPComment,	Byte,	Comment tag used by Windows, encoded in UCS2
XPAuthor,	40093,	0x9c9d,	Image,	Exif.Image.XPAuthor,	Byte,	Author tag used by Windows, encoded in UCS2
XPKeywords,	40094,	0x9c9e,	Image,	Exif.Image.XPKeywords,	Byte,	Keywords tag used by Windows, encoded in UCS2
XPSubject,	40095,	0x9c9f,	Image,	Exif.Image.XPSubject,	Byte,	Subject tag used by Windows, encoded in UCS2
```

From the command line:

```
$ exiv2 -M'set Exif.Image.XPAuthor 49 00 50 00' Stonehenge.jpg ; bin/exiv2 -pa --grep XP Stonehenge.jpg
Exif.NikonAf2.AFAreaXPosition                Short       1  0
Exif.Image.XPAuthor                          Byte        4  12
$ 
```
