### ISSUE TITLE
Replace deprecated SHGetFolderPathA

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#1060]
In #1059 we added a missing windows dependency on `shell32` due to the usage of the windows function `SHGetFolderPathA()`. 

According to this documentation, the function is deprecated and it should be replaced with a new mechanism.

https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetfolderpatha

**Comment by janisozaur** [comment]
I don't know what's your stance on XP support, but the non-deprecated version is only available since Vista.

**Comment by piponazo** [comment]
We try to support as many platforms as possible, although I would say XP or Vista are not relevant cases for Exiv2. 

Honestly, I have little experience playing with the windows API. Should not we upgrade that code to something like this to obtain the %HOME% dir?
https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath

**Comment by janisozaur** [comment]
I suppose there's no need, unless you actually need to use the new functionality? The docs read:

> As of Windows Vista, this function is merely a wrapper for SHGetKnownFolderPath

For UWP, if you want to support it, you can't use files in such way anyway, so you will have to compile it out and rely on the library consumer passing the data to you or implementing the UWP-way, which is bonkers, to say the least.

**Comment by tbeu** [comment]
Can do.

**Comment by clanmills** [comment]
We only use this in one place:

```bash
662 rmills@rmillsm1:~/gnu/github/exiv2/main $ find . -name "*pp" | xargs grep -i SHGetFolderPath
./src/makernote_int.cpp:            if (SUCCEEDED(SHGetFolderPathA(NULL, CSIDL_PROFILE, NULL, 0, path))) {
663 rmills@rmillsm1:~/gnu/github/exiv2/main $ 
```

It's used to locate the Config file (~/.exiv2 on Cygwin/Linux and %USERPROFILE%\exiv2.ini with MSVC/MinGW).

```cpp
        std::string getExiv2ConfigPath()
        {
            std::string homedir;
            std::string inifile;
#if defined(_MSC_VER) || defined(__MINGW__)
            char path[MAX_PATH];
            if (SUCCEEDED(SHGetFolderPathA(NULL, CSIDL_PROFILE, NULL, 0, path))) {
                homedir = std::string(path);
                inifile = "exiv2.ini"      ;
            }
#else
            struct passwd* pw = getpwuid(getuid());
            homedir = std::string(pw?pw->pw_dir:"");
            inifile = std::string(".exiv2");
#endif
            return homedir + EXV_SEPARATOR_CHR + inifile;
        }
```

My Windows skills are very rusty having had little use exercise in the last 10 years.  Looking at https://docs.microsoft.com/en-us/cpp/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app?view=msvc-160 the following flags could be probably be used:

```cpp
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_PC_APP)
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_PHONE_APP)
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
```

If it's not PC_APP or DESKTOP, we could return "\\".  Any path that is not a file will meet our purposes.

**Comment by neheb** [comment]
Fixed with https://github.com/Exiv2/exiv2/commit/3b15b6f9fb853c32c0553186b04f1609e04a7d97
