### ISSUE TITLE
UWP builds not possible due to use of forbidden APIs

### ISSUE THREAD

**Issue by janisozaur** [Exiv2/exiv2#1063]
I tried building UWP version and compilation works fine, but it's impossible to link the library due to use of forbidden APIs:
```
src\basicio.cpp(332,33): error C2039: 'GetModuleHandleA': is not a member of '`global namespace'' 
src\basicio.cpp(332,49): error C3861: 'GetModuleHandleA': identifier not found 
src\basicio.cpp(496,21): error C3861: 'CreateFileMapping': identifier not found 
src\basicio.cpp(508,20): error C3861: 'MapViewOfFile': identifier not found 
src\basicio.cpp(773,37): error C2039: 'GetModuleHandleA': is not a member of '`global namespace'' 
src\basicio.cpp(773,53): error C3861: 'GetModuleHandleA': identifier not found 
src\futils.cpp(479,31): error C2679: binary '=': no operator found which takes a right-hand operand of type 'TCHAR [260]' (or there is no acceptable conversion)
src\version.cpp(171,10): error C3861: 'EnumProcessModules': identifier not found
loadlibrary.obj : error LNK2019: unresolved external symbol GetModuleHandle referenced in function _Expat_LoadLibrary
loadlibrary.obj : error LNK2019: unresolved external symbol LoadLibrary referenced in function _Expat_LoadLibrary
```

UWP restricts access to some APIs in name of portability.

Naïve approach could be providing empty implementations for some of those, e.g.:
```diff
diff --git a/src/makernote_int.cpp b/src/makernote_int.cpp
index 20cd7629..043daabc 100644
--- a/src/makernote_int.cpp
+++ b/src/makernote_int.cpp
@@ -95,12 +95,15 @@ namespace Exiv2 {
         {
             std::string homedir;
             std::string inifile;
-#if defined(_MSC_VER) || defined(__MINGW__)
+#if (defined(_MSC_VER) || defined(__MINGW__))
+    // In UWP you can't access files directly. Just skip the config.
+    #if !(defined(WINAPI_FAMILY) && (WINAPI_FAMILY != WINAPI_FAMILY_DESKTOP_APP))
             char path[MAX_PATH];
             if (SUCCEEDED(SHGetFolderPathA(NULL, CSIDL_PROFILE, NULL, 0, path))) {
                 homedir = std::string(path);
                 inifile = "exiv2.ini"      ;
             }
+    #endif
 #else
             struct passwd* pw = getpwuid(getuid());
             homedir = std::string(pw?pw->pw_dir:"");
```

Proper implementation of file access in UWP is… odd. https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-reading-and-writing-files

I don't fully understand why exiv2 implements things like `mmap` (`CreateFileMapping`), dynamic loading of `kernel32.dll` in an unused function: https://github.com/Exiv2/exiv2/blob/7a652acedb77505c5708aec58d6c3c61101eee4a/src/basicio.cpp#L335 and others, so I will leave addressing this to someone else.

**Comment by janisozaur** [comment]
Didn't really mean to label this as a bug

**Comment by piponazo** [comment]
I just assigned a new label to the issue "Windows" which will be used for windows specific issues. 

Could you please leave some details or reference about how to build the project for UWP? Do you know if it would possible to enable that mode via CMake ?

**Comment by janisozaur** [comment]
You can do a cmake UWP build through vcpkg.

**Comment by clanmills** [comment]
I'm going to close this for two reasons:

1. There is a work-around.
2. This issue is rather elderly and nobody else has expressed concern.
