### ISSUE TITLE
Add lens Tamron SP 35mm f/1.4 Di USD (Canon)

### ISSUE THREAD

**Issue by PavelLinux** [Exiv2/exiv2#1064]
$ exiv2 -pt IMG_3493.JPG | grep -ai lens
Exif.CanonCs.LensType                        Short       1  (117)
Exif.CanonCs.Lens                            Short       3  35.0 mm
Exif.Canon.LensModel                         Ascii      74  TAMRON SP 35mm F/1.4 Di USD F045
Exif.Photo.LensSpecification                 Rational    4  35/1 35/1 0/1 0/1
Exif.Photo.LensModel                         Ascii      33  TAMRON SP 35mm F/1.4 Di USD F045
Exif.Photo.LensSerialNumber                  Ascii      11  0000000000

![IMG_3493](https://user-images.githubusercontent.com/57952645/69157168-27511500-0b17-11ea-8874-e8cf45ff033e.JPG)

**Comment by D4N** [comment]
Same question as in #1072: what do you expect exiv2 to parse from that image?

**Comment by PavelLinux** [comment]
Add to project. I made local fix.

[canon]
117=Tamron SP 35mm f/1.4 Di USD
750=Tamron SP 85mm f/1.8 Di VC USD
0=Samyang 14mm f/2.8 ED AS IF UMC

**Comment by D4N** [comment]
> [canon]
> 117=Tamron SP 35mm f/1.4 Di USD
> 750=Tamron SP 85mm f/1.8 Di VC USD
> 0=Samyang 14mm f/2.8 ED AS IF UMC

Is that what you put into your `~/.exiv2` file?

**Comment by PavelLinux** [comment]
Yes.

**Comment by clanmills** [comment]
@PavelLinux Are we done with this and #1069 ?

Lens recognition is very troublesome because the same LensID is frequently used by several lenses.  So, the `~/.exiv2` file was added in Exiv2 v0.26 to enable the user to overwrite the built-in lens names.

**Comment by clanmills** [comment]
No reply from @PavelLinux

A work around has been provided.
