### ISSUE TITLE
Add lens Tamron SP 35mm f/1.4 Di USD (Nikon)

### ISSUE THREAD

**Issue by PavelLinux** [Exiv2/exiv2#1069]
I don't have camera Nikon. I found a jpeg from Nikon on the web.
$ exiv2 -pt DSC_0495.JPG | grep -ai lens
Exif.Nikon3.LensType                         Byte        1  D G 
Exif.Nikon3.Lens                             Rational    4  35mm F1.4
Exif.Nikon3.LensFStops                       Undefined   4  7
Exif.NikonLd3.LensIDNumber                   Byte        1  200
Exif.NikonLd3.LensFStops                     Byte        1  F7.0

![DSC_0495 JPG](https://user-images.githubusercontent.com/57952645/69504028-26bee100-0f52-11ea-9446-bbb3d5823f37.jpg)

**Comment by clanmills** [comment]
Without test images, this fix will not be submitted to the code base.  A work around has been provided.
