### ISSUE TITLE
Add lens Tamron SP 85mm F/1.8 Di VC USD (Canon)

### ISSUE THREAD

**Issue by PavelLinux** [Exiv2/exiv2#1072]
Please fix conflict and add lens.

$ exiv2 -pt IMG_4600.JPG | grep -ai lens
Exif.CanonCs.LensType                        Short       1  Canon EF 35mm f/1.4L II USM
Exif.CanonCs.Lens                            Short       3  85.0 mm
Exif.Canon.LensModel                         Ascii      74  TAMRON SP 85mm F/1.8 Di VC USD F016
Exif.Photo.LensSpecification                 Rational    4  85/1 85/1 0/1 0/1
Exif.Photo.LensModel                         Ascii      36  TAMRON SP 85mm F/1.8 Di VC USD F016
Exif.Photo.LensSerialNumber                  Ascii      11  0000000000

![IMG_4600](https://user-images.githubusercontent.com/57952645/70375567-b771c580-1931-11ea-92a1-bdb1ee214959.JPG)

**Comment by D4N** [comment]
Would you mind telling us what you expect exiv2 to output?

**Comment by PavelLinux** [comment]
Add to project. I made local fix.

**Comment by D4N** [comment]
> I made local fix.

Would you share the local fix? Or provide us with more information? I see that you have pasted some exiv2 output in the issue description: is that the desired output, or the current output?

**Comment by PavelLinux** [comment]
In #1064

**Comment by clanmills** [comment]
No reply from @PavelLinux

A work around has been provided.
