### ISSUE TITLE
Reconsider taglist testing strategy

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#1075]
In #1015 we decided to remove from master a test which was added in `0.27-maintenance`to check the output of the taglist sample application. Such sample application was extended to be able to check whether exiv2 is able to recognise certain tags and we decided to add a python test to analyse the output of it. However, when adding support for new tags, taglist's output change and therefore the test fail with non understandable errors.

The objective of this issue is to reconsider the testing strategy with some of the approaches discussed in #1015. Another possible outcome of this issue would be to just decide to not add such test.

**Comment by clanmills** [comment]
I agree.  This test is difficult to manage.  It was added at Dan's request.  I've removed it from the 0.27-maintenance branch.
