### ISSUE TITLE
Update of 2 sigmas lenses on Canon body AND way to differentiate lenses with same ID

### ISSUE THREAD

**Issue by fabeng07** [Exiv2/exiv2#1076]
Hello,

In the array: canonCsLensType of the file canonmn_int.cpp, please could you add these 2 lenses:

        { 231, "Sigma 12-24mm f/4 DG HSM | A"                               }
        { 495, "Sigma 24-70mm f/2.8 DG OS HSM | A"                       }

For the number 495, there is already one canon lens with same focal and aperture so not possible to differentiate with actual code.
{ 495, "Canon EF 24-70mm f/2.8L II USM"                             }

It is nevertheless possible to differentiate by using the tag: 0x0095, "LensModel" of CanonMakerNote which is:

"12-24mm F4 DG HSM | Art 016"
"24-70mm F2.8 DG OS HSM | Art 017"

Maybe it would be a good idea when the match has 2 possible solutions to use this tag.
Either by finding exactly the same substring "24-70mm F2.8 DG OS HSM | Art 017" to differentiate with the canon lens or using the distinctive "Art" which has a high probability to be specific to sigma lenses.

I can provide images if needed.

Kind regards,
Fabien

**Comment by clanmills** [comment]
@fabeng07 Please attach sample images to be added to the test suite.

We normally put .exv files into the test suite.  You can create them with `$ exiv2 --force --verbose -ea foo.image`.

Perhaps you'd like to also write the python tests.  You'll find the existing tests `tests/bugfixes/github/test_pr_992.py` and/or `tests/bugfixes/github/test_issue_20.py` a good model.  The test harness will automatically find your test script `tests/bugfixes/github/test_issue_1076.py`

BTW, you can fix this issue for yourself by adding the following to the file `~/.exiv2`

```
[canon]
231=Sigma 12-24mm f/4 DG HSM | A
495=Sigma 24-70mm f/2.8 DG OS HSM | A
```

The (optional) file ~/.exiv2 is documented in the man page `man exiv2`

**Comment by D4N** [comment]
@fabeng07 Would you be willing to help out with the coding part? Unfortunately I have had very little time to dedicate to exiv2 in the past months, so I cannot promise any ETA at all.

In any case, could you please provide us with some sample images?

**Comment by clanmills** [comment]
@fabeng07 I have submitted a PR #1119  Please provide test files and I will update the test suite.

**Comment by clanmills** [comment]
Without test images, this fix will not be submitted to the code base.
