### ISSUE TITLE
Silent warnings when building as an external dependency

### ISSUE THREAD

**Issue by SPlesskin** [Exiv2/exiv2#1080]
Hi,

I'm building Exiv2 as an external library for my project. I'm using CMake and the ExternalProject module for that purpose. Everything works fine but I'd like to disable the warning/error messages that appear in the console window. I know I've to define a special macro (SUPPRESS_WARNINGS) at compile time but I'm having a hard time finding how to do so. Can someone tell me a solution for this problem ? Here's the CMake script I use to compile the library:

set(EXIV2_PREFIX exiv2)
set(EXIV2_URL "${CMAKE_SOURCE_DIR}/exiv2/exiv2-0.27.2-Source.tar.gz")
set(EXIV2_URL_MD5 8c39c39dc8141bb158e8e9d663bcbf21)

ExternalProject_Add(
    ${EXIV2_PREFIX}
    PREFIX ${EXIV2_PREFIX}
    #-- Download step -------
    URL ${EXIV2_URL}
    URL_MD5 ${EXIV2_URL_MD5}
    #-- Configure step ------
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
               -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
               -DEXIV2_ENABLE_XMP=OFF
               -DEXIV2_ENABLE_PNG=OFF
               -DEXIV2_BUILD_SAMPLES=OFF
               -DEXIV2_BUILD_EXIV2_COMMAND=OFF
    #-- Logging options -----
    LOG_DOWNLOAD 1
    LOG_BUILD 1)

Thank you very much for your help.

**Comment by boardhead** [comment]
Just a guess, but did you try adding -DSUPPRESS_WARNINGS ?

**Comment by SPlesskin** [comment]
Yes, I tried to set the CMAKE_CXX_FLAGS and CXX_FLAGS variables with "-DSUPPRESS_WARNINGS" but it was unsuccessful. It seems also that I can't do this with the make command.

**Comment by clanmills** [comment]
The following works for me on MacOSX 10.15.2 with cmake version 3.15.0
```
$ cmake .. -DCMAKE_CXX_FLAGS=-DSUPPRESS_WARNINGS
```
It reports:
```
719 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ cmake .. -DCMAKE_CXX_FLAGS=-DSUPPRESS_WARNINGS 
-- The CXX compiler identification is AppleClang 11.0.0.11000033
...
-- ------------------------------------------------------------------
-- CMake Generator:   Unix Makefiles
-- CMAKE_BUILD_TYPE:  
-- Compiler info: AppleClang (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++) ; version: 11.0.0.11000033
--  --- Compiler flags --- 
-- General:           -DSUPPRESS_WARNINGS
	 -fstack-protector-strong
	 -Wp,-D_GLIBCXX_ASSERTIONS
	 -Wall
	 -Wcast-align
	 -Wpointer-arith
	 -Wformat-security
	 -Wmissing-format-attribute
	 -Woverloaded-virtual
	 -W
-- Extra:              
-- Debug:             -g3 -gstrict-dwarf -O0
-- Release:           -O3 -DNDEBUG
-- RelWithDebInfo:    -O2 -g -DNDEBUG
-- MinSizeRel:        -Os -DNDEBUG
--  --- Linker flags --- 
-- General:           
-- Debug:             
-- Release:           
-- RelWithDebInfo:    
-- MinSizeRel:        
-- 
-- Compiler Options
-- Warnings as errors:                 NO
-- Use extra compiler warning flags:   NO
-- 
-- ------------------------------------------------------------------
-- Building shared library:            YES
-- Building PNG support:               YES
-- XMP metadata support:               YES
-- Native language support:            NO
-- Conversion of Windows XP tags:      YES
-- Nikon lens database:                YES
-- Building webready support:          NO
-- Building exiv2 command:             YES
-- Building samples:                   YES
-- Building PO files:                  NO
-- Building unit tests:                NO
-- Building fuzz tests:                NO
-- Building doc:                       NO
-- Building with boost::regex          NO
-- Building with coverage flags:       NO
-- Using ccache:                       NO
-- ------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/rmills/gnu/github/exiv2/exiv2/build
```

**Comment by clanmills** [comment]
@SPlesskin Did this work for you?  Can we close this issue now?

**Comment by clanmills** [comment]
I'm going to close this because I believe I've provided the necessary explanation.  @SPlesskin I will re-open this issue if you wish to discuss this further.
