### ISSUE TITLE
Having problem in installing exiv2 in ubuntu 18.04lts

### ISSUE THREAD

**Issue by vaibhav135** [Exiv2/exiv2#1083]
I have downloaded the exiv2-0.27.2-Source.tar.gz. 
I have extracted it in the same directory i.e, home/dir/Downloads/
Now following the instructions from the github page 

 **Build, Install, Use Exiv2 on a UNIX-like system**
`cd $EXIV_ROOT
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
make tests
sudo make install`

![Screenshot from 2020-01-14 11-04-53](https://user-images.githubusercontent.com/39329182/72317018-faa41e80-36bd-11ea-90d5-81d3da32ba9d.png)

I Have to install the exiv2 for the osm/merkaartor. Please help

**Comment by clanmills** [comment]
I think your variable EXIV_ROOT is incorrectly set, or possibly not set at all!  And that's why cmake is issuing the message:

```
CMake Error: The source directory "/home/dev135" does not appear to contain CMakeLists.txt
```

CMake cannot generate a Makefile, and everything that follows (`mkdir build; cd build ; cmake --build . ; make tests`) will fail.

Could you mean `EXIV_ROOT` to be set to `/home/dev135/Downloads/exiv2-0.27.2-Source`?

**Comment by vaibhav135** [comment]
> I think your variable EXIV_ROOT is incorrectly set, or possibly not set at all! And that's why cmake is issuing the message:
> 
> ```
> CMake Error: The source directory "/home/dev135" does not appear to contain CMakeLists.txt
> ```
> 
> CMake cannot generate a Makefile, and everything that follows (`mkdir build; cd build ; cmake --build . ; make tests`) will fail.
> 
> Could you mean `EXIV_ROOT` to be set to `/home/dev135/Downloads/exiv2-0.27.2-Source`?

yes

**Comment by vaibhav135** [comment]
Can you please give me a straight example as of how can I install this in my machine

**Comment by clanmills** [comment]
Please use the words "Please" and "Thank You" when we talk.

Three ways to make progress:

1 Install Exiv2 on ubuntu with apt
2 Download the pre-built binary for Linux
3 Build from source

-------
*Install Exiv2 on ubuntu with apt*
```
$ sudo apt-get install --yes exiv2
```

-------
*Download the pre-built binary for Linux*

You can download pre-built binaries (for Linux and other platforms) from:
https://www.exiv2.org/download.html

The file ReadMe.txt has instructions for installing and building code with the distribution.

-------
*Build from source*

You can get source from GitHub, or download source from:  https://www.exiv2.org/download.html

Please study README.md in the distribution.

**Comment by clanmills** [comment]
I believe I know exactly what has caused your difficulty.  README.md says:
```
cd $EXIV_ROOT
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
make test
sudo make install
```

It doesn't explicitly say you should declare the variable EXIV_ROOT to the directory of the source!  In your case:

```
EXIV_ROOT=/home/dev135/Downloads/exiv2-0.27.2-Source
cd $EXIV_ROOT
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
make test
sudo make install
```

I hope this is now working correctly for you.  The other methods I suggested (using apt and downloading a pre-built binary) are probably easier and quicker.

Building open-source is often challenging as it involves unfamiliar tools and procedures.    Tenacity and determination are usually required.

I'v never heard of osm/merkaartor.  Thank You for using Exiv2.

**Comment by vaibhav135** [comment]
> Please use the words "Please" and "Thank You" when we talk.
> 
> Three ways to make progress:
> 
> 1 Install Exiv2 on ubuntu with apt
> 2 Download the pre-built binary for Linux
> 3 Build from source
> 
> _Install Exiv2 on ubuntu with apt_
> 
> ```
> $ sudo apt-get install --yes exiv2
> ```
> 
> _Download the pre-built binary for Linux_
> 
> You can download pre-built binaries (for Linux and other platforms) from:
> https://www.exiv2.org/download.html
> 
> The file ReadMe.txt has instructions for installing and building code with the distribution.
> 
> _Build from source_
> 
> You can get source from GitHub, or download source from: https://www.exiv2.org/download.html
> 
> Please study README.md in the distribution.

Hello 
Thanks for the explanation and I am really sorry for my manners. Since I am new to the open source community.
I am extremely thankful to you.

**Comment by vaibhav135** [comment]
Actually OSM stands for open street map.By the way sir is your organisation going to appear for GSoC.

**Comment by clanmills** [comment]
Thanks for apologising.  Very much appreciated.  Please remember all open-source engineers are unpaid volunteers.  You reward us by saying "Thanks".  

We participated in GSoC in 2012 and 2013.  We applied in 2019 and were declined.  There's no plan to apply in 2020. #659 

I've retired now from Exiv2 (after 12 years and 10,000+ hours).  I occasionally answer support questions, however I will not submit code changes in future.

I enjoyed working with the GSoC students and Alison and I attended Tuan's wedding in 2017.  We plan to visit him and Alice and their son in Singapore in February.

**Comment by vaibhav135** [comment]
Thank you Sir for your humble reply. I will always remember that. I will never repeat the same mistake again.

**Comment by clanmills** [comment]
When doing some general maintenance of README.md in preparation for Exiv2 v0.27.3, I modified the document to say:
```
2.1 Build, Install, Use Exiv2 on a UNIX-like system

cd ~/gnu/github/exiv2  # location of the project code
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
make tests
sudo make install
```

Exiv2 v0.27.3 is scheduled for release on 2020-06-30.  https://github.com/Exiv2/exiv2/issues/1018#issuecomment-604539346
