### ISSUE TITLE
Irix lens names in Pentax

### ISSUE THREAD

**Issue by StefanGyuzelev** [Exiv2/exiv2#1084]
Hello!
It's not a bug, it's just missing information about Irix150mm, Irix11mm lenses in photos taken with Pentax. I suggest the following patch to add this information:
[Pentax-Irix.patch.zip](https://github.com/Exiv2/exiv2/files/4060622/Pentax-Irix.patch.zip)

**Comment by D4N** [comment]
Thanks for the patch! JFYI: you can submit patches directly via the mailinglist as noted at the top of the README ;-)

Could you share some source/confirmation that backs up these changes and provide some test images for the lenses? (If you own a camera with the respective lenses, then please just make a blank photo and upload it here).

**Comment by StefanGyuzelev** [comment]
This is link to my example with Irix150mm and Irix15mm with Pentax K-1
https://drive.google.com/drive/folders/1Qn8SVBVPk-6zZJ-G9LqHImFEmJevou7f?usp=sharing
I don't have Irix11 f / 4, but I downloaded an example from: https://www.pentaxforums.com/forums/122-lens-clubs
Unfortunately the site does not open today  to give the exact address to a photo of Pentax k-1 with Irix 11mm which contains exif

**Comment by clanmills** [comment]
See #1085.
