### ISSUE TITLE
Lens request: Leica DC Vario-Summilux 10.9–34 mm f/1.7–2.8 ASPH

### ISSUE THREAD

**Issue by lake-effect** [Exiv2/exiv2#1096]
This is a lens included in a few built-in cameras, including the [Leica D-Lux](https://www.dpreview.com/articles/9078374619/leica-introduces-d-lux-24-75mm-equiv-compact-with-four-thirds-sensor#specs) and Panasonic Lumix LX-100II.

**Comment by boardhead** [comment]
Can you provide a sample image taken with this lens?

**Comment by lake-effect** [comment]
Sure! Here's a RAW with no lens correction: https://mega.nz/#!1mRn0SJY!hyXERCpbGn4ENOIQHPNePmdGtJBZV1nKJaBaVXqKvyk

For reference, darktable has a "fixed lens" for Panasonic/LX-100 cameras that is close but its settings bottom out at 11mm whereas this has 10mm.

**Comment by boardhead** [comment]
I'm not sure exactly what you want with this request, but there is no lens identification information in this image.

**Comment by lake-effect** [comment]
You might have to walk me through what you need exactly, I'm new to photography. I'm following the [documentation for darktable](https://www.darktable.org/2015/02/on-lens-detection-and-correction/) that brought me here:

> If you still can’t find your lens, please file a feature request with the Exiv2 project here (and yes, you’ll need to create an account):

>    http://dev.exiv2.org/projects/exiv2/issues/new

> Please include the following information:

>    Full output of:

>    exiv2 -pt FILENAME | grep -ai lens
> 
>     - The proper full name of the lens (be mindful of capitalization)
>     - Preferably include a link to the lens’ product page on the manufacturers website
>     - Attach a sample low resolution JPEG (unmodified, most cameras allow you to shoot lower resolution JPEGs)

Would a JPEG help, as mentioned there?

**Comment by boardhead** [comment]
I don't think there is anything to be done here.  The lens identification generally applies only to removable lenses.

**Comment by lake-effect** [comment]
I'm a little bit lost. It may be a prime lens but the workflow for dealing with lens distortion is just as relevant even if it's the same lens with every shot, no? I see nothing in [CONTRIBUTING](https://github.com/Exiv2/exiv2/blob/06ce5efa28ee3e523be8dce1c57bd6a07244dac9/CONTRIBUTING.md#4-contributing-lens-data) that specifically excludes non-removable lenses.

Attached are a couple images with the lens cap on as mentioned in CONTRIBUTING. Please let me know if there's anything else I can do to help improve Exiv2's support of this lens.

![P1011747](https://user-images.githubusercontent.com/39317653/75472187-ee131700-5947-11ea-98d7-4eb33aa89ea9.JPG)

![P1011746](https://user-images.githubusercontent.com/39317653/75472228-fcf9c980-5947-11ea-89ed-7cf715ebcb61.JPG)

**Comment by boardhead** [comment]
Perhaps I'm missing the point.  For cameras with fixed lenses, doesn't the camera model name give you everything you need to know in order to determine which lens was used?

**Comment by lake-effect** [comment]
I think we're locating the confusion 😄  My understanding was that Exiv2 was the library in which lens correction/geometry information was also stored, such that apps like darktable could use that in their functioning. Is that sort of thing on darktable's side of the fence?

**Comment by clanmills** [comment]
@lake-effect The headline statement on https://exiv2.org is:

_Exiv2 is a Cross-platform C++ library and a command line utility to manage image metadata. It provides fast and easy read and write access to the Exif, IPTC and XMP metadata and the ICC Profile embedded within digital images in various formats. Exiv2 is available as free software and is used in many projects including KDE and Gnome Desktops as well as many applications including GIMP, darktable, shotwell, GwenView and Luminance HDR._

Exiv2 is not involved in lens correction, or indeed any aspect of the meaning or use of the metadata.

Various applications, such as darktable,  use libexiv2 to read the metadata.  They may use lens metadata as input to code which preforms lens correction.  There is no lens correction code in Exiv2.

From what @boardhead has said, I understand that your camera has a fixed lens therefore the camera model is sufficient to identify the lens.

Asking about _**darktable's side of the fence**_, implies that darktable and Exiv2 are cooperating to achieve a result.  That's not true.  Exiv2 identifies the metadata and has no involvement with how the metadata is used by darktable.

**Comment by lake-effect** [comment]
That covers it for me. Thanks!
