### ISSUE TITLE
Build as static library issue

### ISSUE THREAD

**Issue by diuming** [Exiv2/exiv2#1108]
macOS 10.15

I try to build as static library and link to specific static libraries(/opt/libz.a, /opt/libexpat.a, libiconv.a)

Coud I build it with static dependence libraries?

It looks like always link to system libraries(even I set PKG_CONFIG_PATH)
```
CFLAGS="-I/opt/zlib-1.2.11/include -I/opt/expat-2.2.9/include -I/opt/libiconv-1.16/include" \
LDFLAGS="-L/opt/zlib-1.2.11/lib -L/expat-2.2.9/lib -L/opt/libiconv-1.16/lib" \
cmake .. \
-DIconv_INCLUDE_DIR=/opt/libiconv-1.16/include \
-DIconv_LIBRARY=/opt/libiconv-1.16/lib \
-DCMAKE_INSTALL_PREFIX:PATH=/opt/exiv2-0.27.2 \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_SHARED_LIBS=OFF
```

**Comment by clanmills** [comment]
Yes.  It's possible.  I've been having a sabbatical for 6 months and only returned to the project this week-end.  I need to do a brain refresh! 

Good news, I develop Exiv2 on MacOS (currently 10.15.3).  I have dependencies such as zlib and expat built from source in `/usr/local/...`  I'll install the static libraries with brew and see how it goes.

What is your cmake command?  My guess is:
```
$ export LD_LIBRARY_PATH="/opt/lib:$LD_LIBRARY_PATH" cmake ..
```
I also suggest you install conan.  It's very good at dealing with dependencies.  The documentation is in README-CONAN.md

**Comment by clanmills** [comment]
Here's what happens when I run brew:
```
1360 rmills@rmillsmbp:/opt $ brew reinstall zlib
==> Reinstalling zlib 
==> Downloading https://homebrew.bintray.com/bottles/zlib-1.2.11.catalina.bottle.tar.gz
Already downloaded: /Users/rmills/Library/Caches/Homebrew/downloads/b2ddf2c27ff5f1b39cb0eba4a8deb993a17c1bef8c6b1ae3ae9b00312e042269--zlib-1.2.11.catalina.bottle.tar.gz
==> Pouring zlib-1.2.11.catalina.bottle.tar.gz
==> Caveats
zlib is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

For compilers to find zlib you may need to set:
  export LDFLAGS="-L/usr/local/opt/zlib/lib"
  export CPPFLAGS="-I/usr/local/opt/zlib/include"

For pkg-config to find zlib you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/zlib/1.2.11: 12 files, 376.4KB
1361 rmills@rmillsmbp:/opt $ 
```

I think you should keep clear of brew for dependencies.  It's easy to download and build zlib and expat from source.  I've documented where to get the code in README.md.

You can build exiv2 as a dynamic or static library.  I know you can link with either static or dynamic dependencies.  I personally always use dynamic libraries, however I'm confident that static is possible.

**Comment by diuming** [comment]
@clanmills thanks for Help.

**Comment by diuming** [comment]
@clanmills  welcome back. ^_^
