### ISSUE TITLE
Question: about alpha channels in TIFF?

### ISSUE THREAD

**Issue by diuming** [Exiv2/exiv2#1109]
macOS 10.15.3
exiv2-0.27.2

I combine 7 gray(8bit) tiff files into one `source.tiff`(cmyk + 3 alpha channels).
is it possible change `source.tiff`'s 3 alpha channes to spot channels and naming each title.
It looks like `destination.tiff`.
if so, could you give me some advance, hints or examples.
thanks

|source.tiff|using exiv2 library |destination.tiff|
| ------------- |:---:|---|
|cmyk + 3 alpha channels |  |cmyk + 3 spot channels|
|c.tiff| |c.tiff|
|m.tiff| |m.tiff|
|y.tiff| -----> |y.tiff|  
|k.tiff| |k.tiff|
|a1.tiff (alpha)| |a1.tiff (spot name: my_spot2)|
|a2.tiff (alpha)| |a2.tiff (spot name: my_spot3)|
|a3.tiff (alpha)| |a3.tiff (spot name: my_spot4)|

**Comment by clanmills** [comment]
Thanks for saying "welcome back".  Happy to be here.

Exiv2 can't help with this matter as it manipulates metadata and has no code to work with pixels!  Libtiff is a very capable library which comes with a number of utilities.  Perhaps the utility`tiff2rgba` will help you:
```
       Tiff2rgba  converts  a wide variety of TIFF images into an RGBA TIFF image.  This includes
       the ability to translate different color spaces and photometric interpretation into  RGBA,
       support for alpha blending, and translation of many different bit depths into a 32bit RGBA
       image.
```

If that's not suitable, here are the other libtiff utilities installed on my machine:
```
1408 rmills@rmillsmbp:/usr/local/bin $ dir *tiff*
-rwxr-xr-x  1 root    admin   115K 26 Sep 19:35 tiff-test*
-rwxr-xr-x  1 rmills  admin    19K 23 Apr  2015 bmp2tiff*
-rwxr-xr-x  1 rmills  admin    16K 23 Apr  2015 fax2tiff*
-rwxr-xr-x  1 rmills  admin    22K 23 Apr  2015 gif2tiff*
-rwxr-xr-x  1 rmills  admin    15K 23 Apr  2015 ppm2tiff*
-rwxr-xr-x  1 rmills  admin    14K 23 Apr  2015 ras2tiff*
-rwxr-xr-x  1 rmills  admin    18K 23 Apr  2015 raw2tiff*
-rwxr-xr-x  1 rmills  admin    19K 23 Apr  2015 tiff2bw*
-rwxr-xr-x  1 rmills  admin    82K 23 Apr  2015 tiff2pdf*
-rwxr-xr-x  1 rmills  admin    49K 23 Apr  2015 tiff2ps*
-rwxr-xr-x  1 rmills  admin    15K 23 Apr  2015 tiff2rgba*
-rwxr-xr-x  1 rmills  admin    19K 23 Apr  2015 tiffcmp*
-rwxr-xr-x  1 rmills  admin    41K 23 Apr  2015 tiffcp*
-rwxr-xr-x  1 rmills  admin   102K 23 Apr  2015 tiffcrop*
-rwxr-xr-x  1 rmills  admin    14K 23 Apr  2015 tiffdither*
-rwxr-xr-x  1 rmills  admin    20K 23 Apr  2015 tiffdump*
-rwxr-xr-x  1 rmills  admin    18K 23 Apr  2015 tiffgt*
-rwxr-xr-x  1 rmills  admin    16K 23 Apr  2015 tiffinfo*
-rwxr-xr-x  1 rmills  admin    24K 23 Apr  2015 tiffmedian*
-rwxr-xr-x  1 rmills  admin    14K 23 Apr  2015 tiffset*
-rwxr-xr-x  1 rmills  admin    15K 23 Apr  2015 tiffsplit*
1409 rmills@rmillsmbp:/usr/local/bin $ 
```

**Comment by diuming** [comment]
@clanmills thanks for replying.

the `source.tiff` is already done.
a1.tiff, a2.tiff and a3.tiff are always appear as alpha channel in photoshop.
so, I want to use `exiv2` to modify xmp metadata become as spot channel and naming title.
it looks like destination.tiff.
is it possible?
thanks

**Comment by clanmills** [comment]
I'm not sure I understand this.  Are you asking about something like this:
```
+--------------+       +-----------+      channel_1.tiff  +------------+  
| source.tiff  |  -->  | photoshop |   -> channel_2.tiff  | some magic | -> something
+--------------+       +-----------+      channel_3.tiff  +------------+
                                          etc...
```

**Comment by diuming** [comment]
@clanmills , Sorry my english is not very wall.
I mean use `Exiv2` to modify(xmp metadata) `source.tiff`'s 3 alpha channels become 3 spot channels and than save it.

**Comment by clanmills** [comment]
Can you attach your tiff, please.  I will investigate.

**Comment by diuming** [comment]
@clanmills thanks for helping me.

just modify 3 alpha channel(xmp metadata) to spot color channels.
[source.tiff.zip](https://github.com/Exiv2/exiv2/files/4370572/source.tiff.zip)

**Comment by clanmills** [comment]
I think I understand.  This image has 3 color planes which start at 8, 512008, 1024008 bytes into the file.  The length of the channels are 512000, 51200, and 280000 bytes long.

This part of the metadata is part of the image itself.  It can't be changed.  It's like the size of the image (500x326).  It's a physical property of the image and Exiv2 protects that data from change.

```
Exif.Image.StripOffsets                      Long        3  8 512008 1024008
Exif.Image.Orientation                       Short       1  top, left
Exif.Image.SamplesPerPixel                   Short       1  8
Exif.Image.RowsPerStrip                      Short       1  128
Exif.Image.StripByteCounts                   Long        3  512000 512000 280000
```

I don't believe Exiv2 can help you with this challenge.

I think you can use PhotoShop to extract the three colors as one plane images. And then create a new image with 3 spot colors image.  Import each one plane images in the spot.  I don't know much about PhotoShop and don't have it installed on my machines.

**Comment by diuming** [comment]
@clanmills thank you for taking the time to help me.
