### ISSUE TITLE
Add support for Tamron AF 17-50mm 1:2.8 [IF] A16 LD XR DiII SP for F-Mount

### ISSUE THREAD

**Issue by kwazel** [Exiv2/exiv2#1155]
**Is your feature request related to a problem? Please describe.**
If I use my Tamron 17-50mm on my Nikon D7500, darktable does not recognize this lens but instead displays it as "124"

**Describe the solution you'd like**
Add this lens to database. Use this jpeg as a sample.
![DSC_5864](https://user-images.githubusercontent.com/26428407/79152760-0c848300-7dcd-11ea-951c-8b16def7e7fa.JPG)
Note, I used a white image instead of a black one because my camera compresses it much nicer: black was all noise and added up to 5MB.

**Describe alternatives you've considered**
I now select another Tamron 17-50mm by hand.

**Comment by clanmills** [comment]
This isn't a bug.  Your lensID is 124.  Exiv2 will recognise you lens when you put information into the ~/.exiv2.
```
522 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ exiv2 -pa --grep lens/i --grep Make  -grep ~/Downloads/79152760-0c848300-7dcd-11ea-951c-8b16def7e7fa.JPG | grep -i Nikon
Exif.Image.Make                              Ascii      18  NIKON CORPORATION
Exif.Nikon3.LensType                         Byte        1  D G 
Exif.Nikon3.Lens                             Rational    4  17-50mm F2.8
Exif.Nikon3.LensFStops                       Undefined   4  7
Exif.NikonLd3.LensIDNumber                   Byte        1  124
Exif.NikonLd3.LensFStops                     Byte        1  F7.0
```
Now update ~/.exiv2
```
523 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ cat ~/.exiv2
[nikon]
124=Tamron AF 17-50mm 1:2.8 [IF] A16 LD XR DiII SP for F-Mount
```
Your lens will be recognised.
```
524 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ exiv2 -pa --grep lens/i --grep Make  -grep ~/Downloads/79152760-0c848300-7dcd-11ea-951c-8b16def7e7fa.JPG | grep -i Nikon
Exif.Image.Make                              Ascii      18  NIKON CORPORATION
Exif.Nikon3.LensType                         Byte        1  D G 
Exif.Nikon3.Lens                             Rational    4  17-50mm F2.8
Exif.Nikon3.LensFStops                       Undefined   4  7
Exif.NikonLd3.LensIDNumber                   Byte        1  Tamron AF 17-50mm 1:2.8 [IF] A16 LD XR DiII SP for F-Mount
Exif.NikonLd3.LensFStops                     Byte        1  F7.0
525 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ 
```

**Comment by clanmills** [comment]
This is discussed in numerous places, including the exiv2 man page.  Here's an article on the Wiki about this:  https://dev.exiv2.org/projects/exiv2/wiki/Lens_Recognition_in_Exiv2_v026_(and_later)

**Comment by boardhead** [comment]
What is the exact Tamron model number for this lens?  (A16 or A16NII perhaps?)

**Comment by kwazel** [comment]
> What is the exact Tamron model number for this lens? (A16 or A16NII perhaps?)

A16

**Comment by boardhead** [comment]
Thanks
