### ISSUE TITLE
Dash as date separator

### ISSUE THREAD

**Issue by dandelionred** [Exiv2/exiv2#1180]
First of all, thanks to all the devs for the epic piece of software!

I've got images shot with an old android phone (galaxy gio). Running those through the `-t` option I get `Failed to parse timestamp` error message.

Here is datetime data from a sample file:

```
$ exiv2 -Pkt 2012-12-22\ 12.37.28.jpg | grep -i datetime
Exif.Image.DateTime                           2012-12-22 10:37:28 
Exif.Photo.DateTimeOriginal                   2012-12-22 10:37:28 
Exif.Photo.DateTimeDigitized                  2012-12-22 10:37:28
```

So the problem with failed parser are dashes as date separators. Please, consider allowing dash as date separator in `src/actions.cpp :: str2Tm()`.

Here is how I patched it locally (it is exiv2-0.23 in ubuntu 14.04; git master does the same processing though)

```patch
Index: exiv2-0.23/src/actions.cpp
===================================================================
--- exiv2-0.23.orig/src/actions.cpp	2012-03-22 17:19:35.000000000 +0200
+++ exiv2-0.23/src/actions.cpp	2020-04-24 16:55:31.210712814 +0300
@@ -1762,7 +1762,7 @@
     {
         if (timeStr.length() == 0 || timeStr[0] == ' ') return 1;
         if (timeStr.length() < 19) return 2;
-        if (   timeStr[4]  != ':' || timeStr[7]  != ':' || timeStr[10] != ' '
+        if (   timeStr[4]  != ':' && timeStr[4] != '-' || timeStr[7]  != ':' && timeStr[7] != '-' || timeStr[10] != ' '
             || timeStr[13] != ':' || timeStr[16] != ':') return 3;
         if (0 == tm) return 4;
         std::memset(tm, 0x0, sizeof(struct tm));
```

**Comment by clanmills** [comment]
Ah, how interesting.  On my Samsung phone:

```
1100 rmills@rmillsmbp:~/Pictures/2020/April $ exiv2 -Pkt --grep datetime/i 20200419_180819.jpg  
Exif.Image.DateTime                           2020:04:19 18:08:18
Exif.Photo.DateTimeOriginal                   2020:04:19 18:08:18
Exif.Photo.DateTimeDigitized                  2020:04:19 18:08:18
1101 rmills@rmillsmbp:~/Pictures/2020/April $ 
```

I believe `YYYY-MM-DD` is an ISO standard date format.  I'll check the Exif spec.  I'm almost certain that it specifies `YYYY:MM:DD`.   However forgiving your phone is probably harmless.  Can you attach a sample image please.  If I agree to this change, I'll want to add something to the test harness.

Incidentally, your timing's perfect.  Exiv2 v0.27.3 RC1 is on track to ship as scheduled on 2020-04-30.  You don't have long to wait!

**Comment by dandelionred** [comment]
I've got 3 more samsung phones (c3011, b350e, j120h) - all of them use colon lol.

Sample image from galaxy gio https://user-images.githubusercontent.com/19490344/80241754-d7015480-866c-11ea-9a45-96804fcfae00.jpg
It is android 2.3.6, stock camera app.

> Incidentally, your timing's perfect. Exiv2 v0.27.3 RC1 is on track to ship as scheduled on 2020-04-30. You don't have long to wait!

I guess there is no chance it would land into focal-updates anytime?

**Comment by clanmills** [comment]
I've checked both the Exif 2.2 and 2.3 specs:

_D. Other Tags_
_DateTime_

_The date and time of image creation. In this standard it is the date and time the file was changed. The format is "YYYY:MM:DD HH:MM:SS" with time shown in 24-hour format, and the date and time separated by one blank character [20.H]. When the date and time are unknown, all the character spaces except colons (":") may be filled with blank characters, or else the Interoperability field may be filled with blank characters. The character string length is 20 bytes including NULL for termination. When the field is left blank, it is treated as unknown._

When you send the test file, I'll look at your code, run the test harness.  If I accept this, I should update the man page.  It doesn't say anything about Exif DateTime.  About IPTC, it says:
```
The format for an IPTC Date value is:
	  YYYY-MM-DD (year, month, day)

The format for an IPTC Time value is:
	  HH:MM:SS (hours, minutes, seconds)
and may optionally be followed by:
     -HH:MM or +HH:MM (hours, minutes ahead/behind UTC)
```

**Comment by dandelionred** [comment]
Tbh my point is it doesn't matter what the specs say. We should look into was existing devices produce. So a good function would successfully parse both colons and dashes.

**Comment by clanmills** [comment]
Ah, you've sent the test file.
```
1111 rmills@rmillsmbp:~/Downloads $ exiv2 -pa --grep DateTime 80241754-d7015480-866c-11ea-9a45-96804fcfae00.jpg 
Exif.Image.DateTime                          Ascii      50  2020-04-24 17:44:15 
Exif.Photo.DateTimeOriginal                  Ascii      50  2020-04-24 17:44:15 
Exif.Photo.DateTimeDigitized                 Ascii      50  2020-04-24 17:44:15 
1112 rmills@rmillsmbp:~/Downloads $ 
```

I'm sure I can accept this change because actions.cpp is part of the exiv2 command-line program, so this change doesn't impact the library.  None-the-less, I'll update the test suite and the man page.

**Question**
> _I guess there is no chance it would land into focal-updates anytime?_

I don't understand the question.

BTW.  I think conforming to standards is important.  Very important.  This is a bug in the firmware of your device.  However, we can "tweak" the -t option in the exiv2 command-line program without compromising the Exif 2.x standards.

**Comment by dandelionred** [comment]
> I don't understand the question.

Dw, forget it.

> I think conforming to standards is important. Very important.

The library should only **produce** conformant stuff. In the meanwile the parser could be more relaxed, it doesn't harm anything.

**Comment by clanmills** [comment]
OK.  I'm going to accept this change for Exiv2 v0.27.3.  #1183

Incidentally, in working on the tests, I discovered another bug in the firm-ware of your device.  It write the DateTime as 50 bytes with a trailing ' space\n...........`.   Not good.  Anyway, it isn't fatal.
