### ISSUE TITLE
Is there an opposite of `-t` ?

### ISSUE THREAD

**Issue by alvinsight** [Exiv2/exiv2#1182]
Hello, Exiv2 team! 
My respect to Robin for coming out of retirement to carry this project forward 👏

I'm curious if there is a way to do the opposite of the `-t` option. 
That is, setting the EXIF creation date based on the file creation date.

It's totally OK if not, just checking I didn't miss it.

**Comment by clanmills** [comment]
Yes, congratulations and _**Thank You**_ to me.  You're the only person who has thanked me.  I've had excellent support and encouragement from Luis (@piponazo), Phil (@boardhead) and Andreas S (@cryptomilk).

What you're asking isn't a feature of the exiv2 command-line program, however you can do it with a one-liner in bash.
```
589 rmills@rmillsmbp:~/temp $ curl -O --silent http://clanmills.com/Stonehenge.jpg
590 rmills@rmillsmbp:~/temp $ ls -l Stonehenge.jpg 
-rw-r--r--  1 rmills  staff  6757827 25 Apr 08:40 Stonehenge.jpg
591 rmills@rmillsmbp:~/temp $ exiv2 -K Exif.Image.DateTime Stonehenge.jpg 
Exif.Image.DateTime                          Ascii      20  2015:07:16 20:25:28
592 rmills@rmillsmbp:~/temp $ stat --format '%w'  Stonehenge.jpg 
2020-04-25 08:40:51.902414332 +0100
593 rmills@rmillsmbp:~/temp $ stat --format '%w' Stonehenge.jpg | cut -d. -f 1 | sed s/-/:/g
2020:04:25 08:40:51
594 rmills@rmillsmbp:~/temp $ exiv2 -K Exif.Image.DateTime Stonehenge.jpg 
Exif.Image.DateTime                          Ascii      20  2015:07:16 20:25:28
595 rmills@rmillsmbp:~/temp $ exiv2 -M"set Exif.Image.DateTime $(stat --format '%w' Stonehenge.jpg | cut -d. -f 1 | sed s/-/:/g)" Stonehenge.jpg 
596 rmills@rmillsmbp:~/temp $ exiv2 -K Exif.Image.DateTime Stonehenge.jpg 
Exif.Image.DateTime                          Ascii      20  2020:04:25 08:40:51
597 rmills@rmillsmbp:~/temp $ 
``` 

So there's the formula:

```
$ exiv2 -M"set Exif.Image.DateTime $(stat --format '%w' Stonehenge.jpg | cut -d. -f 1 | sed s/-/:/g)" Stonehenge.jpg
```

It's a pity you have to mention the filename twice in the command, however with a two line script you could pass loads of files something like:  `exiv2_stamper *.jpg`
