### ISSUE TITLE
Exiv2 v0.27.3 Available

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1186]
Exiv2 v0.27.3. RC2 is available from: https://exiv2.org 

Thank you to Phil, Sridhar, Luis, Kevin, and Andreas S for working with me on the release.  As always, thanks to my wife Alison and our cat Lizzie for their support.

Highlights of Exiv2 v0.27.3

* Bug and security fixes
* UNIX suppport
* Support for building with C++11 and C++14
* Revised build and test environments
* Revised documentation
* Improved charset handling in UserComment
* Other improvements

Release notes: https://github.com/Exiv2/exiv2/issues/1018#issuecomment-604539346"

**The future of Exiv2**

What happens to Exiv2 in future is a matter for the community.  I returned from retirement to deal with Exiv2 v0.27.3 as progress on v0.28 is glacial. 

I am writing a book called Image Metadata <i>and</i> Exiv2 Architecture.
https://clanmills.com/exiv2/book/

I would like to give a talk at LGM in Rennes in May 2021 and run an afternoon work-shop to talk about both the book.  I will be 70 in January and will retire after LGM 2021.

I hope the Community at LGM will discuss the future of Exiv2.

|  Exiv2 v0.27.3 | _Schedule_ |
|:-- |:-- |
| RC1 | **2020-04-30** |
| RC2 |  **2020-05-31** |
| GM | **2020-06-30** |

The GM release be posted on https://exiv2.org

I’d like to thank Phil, Sridhar, Luis, Kevin and Andreas S for working with me on this release. As always, I want to thank my wife Alison and our cat Lizzie for their support.

|  | **URL** |
|:-- |:-- |
| _Release notes_ | https://github.com/Exiv2/exiv2/issues/1018#issuecomment-604539346 |
| _Remaining work_ | https://github.com/Exiv2/exiv2/milestone/5 |

I hope that Exiv2 v0.28 will be ready in 2021. Future **dot** v0.27.4 if necessary.

**Comment by clanmills** [comment]
I've made a single announcement on pixls and FB with the release schedule.  So I don't need to make further announcements.

https://discuss.pixls.us/t/exiv2-v0-27-3-release/17830
https://www.facebook.com/exiv2/

Slept for 10 hours last night.  I'm exhausted.

-----------

_I’ve come back out of retirement to create Exiv2 v0.27.3. RC1 Preview is available from: https://pre-release.exiv2.org_

_The pre-release schedule is:_
_RC1: 2020-04-30_
_RC2: 2020-05-31_
_GM: 2020-06-30_
_The final release be posted on https://exiv2.org_

_I’d like to thank Phil, Sridhar, Luis, Kevin and Andreas S for working with me on this release. As always, I want to thank my wife Alison and cat Lizzie for their support._

_Release notes: https://github.com/Exiv2/exiv2/issues/1018#issuecomment-604539346_

--------------

I hope that Exiv2 v0.28 will be ready next year. If necessary, I will create Exiv2 v0.27.4 in 2021.

**Comment by clanmills** [comment]
Exiv2 v0.27.3 RC2 is "on track" to ship as scheduled on Sunday 2020-05-31.

Preview (0.27.3.20) on https://pre-release.exiv2.org  Feedback Welcome.

**Comment by clanmills** [comment]
Exiv2 v0.27.3 is available on: https://exiv2.org

If nobody reports anything that requires attention, I will make an announcement on Facebook and https://discuss.pixls.us at 18:00 BST 2020-06-30.

**Comment by philvl** [comment]
Hello,

I would like to report a little mistake: under Linux, the versionString () function of Exiv2 v0.27.3 returns erroneous information: "0.27.2".

Thanks to the development team for Exiv2 last release ;-)

**Comment by tbeu** [comment]
Hi Robin, thanks for releasing the new maintenance release some weeks ago. I immediately updated my application to that new version.

Just a question: Are there any functional fixes from you in the maint branch that are not yet ported to the master branch?

**Comment by clanmills** [comment]
It's always good to hear from you, Thomas.  Hope you and yours are all safe and well in C-19 times.  We're all fine and don't know anybody who has been sick.

There are about 50 PRs to be ported from 0.27-maintenance to master and they are clearly marked as they end `_0.27`  If I'm invited to be the release engineer for Exiv2 v0.28, I will port them.

I will never put any code involving libheif into 0.27-maintenance.  Our existing JP2 support can be easily modified to deal with other ISOBMFF formats such as HEIF, CR3 and AVI.  This will be documented in my book.

**Comment by tbeu** [comment]
> It's always good to hear from you, Thomas. Hope you and yours are all safe and well in C-19 times. We're all fine and don't know anybody who has been sick.
> 

Thanks. We are also fine and cautious.

> There are about 50 PRs to be ported from 0.27-maintenance to master and they are clearly marked as they end `_0.27` If I'm invited to be the release engineer for Exiv2 v0.28, I will port them.
> 

That is not the best situation. However, given that you know what you did in the maint branch, and given that you did an outstanding job in maintaining v0.27, I would be very glad if these fixes will get ported to master soon.

> I will never put any code involving libheif into 0.27-maintenance. Our existing JP2 support can be easily modified to deal with other ISOBMFF formats such as HEIF, CR3 and AVI. This will be documented in my book.

I agree since a maintenance release is usually not meant for adding new features. I will not jump into the previous discussions of patents and license issues with libheif here.

I am in the dilemma that v0.27.3 has fixes that are missing in master and that I want to add HEIF support in my application [ImageMetaData](https://totalcmd.net/plugring/iptcwdx.html). I will see how easy I can back-port @cgilles' commits from master to maint branch (for my inofficial application only). I do hope that this will be a quick win for users of ImageMetaData.

**Comment by clanmills** [comment]
Dan and Luis came to England for a weekend in May 2018.  The main purpose of the week-end was to really get to know each other.  Dan's Lady Elizabeth also came.  We had a nice time.  The weather was perfect.  We had dinner on Friday Evening, ran 5k on Saturday morning, did some work and had a BBQ on Saturday.  Another run and some work on Sunday morning and sadly the week-end was over.

We agreed that I would be the release engineer for v0.27 and do "dots" for as long as necessary while they refactored a lot of the code for 0.28.  v0.28 is "all new" (as Americans say).  We wouldn't bother with API compatibility, the code would be "modernised" into C++11 or later.  Luis wanted move directly to C++17 and the KDE people asked for C++11.  And we deprecated Video, EPS and SSH.

I've stuck to my assignment.  It was a huge amount of work (1000+ hours) to get v0.27 done.  v0.27.1, v0.27.2 and v0.27.3 have been hundreds of hours each.

When I returned to do v0.27.3, I hoped that Dan and Luis would be motivated to use C-19/lockdown to work on v0.28.  That hasn't happened.  v0.28 is effectively dead.  Almost nothing has been done in the last 6 months.  My offer to port the changes from 0.27-maintenance into master and release it as v0.28 has been ignored.

I will finish the book by the end of 2020.  The code that accompanies the book is about 3000 lines of C++ and decodes Exif, ICC, IPTC and XMP in about 15 formats (JPEG, TIFF, PNG etc).  The code decodes MakerNotes.  I hope that the book will inspire somebody to maintain Exiv2 or to write a new library.  I'm considering including a version of the code in Python and Rust.  

I cannot continue to carry the world of Exiv2 alone on my back forever.  I hope LGM will happen in Rennes in 2021.  I will attend and give a talk about the book and run an afternoon work-shop.  When I leave Rennes, I will be finished with open-source, Exiv2 and metadata.  I've done my best.

Chapter 13 deals with Project Management and has sections on Build, Code, Test, Documentation, User Support and so on.  23 major items of activity.  And it's me and Lizzie the cat.  That's it.  The community help by sending abusive emails.  M Caulier is the worst offender.  Please read the introduction to Chapter 13 and you'll get an idea of what's involved.  https://clanmills.com/exiv2/book/#13

We live in an expanding universe.  The scope of Exiv2 is much much larger today that it was when Andreas started in 2004.  Yet, the number of contributors remains at one.  This cannot continue.
