### ISSUE TITLE
Update request: Sigma 35mm F1.4 DG HSM ART Canon Mount

### ISSUE THREAD

**Issue by MStraeten** [Exiv2/exiv2#1192]
**Describe the solution you'd like**
with current firmware the identification of the lens changed to older firmware, so my request for an update

% exiv2 --version
exiv2 0.27.2

**before (sigma firmware 1.03):**
% exiv2 -pa --grep lens/i  ~/Pictures/Import_20200430/20200430-IMG_8228.CR2
Exif.CanonCs.LensType                        Short       1  Sigma 35mm f/1.4 DG HSM
Exif.CanonCs.Lens                            Short       3  35.0 mm
Exif.Canon.LensModel                         Ascii      74  35mm
Exif.Photo.LensSpecification                 Rational    4  35/1 35/1 0/1 0/1
Exif.Photo.LensModel                         Ascii       5  35mm
Exif.Photo.LensSerialNumber                  Ascii      11  0000000000

**after (sigma firmware 2.01):**
% exiv2 -pa --grep lens/i  ~/Pictures/Import_20200430_0004/20200430-IMG_7825.JPG
Exif.CanonCs.LensType                        Short       1  Sigma 18-35mm f/1.8 DC HSM | A
Exif.CanonCs.Lens                            Short       3  35.0 mm
Exif.Photo.LensSpecification                 Rational    4  35/1 35/1 0/1 0/1
Exif.Photo.LensModel                         Ascii      27  35mm F1.4 DG HSM | Art 012
Exif.Photo.LensSerialNumber                  Ascii      11  0000000000

attached the jpg after update:
![20200430-IMG_7825](https://user-images.githubusercontent.com/39386816/80739639-16212100-8b17-11ea-8469-502ce825c942.JPG)

**Comment by clanmills** [comment]
@MStraeten You can fix this for yourself using the file ~/.exiv2

```
538 rmills@rmillsmbp:~/Downloads $ exiv2 -pa --grep lens/i 80739639-16212100-8b17-11ea-8469-502ce825c942.JPG 
Exif.CanonCs.LensType              Short       1  Sigma 14-24mm f/2.8 DG HSM | A <--- builtin lens type
Exif.CanonCs.Lens                  Short       3  35.0 mm
Exif.Photo.LensSpecification       Rational    4  35/1 35/1 0/1 0/1
Exif.Photo.LensModel               Ascii      27  35mm F1.4 DG HSM | Art 012
Exif.Photo.LensSerialNumber        Ascii      11  0000000000
539 rmills@rmillsmbp:~/Downloads $ exiv2 -pv --grep lens/i 80739639-16212100-8b17-11ea-8469-502ce825c942.JPG 
0x0016 CanonCs      LensType          Short       1  368   <--- The LensID
0x0017 CanonCs      Lens              Short       3  35 35 1
0xa432 Photo        LensSpecification Rational    4  35/1 35/1 0/1 0/1
0xa434 Photo        LensModel         Ascii      27  35mm F1.4 DG HSM | Art 012
0xa435 Photo        LensSerialNumber  Ascii      11  0000000000
```
Enter the LensID into [canon] in ~/.exiv2 _(you'll have to create ~/.exiv2)_
```
540 rmills@rmillsmbp:~/Downloads $ bbedit "/Users/rmills/.exiv2"
541 rmills@rmillsmbp:~/Downloads $ cat ~/.exiv2
[canon]
368=Sigma 35mm F1.4 DG HSM ART <--- Identify it
```
And exiv2 will use your definition!
```
542 rmills@rmillsmbp:~/Downloads $ exiv2 -pa --grep lens/i 80739639-16212100-8b17-11ea-8469-502ce825c942.JPG 
Exif.CanonCs.LensType              Short       1  Sigma 35mm F1.4 DG HSM ART <-- Your definition
Exif.CanonCs.Lens                  Short       3  35.0 mm
Exif.Photo.LensSpecification       Rational    4  35/1 35/1 0/1 0/1
Exif.Photo.LensModel               Ascii      27  35mm F1.4 DG HSM | Art 012
Exif.Photo.LensSerialNumber        Ascii      11  0000000000
543 rmills@rmillsmbp:~/Downloads $ 
```
Lens Identification is very troubling because the Lens isn't stored in the metadata!  It's common for several lenses to use the same LensID.  So, the ~/.exiv2 file was introduced with Exiv2 v0.26 to enable you to update the lens definition on your machine.

~/.exiv2 is documented under "Configuration File" in the man page: `$ man exiv2`

**Comment by MStraeten** [comment]
Thanks for the hint
