### ISSUE TITLE
Sigma Art 85 mm F1.4 Nikon F mount support

### ISSUE THREAD

**Issue by frli8848** [Exiv2/exiv2#1208]
Hi all,

Here is a one-liner patch to support the Sigma Art 85 mm F1.8 F mount lens. The lens number is taken from Sigma's lens catalouge: https://www.sigma-global.com/en/download/lenses/brochures-manuals/

[sigma-art-85mm_f1-4-nikon-f.patch.gz](https://github.com/Exiv2/exiv2/files/4644505/sigma-art-85mm_f1-4-nikon-f.patch.gz)

[_85D6176.exv.gz](https://github.com/Exiv2/exiv2/files/4644508/_85D6176.exv.gz)

**Comment by clanmills** [comment]
Thanks, Freddie.   Good to hear from you.  Hope all's well with you and yours.

I'll have a look at this later today.    Exiv2 v0.27.3 RC2 is scheduled for release on 2020-05-31 and I expect this to be included.  https://github.com/Exiv2/exiv2/issues/1018#issuecomment-604539346

**Comment by frli8848** [comment]
Hi Robin,

Yes all good here - good luck with the release!

**Comment by clanmills** [comment]
Freddie.  This looks fine.  Can you provide another test file.  There's no exif data in that file!
```
1058 rmills@rmillsmbp:~/Downloads $ ls -l _85D6176.exv 
-rw-r--r--@ 1 rmills  staff  2492 18 May 18:01 _85D6176.exv
1059 rmills@rmillsmbp:~/Downloads $ exiv2 -pa _85D6176.exv 
Xmp.xmp.CreatorTool                          XmpText    24  NIKON D850 Ver.1.01     
Xmp.xmp.CreateDate                           XmpText    22  2020-01-25T18:48:45.42
Xmp.xmp.Rating                               XmpText     1  0
1060 rmills@rmillsmbp:~/Downloads $ 
```
I'll update the test suite and submit the PR.

**Comment by frli8848** [comment]
Robin, here is a new one.
[_85D6176.exv.gz](https://github.com/Exiv2/exiv2/files/4645895/_85D6176.exv.gz)

And, here is how I created it: 
<pre>
$ exiv2 ex _85D6176.NEF
$ gzip _85D6176.exv
</pre>

**Comment by clanmills** [comment]
Yup. `-ex` = extract XMP.  `-ea` = extract all, `-ee` = extract Exif, `-ei` = extract IPTC.

Try this:   `-ea-` = extract all the metadata and output it on stdout.
```
$ exiv2 -ea- _85D6176.NEF > issue_1208.exv
$ gzip issue_1208.exv
```

**Comment by clanmills** [comment]
This one's fine, Freddie.  I'll push the PR in the next few minutes.  Exiv2 v0.27.3 is 98% complete (only one remaining issue and it doesn't involve any code).

```
815 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ bin/exiv2 -pa --grep lens/i ~/Downloads/_85D6176-2.exv
Exif.Nikon3.LensType                         Byte        1  D G 
Exif.Nikon3.Lens                             Rational    4  85mm F1.4
Exif.Nikon3.LensFStops                       Undefined   4  7
Exif.NikonLd3.LensIDNumber                   Byte        1  200
Exif.NikonLd3.LensFStops                     Byte        1  F7.0
816 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ make
... deleted ...
817 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ bin/exiv2 -pa --grep lens/i ~/Downloads/_85D6176-2.exv
Exif.Nikon3.LensType                         Byte        1  D G 
Exif.Nikon3.Lens                             Rational    4  85mm F1.4
Exif.Nikon3.LensFStops                       Undefined   4  7
Exif.NikonLd3.LensIDNumber                   Byte        1  Sigma 85mm F1.4 DG HSM | A
Exif.NikonLd3.LensFStops                     Byte        1  F7.0
818 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ make tests
```

**Comment by clanmills** [comment]
Fix submitted.  PR #1209.  I'll merge and close #1209 when the CI has completed.
