### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#121]
Add a file indicating how to contribute to the project:
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

In this document we should explain topics such as:

- Code formatting (once we setup the clang-format configuration for it)
- Considerations about CI processed (travis-ci , appveyor, and future stuff)
- Procedures for rebasing and merging
- Other topics

**Comment by D4N** [comment]
- How to add unit test/files to the test suite
- How to write documentation
- code formatting could already be done now (not via clang-format but just a rough description how the code should look like)
- A variable, functions, member & namespace naming guide + when to use namespaces

**Comment by D4N** [comment]
This has been fixed by #171.
