### ISSUE TITLE
UBSan violations

### ISSUE THREAD

**Issue by andreafioraldi** [Exiv2/exiv2#1228]
Hi, I spotted 4 undefined behaviors while fuzzing with UBSan+ASan:
 
 Error type     : 5.73884e+21 is outside the range of representable values of type 'long'
 Error location : src/types.cpp:782:50
 Testcase   : ubsan2

 Error type     : 5.73884e+21 is outside the range of representable values of type 'int'
 Error location : src/types.cpp:793:50
 Testcase   : ubsan2

Error type     : 3.29343e+43 is outside the range of representable values of type 'long'
 Error location : src/tags_int.cpp:2203:43
 Testcase   : ubsan2

 Error type     : -1.00692e+128 is outside the range of representable values of type 'long'
 Error location : include/exiv2/value.hpp:1648:34
 Testcase   : ubsan1

I attach a zip files with the testcases, I'm using the read-metadata.cpp harness in the repo.
[ubsan_violations.zip](https://github.com/Exiv2/exiv2/files/4728421/ubsan_violations.zip)

**Comment by andreafioraldi** [comment]
There are also several unhandled exceptions due to Safe::add, but I think they are intended (?).

**Comment by clanmills** [comment]
@andreafioraldi I am very pleased to say that Team Exiv2 now has 8 enthusiastic contributors and we are planning to release Exiv2 v1.00 on 2021-012-15.  I would be delighted if you would join the team to work on this and other security related matters.

**Comment by kevinbackhouse** [comment]
I think these are probably fixed now, because we are fuzzing continuously with OSS-Fuzz. I can't reproduce these failures on the `main` branch, so I will close this issue.
