### ISSUE TITLE
Website: API documentation link

### ISSUE THREAD

**Issue by philvl** [Exiv2/exiv2#1241]
Hello Exiv2 team!

The main menu of the website displays two different links to access the API documentation:
- a direct link to the API documentation page (which works)
- an API drop-down list that does not work (the link always returns to the open page)

Note that:
- API dropdown appears in every page
- API direct link appears in the following webpages:
  - Getting started
  - Download
  - What's New
  - Metadata
  - Makernote
  - Manual
  and disappears in :
  - Examples
  - API

I think this mistake sows doubt.

Regards,

**Comment by clanmills** [comment]
I've update the web site.  I removed the drop-down from the top-level menus.  It's still in "lower" pages which I think are generated from the source code by doxygen.  When the API drop-down is there, it does work.  Where it says "Quick start", it should say "Getting started" and there's a typo in "Libary".  I'll look at this more later today and discover how the "lower pages" are generated.  So it's better.  It's still not totally fixed.

**Comment by clanmills** [comment]
I think this is fixed now.  I you agree, can you close the bug, please?

**Comment by philvl** [comment]
Thank you for your speed and efficiency :)

**Comment by clanmills** [comment]
@philvl President Thomas Jefferson said "Never put off for tomorrow anything you can get done today." and that's what I do.  Mind you, he also said "when somebody makes me angry, I count to 10 before replying.  Very angry?  100!".  I wish I could learn
