### ISSUE TITLE
exiv2 0.27.3 fails to build on PPC

### ISSUE THREAD

**Issue by pkubaj** [Exiv2/exiv2#1244]
**Describe the bug**
Building using GCC 10 on PPC/PPC64 fails with:
`cc1plus: error: '-fcf-protection=full' is not supported for this target
`

**To Reproduce**
Steps to reproduce the behaviour:

1. Try building on PPC platforms.

**Expected behavior**
exiv2 should build.

**Desktop (please complete the following information):**
 - OS: FreeBSD
 - Compiler & Version GCC 10.1
 - Compilation mode and/or compiler flags
Default flags.

**Additional context**
https://github.com/Exiv2/exiv2/commit/1ea63ccb345a4498b41cb8842622ba7ecc9fd484 fixed build on arm, ppc needs the same.

**Comment by pkubaj** [comment]
On PPC64 CMAKE_SYSTEM_PROCESSOR apparently is "powerpc64".

**Comment by clanmills** [comment]
It never fails to amaze me that two people can report almost the same thing on the same day in code that hasn't been changed for years!

Right now I'm investigating a issue with a build flag on a very elderly Xcode 6.1.  I'll apply similar medicine for `-fcf-protection=full`.

On which branch are you working?  I maintain the 0.27-maintenance branch.  Can you test my fix when it's available?

**Comment by pkubaj** [comment]
I'm not using any branch, I just build from FreeBSD ports tree.
And it's not that it got broken "years" ago. 0.27.2 built just fine, the regression happened in 0.27.3.

**Comment by clanmills** [comment]
I don't know what FreeBSD ports tree is.  I frequently build and test 0.27.3 on FreeBSD on our buildserver.  I don't have a PPC machine.  Can you test my fix when it's available?

**Comment by pkubaj** [comment]
Well, I already wrote in my 1st message that PPC need the same that was done for ARM. So the correct fix is putting:
`if (NOT (${CMAKE_SYSTEM_PROCESSOR} MATCHES "arm" OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES "powerpc"))` in `cmake/compilerFlags.cmake`.

**Comment by clanmills** [comment]
I don't know anything about that "arm" code on master.  I deal with the 0.27-maintenance branch.

**Comment by pkubaj** [comment]
Then this commit adding ARM should be merged to 0.27-maintenance. It should also add PPC (and other broken architectures, if there are any).

Anyway, I think `-fcf-protection` is supported only on x86_64, so it should only be enabled there (but that should be researched first).

**Comment by clanmills** [comment]
I've unassigned myself from this and will leave this to the people managing 'master'.

**Comment by jtojnar** [comment]
With https://github.com/Exiv2/exiv2/pull/1252 merged, this is likely fixed on master but still an issue in 0.27 branch.

**Comment by clanmills** [comment]
I agree that this is an issue on the 0.27-maintenance branch.  I tried to fix this in July.  My dyslexia got the better of me.  https://github.com/Exiv2/exiv2/pull/1245

@ryandesign offered to help.  I would very much appreciate some help with both the necessary changes (to support ARM, PPC and Xcode 6.1).  I've set up a VM for Xcode 6.1.  Should a buy a raspberry pi?  Any suggestions?

**Comment by jtojnar** [comment]
I opened https://github.com/Exiv2/exiv2/pull/1271 fixing this for 0.27.

**Comment by clanmills** [comment]
I believe #1271 solves this issue.  Thanks to @jtojnar for this contribution.  I'm going to close this.
