### ISSUE TITLE
Getty Images Personality Support Feature Request 

### ISSUE THREAD

**Issue by Constantin-Scholz** [Exiv2/exiv2#1246]
Dear Exiv2 Team,

Would it be possible to add support for the GettyImages: GettyImagesGIFT field: Personality ?

Thanks,
Consti

**Comment by clanmills** [comment]
Probably! 

I've never heard of this.  For sure, Exiv2 doesn't know 'personality'.
```
1383 rmills@rmillsmbp:~/gnu/exiv2/team/book $ taglist ALL | grep -i personality
1384 rmills@rmillsmbp:~/gnu/exiv2/team/book $ 
```

I've looked at this:  https://contributors.gettyimages.com/img/articles/downloads/7231973d-a414-4f91-8dcf-3e9a1cfd2ce2.pdf  I think it's an IPTC field.

A couple of questions:
1. Do you have a test image? 
2. Can you say something more about why you are making this request and why this should be added to Exiv2

**Comment by boardhead** [comment]
Here is an XMP file generated by ExifTool that you can use for testing:

[getty.xmp.zip](https://github.com/Exiv2/exiv2/files/4912538/getty.xmp.zip)

**Comment by clanmills** [comment]
Thank you, Phil.  What a helpful person you are.  Looks at though it's working:
```
1387 rmills@rmillsmbp:~/Downloads $ exiv2 -px getty.xmp 
Xmp.GettyImagesGIFT.AssetID                  XmpText     4  test
Xmp.GettyImagesGIFT.CallForImage             XmpText     4  test
Xmp.GettyImagesGIFT.CameraFilename           XmpText     4  test
Xmp.GettyImagesGIFT.CameraMakeModel          XmpText     4  test
Xmp.GettyImagesGIFT.CameraSerialNumber       XmpText     4  test
Xmp.GettyImagesGIFT.Composition              XmpText     4  test
Xmp.GettyImagesGIFT.ExclusiveCoverage        XmpText     4  test
Xmp.GettyImagesGIFT.GIFTFtpPriority          XmpText     4  test
Xmp.GettyImagesGIFT.ImageRank                XmpText     4  test
Xmp.GettyImagesGIFT.MediaEventIdDate         XmpText     4  test
Xmp.GettyImagesGIFT.OriginalFilename         XmpText     4  test
Xmp.GettyImagesGIFT.ParentMEID               XmpText     4  test
Xmp.GettyImagesGIFT.ParentMediaEventID       XmpText     4  test
Xmp.GettyImagesGIFT.Personality              XmpBag      1  test
Xmp.GettyImagesGIFT.PrimaryFTP               XmpBag      1  test
Xmp.GettyImagesGIFT.RoutingDestinations      XmpBag      1  test
Xmp.GettyImagesGIFT.RoutingExclusions        XmpBag      1  test
Xmp.GettyImagesGIFT.SecondaryFTP             XmpBag      1  test
Xmp.GettyImagesGIFT.TimeShot                 XmpText     4  test
1388 rmills@rmillsmbp:~/Downloads $ 
```

I'm making solid progress on the book.  I'm confident it will be finished by Christmas if nothing unusual happens (such as Alison or I get getting covid-19).

**Comment by clanmills** [comment]
I'm going to close this as we have had no response from the user.

@Constantin-Scholz If you wish to discuss this further, I will re-open the issue.

**Comment by Constantin-Scholz** [comment]
@clanmills Thank you very much it works!!! Just implemented it. Appreciate the quick help.
