### ISSUE TITLE
Investigate vcpkg support for Exiv2

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1255]
**Is your feature request related to a problem? Please describe.**
Microsoft have been developing a cross-platform package manager called vcpkg.  vcpkg is an open-source project and provides support for:

1. Visual Studio and GCC on Windows
2. GCC on macOS and linux.

I was very pleased to discover that Exiv2 v0.27.3 is already supported.

**Describe the solution you'd like**
I would like to know something about the performance on vcpkg and add a section to README.md.  For Exiv2 v0.27.4, I intend to continue to recommend conan+CMake for Visual Studio builds and CMake for all other platforms.

**Describe alternatives you've considered**
I have successfully built Visual Studio 2019 + Exiv2/DLL and exiv2.exe.  https://github.com/Exiv2/exiv2/issues/1250#issuecomment-663360908

**Additional context**
No comment.

**Comment by tester0077** [comment]
Just installed exiv2 via vcpkg on a spare machine.
By default it installed the shared library version for x86 as well as all of its dependencies which had not been installed as yet.
As an experiment I also installed exiv2[unicode] and it looks like it replaced the non-Unicode version.
Still have to sort out what if any implications either versions imply for my use.
Another experiment was to install exiv2:x86-windows-static
It too, seems to have worked, and installed all of the static dependencies, though, at this time, I have not tested any of these.
Presumably, the 64-bit version ought to be installable via install exiv2:x64-windows for the sharable/DLL version ....

Question: (from what I have seen during the install process, vcpkg uses an Exiv2 source package from the 'community' stash somewhere.) :
Do we know which Github version this corresponds to? and
Can we control which version is used - i.e. who looks after updating for newer versions?
Can we control which version is actually used?

**Comment by clanmills** [comment]
I don't have time to work on this.

**Comment by clanmills** [comment]
I will never have time to work on this.  I believe it works fine.

**Comment by tester0077** [comment]
Good decision; Exiv2 under vcpkg is maintained by other interested parties according to their needs and completely beyond the control of the exiv2 maintainers

**Comment by clanmills** [comment]
Thanks, @tester0077.  If there's a issue, somebody will come to us for support.

The Exiv2 v1.00 project is coming together well.  I never thought I would be with Exiv2 which it reached v1.00.  It'll be there by December.  I now have the right people working with me to make that happen.  Boy it's been a struggle.  A successful struggle.
