### ISSUE TITLE
Allow to set configuration path holding exiv2.ini

### ISSUE THREAD

**Issue by norbertj42** [Exiv2/exiv2#1256]
**Is your feature request related to a problem? Please describe.**
I am using the library exiv2 in an own program for Windows. I would like to have the exiv2.ini stored in %APPDATA% instead of the program's folder. Also I want to enable the user to specify the location, e.g. if he is using also exiv2 as commandline tool, he may configure my program to use the exiv2.ini stored in the commandline tool's folder (instead of having two files).

**Describe the solution you'd like**
My idea is to modify makernote_in.cpp. A new method allows to store the path of exiv2.ini in a variable. getExiv2ConfigPath checks first, if that variable is set. If it is not set, it returns the path in the same way as now.

**Comment by clanmills** [comment]
The configuration file is stored in a user dependant file.  On Unix systems, it's $HOME/.exiv2 and on Visual Studio builds it is %USERPROFILE%/exiv2.ini.  You can reveal it with:

```
C:\Users\rmills\gnu\github\exiv2\0.27-maintenance\build>bin\exiv2 -vVg config -g version -g platform
exiv2 0.27.3.20
platform=windows
version=13.26 (2019/x64)
config_path=C:\Users\rmills\exiv2.ini
```

Cygwin64 and MinGW/msys2 follow the Unix convention:

```
237 CYGWIN rmills@rmillsmm-w10:~/gnu/github/exiv2/0.27-maintenance/build $ bin/exiv2 -vVg config --grep version --grep platform
exiv2 0.27.3
platform=cygwin
version=7.4.0
config_path=/home/rmills/.exiv2
238 CYGWIN rmills@rmillsmm-w10:~/gnu/github/exiv2/0.27-maintenance/build $
```

It's in a user dependant file so that one file can be shared by every application on the user's machine.

**Comment by norbertj42** [comment]
Ok, that should fit for most users, thanks for the explanation.

**Comment by clanmills** [comment]
I'm pleased that you're happy with this explanation.  I've reviewed the information in the man page exiv2.1 and it seems complete and adequate.  It says:

```
CONFIGURATION FILE
       Exiv2  can read an optional configuration file ~/.exiv2 on Unix systems
       and %USERPROFILE%\exiv2.ini on Windows (using a Visual  Studio  build).
       Cygwin and MinGW/msys2 follow the unix convention and use ~/.exiv2  You
       can determine the location of the configuration file with the command:

       $ exiv2 --verbose --version --grep config_path
       exiv2 0.27.0.1
       config_path=/Users/rmills/.exiv2

       The purpose of the configuration file is to define your own lenses  for
       recognition by Exiv2.  The configuration file is in Windows .ini format
       and  has  sections  for	each  of   the	 major	 camera   manufactures
       canon,nikon,pentax,minolta,olympus  and	sony.	The  lens  metadata is
       stored as a integer called the lensID.  You can change  the  lens  name
       associated with any lensID.

       $ cat ~/.exiv2
       [nikon]
       146=Robin's Sigma Lens  <--- The name of your lens

       You obtain the lensID for your camera with the command:
       $ exiv2 -pv --grep lens/i http://clanmills.com/Stonehenge.jpg
       0x0083 Nikon3	   LensType	      Byte	 1  14
       0x0084 Nikon3	   Lens 	      Rational	 4  180/10 2500/10 35/10 63/10
       0x008b Nikon3	   LensFStops	      Undefined  4  55 1 12 0
       0x000c NikonLd3	   LensIDNumber       Byte	 1  146 <--- This number
       0x000d NikonLd3	   LensFStops	      Byte	 1  55
```
