### ISSUE TITLE
Update testsuite to read and write metadata of PSD files

### ISSUE THREAD

**Issue by tbeu** [Exiv2/exiv2#1261]
Derived from #1260: Update the testsuite to read and write metadata of PSD files.

**Comment by clanmills** [comment]
PR #1261 submitted.

**Comment by clanmills** [comment]
This has been dealt with on the 0.27-maintenance branch.  I've made a proposal to release v0.28 in Spring 2021 and this change will be included: https://github.com/Exiv2/exiv2/issues/1018#issuecomment-694383754
