### ISSUE TITLE
Exiv2::BasicIo:: AutoPtr and Exiv2::BasicIo::UniquePtr

### ISSUE THREAD

**Issue by tomerbarak11** [Exiv2/exiv2#1264]
I'm wondering,
Why does Exiv2::BasicIo::AutoPtr work in Windows and doesn't work in Linux?
Why does Exiv2::BasicIo::UniquePtr work in Linux and doesn't work in Windows?
I want to write the same code for both Operation Systems Windows and Linux and I can't.

**Comment by clanmills** [comment]
Exiv2 v0.27.3 (and earlier) uses AutoPtr and should be compiled with C++98.  It will compile with C++11 and C++14 using the CMake options:  `-DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_FLAGS=-Wno-deprecated`  I was the release engineer for every release of Exiv2 v0.27 and believe it compiles on all supported platforms.

Exiv2 on the 'master' branch user UniquePtr and should be compiled with C++11 or later.  The 'master' branch will be labelled Exiv2 v0.28 when it is eventually released.  I'm not involved with 'master', however I believe it compiles on all platforms.

What is your version of Exiv2 (look in CMakeLists.txt), how did you obtain it, and what compiler(s) are you using?

**Comment by clanmills** [comment]
I've thought of how you could arrive in this situation.  You have a different versions of the library on Linux and Windows.  So you are using a version of Exiv2 v0.27 on Windows and 'master' (0.27.99.0).

We took decisions in 2018 to:

1. Modernise the code to C++11 (and later)
2. Remove some features
3. Not preserve the API from 0.27
4. 0.27 "dot" release issue deprecation warnings for features removed from 'master' (0.28).

You have to choose the work with 0.27, or 'master' (0.28).  To ease the transition to 0.28, we have published 3 "dot" releases of Exiv2 v0.27 and will publish another if necessary in 2021.  We provide the macro `EXIV2_TEST_VERSION` to enable you to write code which can works with both.  If you are writing new code, you should choose to develop with 0.27, or 'master' and keep your life simple!

**Comment by clanmills** [comment]
I'm going to close this.  The issue will be reopened when the user provides evidence.
