### ISSUE TITLE
segfault in libexiv2.so.26.0.0

### ISSUE THREAD

**Issue by brkorb** [Exiv2/exiv2#1265]
**Describe the bug**
    [196804.121122] single[20429]: segfault at 10 ip * sp * error 4 in libexiv2.so.26.0.0[*+2d9000]
    [196804.121127] Code: 0f 87 af 03 00 00 48 39 dd 0f 87 15 ff ff ff 0f 1f 80 00 00 00 00 48 8d 05 71 53 31 00 4c 8b 74 24 48 4c 8b 6c 24 40 48 8b 00 <48> 8b 68 10 48 8d 58 08 48 89 44 24 18 48 89 5c 24 10 48 85 ed 75

**To Reproduce**
Steps to reproduce the behaviour:
1. No idea whether or not anyone else can reproduce. This is from "dmesg" output on Linux.

**Expected behavior**
libraries should never, ever seg fault

**Desktop (please complete the following information):**
 - OS: Linux
 - Compiler & Version
    $ gcc --version
    gcc (SUSE Linux) 7.5.0
    Copyright (C) 2017 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I didn't look. I took the source release and ran:
     cmake .. && make && make install && echo success

**Additional context**

**Comment by clanmills** [comment]
There is no information in this report with which to reproduce this issue, so it's impossible to investigate and fix.  v0.26.0 is a rather elderly version of Exiv2.  I believe somebody at Suse is back-porting security fixes, so it's possible that it is already fixed on the 0.26 branch.

I'm going to (reluctantly) close this issue as I cannot think of any way in which to give this matter more consideration.

**Comment by brkorb** [comment]
On my system, at least, it happens over and over.
    dmesg | sed -n '/segfault at 10 ip /s/].*/]/p;/] Code: 0f 87 /s/].*/]/p' | sort -u > ~/tmp/fault-times.txt

[fault-times.txt](https://github.com/Exiv2/exiv2/files/5145331/fault-times.txt)

so every few seconds. I'd be happy to diagnose.

**Comment by brkorb** [comment]
By the way, I downloaded and built the sources from the release link on GitHub, so I'm a bit surprised to learn it's long in the tooth. Ah:
`$ sudo find /usr/lib* /lib* /usr/local/lib* -type f -name 'libexiv2.so*'
/usr/lib64/libexiv2.so.26.0.0
/usr/local/lib64/libexiv2.so.0.27.3`
so "cnf" doesn't know about the "exiv2" command (hence my download and build), but SuSE installed the old library in their just-released PRETTY_NAME="openSUSE Leap 15.2". So, to reproduce, just use the current exiv2 with the old library. There are mechanisms for causing the dynamic link to fail so the problem can be more readily identified. I'll wrap your executable in a script that forces the correct library.

**Comment by clanmills** [comment]
Thanks.  I don't know what dmsg or cnf is.  Can you try this will a more recent release such as Exiv2 v0.27.3 which shipped on 2020-06-30.  You can get the code from https://exiv2.org

If this is restricted to v0.26, can you use the the 0.26 branch on GitHub.

Are you mixing and matching the exiv2 command-line program with different versions of the library.  I wouldn't expect that to work.  The command `$ exiv2 --verbose --version` reports about 100 lines of build related information and it reports the path of both the exiv2 executable and the library:

```bash
554 rmills@rmillsmbp:~/Downloads $ exiv2 --verbose --version | grep exiv2
exiv2 0.27.3
exiv2=0.27.3
package_name=exiv2
executable=/usr/local/bin/exiv2
library=/usr/local/lib/libexiv2.0.27.3.dylib
config_path=/Users/rmills/.exiv2
555 rmills@rmillsmbp:~/Downloads $ 
```

**Comment by clanmills** [comment]
Thank You for volunteering to work with me on this.  I'm reopening this.  I suspect we'll have some fun.  These things are usually easy to fix once we have a solid way to reproduce the issue.

**Comment by brkorb** [comment]
"cnf" is a command on Linux. It stands for, "command not found" and searches the known software depots for packages that supply that command. Some command that I have likely uses "libexiv2" and so the library was sucked in, but SuSE doesn't have a package that includes the "exiv2" command itself, hence "cnf" doesn't find the command.

"dmsg" is a system command that prints out system messages, like unexpected seg faults. The numbers I showed are seconds since last boot up, to the microsecond. (Supposedly, the clock actually has less resolution than that.)

**Comment by brkorb** [comment]
`$ sudo lsof /usr/lib64/libexiv2.so.26.0.0

lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.`

(lsof: list openers of a file)

I'm going to reboot and this may go away. It seems the "fuse" file system (kernel hooks to reach into user space daemons [programs] to satisfy file system request) is using the library and I don't have visibility into what it's doing.

**Comment by brkorb** [comment]
> [   33.171882] fuse: init (API version 7.31)
> [   47.935091] show_signal_msg: 42 callbacks suppressed
> [   47.935094] single[2762]: segfault at 10 ip 00007f686888da0c sp 00007f685ca04fb0 error 4 in libexiv2.so.26.0.0[7f6868678000+2d9000]
> [   47.935102] Code: 0f 87 af 03 00 00 48 39 dd 0f 87 15 ff ff ff 0f 1f 80 00 00 00 00 48 8d 05 71 53 31 00 4c 8b 74 24 48 4c 8b 6c 24 40 48 8b 00 <48> 8b 68 10 48 8d 58 08 48 89 44 24 18 48 89 5c 24 10 48 85 ed 75
> [   85.904953] tracker-miner-f[2524]: segfault at ffffffff ip 00007fe0ecaf6a38 sp 00007ffdd2f64030 error 4 in libglib-2.0.so.0.6200.5[7fe0ecaa8000+122000]
> [   85.904959] Code: 00 00 48 8b 7d 20 48 8b 33 e8 24 ff ff ff 48 8b 5b 08 48 85 db 75 eb 48 8b 45 58 48 8b 58 18 48 85 db 74 24 66 0f 1f 44 00 00 <48> 8b 33 48 8b 7d 20 e8 fc fe ff ff 48 8b 5b 08 48 85 db 75 eb 48

**Comment by clanmills** [comment]
The world of technology is a pyramid of unbelievable and unknowable complexity.

Exiv2 is me and Lizzie (the cat) are sitting in England working on this stuff.  We have to idea how or where it will be deployed.  It's amazing that this works most of the time.

I know the exiv2 library is used on the gnome desktop to display previews and other metadata.  If you take a random version of the command-line program and ask it dance with the installed library, you are on thin ice.  I thought SONAME was meant to marry the executable to the correct library.

![dependency](https://user-images.githubusercontent.com/529982/91640377-0d811e80-ea15-11ea-9ac4-7ad92611b2ac.png)

**Comment by brkorb** [comment]
Can I plagiarize that drawing?

**Comment by clanmills** [comment]
I doesn't appear that the command-line program and the issue reported by dmsg about fuse crashing on libexiv2.so.26.0.0 are unrelated.

We need to know what fuse is doing.  I've used fuse (about 10 years ago) to mount an ssh share on macOS.

I have a couple of Suse VMs.  One has a cute name.  Is it "tangleweed"?  Should I get 15.2?  Get out your flash light to show me where to go next.

**Comment by clanmills** [comment]
_Can I plagiarize that drawing?_ Sure.  I stole it from somewhere.  I think it might have been the daily "Code Project" email about 3 weeks ago.

Curiously, my Adobe friend Daniel sent it to me on Friday and said "They don't know how to spell England".  I had stolen it earlier from somewhere.  It's in my book.  https://clanmills.com/exiv2/book/#13 under "Project Management".  I  want to finish the book by the end of 2020 and retire.  I've done my best and can take no more abuse from the community.

I've been searching for a little Scottish weight-lifter cartoon to put beside it.  Me being crushed by the community.  I know a retired commercial artist and I might bribe him to immortalise me!

![robinkilt](https://user-images.githubusercontent.com/529982/91640689-55a14080-ea17-11ea-83ae-4fbcad1c6c59.gif)

**Comment by brkorb** [comment]
This happens in a constrained context that is unlikely to be run into very often.
