### ISSUE TITLE
Fix test/Makefile all: 

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1269]
https://github.com/Exiv2/exiv2/pull/1168#issuecomment-683378035

**Comment by kmilos** [comment]
FWIW, current (0.27.3) `python_tests` fails for msys2 builds OOB since EXIV2_EXT is not defined by cmake:

```
---- Running python_tests ----

bash -c  . functions.source ; cd ../tests ; if [ ! -z  ]; then verbose=--verbose ;fi ; python3 runner.py
Traceback (most recent call last):
  File "runner.py", line 48, in <module>
    system_tests.configure_suite(conf_file)
  File "C:\msys64\home\kmilos\exiv2-0.27.3\tests/system_tests.py", line 175, in configure_suite
    raise ValueError(
ValueError: Path replacement for exiv2: C:/msys64/home/kmilos/build/bin/exiv2 does not exist (was expanded from C:/msys64/home/kmilos/build/bin/exiv2)
make[4]: *** [Makefile:152: python_tests] Error 1
make[3]: *** [CMakeFiles/python_tests.dir/build.make:77: CMakeFiles/python_tests] Error 2
make[2]: *** [CMakeFiles/Makefile2:301: CMakeFiles/python_tests.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:308: CMakeFiles/python_tests.dir/rule] Error 2
make: *** [Makefile:197: python_tests] Error 2
```

`EXIV2_EXT=.exe make python_tests` does work.

**Comment by clanmills** [comment]
Yes, this is getting attention.  PR #1257 in response to proposal #1215.  The aim is to only have python_tests and the functionality of bash_tests is being rewritten in python.  I discussed killing off EXIV2_EXT with LeoHsiao1 earlier today.

Are you sure about this?  I was run those tests frequently (on MinGW/msys2 and cmd.exe) and I don't set either EXIV2_BINDIR or EXIV2_EXT.  The defaults work OK for me.  Perhaps it creep into the environment from functions.source (which is also heading into history).

**Comment by kmilos** [comment]
Yes, just tried on pristine 0.27.3 source tarball...

EXIV2_BINDIR is taken care of e.g. [here](https://github.com/Exiv2/exiv2/blob/194bb65ac568a5435874c9d9d73b1c8a68e4edec/CMakeLists.txt#L118).

For `bash_tests`, EXIV2_EXT is taken care of in [funsctions.source](https://github.com/Exiv2/exiv2/blob/194bb65ac568a5435874c9d9d73b1c8a68e4edec/test/functions.source#L427). Seems not so for `python_tests`...

I'll take look at the other threads and follow up there, and try out master at some point as well.

**Comment by clanmills** [comment]
You're welcome to try out master.  I'm not involved in that project.  I agreed to be the release engineer for v0.27 and the dots while the others refactored the code for the future.  The LGM Conference (Libre Graphics Meeting) is due to be held in Rennes in May 2021.  I'll give have a talk about the book and run an afternoon workshop.  

The book's coming along well.   I'd like to complete a book about Exiv2 before my 70th birthday on 2021-01-18.  After Rennes, I will retire.  Current status of the book:  https://clanmills.com/exiv2/book/

**Comment by clanmills** [comment]
@LeoHsiao1  There are two different matters here.

1 Fix test/Makefile#45 (as discussed in #1168)
test/Makefile#45 should be:

```make
all: tests
```

2 Remove EXIV2_EXT from the code base (see comments above by @kmilos)

I've opened a new issue about this #1273.

**Comment by LeoHsiao1** [comment]
I have received nearly 10 email notifications, and it is good to have your words as a summary.

**Comment by clanmills** [comment]
I'm going to close this.  I don't see an issue here as I believe the test commands in README.md all work as documented.

### 4.5 Test Summary

| *Tests* | Unix Style Platforms _(bash)_ | Visual Studio _(cmd.exe)_ |
|:-- |:---                                |:--                                   |
| | $ cd \<exiv2dir\>/build **or**<br> $ cd \<exiv2dir\>/test          |  \> cd \<exiv2dir\>/build             |
| tests | $ make tests                       | \> cmake --build . --config Release --target tests |
| bash_tests | $ make bash_tests                       | \> cmake --build . --config Release --target bash_tests |
| python_tests | $ make python_tests                       | \> cmake --build . --config Release --target python_tests |
| unit_test | $ make unit_test                       | \> cmake --build . --config Release --target unit_test |
| version_test | $ make version_test                       | \> cmake --build . --config Release --target version_test |
