### ISSUE TITLE
Remove EXIV2_EXT from code-base

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1273]
See https://github.com/Exiv2/exiv2/issues/1269#issuecomment-685622174

This environment string has caused difficulties on #1257 and should be removed from the code AND documentation.

I intend to invite @LeoHsiao1 to work on this.

**Comment by kmilos** [comment]
Thanks @clanmills, happy to help w/ testing this on msys2/mingw64

**Comment by LeoHsiao1** [comment]
Ok, I will try to remove `EXIV2_EXT` completely from the `exiv2/tests` directory.

**Comment by clanmills** [comment]
@LeoHsiao1.  Please keep focus and get #1257 finished and merged.  Removing EXIV2_EXT from system_tests is a different issue.

I've asked GitHub to invite you to join Team Exiv2 as this will make it easier for me to assign issues for your attention.  Because you have write access, you can re-assign issues to me if you don't want to deal with something assigned to you!

**Comment by LeoHsiao1** [comment]
Are you asking me to ignore #1273 until #1257 is done?
Then directly submit #1273 to the Maintainer branch?

**Comment by LeoHsiao1** [comment]
I believe #1257 will be completed quickly if there are no new problems

**Comment by clanmills** [comment]
I also think we are almost 100% done on #1257.  I think we only need to remove one line of code from tests/system_tests.py.  That's it.

```bash
565 rmills@rmillsmbp:~/gnu/github/exiv2/leo/tests $ grep BT *.py
system_tests.py:from bash_tests import utils as BT
system_tests.py:    BT.Config.bin_dir       = os.path.abspath(config['ENV']['exiv2_path'])
system_tests.py:    BT.Config.data_dir      = os.path.abspath(config['paths']['data_path'])
system_tests.py:    BT.Config.tmp_dir       = os.path.abspath(config['paths']['tmp_path'])
system_tests.py:    BT.Config.exiv2_ext     = config['ENV']['binary_extension']   # <---- Remove this!
system_tests.py:    BT.Config.exiv2_http    = config['ENV']['exiv2_http']
system_tests.py:    BT.Config.exiv2_port    = int(config['ENV']['exiv2_port'])
566 rmills@rmillsmbp:~/gnu/github/exiv2/leo/tests $ 
```

I would like to see the bash wrappers for `$ make unit_test` and `$ make version_test` removed.  However, that can go into a future PR.

Keep the 'rocknroll' magic.  I have no idea what it does.  However it's not causing me any trouble.  Keep it!  Should it go into `execute()`?

**Comment by clanmills** [comment]
Always submit into 0.27-maintenance.

I don't know if anybody is working on 'master' any more.  Nothing much has been done since January.

**Comment by clanmills** [comment]
And yes, don't bother with #1273 until #1257 is merged.

**Comment by clanmills** [comment]
I think this is finished with #1289

**Comment by piponazo** [comment]
Hi guys,

I would like to know if this work (the whole work about migrating bash tests to python) is being ported to master or if you had any discussion about it.

**Comment by clanmills** [comment]
We're not done yet with #1215 on 0.27-maintenance. 

I would like to operate both `test/*.so` scripts and their python replacements `tests/bash_tests/*.py` for a while (perhaps two months).

Then we should "decommission" tests/*.so by updating test/makefile, test/CMakeList.txt, README.md and README-CONAN.md  #1274

After that we can port them to 'master'.  I hope porting will be painfree and _only_ involve:
1. syncing 0.27-maintenance/test  into master/test
2. syncing 0.27-maintenance/tests into master/tests/
3. syncing 0.27-maintenance/*.md into master/

This will cause EXIV2_EXT to disappear from 'master'.

The big win here is to simplify running the test suite on Visual Studio builds.  Users will have to install python3 (with the lxml support) and not require bash/make and other MinGW/msys2 utilities to be on their PATH.

The aim of #1215 is to extend the excellent tests/system_tests.py developed by Dan while making life for Visual Studio users much simpler.
