### ISSUE TITLE
Names of two tags seem to be strange, typo?

### ISSUE THREAD

**Issue by norbertj42** [Exiv2/exiv2#1344]
I found two tags, which look strange to me:

Exif.Fujifilm.Tone: the description is "Contrast setting" which in my eyes does not fit to the name.
Exif.Panasonic.BurstSheed: the description is "Burst Speed in pictures per second"; I think there is a typo in name ...S**h**eed should be ...S**p**eed.

By the way, may I ask another question: were do you get the names and descriptions from? Some of course come from specifications, but do you get also specifications from manufacturers?

**Comment by clanmills** [comment]
I don't know how the tag names arrived in the code.  Lots of searching about on the internet, I believe.  The URLs used are documented:  https://exiv2.org/makernote.html

The tags are compiled into the tagInfo arrays in the code.  There's program samples/taglist which formats a file of comma-separated data about the tags and there's a script in the web-site/release code that builds the web-site for the different IFDs.  For example:  https://exiv2.org/tags.html

There's a longer discussion about tag names in my book:  https://clanmills.com/exiv2/book/#8-2

BurstSheed has to be a typo!

**Comment by clanmills** [comment]
I'll deal with this and #1393 in one PR.

**Comment by clanmills** [comment]
@kmilos Can I ask you to deal with this, please?  It's very simple.  I decided not to fold this in't #1393.

**Comment by kmilos** [comment]
The Fuju tag is named "Tone" by at least two sources:

https://web.archive.org/web/20111025004429/http://park2.wakwak.com/~tsuruzoh/Computer/Digicams/exif-e.html
http://www.ozhiker.com/electronics/pjmt/jpeg_info/fujifilm_mn.html#Fujifilm_Tags

I have just slightly improved the description...

**Comment by clanmills** [comment]
If you fancy a challenge, take a look at #1334.  It's a magnitude more difficult than the DNG/Tiff-EP tags as you'll probably need to define a binary decoder.  Happy to mentor you.  Happy if you leave this to me.

Happy Thanksgiving.  I recorded Sousa's "Washington Post March" this morning to share with some chums.  I've been learning the Euphonium for 2 years. https://youtu.be/NnwqaRyAWgE

**Comment by kmilos** [comment]
Thanks for that, a very cheerful march rendition!

Unfortunatly, I won't be able to take on some more demanding tasks in the near future due to other responsibilities :(

**Comment by clanmills** [comment]
That's fine, Milo&scaron;.  I appreciate what you have done.  I'll take care of #1334.
