### ISSUE TITLE
Update test/bash_tests/testcases.py exiv2-test to deal with PSD files

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1357]
@LeoHsiao1 Can you investigate this, please?

https://github.com/Exiv2/exiv2/pull/1356#issuecomment-707863209

test/exiv2-test.sh was updated in #1342 to run tests on PSD (photoshop) files.  Three files were added to the test suite.

In the pythonic tests/bash_tests, adding the three files to the arrays in `exiv2-test()` is not sufficient.  We get the error:

```bash
======================================================================
ERROR: exiv2_test (bash_tests.testcases.TestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rmills/gnu/github/exiv2/0.27-maintenance/tests/bash_tests/testcases.py", line 379, in exiv2_test
    out += BT.Executer('exiv2 -u -v -b -pt print        {images_2_str}', vars())
  File "/Users/rmills/gnu/github/exiv2/0.27-maintenance/tests/bash_tests/utils.py", line 418, in __init__
    self.run()
  File "/Users/rmills/gnu/github/exiv2/0.27-maintenance/tests/bash_tests/utils.py", line 456, in run
    raise RuntimeError('\n' + log.to_str())
RuntimeError: 
[ERROR] Failed to execute: ['/Users/rmills/gnu/github/exiv2/0.27-maintenance/build/bin/exiv2', '-u', '-v', '-b', '-pt', 'print', 'exiv2-empty.jpg', '20031214_000043.jpg', '20000506_020544.jpg', '20040329_224245.jpg', '20010405_235039.jpg', '20030925_201850.jpg', '20001026_044550.jpg', '20030926_111535.jpg', '20040316_075137.jpg', '20040208_093744.jpg', '20050218_212016.jpg', '20050527_051833.jpg', '20060802_095200.jpg', '20001004_015404.jpg', '20060127_225027.jpg', '20110626_213900.psd']
[ERROR] The asserted return code is [0], but got 255
[INFO] OUTPUT:
....
```

I've also seen messages about 20110626_213900.psd being missing although it is in the repos.

**Comment by LeoHsiao1** [comment]
- I am still investigating the error reporting 'Failed to execute'.
- The reason for `20110626_213900.psd being missing` is that  it hasn't been copied at all.
   Because `exiv2-test.sh` copies only the images from the first array:
    <https://github.com/Exiv2/exiv2/blob/fc0cc4e238e1cd4b6877f89aa3c1eec330544447/test/exiv2-test.sh#L69>
   So does Testcases.py:
    <https://github.com/Exiv2/exiv2/blob/fc0cc4e238e1cd4b6877f89aa3c1eec330544447/tests/bash_tests/testcases.py#L353-L354>
   So do you want to change this code?

- BTW, are you sure there are two `20060127_225027.jpg`?
   <https://github.com/Exiv2/exiv2/blob/fc0cc4e238e1cd4b6877f89aa3c1eec330544447/test/exiv2-test.sh#L48-L50>

**Comment by clanmills** [comment]
I noticed that I had duplicated 20060127_225027.jpg.  Cut'n'paste error.  Should be harmless.

You can change `exiv2-test.sh` if you wish.  I don't know anything about that code.  Never looked at it before.  It's quite possible the test suite creates the .exv files itself.  I think you're going to have to study that code and figure out what it does, and then decide what should be done.

**Comment by LeoHsiao1** [comment]
When I changed the following code in testcases.py:
```py
        for i in images_1 + ['20110626_213900.psd']:
            BT.copyTestFile(i)
```
The error is reduced, but the output does not match:
```sh
[ERROR] The output of the testcase mismatch the reference
[INFO] The output has been saved to file /mnt/d/1/exiv2/test/tmp/exiv2-test.out
[INFO] simply_diff:
/mnt/d/1/exiv2/test/data/exiv2-test.out: 8606 lines
/mnt/d/1/exiv2/test/tmp/exiv2-test.out: 8771 lines
The first mismatch is in line 131:
< File  1/15: exiv2-empty.jpg
> File  1/16: exiv2-empty.jpg
```

I noticed that you modified the reference file `test/data/exiv2-test.out` in Commit <https://github.com/Exiv2/exiv2/commit/fc0cc4e238e1cd4b6877f89aa3c1eec330544447>(`Fixing previous incorrect commit`).
Is the current reference file accurate?

**Comment by clanmills** [comment]
Time for you to got to bed, young man.

Well, the code in test/exiv2-test.sh and the refererence output in test/data/exiv2-test.out are a pair.  When you change the test code, you the reference output usually needs to be changed.  If you believe the test is working correctly and the reference output is wrong, you can simply `cp test/tmp/exiv2-test.out test/data/exiv2-test.out` and `git add test/data/exiv2-test.out`

It this case, the difference is because the of the length of the array is reported - so `cp` and `git add` is almost certainly the correct fix.

**Comment by LeoHsiao1** [comment]
Submitted #1362  , please move to discuss there.
