### ISSUE TITLE
Absolute path to libexpat in generated exiv2Config.cmake

### ISSUE THREAD

**Issue by kmilos** [Exiv2/exiv2#1363]
**Describe the bug**
The generated and packaged share/cmake/exiv2Config.cmake contains an absolute path, e.g.

```
# Create imported target exiv2-xmp
add_library(exiv2-xmp STATIC IMPORTED)

set_target_properties(exiv2-xmp PROPERTIES
  INTERFACE_LINK_LIBRARIES "D:/a/_temp/msys/msys64/mingw64/lib/libexpat.dll.a"
)
```

**To Reproduce**
From msys2 terminal, run `makepkg-mingw` on the mingw-w64-exiv2/PKGBUILD and observe the telling

```
==> WARNING: Package contains reference to $(cygpath -m /)
````

near the end of the output.

**Expected behavior**
No warning during build and no absolute paths in shipped & installed package.

**Desktop (please complete the following information):**
 - Version 0.27.3
 - OS: Windows
 - Compiler & Version: gcc 10.2 (mingw-w64)

**Comment by clanmills** [comment]
This is a surprise.  Thanks to the work earlier this week on #1356 with @gaaned92, we know about using the mingw tools and installing GCC 10.2.   On macOS, the generated file exiv2Config.cmake has:

```
# Create imported target exiv2-xmp
add_library(exiv2-xmp STATIC IMPORTED)

set_target_properties(exiv2-xmp PROPERTIES
  INTERFACE_LINK_LIBRARIES "/usr/local/lib/libexpat.dylib"
)
```
It has an absolute path which might be derived from the `prefix` directory (/usr/local by default).  However looking in CMakeCache.txt, I see:

```bash
758 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ grep local CMakeCache.txt  | grep expat
EXPAT_LIBRARY:FILEPATH=/usr/local/lib/libexpat.dylib
exiv2-xmp_LIB_DEPENDS:STATIC=general;/usr/local/lib/libexpat.dylib;
pkgcfg_lib_PC_EXPAT_expat:FILEPATH=/usr/local/lib/libexpat.dylib
FIND_PACKAGE_MESSAGE_DETAILS_EXPAT:INTERNAL=[/usr/local/lib/libexpat.dylib][/usr/local/include][v2.2.9()]
PC_EXPAT_LDFLAGS:INTERNAL=-L/usr/local/lib;-lexpat
PC_EXPAT_STATIC_LDFLAGS:INTERNAL=-L/usr/local/lib;-lexpat
759 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

Can you look at that file, please?  Perhaps you're linking expat from  `D:/a/_temp/msys/msys64/mingw64/lib/` and your generated exiv2Config.cmake is correct!  And can you run the following command to discover which library is being loaded at run-time:

```bash
759 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ bin/exiv2 -vVg lib | grep expat
library=/usr/local/lib/libexpat.1.6.11.dylib
760 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

Tomorrow, I'll investigate on MinGW/msys2.  @piponazo is our CMake wizard and may say something about this.

**Comment by piponazo** [comment]
Thanks for reporting this. There is something I do not understand though. Are you trying to consume the `share/cmake/exiv2Config.cmake` from a exiv2 version that you have compiled by youself? Or are you trying to consume some of the pre-compiled binaries in this page: https://exiv2.org/download.html?

It is true that I have observed this problem in the past, but up to now nobody complained about it.  I have been checking the CMake doc, and there are some mentions about how to fix this issue:

https://cmake.org/cmake/help/git-stage/guide/importing-exporting/index.html
https://cmake.org/cmake/help/git-stage/guide/importing-exporting/index.html#creating-relocatable-packages

I will try to dig into it and try to solve the issue.

**Comment by clanmills** [comment]
I've had a new thought about this.  Can you send us the output from the cmake command, please?  I will look at this later today on MinGW/msys2 - however perhaps there will be a clue in your cmake output.  Please run the command in a clean/empty build directory.

**Comment by kmilos** [comment]
The path above is from the shipped package here https://packages.msys2.org/package/mingw-w64-x86_64-exiv2?repo=mingw64 and clearly comes from the build machine setup.

For my local build it is packaged as

```
set_target_properties(exiv2-xmp PROPERTIES
  INTERFACE_LINK_LIBRARIES "C:/msys64/mingw64/lib/libexpat.dll.a"
) 
```

In the MINGW packages you ship at exiv2.org it is hard-coded to

```
set_target_properties(exiv2-xmp PROPERTIES
  INTERFACE_LINK_LIBRARIES "/usr/lib/libexpat.dll.a"
) 
```

**Comment by clanmills** [comment]
What does this do?

> To Reproduce
> From msys2 terminal, run makepkg-mingw on the mingw-w64-exiv2/PKGBUILD and observe the telling
> 
> ==> WARNING: Package contains reference to $(cygpath -m /)
> 

Is this the concern of Exiv2?

**Comment by kmilos** [comment]
> Is this the concern of Exiv2?

As mentioned above, you also have absolute paths in the packages you ship on exiv2.org.

The `makepkg-mingw` warning is just how I noticed it.

**Comment by clanmills** [comment]
I'm not trying to resist you.  I'm trying to understand what's wanted.  I think @piponazo does understands the issue.

The builds we publish on exiv2.org are produced by CPack.  The build machine builds them with the default _**prefix**_ (/usr/local on macOS).   You are expected to install them into _**prefix**_ as documented in ReadMe.txt in the bundle ( releasenotes/__platform__/ReadMe.txt).  If you want to install into a different _**prefix**_, you have to build from source.  Looks as though the MinGW _**prefix**_ is C:/msys64/mingw64/

**Comment by kmilos** [comment]
As mentioned above, you have "/usr/lib/libexpat.dll.a" in the MinGW package on exiv2.org

This absolute path does not exist on Windows.

**Comment by clanmills** [comment]
I've just done a build on the "new to me, mingw-64" and it installed the localisation files into `c:\Program Files (x86)\exiv2\share...`.  I don't know where is install exiv2.exe.  

The builds on exiv2 have been tested (by hand) in the msys2 environment.  The notes in ReadMe.txt are valid.  I have /usr/lib/libexpat.dll.a installed in MinGW/msys2 msys2 environment on my machines.

What we've discovered here is that there is an assumption that the dependences (expat and zlib) are in /usr/local/lib.  And might not be true.  In your case, you're saying that this file references expat in `D:/a/_temp/msys/msys64/mingw64/lib/` - which is unique to the build machine and will almost never be a a user's machine.

There's much to be investigated here.  I'll look at it next week.

**Comment by kmilos** [comment]
There is no such path as /usr nor /usr/local in a MINGW32/64 environment, and I find that you get them in your builds very curious. For starters, they're invalid as absolute paths on Windows... /usr and /usr/local do however exist in the MSYS/Cygwin POSIX emulation environment, so I'm wondering if there's also something else going on with the Exiv2 MINGW builds... Are you building for MINGW32/64 or for MSYS2? [These are two very different beasts](https://www.msys2.org/wiki/MSYS2-introduction/).

But this is a separate issue to the one reported here that seems to be happening an any platform, and it looks like @piponazo is on to something in the PR.

**Comment by piponazo** [comment]
I have tried different things. I'll try to give a summary here:

When removing the installation of the **exiv2-xmp** target (which for me, it should not be needed, since it is an implementation detail) as I did in #1364, the absolute paths are removed from the cmake config file `share/cmake/exiv2Config.cmake`. However, when trying to configure the project with `-DBUILD_SHARED_LIBS=OFF` (to generate exiv2lib as a STATIC library), CMake says that it needs to export information about the target **exiv2-xmp**:

```
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=install ../
...
CMake Error: install(EXPORT "exiv2Config" ...) includes target "exiv2lib" which requires target "exiv2-xmp" that is not in any export set.
-- Generating done
```

If we leave the code as it is, the CMake configuration file will contain information about the **exiv2-xmp** target, which is depending on LIBEXPAT (either its STATIC or SHARED version, but always as a absolute path)

```
# Create imported target exiv2-xmp
add_library(exiv2-xmp STATIC IMPORTED)

set_target_properties(exiv2-xmp PROPERTIES
  INTERFACE_LINK_LIBRARIES "/home/luis/.conan/data/expat/2.2.10/_/_/package/2af715f34a7c8c2aeae57b25be0a52c4110dc502/lib/libexpat.so"
)
```

However, I am not sure if this would create a problem for a consumer of **exiv2lib**. That absolute path is associated to the target **exiv2-xmp** and consumers of exiv2 should normally only consume **exiv2lib**. Altough, I understand the issue mentioned by @kmilos , in which he is getting the warning:

```
==> WARNING: Package contains reference to $(cygpath -m /)
```

Just before publishing this comment, I noticed that I can hide the absolute path by using this:

```
target_link_libraries(exiv2-xmp
    PRIVATE 
        $<BUILD_INTERFACE:${EXPAT_LIBRARY}>
)
```

instead of:

```
target_link_libraries(exiv2-xmp
    PRIVATE 
        ${EXPAT_LIBRARY}
)
```

Let's see what the CI jobs have to say about it ...

**Comment by clanmills** [comment]
I've built using -CMAKE_INSTALL_PREFIX=/usr/local and everything is works.  Even localisation.  It has built with both Zlib and Expat, however it appears to be statically linked and therefore the DLLs are not loaded and run-time and not mentioned in exiv2Config.cmake.

Perhaps the fix is to build and distribute exiv2 with static linking (both dependences and run-time support).

The path /usr/local exists in the MinGW/msys2/MinGW-64 bash shell.  However, you're talking about Windows.  I've discovered that by default, cmake is uses the **prefix** c:/Program File (x86)/exiv2.  I can't run c:/Program File (x86)/exiv2/bin/exiv2.exe from cmd.exe because it's looking for the MinGW support dlls such as libintl-8.dll and libstdc++-6.dll.  Using the -DEXIV2_ENABLE_DYNAMIC_RUNTIME=0 fixes that.

I'm going to back out of this discussion.  If @piponazo fixes something (that I don't understand) in #1364, that's wonderful.

I will update #1356 to include -CMAKE_INSTALL_PREFIX=/usr/local

Since last week, we have adopted MinGW-64 and dropped MSYS2.  In our release procedure, I test the builds we publish actually work as documented in ReadMe.txt.

**Comment by kmilos** [comment]
Actually, I might be oversimplifying a bit... It looks like MINGW will after all look into /usr if the libraries are not found in /mingw64:

```
$ ld --verbose | grep SEARCH_DIR | tr -s ' ;' \\012
SEARCH_DIR("=/mingw64/x86_64-w64-mingw32/lib")
SEARCH_DIR("=/mingw64/lib")
SEARCH_DIR("=/usr/local/lib")
SEARCH_DIR("=/lib")
SEARCH_DIR("=/usr/lib")
```

So, what you're saying is, that for the Exiv2.org builds, you have the MINGW libexpat compiled from source and installed in /usr/local rather than the msys2 pre-built one that installs into /mingw64?

In any case, the absolute paths problem remains, as it is only valid on the build machine.

**Comment by clanmills** [comment]
I'm mistaken about expat not being mentioned in exiv2Config.cmake, it's expecting it in c:/msys64/mingw64/lib/libexpat.dll.a which was populated by pacman.

So, is the fix to set up the builder as documented in README.md

```bash
for i in base-devel git coreutils dos2unix tar diffutils make                     \
    mingw-w64-x86_64-toolchain mingw-w64-x86_64-gcc      mingw-w64-x86_64-gdb     \
    mingw-w64-x86_64-cmake     mingw-w64-x86_64-gettext  mingw-w64-x86_64-python3 \
    mingw-w64-x86_64-libexpat  mingw-w64-x86_64-libiconv mingw-w64-x86_64-zlib    \
    mingw-w64-x86_64-gtest
do (echo y | pacman -S $i) ; done
```

**Comment by kmilos** [comment]
Hats off to @piponazo as #1364 indeed got rid of the warning for me when using `makepkg-mingw`. I now get in exiv2Config.cmake

```
# Create imported target exiv2-xmp
add_library(exiv2-xmp STATIC IMPORTED)

set_target_properties(exiv2-xmp PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:>"
)
```
with the relative paths in exiv2Config-release.cmake:

```
# Import target "exiv2-xmp" for configuration "Release"
set_property(TARGET exiv2-xmp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(exiv2-xmp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libexiv2-xmp.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS exiv2-xmp )
list(APPEND _IMPORT_CHECK_FILES_FOR_exiv2-xmp "${_IMPORT_PREFIX}/lib/libexiv2-xmp.a" )
```

Is this `INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:>"` to be expected now? No idea what it actually does...

**Comment by clanmills** [comment]
Huge Round of Applause for Luis @piponazo.  Incredible Job!

**Comment by clanmills** [comment]
Fix has been merged #1366.  I invite you to agree with the fix by closing this ticket.

**Comment by piponazo** [comment]
Just to clarify:
- #1364 is the fix for **0.27-maintenance**
- #1366 is the fix for **master**

**Comment by kmilos** [comment]
Thanks both @clanmills and @piponazo for an amazing response for a non-critical issue, but hopefully this contributes to the overall stability and polish of the project.

Confirmed fixed AFAICT

**Comment by clanmills** [comment]
We aim to make our users happy.  You could reward our efforts on https://www.openhub.net/p?ref=homepage&query=Exiv2

You can give "Kudos", leave a review or, check the box "I use this this." on the following site. Registration is free.

**Comment by clanmills** [comment]
Thanks for giving "Kudos" to Luis and myself.  For sure, @piponazo deserves this.
