### ISSUE TITLE
Support EXIV2 Environment Strings in tests/bash_tests

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1372]
The following environment strings are documented in README.md and should be support in test/bash_tests/*

| Variable        | Default | Platforms | Purpose |
|:--                 |:--        |:--     |:-- |
| EXIV2_BINDIR       | **\<exiv2dir\>/build/bin** | All Platforms | Path of built binaries (exiv2.exe) |
| EXIV2_PORT         | **12762**<br>**12671**<br>**12760**  | Cygwin<br>MinGW/msys2<br>Other Platforms | Test TCP/IP Port   |
| EXIV2_HTTP         | **http://localhost**  | All Platforms | Test http server   |
| EXIV2_ECHO         | _**not set**_ | All Platforms | For debugging Bash scripts |
| VALGRIND           | _**not set**_ | All Platforms | For debugging Bash scripts |
| VERBOSE            | _**not set**_ | All Platforms | Causes make to report its actions |
| PATH<br>DYLD\_LIBRARY\_PATH<br>LD\_LIBRARY\_PATH    | $EXIV2\_BINDIR/../lib | Windows<br>macOS<br>Other platforms | Path of dynamic libraries |

The Variable EXIV2\_PORT or EXIV2\_HTTP can be set to None to skip http tests.  The http server is started with the command `python3 -m http.server $port`.  On Windows, you will need to run this manually _**once**_ to authorise the firewall to permit python to use the port.

**Comment by LeoHsiao1** [comment]
Do these variables need to be supported in python tests?
```
EXIV2_ECHO
VALGRIND
VERBOSE

PATH
DYLD_LIBRARY_PATH
LD_LIBRARY_PATH
```

**Comment by clanmills** [comment]
Yes, I think so.  Play with them to see how they behave:

```
$ cd build/../test
$ env EXIV2_ECHO=1 ./icc_test.sh
$ cd ../build
$ make bash_tests EXIV2_ECHO=1
```

VALGRIND is use to specify a command preprossor - which will usually be `valgrind`, but it could be `gdb` or `dbxtool` or something else.  I think you can make that happen in BT.Executor.

EXIV2_ECHO causes the commands to be echoed to the terminal.  Again, I think you can implement that in BT.Executor.

VERBOSE is supported by make in the real bash tests.  It is transformed into --verbose option to `python3 runner.py`, so I don't think you need to do anything.

PATH, DYLD_LIBRARY_PATH, LD_LIBRARY_PATH are important.  They ensure that when you use the test suite, you are using the shared objects you have built in the build/lib directory and not /usr/local/lib

It's quite likely that you discover bugs in the existing scripts!  They've been around for-ever.  They are a rat-bag collection of things.  When I added functions.source in 2012, they got a little better - however they are all mostly horrible.  They serve their purpose.  You'll clean this up and life will be better.

**Comment by clanmills** [comment]
I've had a new thought about VERBOSE.  runner.py should respect that.

The test suite should run correctly without make.  So the default when VERBOSE is set, tests/runner runner.py should assume the option --verbose.

For example you can could run tests on DOS/cmd.exe as follows:

```bat
>cd build
>set VERBOSE=1
>cmake --build . --config Release --target tests
```

make isn't being used here and cmake executes `python3 runner.py` which should run in verbose mode.

**Comment by LeoHsiao1** [comment]
I have a little problem with understanding:
-  Which of the following variables has a default value `$EXIV2_BINDIR/../lib` ?
    ```
    PATH
    DYLD_LIBRARY_PATH
    LD_LIBRARY_PATH
    ```

- Should the variable `PATH` be renamed to `EXIV2_PATH` to distinguish it from the system default variable `PATH`?

**Comment by clanmills** [comment]
You should set:
```
PATH=$EXIV2_BINDIR
LD_LIBRARY_PATH=$EXIV2_BINDIR/../lib
DYLD_LIBRARY_PATH=$EXIV2_BINDIR/../lib
```
LD_LIBRARY_PATH isn't used by Visual Studio or macOS.  DYLD_LIBRARY_PATH is only used on macOS.  However, it's harmless to set all three variables on all platforms.

These variable are not used in our scripts.  They are system variables you should set to be certain that the system loads the correct DLLs/shared-libs.
