### ISSUE TITLE
Add Tamron SP 70-200mm F/2.8 Di VC USD G2  support

### ISSUE THREAD

**Issue by jobec** [Exiv2/exiv2#1388]
**Is your feature request related to a problem? Please describe.**
Exiv2 does not support the `Tamron SP 70-200mm F/2.8 Di VC USD G2` lens on Nikon.

**Describe the solution you'd like**
Have it added to the list of recognized lenses for Nikon

**Context**
This lens isn't recognized by Exiv2 and shows as 226 in Darktable. As a consequence it is not recognized by lensfun to apply the corrections it has for it.

**Comment by clanmills** [comment]
There are two ways to fix this:

1. Put an entry in the configuration file ~/.exiv2
This is documented in the exiv2 man page
This is immediate.  You can fix this on your machine instantly without waiting for a new release of Exiv2.

2. Update the C++ lens recognition code
You won't get the fix on your machine until the next version of Exiv2 arrives on your machine and that can take years.
The next release of Exiv2 is currently scheduled, however it's likely to be spring 2021.
It can take years for a release to reach the distribution.
The code for nikon lens's is in src/nikonmn_int.cpp:

```cpp
static const struct FMntLens {unsigned char lid,stps,focs,focl,aps,apl,lfw, ltype, tcinfo, dblid, mid; const char *manuf, *lnumber, *lensname;}
fmountlens[] = {
....
// https://github.com/Exiv2/exiv2/issues/743
{0xc9,0x48,0x37,0x5c,0x24,0x24,0x4b,0x4e,0x01,0x00,0x00, "Sigma", "", "24-70mm F2.8 DG OS HSM Art"},
//  https://github.com/Exiv2/exiv2/issues/598 , https://github.com/Exiv2/exiv2/pull/891
{0xCF,0x47,0x5C,0x8E,0x31,0x3D,0xDF,0x0E,0x00,0x00,0x00, "Tamron", "A030", "SP 70-300mm F/4-5.6 Di VC USD"},
//
{0xf4,0x4c,0x7c,0x7c,0x2c,0x2c,0x4b,0x02,0x00,0x00,0x00, "Sigma", "", "APO Macro 180mm F3.5 EX DG HSM"},
// https://github.com/Exiv2/exiv2/issues/1078
{0x80,0x48,0x1C,0x29,0x24,0x24,0x7A,0x06,0x00,0x00,0x00, "Tokina", "", "atx-i 11-16mm F2.8 CF"},
// https://github.com/Exiv2/exiv2/issues/1069
{0xc8,0x54,0x44,0x44,0x0d,0x0d,0xdf,0x46,0x00,0x00,0x00, "Tamron", "F045", "SP 35mm f/1.4 Di USD"},
// https://github.com/Exiv2/exiv2/pull/1105
{0xCB,0x3C,0x2B,0x44,0x24,0x31,0xDF,0x46,0x00,0x00,0x00, "Tamron", "A037", "17-35mm F/2.8-4 Di OSD"},
// https://github.com/Exiv2/exiv2/issues/1208
{0xC8,0x54,0x62,0x62,0x0C,0x0C,0x4B,0x46,0x00,0x00,0x00, "Sigma", "321550", "85mm F1.4 DG HSM | A"},
// Always leave this at the end!
{0,0,0,0,0,0,0,0,0,0,0, NULL, NULL, NULL}
};
```
There are 11 metadata items/lens that must match your lens.  You can obtain those values from a photo taken with the lens.  This is discussed in the issues referenced in the code.  We also require a (simple) python test file when we update C++ lens recognition code.

Please don't ask me to do this work for you.  I am writing a book about Exiv2 and want to retire on my 70th birthday.  https://clanmills.com/exiv2/book/

**Comment by jobec** [comment]
Not asking to do the work ;)
These pointers should do the trick.

I already fixed it locally in such .exiv2 file. But I think more people would like it supported eventually.

Anyway, thanks for the pointers, I'll see what I can do.

**Comment by clanmills** [comment]
Thanks for not adding this to my TODO list.

It's Thursday and I've only added about 6 lines of text to my book this week.  Mind you, almost every week the project reveals something I didn't know about which I investigate and fix.  Then I document it and the book is better and stronger.

On Monday, somebody requested additions to the "easyaccess" API about which I knew nothing.  It's consumed 3 days of unscheduled work and discovery.  Last week it was something to do with base64encode/decode.  Every week, something unplanned.

I didn't write exiv2, there are still secrets buried in the code.  However the purpose of the book is to document everything I know about Exiv2 as a courtesy to a future maintainer (or even replacer).  However, in the case of lens recognition, it's a chore to deal with that.  I added the "Configuration File" in exiv2 v0.26 and that's reduced the never ending stream of requests to deal with new lenses.

```bash
1469 rmills@rmillsmbp:~/gnu/exiv2/team/book $ svn log IMaEA.md  | head -24
------------------------------------------------------------------------
r5127 | robinwmills | 2020-11-05 10:33:12 +0000 (Thu, 05 Nov 2020) | 1 line

documenting man page exiv2.1
------------------------------------------------------------------------
r5126 | robinwmills | 2020-11-05 09:24:03 +0000 (Thu, 05 Nov 2020) | 1 line

renumber chapters
------------------------------------------------------------------------
r5125 | robinwmills | 2020-10-30 19:28:00 +0000 (Fri, 30 Oct 2020) | 1 line

text polishing
------------------------------------------------------------------------
r5124 | robinwmills | 2020-10-28 21:33:22 +0000 (Wed, 28 Oct 2020) | 1 line

fixing typos
------------------------------------------------------------------------
r5123 | robinwmills | 2020-10-28 08:02:04 +0000 (Wed, 28 Oct 2020) | 1 line

documenting 'Security'
------------------------------------------------------------------------
r5122 | robinwmills | 2020-10-27 10:57:33 +0000 (Tue, 27 Oct 2020) | 1 line

documented FreeImage.
1470 rmills@rmillsmbp:~/gnu/exiv2/team/book $ 
```

**Comment by clanmills** [comment]
I forgot to let you know that I recently added a page to the Wiki about _**Adding a New Lens**_  https://github.com/Exiv2/exiv2/wiki/Adding-a-new-lens

**Comment by clanmills** [comment]
I think we can close this as I don't believe any further work is anticipated.
