### ISSUE TITLE
Building exiv2 for iOs.

### ISSUE THREAD

**Issue by OlivierLDff** [Exiv2/exiv2#1390]
**Describe the bug**
When building for iOs (arm64), [`libproc.h`](https://opensource.apple.com/source/Libc/Libc-583/darwin/libproc.h) include in `futils.cpp` doesn't exist.

https://github.com/Exiv2/exiv2/blob/363bffa078cf70b975543195672397e37fc102f3/src/futils.cpp#L58-L60

So following code can't work on ios
https://github.com/Exiv2/exiv2/blob/363bffa078cf70b975543195672397e37fc102f3/src/futils.cpp#L489-L494

**To Reproduce**
Steps to reproduce the behaviour:

Compile for iOs with following toolchain : https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake
`cmake -DCMAKE_PREFIX_PATH=path/to/ios.toolchain.cmake ..`
 
**Expected behavior**
libproc.h doesn't exist

**Desktop (please complete the following information):**
 - macos
 - xcode

**Proposed solution**
Simple code snippet to detect wheter host mac or ios:
```c
#if __APPLE__
    #include "TargetConditionals.h"
    #if TARGET_OS_IPHONE && TARGET_IPHONE_SIMULATOR
        // define something for simulator   
    #elif TARGET_OS_IPHONE
        // define something for iphone  
    #else
        #define TARGET_OS_OSX 1
        // define something for OSX
    #endif
#endif
```
Source: https://stackoverflow.com/a/18729350

The idea would be to add a `#ifndef TARGET_OS_IPHONE ` before including libproc and using its content.

Here an example of a patch file 👍 
```patch
diff --git a/src/futils.cpp b/src/futils.cpp
index 67c910a..e438a8d 100644
--- a/src/futils.cpp
+++ b/src/futils.cpp
@@ -47,8 +47,11 @@
 #if defined(_MSC_VER)
 #define S_ISREG(m)      (((m) & S_IFMT) == S_IFREG)
 #elif defined(__APPLE__)
+#include <Targetconditionals.h>
+#ifndef TARGET_OS_IPHONE
 #include <libproc.h>
 #endif
+#endif
 
 #if defined(__FreeBSD__)
 #include <sys/mount.h>
@@ -485,11 +488,13 @@ namespace Exiv2 {
             CloseHandle(processHandle);
         }
     #elif defined(__APPLE__)
+    #ifndef TARGET_OS_IPHONE
         const int pid = getpid();
         char pathbuf[PROC_PIDPATHINFO_MAXSIZE];
         if (proc_pidpath (pid, pathbuf, sizeof(pathbuf)) > 0) {
             ret = pathbuf;
         }
+    #endif
     #elif defined(__FreeBSD__)
         unsigned int       n;
         char               buffer[PATH_MAX] = {};
```

i worked on v0.27.3 release so i don't know how `# include <mach-o/dyld.h> ` affect the build. iOs use static linking in general.

**Comment by clanmills** [comment]
Team Exiv2 does not support mobile platforms such as iOS and Android.  I've never worked in those environments.  However, I'm confident the Exiv2 code will work when the platform dependent code is implemented in utils.cpp, version.cpp, futils.cpp (and possibly other places).

Our test suite is mostly python3 and we are currently transitioning our legacy bash scripts.  As I never develop for iOS or Android, I have no idea how to run bash or python on a mobile platform.

Are you are offering to be the "Exiv2 Mobile Man"?
