### ISSUE TITLE
Current status of bash tests on master

### ISSUE THREAD

**Issue by moon6969** [Exiv2/exiv2#1413]
I can't get xmpparser-test.sh to pass on master branch...
On 0.27.3 the diff in the tests included `--strip-trailing-cr` but this has been changed in master.

I see there is working going on to migrate the bash tests to python (#1301 by @LeoHsiao1 ), but the associated PRs seem to be for 0.27-maintenance.

Is it worthwhile for me to investigate the xmpparser-test.sh issue on master now?
Or just wait until the python conversion hits master?

**Comment by LeoHsiao1** [comment]
Let's hear his opinion. @clanmills

**Comment by clanmills** [comment]
Thanks @moon6969 and @LeoHsiao1.  I don't contribute to 'master'.  Here's my most recent comment on the "Road Map".
https://github.com/Exiv2/exiv2/issues/1018#issuecomment-694383754

The 'master' branch needs to be owned and managed as I do for 0.27-maintenance.  Who will volunteer?

![open-source-today](https://user-images.githubusercontent.com/529982/100446656-17173280-30a7-11eb-8a06-6447946496c5.png)

**Comment by moon6969** [comment]
I didn't quite appreciate before I read your book the efforts that go in to open-source projects.

re: **xmpparser-test.sh**
I can't see how the test can work cross-platform without stripping the '\r' at (or before) the diff.
Without `--strip-trailing-cr`, diff will output extra lines on Windows - stripping the '\r' after diff still leaves the rest of the line in the final output.

**Comment by clanmills** [comment]
I've put in about 15,000 hours into Exiv2 and I believe Andreas did much the same.  So between, us we've given about 15 man-years.  And possibly 5 years by other contributors.  So 20 man-years of effort.  Open Hub estimate (using a source code analysis tool) that it is 48 years.  However they lump the two branches.  Exiv2 has taken of the order of 20-30 man years.  https://www.openhub.net/p/exiv2

Quite a lot of unpaid work.  In return, the community sends abusive emails and brutal criticism.  It's very rare for anybody to say "Thank You.".  This week, I dealt with #1409.  You'll notice that while I thanked the user for raising the matter, he didn't extend that courtesy to me for doing 40 hours of work.  #1409

I don't know why xmpparser-test.sh has be modified on 'master'.  I never contribute to that branch.  I maintain 0.27-maintenance and I've (almost) written the book.  And then I will retire.

**Comment by clanmills** [comment]
The bash tests have been rewritten in python for Exiv2 v0.27.4 (currently available as RC2 on https://pre-release.exiv2.org).
