### ISSUE TITLE
Unexpected whitespace added to XmpParser::encode() output

### ISSUE THREAD

**Issue by postscript-dev** [Exiv2/exiv2#1415]
**Describe the bug**
The [xmpsample](https://github.com/Exiv2/exiv2/blob/master/samples/xmpsample.cpp) program creates some Xmp metadata, encodes this into XML and outputs this to the console.  During the encoding process, aditional unwanted whitespace is added and outputted.

The output can be seen in the [xmpsample_with_extra_whitespace.txt](https://github.com/Exiv2/exiv2/files/5609056/xmpsample_with_extra_whitespace.txt) file.

**To Reproduce**
The standard xmpsample program can be used to replicate.

This was observed using the master branch.

**Expected behavior**
```XmpParser::encode()``` to work without adding extra whitespace and this not be outputted by the xmpsample program.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Compiler & Version: gcc.exe (Rev5, Built by MSYS2 project) 10.2.0
 - Compilation mode and/or compiler flags: Debug - other standard flags unchanged.

**Additional context**
The additional whitespace occurs between ```</x:xmpmeta>``` and ```<?xpacket end="w"?>``` tags and is exactly ```2048``` chars long (including newline chars).  This is made up of 20 lines of ```100``` chars plus 1 line of ```27``` chars.

xmpsample calls [XmpParser::encode()](https://github.com/Exiv2/exiv2/blob/master/src/xmp.cpp#L744) and used a default parameter of ```0``` for padding.  This is eventually passed to [XMPMeta::SerializeToBuffer()](https://github.com/Exiv2/exiv2/blob/master/xmpsdk/src/XMPMeta-Serialize.cpp#L1158) but a value of ```0``` is not used as zero padding, but as a trigger for using a default value ([enum { kDefaultPad = 2048](https://github.com/Exiv2/exiv2/blob/master/xmpsdk/src/XMPMeta-Serialize.cpp#L1170)).  This sets the padding to ```2048``` resulting in the unwanted additional whitespace.

**Comment by clanmills** [comment]
@postscript-dev Do you know the fix?

@postscript-dev I'm surprised that you've made no comment on #1395.  It would be very helpful to agree on a definition of the issue.

**Comment by clanmills** [comment]
@postscript-dev Thank you for updating #1395.  I've set the milestone of v0.27.4 for this issue as this matter sounds fairly simple.

I didn't write this code, so I will have to read it to understand what could/should be done.  If you have a proposal, I'd be happy to hear your thoughts and that may save duplication of our efforts.

**Comment by clanmills** [comment]
@postscript-dev Thank You for your analysis.  This is being caused by the Adobe XMPsdk.  I do everything I can to avoid changing that code _for various good and boring reasons_.  The quick fix is:

```diff
1175 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/build $ git diff
diff --git a/xmpsdk/src/XMPMeta-Serialize.cpp b/xmpsdk/src/XMPMeta-Serialize.cpp
index 70a7b020..50e8f105 100644
--- a/xmpsdk/src/XMPMeta-Serialize.cpp
+++ b/xmpsdk/src/XMPMeta-Serialize.cpp
@@ -1211,7 +1211,7 @@ XMPMeta::SerializeToBuffer ( XMP_StringPtr * rdfString,
                }
                padding = 0;
        } else {
-               if ( padding == 0 ) padding = kDefaultPad * unicodeUnitSize;
+               // if ( padding == 0 ) padding = kDefaultPad * unicodeUnitSize; // #1415 Allow padding == 0
                if ( options & kXMP_IncludeThumbnailPad ) {
                        if ( ! this->DoesPropertyExist ( kXMP_NS_XMP, "Thumbnails" ) ) padding += (10000 * unicodeUnitSize);    // *** Need a better estimate.
                }
1176 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

Applying that fix has consequences for the test suite.  Before I change and update the test suite, I'm wondering:

1) Is it better to leave this alone as the issue is cosmetic?
2) Perhaps this is more appropriate for 'master' as it been this way since XMP was added in 2007.
3) No other user has discussed this.  Adding this in 0.27-maintenance is a sudden change in behaviour that could cause unexpected disturbance to code that uses the library.

I've looked at Adobe's latest code: https://github.com/adobe/XMP-Toolkit-SDK.git and it has the same behaviour.  Exiv2 can be built with that code (_see README-CONAN.md 4.4 Build Exiv2 and link Adobe XMPsdk library_). Therefore if a user builds Exiv2 with Adobe's code, the "lots of useless white space" will be back.

I'd like to suggest a simpler change that leaves Adobe's code alone and has not impact on users.  We modify the default `padding=0` to `padding=1` on the API `Exiv2::XMPParser::encode()` _**and**_ modify the description of padding in the Doxygen comments:

```bash
1192 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/build $ git diff
diff --git a/include/exiv2/xmp_exiv2.hpp b/include/exiv2/xmp_exiv2.hpp
index 88a05c37..f913128c 100644
--- a/include/exiv2/xmp_exiv2.hpp
+++ b/include/exiv2/xmp_exiv2.hpp
@@ -310,7 +310,7 @@ namespace Exiv2 {
           @param xmpData     XMP properties to encode.
           @param formatFlags Flags that control the format of the XMP packet,
                              see enum XmpFormatFlags.
-          @param padding     Padding length.
+          @param padding     Padding length.  Caution:  padding==0 defaults to 2*1024
           @return 0 if successful;<BR>
                   1 if XMP support has not been compiled-in;<BR>
                   2 if the XMP toolkit failed to initialize;<BR>
@@ -319,7 +319,7 @@ namespace Exiv2 {
         static int encode(      std::string& xmpPacket,
                           const XmpData&     xmpData,
                                 uint16_t     formatFlags =useCompactFormat,
-                                uint32_t     padding =0);
+                                uint32_t     padding =1);
         /*!
           @brief Lock/unlock function type
 
1193 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

It does have modest impact on the test suite.  sample/xmpsample does have a useless white space byte, however the result is less unpleasant.

```bash
1193 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/build $ bin/xmpsample | tail
   </xmpBJ:JobRef>
   <Iptc4xmpCore:CreatorContactInfo
    Iptc4xmpCore:CiAdrCity="Kuala Lumpur"
    Iptc4xmpCore:CiAdrCtry="Malaysia"
    Iptc4xmpCore:CiUrlWork="http://www.exiv2.org"/>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>

<?xpacket end="w"?>
1194 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

Thoughts?

**Comment by tester0077** [comment]
I had noticed similar white space in a number of images.
Although I cannot locate a specific reference explaining this space at the moment, somewhere along the way, I did find some comments about this white space being intended as a buffer which would allow editing/modifying the metadata which are part of this 'packet' without having to rewrite the whole image file.

**Comment by postscript-dev** [comment]
> Thoughts?

I didn't know the history of XMPsdk but was reluctant to change it.  When experimenting with the code, like you I changed the padding to 1 and that seemed better but changing the output string format can cause someone somewhere problems.  I'm not sure if it is a good solution, but upstream an extra enum could be added for the options parameter - e.g. ```kXMP_IgnorePadding``` would not use the padding parameter but use a value of 0 instead.

As you mentioned this is a small cosmetic issue.

> I did find some comments about this white space being intended as a buffer which would allow editing/modifying the metadata which are part of this 'packet' without having to rewrite the whole image file.

I only posted this because xmpsample demonstrates exiv2 and the output looked like it was incorrect.  I am happy for this to remain unchanged if there is a good reason.  If so, then perhaps a comment in the documentation would be enough.

**Comment by clanmills** [comment]
I had been aware that there was a lot of blank space in the generated XMP, however I've always had more pressing issues to investigate.  I think I might go with `=1` + documentation workaround (and numerous changes to test suite).  I'll think about it for a couple of days and look at it again next week.

Adding an enum such as kXMP_IgnorePadding involves modifying Adobe's code, or passing a StringLen of 0xffffffff.  We could open an issue with Adobe about this, however dealing with the Tech Giants in Silicon Valley is usually slow, frustrating and pointless.

**Comment by postscript-dev** [comment]
I am happy to leave this to you.

**Comment by clanmills** [comment]
I'm going to "punt" this to master.  There's an unknowable risk in touching this.  It causes a tsunami of change in the test suite and that is very scary.  The goal of the the test suite is to let us know about consequences of a change.  If I quickly and blindly update the test suite, I'm saying "the consequences are always benign".  Not good on a maintenance branch.  When an application builds/links Exiv2 v0.27.4, they reasonably expect to inherit bug and security fixes with no side effects.

The alternative to the "quick and blind" update to the test suite, is a careful test-by-test review/update to the test suite and I hope that will be done for the next major release of Exiv2.

When Exiv2 'master' is released as Exiv2 v0.28, the library will have a new API and all applications will be aware that substantial changes have been in Exiv2.  Library users should not expect to painlessly adopt Exiv2 v0.28 and will be more sympathetic to unexpected consequences of changes in the library.  By _more sympathetic_ I really mean they will not send abusive email. 

Lastly, I feel this is a bug/undocumented behaviour of the Adobe XMPsdk.

**Comment by clanmills** [comment]
I've thought of something else to say about this.  When Exiv2 issues a "dot" release, it is propagated through the distros to more than 1 billion computers.  All applications linked with Exiv2 v0.27 use the latest "dot".  Exiv2 is used by Gnome Desktop, GIMP, GwenView and many other applications.

Consequential changes to Exiv2 can be _(and are)_ experienced by millions of users and this happens without the knowledge of the Engineers maintaining Exiv2 applications such as the Gnome Desktop.

With a major release (such as Exiv2 v0.28), the application must to be linked with Exiv2 v0.28 and the new version of the application is propagated through the distros to users.  Therefore the Engineers maintaining the application are involved in the upgrade to Exiv2 v0.28.

We shouldn't change this in a "dot" release.  I'm leaving this to the next major release of Exiv2.

**Comment by dgtlmoon** [comment]
+1 @clanmills - the padding is used so that applications can just write/update that 'field' without rewriting the whole stream.. it's part of the specification - how that is returned the user I guess is up to the exiv2 team

**Comment by clanmills** [comment]
@dgtlmoon Happy New Year.  Thanks for your further investigation about this.  Doing nothing seems to be the best thing to do with this issue.

**Comment by clanmills** [comment]
I'm going to close this one.  For sure, I'm not going to change any code concerning this in 0.27.4.  It's not really a bug.  It's really a question "why does Exiv2 behave in this way?".  And the answer is "We inherit this behaviour from Adobe XMPsdk.
