### ISSUE TITLE
Display dates even if they are from the system

### ISSUE THREAD

**Issue by keybraker** [Exiv2/exiv2#1418]
I am not sure if this is an error or not. As I am evaluating a transition from exiftool to exiv2 as it is a native cpp library for one of my projects I came across a lot of times where exiftool had a lot more data (that I do not care about) which is not an error, but exiv2 did not display dates, which are fundamental for a photo.

I would like for the basic info to always display a date it can find, be that from the system or from metadata.

```
$ exiftool /home/keybraker/Desktop/old/mypic.jpg
ExifTool Version Number         : 12.11
File Name                       : mypic.jpg
Directory                       : /home/keybraker/Desktop/old
File Size                       : 52 KiB
File Modification Date/Time     : 2020:12:02 17:45:56-08:00
File Access Date/Time           : 2020:12:04 06:05:23-08:00
File Inode Change Date/Time     : 2020:12:04 06:05:04-08:00
File Permissions                : rw-rw-r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : inches
X Resolution                    : 72
Y Resolution                    : 72
Image Width                     : 353
Image Height                    : 368
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 353x368
Megapixels                      : 0.130
```
```
exiv2 /home/keybraker/Desktop/old/mypic.jpg
File name       : /home/keybraker/Desktop/old/mypic.jpg
File size       : 53184 Bytes
MIME type       : image/jpeg
Image size      : 353 x 368
/home/keybraker/Desktop/old/pipi.jpg: No Exif data found in the file

```

**Comment by clanmills** [comment]
Exiv2 does this.  The command:

```
$ exiv2 -pa myopic.jpg
```

Will display all the metadata (-pa = print all).  Typically there are about 300 items of metadata in most photos.

If you only wish to see date related metadata, use option --grep date/i   (/i = case ignore)

```bash
566 rmills@rmillsmbp:~/gnu/exiv2/team/book $ exiv2 --grep date/i http://clanmills.com/Stonehenge.jpg
Exif.Image.DateTime                          Ascii      20  2015:07:16 20:25:28
Exif.Photo.DateTimeOriginal                  Ascii      20  2015:07:16 15:38:54
Exif.Photo.DateTimeDigitized                 Ascii      20  2015:07:16 15:38:54
Exif.NikonWt.DateDisplayFormat               Byte        1  Y/M/D
Exif.GPSInfo.GPSDateStamp                    Ascii      11  2015:07:16
Xmp.xmp.ModifyDate                           XmpText    25  2015-07-16T20:25:28+01:00
567 rmills@rmillsmbp:~/gnu/exiv2/team/book $ 
``` 

I don't wish to discourage you from using exiftool as it is excellent and Phil Harvey is a good friend to Team Exiv2.  I think you'll find the API from C++ to Exiv2 is quite easy to use and well documented.  The sample/exifprint.cpp is a simple program to enumerate the Exif Tags in an image.  https://exiv2.org/doc/exifprint_8cpp-example.html

Here are the samples:  https://exiv2.org/doc/examples.html and documentation: https://github.com/Exiv2/exiv2/blob/0.27-maintenance/README-SAMPLES.md

You can download pre-built binaries for Linux, Windows and macOS from https://exiv2.org

**Comment by keybraker** [comment]
Thank you for your swift response, I have tested `-pa`, `-pt `and `-pv` but all return nothing in response.
Is there something I may have missed ?

```
exiv2 -pa --verbose mypic.jpg
File 1/1: mypic.jpg
pipi.jpg: No Exif data found in the file
pipi.jpg: No IPTC data found in the file
pipi.jpg: No XMP data found in the file
```

**Comment by tester0077** [comment]
If the output from exiftool represents all the data, then there is no 
metadata in the file mypic.jpg other the some Exif data such as 
resolution, which is NOT considered to be 'metadata' in the usual sense, 
AFAIK.

The dates from exiftools refer to the image file itself and the rest of 
the data relates to the image properties (exif), but even exiftool does 
not report any _metadata_ - which is what Exiv2 is also reporting.

Arnold

**Comment by keybraker** [comment]
Thank you for clarifying it.

**Comment by clanmills** [comment]
Ah, yes, @tester0077 You've got that right.

Exiv2 doesn't consider system file stamps to be metadata.  Curiously, I did report filesystem information in samples/exiv2json.cpp

```
571 rmills@rmillsmbp:~/gnu/exiv2/team/book $ curl -LO https://clanmills.com/Stonehenge.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6599k  100 6599k    0     0   673k      0  0:00:09  0:00:09 --:--:-- 1208k
572 rmills@rmillsmbp:~/gnu/exiv2/team/book $ date
Fri  4 Dec 2020 17:00:30 GMT
573 rmills@rmillsmbp:~/gnu/exiv2/team/book $ exiv2json f Stonehenge.jpg 
{
	"FS": {
		"path": "Stonehenge.jpg",
		"realpath": "\/Users\/rmills\/gnu\/exiv2\/team\/book\/Stonehenge.jpg",
		"st_dev": 16777220,
		"st_ino": 129054886,
		"st_mode": 33188,
		"st_nlink": 1,
		"st_uid": 501,
		"st_gid": 20,
		"st_rdev": 0,
		"st_size": 6757987,
		"st_atime": 1607101228,
		"st_mtime": 1607101227,
		"st_ctime": 1607101227,
		"st_blksize": 4096,
		"st_blocks": 14408
	}
}
574 rmills@rmillsmbp:~/gnu/exiv2/team/book $ 
```

So the code's available in the samples, however it's not a feature of the library.
