### ISSUE TITLE
Using exiv2 in commercial product

### ISSUE THREAD

**Issue by jobesu14** [Exiv2/exiv2#1430]
Hello, Exiv2 team.
First of all, good job for the great work you are doing!

We would like to use exiv2 as dll in a Windows based application and we have a hard time to reach out to you guys to buy a commercial license.
We read through most of the discussions on the topic here on github and on the website and we have the feeling that you actually don't provide commercial licence and the GPL2 doesn't allow us to use the lib as dll in our commercial product.

It looks that the only way forward for us would be to package the exvi2 as executable and use that in our product as a extrernal process.

We don't like this option for two reasons:
1. when using open source code we think we should contribute somehow (money in this case).
2. it would be way more handy and robust to use Exiv2 as a dll library than a separate executable.

Do you guys think we could schedule a meeting to discuss about that?

**Comment by clanmills** [comment]
The commercial license is no longer available.  Andreas Huggel decided to withdraw from that business when he left the project in 2017.  The code on GitHub.com is open-source and licensed under GPLv2. 

I am not able to offer legal advice.  However, I have some technical suggestions which you may find interesting.

Exiv2.exe is very fast to load and deliver the metadata.  I've never bothered to benchmark the performance or to compare exiv2 performance when it's statically linked and compare it to using a DLL.

Exiv2 is open-source, so you can submit changes for your own purposes.  For example, you could add an option `--daemon` to say "load and don't die" _**or**_ "use your daemon buddy if he's alive".  You'll clearly need a little inter-process communications between the daemon instance and the none daemon instance.  You can patch this option into your copy of the code, or submit it to the code base.

If you wish to talk, I'm happy to use Zoom/Skype/FaceTime or even _(does anybody still use?)_ the phone.  I'm in England.

I'm not looking for money, however if you'd like to pay the AWS bill for hosting exiv2.org, I would be delighted to accept such a contribution.  It's about $10/month, depending on usage.  I intend to retire on my 70th birthday on 2021-01-18 and my wife has been asking me to find a sponsor.

**Comment by clanmills** [comment]
I've run some little tests on macOS to compare times to execute exiv2 on the 6915 test images in the ExifTool Image Archive:

| Case | Command | Result |
|:--     |:--           |:--    |
| Count Every File in a Directory | `time find . -type f \| wc `| 0m0.081s |  
| Echo every filename  | `time for i in $(find . -type f) ; do echo -pa "$i" >/dev/null 2>/dev/null; done` | 0m0.488s |
| Execute exiv2 once with every file on the command line | `time find . -print0 -type f \| xargs -0 exiv2 -pa >/dev/null 2>/dev/null;` | 0m16.690s |
| Execute exiv2 6915 times with one file per command | `time for i in $(find . -type f) ; do echo -pa "$i" >/dev/null 2>/dev/null; done` | 1m49.837s |

Conclusions:

1. the time to load exiv2 from cold is (60+49-16)/6915 = 13 milliseconds.
2. the time for exiv2 to read metadata from a randomly selected image is 16/6915 = 2 milliseconds.

Two more thoughts:

1. /DelayLoad
if you use /DelayLoad when you link exiv2.exe with your `--daemon` option, exiv2.exe will load, call his buddy, and return your results without loading exiv2.dll  On macOS, the relative size of the DLL and executable is 10X, so this will be very quick.

```bash
685 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance $ ls -l build/lib/libexiv2.0.27.3.dylib build/bin/exiv2
-rwxr-xr-x+ 1 rmills  staff   546576  8 Dec 08:27 build/bin/exiv2
-rwxr-xr-x+ 1 rmills  staff  5585536 28 Nov 09:03 build/lib/libexiv2.0.27.3.dylib
686 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance $ 
```

2. Static linking and --daemon
This will save you nothing at all.   By the time you've loaded a static exiv2 with `CreateProcess()`, you're ready to go.  Calling on a buddy to do the job that you can do for yourself won't buy you anything.  In fact, it will take longer.

**Comment by clanmills** [comment]
And here's another _**damn good**_ idea about how to achieve your goal **AND** contribute to Exiv2.

In 2013, we had a couple of students working with us: [https://clanmills.com/Homepages/2013/GSoCProposals.shtml](https://clanmills.com/Homepages/2013/GSoCProposals.shtml)  Tuan successfully completely the "web-ready" part of a project to enable exiv2 to read files from the internet.

We had a "bolder vision" of this architecture to enable Exiv2 to be used as a remote service.  Sadly, time didn't permit us to implement the exiv2 daemon.  Now's your opportunity.

![Exiv2CloudReady](https://user-images.githubusercontent.com/529982/101793615-e7801580-3afd-11eb-95e1-ff02d0b2e1e4.png)
![Exiv2CloudServer](https://user-images.githubusercontent.com/529982/101793623-e949d900-3afd-11eb-9299-7a28490160be.png)
![Exiv2CloudVision](https://user-images.githubusercontent.com/529982/101793627-ea7b0600-3afd-11eb-9084-30fee2e32936.png)

**Comment by clanmills** [comment]
I'm going to close this issue as there is no case to answer.

If you wish to take up offer to meet, please update this issue and GitHub will send me a notification.  Always happy to encourage folks to use of Exiv2.

![exiv2](https://user-images.githubusercontent.com/529982/101839759-da354c00-3b3a-11eb-9d8f-34c7f25b178b.png)

**Comment by clanmills** [comment]
You've realised that I am retired and have lots of time to waste exploring matters that interest me.  You're 100% out of luck with /DelayLoad.  I get this message:

```
LINK : fatal error LNK1194: cannot delay-load 'exiv2.dll' due to import of data symbol '"__declspec(dllimport) const Exi
v2::BasicError<char>::`vftable'" (__imp_??_7?$BasicError@D@Exiv2@@6B@)'; link without /DELAYLOAD:exiv2.dll [C:\Users\rmills\gnu\github\exiv2\0.27-maintenance\build\src\exiv2.vcxproj]
```

I think there' something in the DLL that's needed at the birth of the process.

-------------------

I added the option --sleep argument to exiv2.exe (only on my machine, patch below).

In one cmd.exe window, I run:

```cmd
> bin\exiv2 --sleep 30
```

and in the other:
```cmd
> timex bin\exiv2 -pa f f f f f f f f f f>NULL  .... about 100 hundred fs.  f is a copy of the 6mb file https://clanmills.com/Stonehenge.jpg 
```
`timex` is a little home-made utility that behaves like `time` on unix.

Good News.  Reading  that file 100 times consistently takes 0.323 seconds.  Makes no difference if the --sleep buddy is aive or dead.  Good Performance, eh? 3 milliseconds/image.

Not so fast when you run exiv2 one times in a loop:

```cmd
C:\Users\rmills\gnu\github\exiv2\0.27-maintenance\build\bin>timex for %f in (f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f) do exiv2 %f>NUL
```

62 f's.  1.47 seconds.  It's still pretty good. 24 milliseconds/image.  Makes no difference if there another instance sleeping or not.

Doing CreateProcess() on exiv2 takes about 20 milliseconds on Windows (on my 6 year old MacMini running Windows-10 in a VM).

I have no idea what your application does.  If you're operating on thousands of images, clearly you don't want to do CreateProcess() for every image.

---------------------
```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 10235579..47219e43 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -255,6 +255,9 @@ if(EXIV2_BUILD_EXIV2_COMMAND)
          getopt.cpp getopt.hpp
          utils.cpp utils.hpp
     )
+    if ( MSVC ) 
+        set_target_properties(exiv2 PROPERTIES LINK_FLAGS /DELAYLOAD:exiv2.dll)
+    endif()
 
     set_target_properties( exiv2 PROPERTIES
         COMPILE_FLAGS ${EXTRA_COMPILE_FLAGS}
diff --git a/src/exiv2.cpp b/src/exiv2.cpp
index 0754cd78..9a70f4a0 100644
--- a/src/exiv2.cpp
+++ b/src/exiv2.cpp
@@ -151,6 +151,9 @@ int main(int argc, char* const argv[])
         params.version(params.verbose_);
         return 0;
     }
+    if ( params.sleep_.size() ) {
+        return 0;
+    }
 
     int rc = 0;
 
@@ -372,7 +375,8 @@ void Params::help(std::ostream& os) const
        << _("   -M cmd  Command line for the modify action. The format for the\n"
             "           commands is the same as that of the lines of a command file.\n")
        << _("   -l dir  Location (directory) for files to be inserted from or extracted to.\n")
-       << _("   -S .suf Use suffix .suf for source files for insert command.\n\n");
+       << _("   -S .suf Use suffix .suf for source files for insert command.\n")
+       << _("   -Z sec  Sleep and terminate\n\n");
 } // Params::help
 
 int Params::option(int opt, const std::string& optarg, int optopt)
@@ -410,6 +414,7 @@ int Params::option(int opt, const std::string& optarg, int optopt)
     case 'M': rc = evalModify(opt, optarg); break;
     case 'l': directory_ = optarg; break;
     case 'S': suffix_ = optarg; break;
+    case 'Z': sleep_  = optarg; break;
     case ':':
         std::cerr << progname() << ": " << _("Option") << " -" << static_cast<char>(optopt)
                    << " " << _("requires an argument\n");
@@ -1045,6 +1050,7 @@ int Params::getopt(int argc, char* const Argv[])
     longs["--Version"  ] = "-V";
     longs["--version"  ] = "-V";
     longs["--years"    ] = "-Y";
+    longs["--sleep"    ] = "-Z";
 
     for ( int i = 0 ; i < argc ; i++ ) {
         std::string* arg = new std::string(Argv[i]);
@@ -1061,6 +1067,13 @@ int Params::getopt(int argc, char* const Argv[])
     if (help_ || version_) {
         goto cleanup;
     }
+    if (sleep_.size()) {
+        std::cout << "sleep = " << sleep_ << std::endl;
+        std::string command("sleep "); command += sleep_ ;
+        ::system(command.c_str());
+        goto cleanup;
+    }
+
     if (action_ == Action::none) {
         // This shouldn't happen since print is taken as default action
         std::cerr << progname() << ": " << _("An action must be specified\n");
diff --git a/src/exiv2app.hpp b/src/exiv2app.hpp
index b71fe9b5..cc00c39c 100644
--- a/src/exiv2app.hpp
+++ b/src/exiv2app.hpp
@@ -250,6 +250,7 @@ public:
     Greps greps_;                       //!< List of keys to 'grep' from the metadata
     Keys  keys_;                        //!< List of keys to match from the metadata
     std::string charset_;               //!< Charset to use for UNICODE Exif user comment
+    std::string sleep_;
 
     Exiv2::DataBuf  stdinBuf;           //!< DataBuf with the binary bytes from stdin
 
@@ -266,7 +267,7 @@ private:
       @brief Default constructor. Note that optstring_ is initialized here.
              The c'tor is private to force instantiation through instance().
      */
-    Params() : optstring_(":hVvqfbuktTFa:Y:O:D:r:p:P:d:e:i:c:m:M:l:S:g:K:n:Q:"),
+    Params() : optstring_(":hVvqfbuktTFa:Y:O:D:r:p:P:d:e:i:c:m:M:l:S:g:K:n:Q:Z:"),
                help_(false),
                version_(false),
                verbose_(false),
```
