### ISSUE TITLE
0.27.3 web-site issues

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1440]
As report in #1439 by @postscript-dev

_I tried both sites with Firefox, Edge, Opera and Chrome with cookies, without add ons and made sure that javascript was enabled. I don't get an API dropdown box on the main site but do on the pre-release. Both sites have a non-dropdown API option that correctly links to the source code pages. Another thing, on both sites when you click on the "Examples" or "API" menu options, after the page loads the menu option does not go grey. This is inconsistant with the other menu options although this is a small cosmetic problem._

**Comment by postscript-dev** [comment]
Here are some images to make things a little clearer.

### Pre release website
1. The extra "API" menu entry (that looks like a drop-down menu but that doesn't do anything) is found between the "Manual" and "GitHub" options
![pre-release exiv2 org_nonFunctioningAPI](https://user-images.githubusercontent.com/73354718/103155410-9297fc80-4797-11eb-9ae6-a196a507055c.jpg)

2. After clicking on the normal "API" menu option it disappears but the non-functioning dropdown one remains.
![pre-release exiv2 org_functioningAPIMissing](https://user-images.githubusercontent.com/73354718/103155434-d12db700-4797-11eb-9e47-ddbaff61e9ac.jpg)

### Main website
1. After clicking on a menu option, the new page highlights that option in dark grey.  The correct behaviour is shown below.
![exiv2 org_menuOptionHighlighted](https://user-images.githubusercontent.com/73354718/103155487-6466ec80-4798-11eb-86e7-1615bd62514b.jpg)
However when clicking on "Examples" or "API" this is not highlighted.
![exiv2 org_menuOptionNotHightlighted1](https://user-images.githubusercontent.com/73354718/103155502-81032480-4798-11eb-9e54-43964bbb9260.jpg)
![exiv2 org_menuOptionNotHightlighted2](https://user-images.githubusercontent.com/73354718/103155509-882a3280-4798-11eb-81d8-08d7b83a68d7.jpg)

### General Info
I am using Windows 10 (which is up to date) and the latest versions of Firefox, Edge, Chrome and Opera.

**Comment by clanmills** [comment]
I'm rather puzzled by this.  There pages are stored here:  svn://dev.exiv2.org/svn/team/website  I can't see anything in the log concerning the mysterious "API" being listed twice.  I'm not doing anything about the pre-release web site.  The same code is used to generate both the 'main' and 'pre-release' web sites.  So, let's focus on 'main'.  If/when there is a new 'pre-release' for v0.27.4 or 0.28, it'll be right.

I think the API button is a link to doc/index.html and that seems fine.  There was a time when that button caused a menu to appear from which the user could navigate to a choice of entries in the documentation.  However it was giving trouble and I changed it to a static link.

**Comment by clanmills** [comment]
I'm going to close this as I don't anticipate further work here.  If you have more comments, I'll be happy to reopen the issue and investigate.
