### ISSUE TITLE
Missing Lens Information - Lumix G 20mm F1.7 II Asph.

### ISSUE THREAD

**Issue by AxelG-DE** [Exiv2/exiv2#1441]
**Describe the bug**

That Lens **Lumix G 20mm F1.7 II Asph.** is reported in LensType as **Lumix G 20mm F1.7 Asph.**

Hence darktable/lensfun pickup the wrong lens

I tried to create my own entry in .exiv2 (as I successfully did for the Tamron 70-200 G2), but this lens does not provide any LensIDNumber (but "Lens ID", which I donno how to use in .exiv2)

**To Reproduce**

```

$ exiftool -G -n -Lens*  2020-12-25_102819__EM51303.ORF
[MakerNotes]    Lens Type                       : 2 05 10
[MakerNotes]    Lens Serial Number              : 10JG3153013
[MakerNotes]    Lens Firmware Version           : 4368
[MakerNotes]    Lens Properties                 : 16656
[EXIF]          Lens Info                       : 20 20 1.7 1.7
[EXIF]          Lens Model                      : LUMIX G 20/F1.7 II
[Composite]     Lens ID                         : 2 05 10
```

```
$ exiv2 -pa --grep lens/i 2020-12-25_102819__EM51303.ORF
Exif.OlympusEq.LensType                      Byte        6  Lumix G 20mm F1.7 Asph.
Exif.OlympusEq.LensSerialNumber              Ascii      32  10JG3153013
Exif.OlympusEq.LensModel                     Ascii      32  LUMIX G 20/F1.7 II
Exif.OlympusEq.LensFirmwareVersion           Long        1  4368
Exif.OlympusEq.LensProperties                Short       1  16656
Exif.OlympusEq.ConversionLens                Ascii      32  
Exif.Photo.LensSpecification                 Rational    4  20/1 20/1 17/10 17/10
Exif.Photo.LensModel                         Ascii      32  LUMIX G 20/F1.7 II
```

**Expected behavior**
Either LenseType is correctly recognized as **Lumix G 20mm F1.7 II Asph.**
or
a propper entry proposal for .exiv2

**Desktop (please complete the following information):**
* exiv2 Version : 0.27.3 (installed from repo)
* OS                : Linux - kernel 5.10.2-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Xorg              : xorg-server-1.20.10
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"

**Additional context**

**Comment by AxelG-DE** [comment]
OOOoooops, I am not aware how I might have added the bug label..... :blush:

**Comment by clanmills** [comment]
The following ascii string, was written by the manufacturer.

```bash
Exif.Photo.LensModel                         Ascii      32  LUMIX G 20/F1.7
```

There is a 6 byte "Lens Type" and I think that's being by ~/.exiv2.  Please get that value and try it as follows:

```bash
$ exiv2 -pv -g lens/i RAW_OLYMPUS_E-450.ORF
RAW_OLYMPUS_E-450.ORF  0x0201 OlympusEq    LensType                    Byte        6  0 0 35 0 1 0
$
```

```ini
[olympus]
0 0 35 0 1 0=Funny wee lens
```

I that doesn't fix it, please attach a test image using the lens and I will investigate.  I recommend that you keep the lens cap on and shoot at the lowest resolution, however any image will be fine.

**Comment by AxelG-DE** [comment]
@clanmills 
Thanks for your very fast reaction. Unfortunately it did not work.

here is my .exiv2
( wonder it needs to be bracketed or converted to e.g. hex)

```
$ cat .exiv2 
[nikon]
#226=Tamron/ Tamron SP 70-200mm F/2.8 Di VC USD G2
#226=Tamron SP 70-200mm F/2.8 Di VC USD G2
226=Tamron SP 70-200mm F/2.8 Di VC USD G2

[olympus]
0 0 35 0 1 0=Lumix G 20mm F1.7 II Asph.
#0 0 35 0 1 0=Funny Wee Lens
```
Pls find attached one pic with that lens
[2020-12-25_143139__EM51316.zip](https://github.com/Exiv2/exiv2/files/5744613/2020-12-25_143139__EM51316.zip)

**Comment by clanmills** [comment]
For your lens, the key is 2 0 5 16 0 7.

```bash
530 rmills@rmillsmm-local:~/Downloads $ exiv2 --grep lenstype/i 2020-12-25_143139__EM51316.ORF 
Exif.OlympusEq.LensType                      Byte        6  Lumix G 20mm F1.7 Asph.
531 rmills@rmillsmm-local:~/Downloads $ 
525 rmills@rmillsmm-local:~/Downloads $ exiv2 -pv --grep lens/i 2020-12-25_143139__EM51316.ORF 
0x0201 OlympusEq    LensType                    Byte        6  2 0 5 16 0 17   <---------- Use this.
0x0202 OlympusEq    LensSerialNumber            Ascii      32  10JG3153013
0x0203 OlympusEq    LensModel                   Ascii      32  LUMIX G 20/F1.7 II
0x0204 OlympusEq    LensFirmwareVersion         Long        1  4368
0x020b OlympusEq    LensProperties              Short       1  16656
0x0403 OlympusEq    ConversionLens              Ascii      32  
0xa432 Photo        LensSpecification           Rational    4  20/1 20/1 17/10 17/10
0xa434 Photo        LensModel                   Ascii      32  LUMIX G 20/F1.7 II
526 rmills@rmillsmm-local:~/Downloads $ 
```

Update ~/.exiv2:

```bash
[olympus]
2 0 5 16 0 17=AxelG-DE's lens in #1441  <---- Register the lens
```

And by magic _(well, my code actually)_:

```bash
$ 528 rmills@rmillsmm-local:~/Downloads $ exiv2 --grep lens/i 2020-12-25_143139__EM51316.ORF 
Exif.OlympusEq.LensType                      Byte        6  AxelG-DE's lens in #1441   <-------- It's here now
Exif.OlympusEq.LensSerialNumber              Ascii      32  10JG3153013
Exif.OlympusEq.LensModel                     Ascii      32  LUMIX G 20/F1.7 II
Exif.OlympusEq.LensFirmwareVersion           Long        1  4368
Exif.OlympusEq.LensProperties                Short       1  16656
Exif.OlympusEq.ConversionLens                Ascii      32  
Exif.Photo.LensSpecification                 Rational    4  20/1 20/1 17/10 17/10
Exif.Photo.LensModel                         Ascii      32  LUMIX G 20/F1.7 II
529 rmills@rmillsmm-local:~/Downloads $ 
```

Good eh?  If you're happy, can you close the issue please?

**Comment by AxelG-DE** [comment]
Dear Robin,

I feel so stupid. :-(
You sent me the command
rather than trying my self, I just bounced it to you

And you! you are just gentleman (is there a singular?) and do not bang it to my forehead.

Thank you very much.

I wish you a pleasant "between the years" as we in Germany call this time between the hectic time prior x-mas and New Year's eve  :-) and then a healthy and happy new year!

Cheers
 Axel
