### ISSUE TITLE
~/.exiv2 file is insufficient to differentiate multiple Sigma lenses (for Canon)

### ISSUE THREAD

**Issue by czgnp** [Exiv2/exiv2#1446]
**Describe the bug**
For Canon DSLR, Sigma seems to move all their lenses to LensType=368. The concept of a file in ~/.exiv2 to describe this only works if you only have one single Sigma Global Vision lens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Sigma 35mm/1.4 Art on Canon DSLR and take picture. 
2. Check "exiv2 -pv --grep lens/i" for the picture: "0x0016 CanonCs      LensType                    Short       1  368"
3. Switch to Sigma 50mm/1.4 Art and take new picture.
4. Check "exiv2 -pv --grep lens/i" for the picture: "0x0016 CanonCs      LensType                    Short       1  368"
5. Try writing the ~/.exiv2 file, e.g. "[canon]\n368=Sigma 50mm f/1.4 DG HSM [A]"
6. Check "exiv2 -pa --grep lens/i" on both pictures and they will both report being taken with the 50mm lens.

Tested on version exiv2 0.27.2. 

(I was not allowed to upload .cr2 images but you can try on http://privat.bahnhof.se/wb453784/_W5A7360.cr2 and http://privat.bahnhof.se/wb453784/_W5A8059.cr2, 35mm and 50mm respectively, CC-SA.)

**Expected behavior**
I expect a way to get pictures correctly associated with the correct lens. 

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1 Ulyssa
 - darktable 3.4.0

**Additional context**
The exiv2 lens identification and naming is important because **darktable** use this information to pick the correct distortion information from the lensfun project and having to update this information manually for each picture (in the lens correction module) is not fun.
(Compare feature request https://github.com/Exiv2/exiv2/issues/1192.)

**Comment by clanmills** [comment]
This is unfortunate and cannot be fixed using ~/.exiv2.  It is possible to write code to differentiate the different lenses by inspecting the metadata and looking at other metadata.  You are welcome to undertake that investigation and submit a PR.

The Exif standard supports two tags other concerning lens identification which are Exif.Photo.LensMake and Exif.Photo.LensModel.

```
553 rmills@rmillsmm-local:~/gnu/exiv2/team/book $ taglist | csv - | grep -i lens
[LensMake]	[42035]	[0xa433]	[Photo]	[Exif.Photo.LensMake]	[Ascii]	[This tag records the lens manufactor as an ASCII string.]	
[LensModel]	[42036]	[0xa434]	[Photo]	[Exif.Photo.LensModel]	[Ascii]	[This tag records the lens's model name and model number as an ASCII string.]	
553 rmills@rmillsmm-local:~/gnu/exiv2/team/book $ 
```

If these have not been successfully set, I recommend that you write to Canon and/or Sigma and ask them to upgrade their firmware.

If these have been correctly set in the metadata and not used by **darktable**, I recommend that you open an issue with **darktable**.
