### ISSUE TITLE
Joining the Open Invention Network (OIN)

### ISSUE THREAD

**Issue by alexvanderberkel** [Exiv2/exiv2#1447]
**Is your feature request related to a problem? Please describe.**
Currently the Exiv2 project is not being list as an active package of the open invention network. This imposes a theoretical risk for patent infringement issues. 

**Describe the solution you'd like**
In order to avoid patent infringement topics in the future one possible solutions might be to join the open invention network where many well known companies are contribution members such as Canon Inc. The Open Invention Network (OIN) is the largest patent non-aggression community in history and supports freedom of action in Linux as a key element of Open Source Software (OSS). Further reasons to join OIN are listed here: https://openinventionnetwork.com/about-us/why-oin/ 

Member benefits:
- Membership publicly demonstrates open source & patent non-aggression advocacy
- Lifetime membership is FREE without entry barriers
- Patent cross-license covering 3,300+ Linux and core open source technology packages
- Patent peace in a community which owns 2.6+ million patents & applications in total
- Lifetime royalty free license under OIN’s owned patent portfolio of approximately 1,300 global patents & applications, with no field of use restriction
- Membership is available to ALL open source advocates — businesses & individuals
- Members become part of a global, open source network of 3,300+ members from start-ups to Fortune 100 firms
- Everyone signs the same agreement terms
- Holding patents in the Linux System is not required
- You get the opportunity to network with our rapidly-growing community members
- OIN leverages our industry relationships to collect & share prior art as needed
- OIN challenges patent applications as appropriate
- Get INSIDER, OIN’s bi-monthly eNewsletter, to stay in-the-know

The membership is free of charge. 

**Additional context**
Within the linux system definition there are many libraries and image format listed which are potentially of interest to the Exiv2 project: 
.   411 still image
2.   Berkeley YUV still image
3.   BMP still image
4.   Cineon still image
5.   GIF still image
6.   GOULD imaging still image
7.   ICO still image
8.   ILBM still image
9.   JBIG still image
10.   MNG still image
11.   PBM/PGM/PPM/PNM still image
12.   PBM/PNM/PPM still image
13.   PCD still image
14.   PCL5 still image
15.   PCL still image
16.   PCX still image
17.   PNG still image
18.   PNM/PPM still image
19.   PSD still image
20.   PS/EPS/Postscript still image
21.   RAS still image
22.   Raw CMYK still image
23.   RAW still image
24.   SVG still image
25.   TGA still image
26.   TIFF still image
27.   XBM/XPM still image
28.   XCF still image
29.   XWD still image
30.   YUV still image
31.   669/S3M/MOD audio format
32.   ADPCM audio
33.   AIFF audio
34.   AU audio
35.   FLAC audio codec
36.   IMA ADPCM audio
37.   LPCM audio
38.   RIFF/WAV audio

Furthermore, there are couple of libraries and software applications which are listed in the Linux system definition which are linked or similar to Exiv2:

- digikam 
- digikamimageplugins
- f-spot
- gimp
- gphoto2
- ghtumb
- libgphoto
- libkexif
- ufraw
- libwebp
- glitz
- imlib2-loaders
- inkscape
- jhead 
- libjpeg
- libjpeg-turbo
- libmng
- libpng
- librsvg2
- libtiff
- libxcam
- ocrad 
- OpenEXR
- ply-image
- python-imaging
- subsampling-scale-image-view
- tiff
- xloadimage

The Linux System is defined as following: 
“Linux System” shall mean a Linux Environment Component or any combination of such components to the extent each such component is (i) generally available under an Open Source License or in the public domain (and the source code for such component is generally available) and (ii) Distributed with, or for use with, the Linux Kernel (or is the Linux Kernel).

Some examples of projects which have joined OIN are: 
- Gnome
- Inkscape

The license agreement can be found under https://openinventionnetwork.com/joining-oin/join-now/license-agreement/

Steps to become a community member are:
The 3-step process to join our community is simple and only takes a few minutes.

When you are ready to electronically sign the OIN License Agreement, go to Join Now. You will be asked to enter some general information about your company and individual contact information.
- You will receive an email for identity verification. Within the email is a link to click, and which will take you to our electronic signature platform.
- To join the OIN community, please click the link sent to you via email, type your name as your electronic signature, and select - - “Submit signed document” on the last page as the final step.

**Comment by clanmills** [comment]
**Meeting notes of 2021-02-27**

**Participants:**
- Robin Mills
- Volker Griels-Grabsch
- Luis Diaz
- Christoph Hasse
- Peter Kovar
- Alexander Esseling
- Thomas Beutlich

**Join OIN (open invention network)?**
- Joining OIN is being suspended in the short-term
- Decision to evaluate joining the KDE project
- Benefits: KDE is already part of the open invention network
- KDE project might bring new contributor and/or maintainer to the project

**Exiv2 after v0.27.4?**
- No new maintainer has volunteered.
- We agreed to simplify the branch structure and "modernise" the code (C++20 support)
- Current master branch v0.28 will be labeled as old-master and frozen.
- 0.27-maintenance will be frozen.
- We'll branch 0.27-maintenance to 'main' and make it the default branch.
- Luis will port Unique pointer code from old-master to main.
- Robin will release v0.28 from 'main' in the Fall.

There is no active plant for development of Exiv2 beyond 2021.

We hope to have a week-end retreat in Germany in the Fall to celebrate our achievements.

I'm going to close this issue now as no further action is expect on this matter.

**Comment by clanmills** [comment]
I am reopening this issue for v1.00.  We should discuss this again at Exiv2 v1.00 Kick Off.  As we have deferred joining KDE in 2021 (to focus on v1.00), perhaps we should sign the OIN License to coincide with shipping Exiv2 v0.27.4 with (optional) bmff support.

**Comment by benmccann** [comment]
Here's the OIN agreement: https://openinventionnetwork.com/joining-oin/join-now/license-agreement/

I read through it. From my layman's reading, the only question I had is whether the exiv2 codebase is controlled by an organization? The agreement seems meant to be adopted by an organization. E.g. it applies to affiliates, which means it could apply to other organizations the signer owns or controls.

**Comment by tomato42** [comment]
> E.g. it applies to affiliates, which means it could apply to other organizations the signer owns or controls.

Absolutely not, if that was the case then you couldn't have people serving as CEOs or board members of multiple corporations.
