### ISSUE TITLE
Inclusion in align_image_stack in a Flatpak manifest.

### ISSUE THREAD

**Issue by ChrisOfBristol** [Exiv2/exiv2#1457]
It's likely this is just my incorrect use of Exiv2. I get the errors seen below when I build a Flatpak which uses align_image_stack which uses Exiv2.

FAILED: src/hugin_base/CMakeFiles/huginbase.dir/panodata/SrcPanoImage.cpp.o 
/usr/bin/c++ -DGLEW_STATIC -Dhuginbase_EXPORTS -Isrc -I../src/hugin_base -I../src/celeste -Isrc/celeste -I../src -I/app/include/OpenEXR -I../src/foreign -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -g -DNDEBUG -fPIC -fopenmp -pthread -std=gnu++11 -MD -MT src/hugin_base/CMakeFiles/huginbase.dir/panodata/SrcPanoImage.cpp.o -MF src/hugin_base/CMakeFiles/huginbase.dir/panodata/SrcPanoImage.cpp.o.d -o src/hugin_base/CMakeFiles/huginbase.dir/panodata/SrcPanoImage.cpp.o -c ../src/hugin_base/panodata/SrcPanoImage.cpp
../src/hugin_base/panodata/SrcPanoImage.cpp: In member function ‘bool HuginBase::SrcPanoImage::readEXIF()’:
../src/hugin_base/panodata/SrcPanoImage.cpp:358:30: error: expected unqualified-id before ‘&’ token
  358 |     catch (const Exiv2::Error& e)
      |                              ^
../src/hugin_base/panodata/SrcPanoImage.cpp:358:30: error: expected ‘)’ before ‘&’ token
  358 |     catch (const Exiv2::Error& e)
      |           ~                  ^
      |                              )
../src/hugin_base/panodata/SrcPanoImage.cpp:358:30: error: expected ‘{’ before ‘&’ token
../src/hugin_base/panodata/SrcPanoImage.cpp:358:32: error: ‘e’ was not declared in this scope
  358 |     catch (const Exiv2::Error& e)
      |                                ^
[63/304] Building CXX object src/hugin.../huginbase.dir/panodata/Panorama.cpp.o
ninja: build stopped: subcommand failed.
Error: module align_image_stack: Child process exited with code 1
Mon 18 Jan 11:11:53 GMT 2021

**Comment by clanmills** [comment]
I maintain the 0.27-maintenance branch of Exiv2.  There's an issue withExiv2::Error on the 'master' branch of Exiv2.  I haven't experienced this and therefore haven't studied it.   No application should build using development branches of any library.

I know nothing about "align_image_stack".  Please report upstream and Team Exiv2 will investigate when the issue has more clarity.

**Comment by ChrisOfBristol** [comment]
"There's an issue withExiv2::Error on the 'master' branch of Exiv2."
Where would I find this?
