### ISSUE TITLE
Question: copy tags from one image to another

### ISSUE THREAD

**Issue by punksta** [Exiv2/exiv2#146]
Hello, thanks for cool lib.
What's the most fast way to copy all tags from one image to another using command line tool?

**Comment by clanmills** [comment]
The quick way is to pipe the metadata:
```
$ exiv2 -ea- from.jpg | exiv2 -ia- to.jpg
```
The option -ea- means:
**E**xtract
**A**ll
to **std-out**

The option -iea- means:
**I**nsert
**A**ll
from **std-in**

The mechanism by which this is achieved is create/read an .exv (exiv2 metadata file).

There's also a sample application `samples/metacopy.cpp` which does something similar.
