### ISSUE TITLE
Rename does not take IPTC metadata into account

### ISSUE THREAD

**Issue by samidalouche** [Exiv2/exiv2#1470]
Image contains only IPTC DateCreated/TimeCreated metadata, no EXIF metadata
```
exiv2 -pa print 00115_G.jpg
Iptc.Envelope.CharacterSet                   String      3
Iptc.Application2.DateCreated                Date        8  2004-11-20
Iptc.Application2.TimeCreated                Time       11  00:00:00+00:00
Xmp.photoshop.DateCreated                    XmpText    19  2004-11-20T00:00:00
```

```
exiv2 rename 00115_G.jpg
00115_G.jpg: No Exif data found in the file
```

This may be a feature request more than a bug depending on how you see it, but the intuitive behavior would be to use all available metadata and not just EXIF.

**Comment by clanmills** [comment]
Thanks for reporting this.  If you _or anybody else_ would like to submit a PR with a fix, I will accept it.  The PR should also include an update to the test suite.  It would be useful to update the man page man/man1/exiv2.1 to both document this and to explain what happens different dates are conflicted:

```bash
604 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance $ exiv2 -g date/i http://clanmills.com/Stonehenge.jpg
Exif.Image.DateTime                          Ascii      20  2015:07:16 20:25:28
Exif.Photo.DateTimeOriginal                  Ascii      20  2015:07:16 15:38:54
Exif.Photo.DateTimeDigitized                 Ascii      20  2015:07:16 15:38:54
Exif.NikonWt.DateDisplayFormat               Byte        1  Y/M/D
Exif.GPSInfo.GPSDateStamp                    Ascii      11  2015:07:16
Xmp.xmp.ModifyDate                           XmpText    25  2015-07-16T20:25:28+01:00
605 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance $ 
```

I am unwilling to prepare a PR for this.  I hoped to retire on my 70th birthday on 2021-01-18 and agreed to undertake the work to release Exiv2 v0.27.4 on 2021-05-22.  I also want to finish writing my book **Image Metadata _and_ Exiv2 Architecture** https://clanmills.com/exiv2/book

**Comment by clanmills** [comment]
I'm going to close this as "not-a-bug".  The specification of rename in the man page is:

> Rename  files  and/or  set file timestamps according to the Exif create timestamp. Uses the value of tag Exif.Photo.DateTimeOriginal  or,  if  not present, Exif.Image.DateTime to determine the timestamp.

I think it's a small matter to write a bash or python script to deal with this.
