### ISSUE TITLE
Tag name "Location shown" should read "Location Shown" with capital letter "S"

### ISSUE THREAD

**Issue by josemoliver** [Exiv2/exiv2#1473]
**Describe the bug**
As minor bug go, this one has to be the most minor. Still, something within me got triggered, when seen in digiKam the label seeing the "Location Created" and "Location shown" I could not help it that "s" was not capitalized. :) 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://exiv2.org/tags-xmp-iptcExt.html
2. Search for "Location shown"

**Expected behavior**
Location shown should have a capitalized "S".

**Comment by clanmills** [comment]
Please submit a PR with an update to the test suite.
