### ISSUE TITLE
Incorrect lens identification

### ISSUE THREAD

**Issue by drt102** [Exiv2/exiv2#1478]
I have some issues with incorrect lens identification in DarkTable which I understand uses the exiv2 tool.

I have a Sigma 60-600mm f/4.5-6.3 DG OS HMS | Sport lens but this is incorrectly identified as a Sigma 18-35mm f/1.8 DC HSM | A.

I have checked the canonmn_int.cpp file and this contains:
        { 368, "Sigma 18-35mm f/1.8 DC HSM | A"                             }

Runing a .CR2 file from my EOS 5D Mk III with the above lens attached through exiv2 tool with -pv option shows:
0x0016 CanonCs      LensType                    Short       1  368
0x0095 Canon        LensModel                   Ascii      74  60-600mm F4.5-6.3 DG OS HSM | Sports 018

So it looks like (to me as an outsider) that the lens model 368 is either used for more than one Sigma lens or is incorrectly assigned to the 18-35 lens in canonmn_int.cpp.

Let me know if you need any more information to correctly identify and rectify.

**Comment by clanmills** [comment]
Before thinking about modifying the C++ code, please consider using the ~/.exiv2 "configuration file" discussed in the exiv2 man page.  Adding the following to ~/.exiv2 will probably fix everything instantly.

```ini
[canon]
368=Sigma 60-600mm f/4.5-6.3 DG OS HMS | Sport
```
There's a discussion about adding lenses on the wiki:  https://github.com/Exiv2/exiv2/wiki/Adding-a-new-lens

**Comment by clanmills** [comment]
I'm going to close this issue as there has been no feedback from the user.

@drt102 If you wish to discuss this further, please update the issue and I will reopen it to continue the conversation.
