### ISSUE TITLE
FLIR Cameras compatibility

### ISSUE THREAD

**Issue by ericoporto** [Exiv2/exiv2#1479]
**Is your feature request related to a problem? Please describe.**
I would like exiv2 to add support for FLIR jpg exif tags.

**Describe the solution you'd like**
FLIR Cameras produce a jpeg image with lots of additional information, including even embedded images inside their exif tags. Themselves don't provide full documentation but it's been fully reversed engineered and information is available here: https://exiftool.org/TagNames/FLIR.html

**Describe alternatives you've considered**
I tried to use exiftool, which does recovers and reads all tags I need from FLIR infrared jpg images. The problem is I wish to build a FOSS software to work with these images and exiftool is really hard to integrate in your project if you are not using PERL. Having an alternative in C or Cpp would enable to more easily make the application portable across operating systems and platforms.

**Additional context**
Add any other context or
[flir-interface-requirements-tiff.pdf](https://github.com/Exiv2/exiv2/files/6049206/flir-interface-requirements-tiff.pdf)
https://nuage.ch/site/flir-i7-some-analysis/

**Comment by clanmills** [comment]
I investigated this several years ago and joined the FLIR development program.  I abandoned the project because the documentation was poor and I received no reply from a couple of questions I raised on their developer forum.

I'll leave this issue open, however I don't think we can make progress.  If you know of an expert in FLIR, Team Exiv2 can provide the metadata support knowledge of the Exiv2 Architecture.

**Comment by ericoporto** [comment]
> several years ago

Before 2016 there was very few information online, both from FLIR and from people reverse engineering (mostly Phil Harvey from Exiftool and anonymous people on the eevblog forum).

> Exiv2 can provide the metadata support knowledge of the Exiv2 Architecture

I understand a bit of the Exiftool PERL code, but is there any architecture document of the Exiv2 source and how it would be the way to add support for new tags?

**Comment by clanmills** [comment]
I've written a book about Exiv2.  https://clanmills.com/exiv2/book/

I was 70 in January and want to retire.  I've written the book to help people maintain Exiv2 in the future, or to assist/inspire somebody to create a new library.

There's a meeting on Saturday to discuss the future of Exiv2.  You are welcome to attend.  The Agenda and Slides for discussion are here:  #1466.

**Comment by ericoporto** [comment]
Thank you!!! A book was much more than I could hope for, you did a lot of amazing work here. Hope you have a great retirement! I will read the book - I actually started a bit after you sent and I already like your writing! I will close this issue and come back later when I understand it more.

**Comment by clanmills** [comment]
Thanks @ericoporto.  Exif metadata is an embedded Tiff inside an image file.  That's it!

------

The details of image formats (JPEG, TIFF etc) and metadata standards (XMP, IPTC, Exif and ICC) can be overwhelming.

The book leads you through the mine field.  Two warnings about the book:

1. It explains every detail without apology.
2.  It comes with a guaranteed cure for insomnia.  It's really boring.

Best Wishes.

Robin
