### ISSUE TITLE
Empty ASCII string ends up encoded with count of 0 instead of 1

### ISSUE THREAD

**Issue by kmilos** [Exiv2/exiv2#1484]
Try e.g. ` exiv2 -M"set Exif.Image.Copyright Ascii ''" some_image.tif` (same as what darktable exports with no copyright defined).

(`0x8298 Copyright` is mandatory in TIFF/EP for example but is also in Exif allowed to be empty which means "unknown"; there are a couple of other tags that behave similarly.)

LibTIFF then correctly complains:

```
$ tiffcp -c zip:2 some_image.tif some_image_tiffcp.tif
TIFFFetchNormalTag: Warning, ASCII value for tag "Copyright" does not end in null byte.
```

As the TIFF spec says "The value of the Count part of an ASCII field entry includes the NUL", the expected count should be 1, and not 0 as verified in a hex editor (`98 82 02 00 00 00 00 00 00 00 00 00`). If I manually flip the count byte in the hex editor (`98 82 02 00 01 00 00 00 00 00 00 00`), no warning is thrown and everything is fine.

OTOH, writing a non-empty string like 'MK' does end up with the correct count of 3 including the terminating null character (`98 82 02 00 03 00 00 00 4d 4b 00 00`).

I'm currently trying to get to the bottom of this in the debugger...

**Comment by clanmills** [comment]
**Good Find**.  That's a bug.  You'll probably find using the debugger to navigate TiffEncoder is difficult to understand.  If you're stumped, ask for help or ask me to fix it.

```bash
654 rmills@rmillsm1:~/temp $ cp ~/Stonehenge.jpg .
655 rmills@rmillsm1:~/temp $ exiv2 -g Copyright Stonehenge.jpg 
656 rmills@rmillsm1:~/temp $ exiv2 -M"set Exif.Image.Copyright Ascii ''" Stonehenge.jpg 
657 rmills@rmillsm1:~/temp $ exiv2 -g Copyright Stonehenge.jpg 
Exif.Image.Copyright                         Ascii       0  
658 rmills@rmillsm1:~/temp $ exiv2 -pv -g Copyright Stonehenge.jpg 
0x8298 Image        Copyright                   Ascii       0
659 rmills@rmillsm1:~/temp $ tvisitor -pR Stonehenge.jpg  | grep Copyright
660 rmills@rmillsm1:~/temp $ tvisitor -pRU Stonehenge.jpg  | grep 8298
       118 | 0x8298 Exif.Image.0x8298                |     ASCII |        0 |           | 
663 rmills@rmillsm1:~/temp $ 
```

**Comment by kmilos** [comment]
> You'll probably find using the debugger to navigate TiffEncoder is difficult to understand.

You can say that again. I'll keep banging, but will call for help if I get absolutely nowhere in a few days...

**Comment by kmilos** [comment]
Ah, now I think the problem is here in value.cpp:

```c++
    int AsciiValue::read(const std::string& buf)
    {
        value_ = buf;
        if (value_.size() > 0 && value_[value_.size()-1] != '\0') value_ += '\0';
        return 0;
    }
```

**Comment by clanmills** [comment]
You've got it.  You see it's not so tough.

You need steady hands and a clear head for TiffVisitor.  However, it's seldom necessary to really know what it's doing!
