### ISSUE TITLE
Test suite Environment handling is not correct

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1485]
We have to ensure that we are executing the correct version of executables with the correct version of the library.  Under no circumstances should we be the exiv2 library in /usr/local/lib.

1 I'd like **proof** that we're running the correct version of the executable AND the library.  That's the purpose of `$ make version_test`

2 We must handling EXIV2_BINDIR correctly in every part of the test suite.

3 bash_tests/utils.py runTest() does not set LD_LIBRARY_PATH (DYLD_LIBRARY_PATH) on macOS.  I think the correct code should be:

```python
def runTest(cmd):
    """
    Executes a command in the shell.
    Add this function at PR <https://github.com/Exiv2/exiv2/pull/1475> .
    """
    exiv2=system_tests.exiv2

    if sys.platform == 'win32':
        args = cmd
    else:
        args = shlex.split(cmd)

    # Update PATH, LD_LIBRARY_PATH and DYLD_LIBRARY_PATH
    key = "PATH"
    bin_dir = os.path.dirname(exiv2)
    os.environ[key] = bin_dir

    for key in ["LD_LIBRARY_PATH", "DYLD_LIBRARY_PATH"]:
        lib_dir = os.path.join(os.path.dirname(os.path.dirname(exiv2)), 'lib')
        os.environ[key] = lib_dir

    # Execute the command
    try:
...
```

There is a open issue for v0.27.4 concerning tests:  #1274.  I hope you can work on this issue and #1274 at the weekend.

If you don't have time to deal with this, please let me know as I would like to publish Exiv2 v0.27.4 RC1 Preview on Monday 2021-03-15.

**Comment by LeoHsiao1** [comment]
OK, the problem is very simple. I'll fix it this weekend.

**Comment by clanmills** [comment]
Thanks.  That's really good to hear.  It's great to have you working on the test code.  One thing less to keep me busy.

I'm very pleased to say that there's been a great increase in the number of contributors in the last year.  The bmff code has been put together and tested by a small army.  I'd like you to be "King Test" - the Lion of the Exiv2 Test Harness.  You can do it and you'll feel very rewarded by owning this part of the world of open-source.

**Comment by LeoHsiao1** [comment]
Thank you for your approval.
Open source makes my life more meaningful.

**Comment by clanmills** [comment]
I am very pleased with your contribution, Leo.  I expect to complete all my testing today.  So when you do your work on Sunday, I can build and publish Exiv2 v0.27.4 RC1 Preview next week.

----

Chapter 11 of my book is about "Project Management".  You'll probably be surprised at how many things I have to take care of in the project:  Code, Documentation, Scheduling, Build, Security and so on.  23 major elements.  For you to own and take care of Test is a very valuable contribution.  Thank You Very Much.  https://clanmills.com/exiv2/book/

----

There's something I'd like you to add to the test harness.  To make it very easy to run a shell command with pipes.  I want something like:  

```python
import system_tests
import os
exiv2 = system_tests.exiv2
path=os.path.join(system_tests.data_path,"foo.heic")
if runShell('%s %s | grep MIME | cut -d: -f 2',(exiv2,path)) != ' image/heif':
    print('FAILED!')
    return 1
```

All this does is to execute the command:

```bash
exiv2 foo.heic | grep MIME | cut -d: -f 2
```
Of course, it has to configure PATH and LD_LIBRARY_PATH and deal with the data_path (the test images are in test/data).

Dan's system_tests.py is beautiful.  However it cannot use shell pipes.  Test scripts have to provide an output handler in python.  Let's make life easier by providing runShell() to enable pipes to be easily used in the test harness.

Perhaps you could develop runShell() in the next week or two, and it'll go into Exiv2 v0.27.4 RC2 (which will ship about 2021-04-30).

**Comment by LeoHsiao1** [comment]
This issue is passed to <https://github.com/Exiv2/exiv2/pull/1492> for discussion.
