### ISSUE TITLE
Improve BMFF MIME type discovery

### ISSUE THREAD

**Issue by kmilos** [Exiv2/exiv2#1489]
Continuing from https://github.com/Exiv2/exiv2/pull/1487#issuecomment-796726093, it seems it might not be sufficient to check just the major brand of the file type box.

For starters, there are missing major brand cases like 'heix', 'heim', or 'heis', and ['avis' and 'avio'](https://aomediacodec.github.io/av1-avif/#brands).

**Comment by kmilos** [comment]
@1div0 So the remaining question is whether we should bother parsing and checking the compatible brands array of the file type box as well for things like 'mif1'+'heic' that is present in 'test/data/heic.heic' for example?

I'm ok to leave it at major brands for now and wait for user feedback...

**Comment by clanmills** [comment]
@kmilos Are we finished on this one or do have you thoughts of further work for v0.27.4?  Or assign it to Milestone: v0.28.

**Comment by kmilos** [comment]
I'm fine with postponing or closing and don't feel like taking on the idea above unless @1div0 feels it is necessary?

**Comment by 1div0** [comment]
AVIF image sequences have great potential to replace aged GIF. However it might take a years, if note a decade. So until then feel free to postpone to 1.0.0.

**Comment by clanmills** [comment]
Let's get this "off the plate".  At best this is a marginal feature of the library.   I'm going to close this.

I'm finishing up on testing v0.27.2 and v0.27.3 using the 0.27.4 shared-objects/dylib/dlls.  Leo has 3 matters in the test suite to deal with and has promised to do them on Sunday.

We've done it guys.  I'll publish a preview of the release on Monday and v0.27.4 RC1 will ship next Friday.  We're 2 weeks ahead of schedule.

**Comment by kmilos** [comment]
Makes sense, best wait and see if any real requests regarding this come back.

**Comment by 1div0** [comment]
Yes, wait & C/C++

:-)
