### ISSUE TITLE
Testing of the exiv2lib internals

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#149]
Right now we can only write unit tests for the API of exiv2lib. It would be interesting to modify the current structure of the project so we can also test the internal headers.

**Comment by D4N** [comment]
Shouldn't that be already possible right now? Everything that goes into
the namespace `Internal` is only private in the sense that the header
file is not in the `include/exiv2/` directory. The symbols are still in
the library:
```
nm build/lib/libexiv2.so.26.0.0 |grep stringFormat
00000000001483a0 T _ZN5Exiv28Internal12stringFormatB5cxx11EPKcz
```
So in theory the unit test would only need to include one of the
internal headers and it should work.

Functions that are declared `static` on the other hand are impossible to
test. Unless you include the `cpp` file.

**Comment by piponazo** [comment]
You are totally right, the only thing we need to do is to include the internal headers.

The problem right now is that we are just including the directory `include/exiv2` into the **unit_tests** target. We would need to also include `${CMAKE_SOURCE_DIR}/src ` with the current configuration.

I was thinking about moving the `unitTests` folder inside the `src` one, to make clear that the unit tests belong to the **exiv2lib** target.

**Comment by D4N** [comment]
Before we celebrate too early, could someone check that this applies on
Windows too? I vaguely recall the Microsoftism `__declspec(dllexport)`
which indicates that something is included in a library. But our
internal functions don't have that, so that could maybe be an issue.

Where we put the unit tests is imho a matter of personal preference. I
have seen everything from test files in the same directory as the source
files, in a separate directory or in a subdirectory called
tests. Personally, I would either put them in a separate directory (like
it is now) or add them into a subdirectory of `src`.

**Comment by piponazo** [comment]
You are right @D4N . That is the main issue when trying to test the internals of a library. In my company we use an approach that allow us to do so. Basically we treat the internals of a library as a **OBJECT** Target in CMake (That is a bunch of object files) and we use them to generate the final library. 

Later we can reuse those objects when we generate the unit tests target in order to resolve the missing symbols.

In that way we do not need to export the symbols of the internals.

However, I tried to use such OBJECT targets in the past in this project and the CMake - XCode generator could not handle them properly out of the box. 

I can explore all these things in the context of this issue ;)

**Comment by D4N** [comment]
What you are doing at your company sounds reasonable and if the XCode generator could support that, I'd favor that option instead of linking the unit tests against libexiv2.

**Comment by piponazo** [comment]
Closing this issue, since we solved the situation a long time ago.
