### ISSUE TITLE
v0.27.4 application tests

### ISSUE THREAD

**Issue by 1div0** [Exiv2/exiv2#1493]
### Work in progress

1. https://github.com/darktable-org/darktable/pull/8340
2. https://invent.kde.org/graphics/digikam/-/merge_requests/51
3. https://gitlab.gnome.org/GNOME/gexiv2/-/merge_requests/46
![Snímka obrazovky z 2021-03-16 14-30-21](https://user-images.githubusercontent.com/3098510/111318265-2bd30280-8665-11eb-8c05-0572f1ab6d2a.png)

**Comment by novomesk** [comment]
Support in KDE would be good too. See:
https://invent.kde.org/frameworks/kfilemetadata/-/blob/master/src/extractors/exiv2extractor.cpp

**Comment by kmilos** [comment]
I just tried building dt master w/ this patch, but made a mistake of forgetting to build RC1 w/ `-DEXIV2_ENABLE_BMFF=ON`...

The result is a compile error like "enableBMFF is not part of Exiv2 namespace".

Something we should fix probably, I guess we should export this method in any case, just return false if exiv2 is built w/o BMFF support?

**Comment by clanmills** [comment]
Milos. I'm surprised.  The code should compile with a library built with -DEXIV2_ENABLE_BMFF=OFF.

You have to "guard" the call to Exiv2::enableBMFF() to ensure that the code will compile with Exiv2 < 0.27.4.  Like this:

```cpp
#if EXIV2_TEST_VERSION(0,27,4)
    Exiv2::enableBMFF(true);
#endif
```

This is documented in README.md.  I spoke to @1div0 about a month ago and I thought that code was added to **darktable**.

**Comment by kmilos** [comment]
Yes, [that's the patch](https://github.com/darktable-org/darktable/pull/8340/files#diff-1fb9a54118db259d6650881b4ce3926378900701e099cadd0914eca14c97262d), and it fails to compile here (up to date MinGW) when `-DEXIV2_ENABLE_BMFF=OFF`.

**Comment by kmilos** [comment]
I admit it is pretty weird since it is not guarderd by any #ifdef in the header file, so should be exported...

Maybe I did something wrong, I'll check again

**Comment by clanmills** [comment]
Crap.  It's a bug.  I'll have to fix that.  The work around (for now) is of course:

```cpp
#include <exiv2/exiv2.hpp>
....
#if EXIV2_TEST_VERSION(0,27,4)
#ifdef EXV_ENABLE_BMFF
    Exiv2::enableBMFF(true);
#endif
#endif
```

**Comment by clanmills** [comment]
The fix is:

```
746 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ git diff
diff --git a/include/exiv2/exiv2.hpp b/include/exiv2/exiv2.hpp
index 5efd9d57..b4bb507b 100644
--- a/include/exiv2/exiv2.hpp
+++ b/include/exiv2/exiv2.hpp
@@ -45,9 +45,7 @@
 #include "exiv2/mrwimage.hpp"
 #include "exiv2/orfimage.hpp"
 #include "exiv2/pgfimage.hpp"
-#ifdef EXV_ENABLE_BMFF
 #include "bmffimage.hpp"
-#endif
 
 #ifdef EXV_HAVE_LIBZ
 #include "exiv2/pngimage.hpp"
747 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

I'll open an issue report about this.  Thank You for letting me know.

**Comment by clanmills** [comment]
Logged: https://github.com/Exiv2/exiv2/issues/1508

**Comment by clanmills** [comment]
#1508 is a documentation error.  The correct way to use enableBMFF() is:

```cpp
#include <exiv2/exiv2.hpp>
....
#ifdef EXV_ENABLE_BMFF
    Exiv2::enableBMFF(true);
#endif
```

@1div0 I think there's an implication for you because I believe you submitted the `#if EXIV2_TEST_VERSION(0,27,4)` code to libavif and/or digikam.

I think @kmilos has this covered for **darktable**.

**Comment by kmilos** [comment]
I think @1div0 authored all the patches above that need to be refreshed.

**Comment by 1div0** [comment]
I will take care of it during happy WE.

**Comment by clanmills** [comment]
I'm going to close this as I believe this is complete.  @1div0 if there's something still to be done here, we can reopen the issue.

**Comment by 1div0** [comment]
OK
