### ISSUE TITLE
Joining KDE community

### ISSUE THREAD

**Issue by alexvanderberkel** [Exiv2/exiv2#1494]
During the Future of Exiv2 meeting (see issue #1466) it has been decided to evaluate the possiblity to join the KDE community. The first contact has been established and can be followed on the mailing list (https://mail.kde.org/pipermail/kde-devel/2021-March/000360.html). 

Current status: 
- In order to import all all resources from GitHub, the KDE importer needs to enhanced. 
- A ticket for this has been filed at under: https://go.kde.org/systickets
- Personal identities for KDE communities can be created on: https://identity.kde.org
- Set the email address they use on KDE Identity (and thus Invent) to be the same as their publicly visible email address on GitHub.com? (https://docs.github.com/en/rest/reference/users#get-a-user). This is necessary to ensure that everything is mapped to the right users as part of the import process. If no public email is available, it will not be possible to associate content people have authored on GitHub.com with their KDE Invent (invent.kde.org) when it is imported. That content will instead be associated with a Ghost User.

Done:
- Incubator page (https://community.kde.org/Incubator/Projects/Exiv2) --> Agreed by our sponsor as finalized

Next steps: 
- Estimate effort within the team for migrating project into KDE community.  
- Check KDE license and its applicability to Exiv2
- Signup of all necessary contributors to KDE Identity in order to not loose the history

In progress:

**Comment by clanmills** [comment]
Let's aim for the goal of Exiv2 v1.00 in 2021.  It is a surprise that this goal is now within reach.  https://github.com/Exiv2/exiv2/issues/1466#issuecomment-811787134

We have enjoyed a warm and friendly greeting from KDE.  Joining KDE will probably be the Exiv2 goal in 2022.  

I'm very happy with this "two step" approach.

**Step 1 _(2021)_** is v1.00 and for the team to bond and understand more of the code.  Who knows, perhaps somebody _(@alexvanderberkel)_ will agree to be the Project Leader _(Maintainer)_. Another way to express this is _Make Team Exiv2 and the Exiv2 Project **rock solid** and ready for the future._

**Step 2 _(2022)_** is to transition the project resources to KDE approved infrastructure.  KDE may ask for substantial changes to our documentation, build, test or security process.  When Exiv2 v1.00 has been achieved, KDE requests can be handled without causing chaos.
