### ISSUE TITLE
test suite issues for v0.27.4 RC2

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1502]
There are errors in the build logs for 0.27.4 RC1.  We should investigate and fix them for RC2.  The errors can be inspected in <bundle>/logs/built.txt

**MinGW Cygwin macOS**  _**All Clean**_

**Test Suite Design Issue**
The suite mustn't give up when it encounters the first error.  It should continue to the end and report errors.  If python_tests fail, the suite terminates and doesn't run version_test.

**Linux**

Lots of messages such as below.  On the MacMini build, it doesn't seem to run the executables (exiv2 etc).  This is weird because it's working fine from the terminal _**on the same machine**_.  It's working correctly on the CI.  It's a false report from the test harness.

When I run from the terminal, I only get the **timeout** issue.  Everything else is OK.  I discuss **timeout** below.

```
======================================================================
ERROR: addmoddel_test (testcases.TestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rmills/gnu/github/exiv2/buildserver/tests/bash_tests/testcases.py", line 25, in addmoddel_test
    out     += BT.Executer('exiv2 -pv {jpg}', vars())
  File "/home/rmills/gnu/github/exiv2/buildserver/tests/bash_tests/utils.py", line 471, in __init__
    self.run()
  File "/home/rmills/gnu/github/exiv2/buildserver/tests/bash_tests/utils.py", line 509, in run
    raise RuntimeError('\n' + log.to_str())
RuntimeError: 
[ERROR] Failed to execute: ['/home/rmills/gnu/github/exiv2/buildserver/build/bin/exiv2', '-pv', 'exiv2-empty.jpg']
[ERROR] The asserted return code is [0], but got 127
[INFO] OUTPUT:
/home/rmills/gnu/github/exiv2/buildserver/build/bin/exiv2: symbol lookup error: /home/rmills/gnu/github/exiv2/buildserver/build/bin/exiv2: undefined symbol: _Z11_exvGettextPKc
```

**Visual Studio msvc**

```
======================================================================
FAIL: test_run (bugfixes.github.test_issue_1472.test_issue_1472Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\rmills\gnu\github\exiv2\buildserver\tests\system_tests.py", line 666, in test_run
    self.assertFalse(timeout["flag"], msg="Timeout reached")
AssertionError: True is not false : Timeout reached
```

We should **forgive** this error using the optional forgive parameter on BT.reportTest().  We should find out why the test is timing out on the build on the MacMini.  It runs safely on the CI.

**Comment by piponazo** [comment]
Hi @clanmills. When you said:

> The errors can be inspected in /logs/built.txt

To which file are you referring to? Could you attach it in the issue? I wanted to take a look to #1527 , but I would need to see the errors reported in the first place (and try to reproduce it on my system too).

**Comment by clanmills** [comment]
You can download the msvc build from pre-release.exiv2.org  https://pre-release.exiv2.org/builds/exiv2-0.27.4.1-2019msvc64.zip  The logs is logs/build.txt and finishes:

```bash
Renaming file to ./20010405_235039.jpg
File  6/16: exiv2-canon-eos-300d.jpg
Renaming file to ./20030925_201850.jpg

======================================================================
FAIL: test_run (bugfixes.github.test_issue_1472.test_issue_1472Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\rmills\gnu\github\exiv2\buildserver\tests\system_tests.py", line 666, in test_run
    self.assertFalse(timeout["flag"], msg="Timeout reached")
AssertionError: True is not false : Timeout reached

----------------------------------------------------------------------
Ran 223 tests in 391.009s

FAILED (failures=1, errors=1, skipped=10)
Skipped. Because exiv2 is not built with nls.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'C:\Users\rmills\gnu\github\exiv2\buildserver\build\CMakeFiles\f53e15f1876cafe4d906fe2815c71d4e\tests.rule;C:\Users\rmills\gnu\github\exiv2\buildserver\CMakeLists.txt' exited with code 1. [C:\Users\rmills\gnu\github\exiv2\buildserver\build\tests.vcxproj]
``` 

Because this python test timed out, the test suite was abandoned and didn't run version_test.  I want it to run all four elements and not give up when there's an error.

**Comment by clanmills** [comment]
This is a nuisance on the mac-mini buildserver.  It's working fine on the CI.  So let's do nothing about this.
