### ISSUE TITLE
some [Canon] & [Composite] tags get lost or modified

### ISSUE THREAD

**Issue by tenzap** [Exiv2/exiv2#1589]
With linked canon pictures, some [Canon] & [Composite] tags get lost or modified when for example deleting thumbnail when running:

```exiv2 -dt pic.jpg```

Same problem when inserting thumbnail, and maybe whichever operation we do.

This is with 0.27.4 RC2

Sample pictures:
* https://github.com/ianare/exif-samples/raw/master/jpg/hdr/canon_hdr_NO.jpg
* https://github.com/ianare/exif-samples/raw/master/jpg/hdr/canon_hdr_YES.jpg

Report of diff using "exiftool -a -G1 pic.jpg" for one of the pictures above, the other picture has a different diff result
```diff
-[Canon]         AE Setting                      : Normal AE
-[Canon]         AEB Bracket Value               : 0
-[Canon]         AF Area Heights                 : 622 0 0 0 0 0 0 0 0
-[Canon]         AF Area Mode                    : Off (Manual Focus)
-[Canon]         AF Area Widths                  : 829 0 0 0 0 0 0 0 0
-[Canon]         AF Area X Positions             : 0 0 0 0 0 0 0 0 0
-[Canon]         AF Area Y Positions             : 0 0 0 0 0 0 0 0 0
-[Canon]         AF Image Height                 : 3456
-[Canon]         AF Image Width                  : 4608
-[Canon]         AF Points In Focus              : (none)
-[Canon]         Aspect Ratio                    : 4:3
-[Canon]         Auto Exposure Bracketing        : Off
-[Canon]         Auto ISO                        : 400
-[Canon]         Auto Rotate                     : Rotate 90 CW
-[Canon]         Base ISO                        : 200
-[Canon]         Bulb Duration                   : 0
-[Canon]         Camera ISO                      : Auto
-[Canon]         Camera Temperature              : 21 C
-[Canon]         Camera Type                     : Compact
-[Canon]         Canon Exposure Mode             : Program AE
-[Canon]         Canon Firmware Version          : Firmware Version 1.00
-[Canon]         Canon Flash Mode                : Off
-[Canon]         Canon Image Height              : 1536
-[Canon]         Canon Image Size                : Medium 2
-[Canon]         Canon Image Type                : IMG:PowerShot SX60 HS JPEG
-[Canon]         Canon Image Width               : 2048
+[Canon]         Aspect Ratio                    : 3:2
+[Canon]         Camera Temperature              : 0 C
+[Canon]         Canon Firmware Version          : 
+[Canon]         Canon Image Type                : 
 [Canon]         Canon Model ID                  : PowerShot SX60 HS
-[Canon]         Categories                      : (none)
-[Canon]         Continuous Drive                : Single
-[Canon]         Contrast                        : Normal
-[Canon]         Control Mode                    : Camera Local Control
-[Canon]         Cropped Image Height            : 3456
+[Canon]         Cropped Image Height            : 0
-[Canon]         Cropped Image Width             : 4608
+[Canon]         Cropped Image Width             : 0
 [Canon]         Date Stamp Mode                 : Off
-[Canon]         Daylight Savings                : Off
-[Canon]         Digital Zoom                    : None
-[Canon]         Easy Mode                       : Manual
-[Canon]         Exposure Compensation           : +1
-[Canon]         Exposure Time                   : 1/64
-[Canon]         F Number                        : 5.6
-[Canon]         Faces Detected                  : 0
 [Canon]         File Number                     : 102-0153
 [Canon]         Firmware Revision               : 1.00 rev 2.00
-[Canon]         Flash Activity                  : 0
-[Canon]         Flash Bits                      : (none)
-[Canon]         Flash Exposure Compensation     : 0
-[Canon]         Flash Guide Number              : 0
-[Canon]         Flash Output                    : 0
-[Canon]         Focal Units                     : 100/mm
-[Canon]         Focus Continuous                : Manual
-[Canon]         Focus Distance Lower            : 0 m
-[Canon]         Focus Distance Upper            : 65.53 m
-[Canon]         Focus Mode                      : Manual Focus (3)
-[Canon]         Focus Range                     : Manual
-[Canon]         Image Stabilization             : On (2)
-[Canon]         Image Unique ID                 : 54e8b2b5539347478841864f8be0dcc5
-[Canon]         Intelligent Contrast            : On (0x09)
-[Canon]         Lens Type                       : n/a
-[Canon]         Macro Mode                      : Normal
-[Canon]         Manual Flash Output             : n/a
-[Canon]         Max Aperture                    : 5.6
-[Canon]         Max Focal Length                : 247 mm
-[Canon]         Measured EV                     : 10.19
-[Canon]         Metering Mode                   : Evaluative
-[Canon]         Min Aperture                    : 8
-[Canon]         Min Focal Length                : 3.8 mm
-[Canon]         My Color Mode                   : Off
-[Canon]         ND Filter                       : Off
-[Canon]         Num AF Points                   : 9
-[Canon]         Optical Zoom Code               : 139
-[Canon]         Quality                         : Fine
-[Canon]         Record Mode                     : JPEG
-[Canon]         Saturation                      : Normal
-[Canon]         Self Timer                      : Off
-[Canon]         Self Timer 2                    : 0
-[Canon]         Sharpness                       : 0
-[Canon]         Shot Number In Continuous Burst : 0
-[Canon]         Slow Shutter                    : Off
-[Canon]         Spot Metering Mode              : Center
-[Canon]         Target Aperture                 : 5.6
-[Canon]         Target Exposure Time            : 1/60
+[Canon]         Image Unique ID                 : e7e976fa3c9347478841864f8be0dcc5
 [Canon]         Thumbnail Image Valid Area      : 0 0 0 0
-[Canon]         Time Zone                       : +01:00
-[Canon]         Time Zone City                  : (not set)
 [Canon]         VRD Offset                      : 0
-[Canon]         Valid AF Points                 : 1
-[Canon]         White Balance                   : Auto
-[Canon]         Zoom Source Width               : 4608
-[Canon]         Zoom Target Width               : 4608


-[Composite]     Depth Of Field                  : 21.75 m (25.17 - 46.92 m)
-[Composite]     Drive Mode                      : Single-frame Shooting
 [Composite]     Field Of View                   : 6.4 deg
 [Composite]     Focal Length                    : 57.0 mm (35 mm equivalent: 319.9 mm)
 [Composite]     Hyperfocal Distance             : 108.41 m
-[Composite]     ISO                             : 800
 [Composite]     Image Size                      : 2048x1536
-[Composite]     Lens                            : 3.8 - 247.0 mm (35 mm equivalent: 21.3 - 1385.8 mm)
-[Composite]     Lens                            : 3.8 - 247.0 mm
-[Composite]     Lens ID                         : Unknown 3-247mm
 [Composite]     Light Value                     : 7.9
 [Composite]     Megapixels                      : 3.1
 [Composite]     Scale Factor To 35 mm Equivalent: 5.6
-[Composite]     Shooting Mode                   : Program AE
```

**Comment by kmilos** [comment]
Just an FYI: ExifTool's "Composite" tags are [derived/calculated](https://exiftool.org/TagNames/Composite.html) from data, and not actually in the file, so not really relevant for the issue here.

**Comment by tenzap** [comment]
> Just an FYI: ExifTool's "Composite" tags are [derived/calculated](https://exiftool.org/TagNames/Composite.html) from data, and not actually in the file, so not really relevant for the issue here.

Oh ok, I didin't know that, thanks. So problem is with the Canon tags then.

**Comment by hassec** [comment]
It seems that exiv2 doesn't correctly handle the specific makernote in these files...   
Which probably leads to exiv2 messing up the file when one runs `exiv2 -dt`    

Sorry that I can't be more helpful yet.  
Will have to do some more digging.

**Comment by hassec** [comment]
@tenzap are the images you linked straight out of the camera or were they previously modified by some tool?

**Comment by tenzap** [comment]
I don't know if they have been modified.

They have been contributed in that repo by 
`Contributed by: Jesus Cea <jcea@jcea.es>`

See readme in https://github.com/ianare/exif-samples/tree/master/jpg/hdr

**Comment by tenzap** [comment]
> https://github.com/ianare/exif-samples/blob/master/jpg/README

**Comment by hassec** [comment]
Ok, so the good news are that I think I know the reason for the problem: 

The offsets of the makernote IFDs are incorrect. 
Apparently there are multiple things that can cause this... One of which is editing a file with software that doesn't properly handle these makernotes.  

There is some documentation about this in the [exiftool doc](https://exiftool.org/exiftool_pod.html). (search for `fixbase`)

Now that we know this we can come up with a workaround, by simply using `exiftool` to fix the offsets. 
It does so when we write an exif field.

To not actually change the content we do the following:
1. Determine value of one field
```
$ exiftool -exif:resolutionunit tmp.jpg
> Resolution Unit                 : inches
```
2. Overwrite with same value
```bash
$ exiftool -F -exif:resolutionunit=inches tmp.jpg
```

Now you can run `exiv2 -dt` on that file without `exiv2` screwing up these files, and the reported canon tags are still there. 


Now whether there is going to be an `exiv2` only solution soon, I don't know... 
Technically the file is in a somewhat broken state, and `exiftool` seems to notice this and account for that.
Amazing job `exiftool`!! :tada: :muscle: 
I'm new to this project and don't know if we want to go down the road of trying to "on the fly fix" files.  
Just seems like a very open and never ending problem landscape...    

@clanmills are you aware of similar problems in the past? Is this something that is common enough for us to make this urgent? 
Also would love to hear @piponazo's opinion on this.   

Maybe we will just leave this open and try to come up with a solution when the canon makernote gets modernized?

**Comment by clanmills** [comment]
The differences in the metadata between canon_hdr_NO.jpg and canon_hdr_YES.jpg are considerable.  Changes have been made in the the `[exifIFD]` and `[canon makernote]`.  However most of the data in both are untouched.  I'm not convinced that the simple explanation that an incorrect offset to an IFD.  If that were true, the data would be massively disturbed.

A solid issue here is that ExifTool reports `[Composite]` tags which are calculated from other metadata by ExifTool and not by Exiv2.  I don't think Exiv2 should get into the interpretation/manufacture of metadata and should report exactly what's in the file.  If an application such as **darktable** believes `[composite]` values are important to photographers, they can calculate them and display them in their UI.

If **darktable** wants Exiv2 to calculate `[composite]` tags, they could raise an enhancement request for Exiv2 to support this.  In 2019, I did manufacture tags using Canon AutoFocus data. #1001.  With Exiv2 v1.00, we have the opportunity to modify the API and could add a "manufactured" field to TagInfo as such data requires careful handling during writeMetadata().

I haven't studied the claim that deleting the thumbnail causes collateral metadata damage.

We're discussing about four different matters here, so the signal to noise ratio here isn't good.  We need an original camera file which is edited in a simple manner such as:

1. Delete the the thumbnail (and nothing else)
2. Change a single tag in the `[exifIFD]` such as Exif.Photo.DateTimeDigitized (and nothing else)
3. Change a single maker note tag such as Exif.CanonCs.Timer (and nothing else)

I recommend that `[Composite]` tags be handled in the host application and not in the library as those tags are not in the image.

**Comment by hassec** [comment]
Thanks @clanmills for the comments :+1:   

@tenzap, for now at least, the problem of "fixing files on the fly" is out of scope for exiv2.   
Thus, I'll go ahead and label this "wonfix" and close it.   

Please feel free to reopen the issue if you'd like to further discuss this :blush:

**Comment by tenzap** [comment]
I'm not sure I understand everything very well.

I understand that you claim that the metadata has been modified by another tool which didn't update the IFD correctly resulting in exiv2 not being able to understand them. Again I don't know what happened to these test files (the provider of the files didn't answer to my email unfortunately). If input is bad, I can understand that exiv2 may not want to fix them like exiftool does.

I believe canon_hdr_NO.jpg and canon_hdr_YES.jpg are two different pictures, they are not related in sense of one being a derivative of the other in terms of exif metadata.

Concerning composite, it is not that I want it particularly, it was just to show all the differences I get when making a diff, I didn't meant in anyway that it is a bug in exiv2. I event didn't know Composite was actually a "computed" tag by exiftool.

My report was mainly to show that it seems some tags are lost in the process of deleting a thumbnail (and probably any other operation on the exif metadata), I don't have the knowledge to understand/dig more.

Thanks for having had a look at all this

**Comment by clanmills** [comment]
When I went for a walk today, I started to thing about this bug and thought _I'll investigate using -dt on an image from my Canon IXUS 185 Point and Shoot"_.  I'm pleased to say that:

1) The layout of the metadata in my canon image is very similar to Canon PowerShot SX60 HS in your test images.
2) The behaviour of -dt on my image looks correct.
3) There is no collateral metadata damage inflicted by \-dt

Your test images:

```
$ exiv2 -g make/i -g model/i canon*.jpg
canon_hdr_NO.jpg      Exif.Image.Make                              Ascii       6  Canon
canon_hdr_NO.jpg      Exif.Image.Model                             Ascii      24  Canon PowerShot SX60 HS
canon_hdr_NO.jpg      Exif.Photo.MakerNote                         Undefined 5414  31 0 1 0 3 0 ...
canon_hdr_NO.jpg      Exif.MakerNote.Offset                        Long        1  786
canon_hdr_NO.jpg      Exif.MakerNote.ByteOrder                     Ascii       3  II
canon_hdr_NO.jpg      Exif.Canon.ModelID                           Long        1  PowerShot SX60 HS
canon_hdr_YES.jpg     Exif.Image.Make                              Ascii       6  Canon
canon_hdr_YES.jpg     Exif.Image.Model                             Ascii      24  Canon PowerShot SX60 HS
canon_hdr_YES.jpg     Exif.Photo.MakerNote                         Undefined 5414  31 0 1 0 3 0 ...
canon_hdr_YES.jpg     Exif.MakerNote.Offset                        Long        1  786
canon_hdr_YES.jpg     Exif.MakerNote.ByteOrder                     Ascii       3  II
canon_hdr_YES.jpg     Exif.Canon.ModelID                           Long        1  PowerShot SX60 HS
```

My photo:
```
$ exiv2 -g make/i -g model/i img_2129.jpg
Exif.Image.Make                              Ascii       6  Canon
Exif.Image.Model                             Ascii      16  Canon IXUS 185 
Exif.Photo.MakerNote                         Undefined 5870  31 0 1 0 3 0 ...
Exif.MakerNote.Offset                        Long        1  790
Exif.MakerNote.ByteOrder                     Ascii       3  II
Exif.Canon.ModelID                           Long        1  PowerShot ELPH 185 / IXUS 185 / IXY 200
```

Extract the metadata, delete the thumbnail and extract again:
```
$ exiv2 -pa img_2129.jpg > orig.txt
$ exiv2 -dt img_2129.jpg
$ exiv2 -pa img_2129.jpg > dt.txt
```
Display the changes in the metadata:

```
$ diff orig.txt dt.txt
27c27
< Exif.Photo.MakerNote                         Undefined 5870  31 0 1 0 3 0 ...
---
> Exif.Photo.MakerNote                         Undefined 5862  31 0 1 0 3 0 ...
112c112
< Exif.Photo.InteroperabilityTag               Long        1  6924
---
> Exif.Photo.InteroperabilityTag               Long        1  6940
128c128
< Exif.Image.GPSTag                            Long        1  7034
---
> Exif.Image.GPSTag                            Long        1  6994
130,135d129
< Exif.Thumbnail.Compression                   Short       1  JPEG (old-style)
< Exif.Thumbnail.XResolution                   Rational    1  180
< Exif.Thumbnail.YResolution                   Rational    1  180
< Exif.Thumbnail.ResolutionUnit                Short       1  inch
< Exif.Thumbnail.JPEGInterchangeFormat         Long        1  20468
< Exif.Thumbnail.JPEGInterchangeFormatLength   Long        1  5248
```

For sure there is no collateral damage the metadata.  The primary difference is of course the removal of the Exif.Thumbnail.* tags.  There minor changes to the MakerNote, InteroperabilityTag and _surprisingly_ GPSTag.  I could dig in with the debugger and explain the changes byte-by-byte, however I don't believe that's necessary.

I have a feeling that you are relaying this issue from elsewhere.  Somebody has said "There's something wrong with the metadata in canon_hdr_YES.jpg or canon_hdr_NO.jpg"  The relationship between the two files isn't explained.  I encourage you to invite the person who raised this issue to read this analysis provide more information.

I've discussed this on the Exiv2 Chatserver with @hassec.  We agree that making progress with this issue isn't possible because it has not been presented with sufficient clarity.  Of course, that doesn't mean that Exiv2 is innocent.

I've now retired from Exiv2.  If you have additional information about this matter, please update the issue.  I am willing to help debug/analyse this issue when more evidence is available.

**Comment by tenzap** [comment]
These files are provided by this [repo](https://github.com/ianare/exif-samples).

I used them to test my code in [this app](https://github.com/tenzap/exif-thumbnail-adder) which uses exiv2 to add thumbnails. I noticed the differences I filed in this bug report and found that the issue was no in my code but linked to exiv2 and narrowed it down to show there is some issue somewhere when deleting a thumbnail (inserting also lead to the same diff, but the deletion command was easier to provide a test case rather than inserting it or changing any tag)

I created an [issue](https://github.com/ianare/exif-samples/issues/7) in the [repo](https://github.com/ianare/exif-samples). to get more info on these files (if they have been transformed or if they are original) My understanding is these are 2 different shots with the same camera, one with HDR enabled, and one with HDR disabled. As you say, it would be much better if we had the original picture if this one is indeed transformed. Hopefully we will have an update on this to be sure where the problem actually lies.

BTW, there are other canon files in that repo for which there is no problem. Only these two picture show that bug.

**Comment by tenzap** [comment]
I tried with two pictures I found on the internet and which are said to be original.
They are taken by the same camera (Canon PowerShot SX60 HS) as those from the initial report:

* [IMG_0689.JPG](http://www.steves-digicams.com/camera-reviews/canon/powershot-sx60-hs/IMG_0689.JPG) from [http://www.steves-digicams.com/camera-reviews/canon/powershot-sx60-hs/sample-photos-332.html](http://www.steves-digicams.com/camera-reviews/canon/powershot-sx60-hs/sample-photos-332.html)
* [canon_powershot_sx60_hs_01.jpg](https://img.photographyblog.com/reviews/canon_powershot_sx60_hs/photos/canon_powershot_sx60_hs_01.jpg) from [https://www.photographyblog.com/previews/canon_powershot_sx60_hs_photos](https://www.photographyblog.com/previews/canon_powershot_sx60_hs_photos)

Removal of thumbnails by exiv2 showed nothing wrong.

This tends to confirm that these files are not the original & what @hassec said:

>Apparently there are multiple things that can cause this... One of which is editing a file with software that doesn't properly handle these makernotes.

I asked again the original contributor of the canon_hdr_YES.jpg & canon_hdr_NO.jpg if by chance he could provide the original pictures. Let's see.

**Comment by clanmills** [comment]
Thank for following through on this.  I'll self-assign and reopen the issue.  Let's not use the word *bug* until we have a solid case that exiv2 is behaving incorrectly.

**Comment by clanmills** [comment]
I'm also assigning this to milestone v1.00.  In the release notes, I list issues which are "Withdrawn/No Action".

**Comment by clanmills** [comment]
@tenzap I'm impressed to see you have an application to add thumbnail to images.  That capability has never been implemented in Exiv2.  Could you think about joining Team Exiv2 and porting your code into the library.  I've retired from Exiv2, so I'm not offering to mentor or support you.  However I've retired _after 13 years of working on the code_ in the knowledge that there is group of friendly, clever engineers contributing to Exiv2 and I know you'll enjoy working with them.

**Comment by tenzap** [comment]
It is possible to add thumbnails with exiv2 with -it option, I simply reused what is already in exiv2.

Thank you for your proposal, but sorry I don't plan to join the team, I'm more sort of a hobby developer.

Thanks for the great exiv2 tool/lib

**Comment by tenzap** [comment]
I just added some code to add the mandatory exif tags in case there is no exif metadata at all in the file.

You may find it [here](https://github.com/tenzap/exif-thumbnail-adder/blob/master/app/src/main/cpp/Exiv2Helper.cpp)

**Comment by clanmills** [comment]
I'm making up the release notes for v0.27.4.  I'm going to assign this to v0.27.4 and close it.  If/when more information concerning this is available, please open a new issue.
