### ISSUE TITLE
Broken example in man page

### ISSUE THREAD

**Issue by jwilk** [Exiv2/exiv2#1685]
The exiv2 manual page contains the following example:

```console
$ exiv2 insert -l/tmp -S.CRW /data/*.JPG
```
But as of 74bc0e05359fbe843066c3bda53fd56a5a45d976, options are required to be specified before the action, so this no longer works.

**Comment by hassec** [comment]
Thanks for reporting this :+1:   

Documentation should be updated to say: 
```bash
$ exiv2 -l/tmp -S.CRW insert /data/*.JPG
```
