### ISSUE TITLE
Unstable outputs of exiv2

### ISSUE THREAD

**Issue by shao-hua-li** [Exiv2/exiv2#1717]
Hi there,

I found that `exiv2 -p a` would give out unstable results, i.e., some field(s) may change per run. For the input I provide, the field `Exif.Canon.SerialNumber` would change every time you run it.

- exiv2 version: 1.0.0.9 (commit 19000cd53c98c8d8e913349b410bd13a64641747)
- Compiler: clang12
- Platform: Ubuntu 20.04.2 LTS, x86_64
- Reproduce: run `exiv2 -p a diff_1` a few times and check `Exif.Canon.SerialNumber` row.
- File:  [diff_1.tar.gz](https://github.com/Exiv2/exiv2/files/6658615/diff_1.tar.gz) (decompress it first)

I did some analysis and found that the root cause is probably in `canonmn_int.cpp:print0x000c` function. When `is` is an empty string (which is the case for `diff_1`), variable `l` will be assigned an uninitialised value with `is >> l`. A possible quick fix would be adding an empty string check here.

**Comment by kevinbackhouse** [comment]
Yes, this is because `l` is not uninitialized at [canonmn_int.cpp, line 2764](https://github.com/Exiv2/exiv2/blob/fec1813a3e7b0e4aaed7fae7ba9f9b49ca526638/src/canonmn_int.cpp#L2764).

**Comment by hassec** [comment]
Should be fixed in `0.27-maintenance` and `main`, thanks to @kevinbackhouse
