### ISSUE TITLE
strange strings from exifData[exif_data_ptr->key()].toString().c_str();

### ISSUE THREAD

**Issue by CliveMcCarthy** [Exiv2/exiv2#1719]
I'm using exiv2 0.27.2 on Linux 5.12.2 and compiling with gcc version 8.4.0

Something odd is happening with data returned from exifData[exif_data_ptr->key()].toString().c_str(); when it is assigned to a pointer but NOT in all cases. The issue is specific to the EXIF_DATETIME_TAG and EXIF_ORIGINAL_DATETIME_TAG.

Here is my code:
```cpp
/*------------------------------------------------------------------------------
	exiv2 0.27.2
	sudo apt install libexiv2-dev
	#include <exiv2/exiv2.hpp>
	libexiv2.a
------------------------------------------------------------------------------*/
static bool exiv2(const char *jpg_filename, IMAGE *jpg_image)
{
	char *exif_data;
	int exif_entries = 0;

	Exiv2::ExifData::const_iterator exif_data_ptr, begin, end;
	Exiv2::Image::AutoPtr exiv2_image;

    exiv2_image = Exiv2::ImageFactory::open(jpg_filename);

    if(!exiv2_image.get())
    {
		image_lib_program_warning(__FILE__, __LINE__, __FUNC__,
			"exiv2 can't read file\n\t<%s>", jpg_filename);
		return EXIT_FAILURE;
    }

    exiv2_image->readMetadata();
    Exiv2::ExifData &exifData = exiv2_image->exifData();
	begin	= exifData.begin();
    end		= exifData.end();

    for(exif_data_ptr = begin; exif_data_ptr != end; exif_data_ptr++)
    {
		exif_entries++;
 		exif_data = (char *)exifData[exif_data_ptr->key()].toString().c_str();

		switch(exif_data_ptr->tag())
		{
			case EXIF_CAMERA_MANUFACTURER_TAG:
				printf("\tEXIF_CAMERA_MANUFACTURER_TAG\t\"%s\"\n", exif_data);
				// not used
			break;

			case EXIF_CAMERA_MODEL_TAG:
				printf("\tEXIF_CAMERA_MODEL_TAG\t\t\"%s\"\n", exif_data);
				strncpy(jpg_image->CameraModel, exif_data, CAMERA_MODEL_STRING_LENGTH - 1);
			break;

			case EXIF_ORIENTATION_TAG:
				printf("\tEXIF_ORIENTATION_TAG\t\t\"%s\"\n", exif_data);
				jpg_image->orientation = atoi(exif_data);
			break;

			case EXIF_DATETIME_TAG:
				printf(ANSI_COLOR_LIGHT_RED);
/* problem	*/	printf("\tEXIF_DATETIME_TAG\t\t\"%s\"\t???\n", exif_data);
				printf(ANSI_COLOR_RESET);
/*   OK 	*/	printf("\tEXIF_DATETIME_TAG\t\t\"%s\"\n", exifData[exif_data_ptr->key()].toString().c_str());
				strncpy
				(
					jpg_image->DateTime,
					exifData[exif_data_ptr->key()].toString().c_str(),
					DATETIME_STRING_LENGTH - 1
				);

				convert_tiff_time_string_to_tea_time
				(
					jpg_image->DateTime,
					&(jpg_image->time_shot)
				);
			break;

			case EXIF_ORIGINAL_DATETIME_TAG:
				printf(ANSI_COLOR_LIGHT_RED);
/* problem	*/	printf("\tEXIF_ORIGINAL_DATETIME_TAG\t\"%s\"\t???\n", exif_data);
				printf(ANSI_COLOR_RESET);
/*   OK 	*/	printf("\tEXIF_ORIGINAL_DATETIME_TAG\t\"%s\"\n", exifData[exif_data_ptr->key()].toString().c_str());
				convert_tiff_time_string_to_tea_time(exif_data, &jpg_image->time_shot);
			break;

			case EXIF_ISO_TAG: // ISO speed rating
				printf("\tEXIF_ISO_TAG\t\t\t\"%s\"\n", exif_data);
				jpg_image->iso = atoi(exif_data);
			break;

			case EXIF_SOFTWARE_TAG:
				printf("\tEXIF_SOFTWARE_TAG\t\t\"%s\"\n", exif_data);
				// not used
			break;

			default:
				//printf("\ttag %5d =\"%s\"\n", exif_data_ptr->tag(), exif_data);
			break;
		}
		printf(ANSI_COLOR_RESET);
    }
	printf("exif entries %d\n\n", exif_entries);
	return EXIT_SUCCESS;
}

```

**Comment by hassec** [comment]
Hi @CliveMcCarthy, thanks for the report! 

Do you think you could boil this down into a minimal reproducer, such that I could see what's going on?

**Comment by CliveMcCarthy** [comment]
I can't readily boil it down further. It is basically a small variation of your published exifprint.cpp example.

I simply added a switch statement inside the tag loop, dumped the hideous C++ cout stuff and put in a bunch of printf statements for the various cases. It seems that calls to exifData[exif_data_ptr->key()].toString().c_str(); _sometimes_ produce garbage.

I'm not a C++ programmer, I just write C so the 'conversions' of the exif data to a string and then a C string are beyond me. I presume that the calls reference a static string and that a pointer is returned to it ?

Here's a version with my specific calls deleted so this is even closer to the exifprint.cpp example.

/*------------------------------------------------------------------------------
	exiv2 0.27.2
	sudo apt install libexiv2-dev
	#include <exiv2/exiv2.hpp>
	libexiv2.a
------------------------------------------------------------------------------*/
static bool exiv2(const char *jpg_filename)
{
	char *exif_data;
	int exif_entries = 0;

	Exiv2::ExifData::const_iterator exif_data_ptr, begin, end;
	Exiv2::Image::AutoPtr exiv2_image;

    exiv2_image = Exiv2::ImageFactory::open(jpg_filename);

    if(!exiv2_image.get())
    {
		return EXIT_FAILURE;
    }

    exiv2_image->readMetadata();
    Exiv2::ExifData &exifData = exiv2_image->exifData();
	begin	= exifData.begin();
    end		= exifData.end();

    for(exif_data_ptr = begin; exif_data_ptr != end; exif_data_ptr++)
    {
		exif_entries++;

                // exif_data is a pointer to a string ???
 		exif_data = (char *)exifData[exif_data_ptr->key()].toString().c_str();

		switch(exif_data_ptr->tag())
		{
			case EXIF_CAMERA_MANUFACTURER_TAG:
				printf("\tEXIF_CAMERA_MANUFACTURER_TAG\t\"%s\"\n", exif_data);
			break;

			case EXIF_CAMERA_MODEL_TAG:
				printf("\tEXIF_CAMERA_MODEL_TAG\t\t\"%s\"\n", exif_data);
			break;

			case EXIF_ORIENTATION_TAG:
				printf("\tEXIF_ORIENTATION_TAG\t\t\"%s\"\n", exif_data);
			break;

			case EXIF_DATETIME_TAG:
				printf(ANSI_COLOR_LIGHT_RED);
/* problem	*/	printf("\tEXIF_DATETIME_TAG\t\t\"%s\"\t???\n", exif_data);
				printf(ANSI_COLOR_RESET);
/*   OK 	*/	printf("\tEXIF_DATETIME_TAG\t\t\"%s\"\n", exifData[exif_data_ptr->key()].toString().c_str());
			break;

			case EXIF_ORIGINAL_DATETIME_TAG:
				printf(ANSI_COLOR_LIGHT_RED);
/* problem	*/	printf("\tEXIF_ORIGINAL_DATETIME_TAG\t\"%s\"\t???\n", exif_data);
				printf(ANSI_COLOR_RESET);
/*   OK 	*/	printf("\tEXIF_ORIGINAL_DATETIME_TAG\t\"%s\"\n", exifData[exif_data_ptr->key()].toString().c_str());
			break;

			case EXIF_ISO_TAG: // ISO speed rating
				printf("\tEXIF_ISO_TAG\t\t\t\"%s\"\n", exif_data);
			break;

			case EXIF_SOFTWARE_TAG:
				printf("\tEXIF_SOFTWARE_TAG\t\t\"%s\"\n", exif_data);
			break;

			default:
				//printf("\ttag %5d =\"%s\"\n", exif_data_ptr->tag(), exif_data);
			break;
		}
		printf(ANSI_COLOR_RESET);
    }
	printf("exif entries %d\n\n", exif_entries);
	return EXIT_SUCCESS;
}

**Comment by hassec** [comment]
Hi @CliveMcCarthy, what makes this hard to debug is that you have a bunch of variables in your switch statement that aren't defined in exiv2 nor in the code you post... e.g.  `EXIF_ORIGINAL_DATETIME_TAG`

Anyway, I think you are running into lifetime problems here.  
Let's look at this line: 
```cpp
exif_data = (char *)exifData[exif_data_ptr->key()].toString().c_str();
```

the `toString` function is doing the translation of the binary data that was read from the file into something in ASCII and then returns a `std::string`.  
You now ask for the underlying pointer of that string via `c_str()` and assing that to `exif_data`. 
But the actual `std::string` isn't assigned to anything, thus goes out of scope after this line, and you are left with a dangling pointer.

Try the below:
```cpp
std::string tmp = exifData[exif_data_ptr->key()].toString();
exif_data = (char *)tmp.c_str();                            
```

as a sidenote, with this line
```cpp
    for(exif_data_ptr = begin; exif_data_ptr != end; exif_data_ptr++)
```
you are already iterating over the container `exifData`. Thus, every round in the for loop the exif_data_ptr points to an exif metadatum on which you can just call `toString()`  no reason to ask for it's key to then ask `exifData` again what entry that key belongs to.

Or in C-language :wink: :
```cpp
&(*exif_data_ptr) =  &exifData[exif_data_ptr->key()]
```

**Comment by CliveMcCarthy** [comment]
All I can say is that I hate C++. For me a simple pointer to data is all I needed but that isn't the way of the C++ world.

Thanks for your attention. Maybe you should publish a simple C version of exifprint.cpp so that others won't fall into the puzzle I had.
