### ISSUE TITLE
add lens: Olympus M.ZUIKO DIGITAL ED 12-45mm F4.0 PRO

### ISSUE THREAD

**Issue by andyrtr** [Exiv2/exiv2#1723]
This [Olympus 12-45 F4 Pro lens](https://asia.olympus-imaging.com/product/dslr/mlens/12-45_4pro/index.html) is not recognized by exiv2 (0.27.3 - Arch Linux):

exiv2 -pa some.ORF | grep -i LensType
```  
Exif.OlympusEq.LensType                      Byte        6  0 0 52 16 0 0  
```

I've added this to my ~/.exiv2
```
[olympus]
12 0 0 52 16 0 0=Olympus M.Zuiko Digital ED 12-45mm F4.0 Pro
```
giving the desired: exiv2 -pa some.ORF | grep -i LensType
```
Exif.OlympusEq.LensType                      Byte        6  Olympus M.Zuiko Digital ED 12-45mm F4.0 Pro
```

New imported pictures in darktable now exactly show that lense name. [lensfun db addition](https://github.com/lensfun/lensfun/issues/1345) is the next step now.

Please add this to data/db/mil-olympus.xml (line 1315)
`            { { 0, 52, 16 }, "Olympus M.Zuiko Digital ED 12-45mm F4.0 Pro"             },`

**Comment by hassec** [comment]
Hi @andyrtr :wave: 

Thanks for filing this issue!
The main problem with adding new lenses to the C++, is that we would like to have a test image to create a test for it.  
Thus we rely on users like you that own the lens in questions and can provide a `*.exv` test file.  

It would be amazing if you could just create a PR that includes the suggested change in `src/olympusmn_int.cpp` + a test image and test.  The procedure is pretty straight foward and outlined [here](https://github.com/Exiv2/exiv2/wiki/Adding-a-new-lens)

If you have the time to do that, it would be much appreciated! Feel free to assign that PR to me :blush: 

If this isn't possible, the minimum I'd need to move forward would be just a `*.exv` testfile for that lens and I can take care of the PR as soon as I find time.

**Comment by hassec** [comment]
cloesd by #1725
