### ISSUE TITLE
Make -t -r fmt options more flexible

### ISSUE THREAD

**Issue by ioctl-user** [Exiv2/exiv2#1770]
There is two issues.

1) For example, I want treat with "-t" option two files in the same directory:

IMG_20210101_123456001.jpg
IMG_20210101_123456002.jpg

The second run will fail, because these files should have the same name. Is it possible to add optional additional numeric extension like Android camera does? Like this:

20210101_123456.jpg
20210101_123456_1.jpg

2) Google Camera app sometimes add suffixes like PANO, MP, NIGHT and so on to files:

IMG_20210101_123456001.PANO.jpg

Is it possible to add option for saving this suffix after rename?

**Comment by norbertwg** [comment]
I wanted to start to work on these issues now. As I see it now, the first issue is solved. Here two quotes from man page:

- The [rename](https://exiv2.org/manpage.html#mv_rename) action will overwrite files when --force is used. Instead, if --Force is used and the file already exists, the new filename is appended with '_1' ('_2', ...) to prevent data loss.

- If the filename to rename to already exists and [--Force](https://exiv2.org/manpage.html#force_Force) and [--force](https://exiv2.org/manpage.html#force_Force) are not used, the user is prompted for an action.
...
[r]ename  Rename the file, but append '_1' ('_2', ...) to the new filename

@ioctl-user : can you confirm, that the first issue is solved for you?

For second issue I suggest to define a placeholder "basesuffix", which holds the text from first to last dot of original filename. The format "%d_%b_%Y:basesuffix" would then keep suffixes from Google Camera app.

@ioctl-user : does this fit to your needs?

**Comment by ioctl-user** [comment]
Yes, I can confirm the first issue is solved.

Idea about second issue looks good.

**Comment by norbertwg** [comment]
@ioctl-user as the associated pull request is merged, I think this issue can be closed. Do you agree or is something left to be done?

**Comment by ioctl-user** [comment]
I cannot check this now.
However if you fixed this, I agree with issue completeness.

**Comment by norbertwg** [comment]
Sorry, perhaps my idea when to close an issue is different from the usual procedure here. My understanding: close, when the related code change is merged. Then contributors looking for an issue to work on will not see it. But I understand also the idea to close it, when it is included in a release, so that it can be checked also by those who do not build an executable on their own using current state of software.
