### ISSUE TITLE
Canon CR3 format: Sigma 30 mm F1.4 DC DN (EFM) wrongly identified

### ISSUE THREAD

**Issue by dheijl** [Exiv2/exiv2#1782]
Camera: Canon M50
Lens: "Sigma 30mm F1.4 DC DN | Contemporary 016" (EF-M version) as reported by Canon DPP 4 

Both exiftool and exiv2 wrongly identify the lens as the "Sigma 56mm f/1.4 DC DN", although the focal length is correctly reported as 30mm.

Example CR3 file attached.

[IMG_2362.zip](https://github.com/Exiv2/exiv2/files/6830259/IMG_2362.zip)

**Comment by hassec** [comment]
This is because this lens isn't known to `exiv2` yet. 
As a workaround, you can use a configuration file as explained [here](https://exiv2.org/manpage.html)

Just add the below to said file
```
[canon]
4208=Sigma 30mm f/1.4 DC DN | C
```
and exiv2 will report the correct lens name:
```bash
Exif.CanonCs.LensType                        Short       1  Sigma 30mm f/1.4 DC DN | C
```

**Comment by dheijl** [comment]
Thanks! I'll do that.

**Comment by hassec** [comment]
@dheijl I've also created #1784 to add this lens to exiv2, so future releases will have this lens correctly identified without the need for a config file.

**Comment by dheijl** [comment]
Thanks and yes sure you can use the image!

**Comment by hassec** [comment]
Thanks!
