### ISSUE TITLE
Some easy way to access Exif metadata from root IFD and sub IFDs?

### ISSUE THREAD

**Issue by amyspark** [Exiv2/exiv2#1879]
Hi!

I'm implementing support for TIFF metadata [for Krita](https://invent.kde.org/graphics/krita/-/merge_requests/1015) and I ran into the following.

Currently, we use Exiv2 to handle only metadata, specially because we can feed the blobs straight to ExifParser. This, however, does not apply to TIFF; libtiff doesn't let you access the available fields wholesale without breaking into its internal state, and exiv2 (to the best of my ability) only parses the first IFD.

Is there any way to tell exiv2 to target only a given IFD/offset, beyond the first one?

**Comment by clanmills** [comment]
Exiv2 parses all the metadata including the linked list of IFDs.
