### ISSUE TITLE
errors when reading from Adobe DNG converted .nef, other unexpected results

### ISSUE THREAD

**Issue by dfontenot** [Exiv2/exiv2#1885]
Hello,

I am seeing some unexpected results with both the original .nef raw file my camera produced, and the resulting .dng file produced by Adobe DNG Converter 13.1.0.658. Ultimately, what I'm trying to do with these .dng files is run the lens correction module in Darktable, but Darktable (v 3.6.0) reports that it can't find the lens data for the converted .dng files. However, it can find the lens data for the original .nef files (I ensured that my lensfun database was up to date). They sent me here to report the issue. I think that these results may be interferring with Darktable.

Here are some of the results from printing out various lens-related tags (I have no idea which tags Darktable is using):

Exiv verison 0.27.2 (Ubuntu 20.04)
`exiv2 -g Exif.Image.LensInfo -Pv DSC_2062.NEF` (fails)
`exiv2 -g Exif.Image.LensInfo -Pv DSC_2062.dng`
Error: Directory Nikon1 with 25665 entries considered invalid; not read.
180/10 550/10 35/10 56/10
* Exif.Photo.LensSpecification (works only for the .dng)
* Exif.Photo.LensMake (does not work on either)
* Exif.Photo.LensModel (works only for the .dng)

Exiv nightly (downloaded today) version exiv2 1.0.0.9 (same results as above)
`/opt/exiv2-1.0.0.9-Linux64/bin/exiv2 -g Exif.Image.LensInfo -Pv DSC_2062.NEF` (fails)
`/opt/exiv2-1.0.0.9-Linux64/bin/exiv2 -g Exif.Image.LensInfo -Pv DSC_2062.dng`
Error: Directory Nikon1 with 25665 entries considered invalid; not read.
180/10 550/10 35/10 56/10
* Exif.Photo.LensSpecification (works only for the .dng)
* Exif.Photo.LensMake (does not work on either)
* Exif.Photo.LensModel (works only for the .dng)

I am able to pull some basic data from the original .nef using exiv2. e.g. `exiv2 -g Exif.Image.Make -Pv DSC_2062.NEF`. Additionally, I can view all of the lens data from both the .dng and the .nef with exiftool v 11.88.

I'm fairly confused by these results, I would have expected that the original .nef would have all of these values (because Adobe DNG Converter would have to get them from somewhere). I'm not sure if the error being printed is affecting Darktable's ability to do lens correction. Please let me know if my command line commands are incorrect, and / or if my understanding of exif is incorrect. Thanks for your time reading this.

**Comment by kmilos** [comment]
As I mentioned in the original dt reported issue, the lens info (and other data) in a NEF and a DNG are not necessarily stored in identical tags in identical ways.

**Comment by clanmills** [comment]
This is a very well written issue report.  Thanks.  If nobody else steps into this, please post the DNG and NEF files and I will investigate on Sunday.

I recommend that you try the commands `$ exiv2 -pR foo.dng` and `$ exiv2 -pR foo.nef` on your files.  These commands are useful for debugging files and reveal the structure of the file.  The tvisitor program in my book is similar and more robust. The commands are `$ tvisitor -pRU foo.dng` and `$ tvisitor -pRU foo.nef` https://clanmills.com/exiv2/book/

With Nikon images, the lens is usually identified with the tag: Exif.NikonLd3.LensIDNumber.  You can use the Exiv2 'configuration file' ~/.exiv2 to force lens recognition.  This might persuade darktable to recognise your lens correctly.  This is discussed in the exiv2 man page.  https://www.exiv2.org/manpage.html

**Comment by kmilos** [comment]
Run e.g. `exiv2 -pa` on both files to see the difference.

**Comment by dfontenot** [comment]
@kmilos I can post a diff between the two different outputs if it would help. The diff is very big due to the .dng having some tags e.g. Exif.Image.ProfileLookTableData with a lot of data in it, whereas the original .nef doesn't have that field at all.

Grepping for just lens data on the .nef
```
Exif.Nikon3.LensType                         Byte        1  D G VR
Exif.Nikon3.Lens                             Rational    4  18-55mm F3.5-5.6
Exif.Nikon3.LensFStops                       Undefined   4  5.33333
Exif.NikonLd3.LensIDNumber                   Byte        1  Nikon AF-P DX Nikkor 18-55mm f/3.5-5.6G VR
Exif.NikonLd3.LensFStops                     Byte        1  F5.3
```

And for the .dng
```
Error: Directory Nikon1 with 25665 entries considered invalid; not read.
Exif.Photo.LensSpecification                 Rational    4  180/10 550/10 35/10 56/10
Exif.Photo.LensModel                         Ascii      23  18.0-55.0 mm f/3.5-5.6
Exif.Image.LensInfo                          Rational    4  180/10 550/10 35/10 56/10
Xmp.aux.LensInfo                             XmpText    25  180/10 550/10 35/10 56/10
Xmp.aux.Lens                                 XmpText    22  18.0-55.0 mm f/3.5-5.6
Xmp.aux.LensID                               XmpText     3  160
```

I'm guessing the issue is the .nef has the tag that @clanmills mentioned and it's not listed in the .dng?

**Comment by dfontenot** [comment]
@clanmills thank you. Here are the links to the files. Please let me know when I can remove sharing on them.

[Original .nef](https://drive.google.com/file/d/1es9aieltPCQNphd7_9bQ8MlvLFLnBtzj/view?usp=sharing)
[Converted .dng](https://drive.google.com/file/d/1f0SuriuEMjTkkBrBETJsFgiRxj0qKWGS/view?usp=sharing)

These are different pictures than my test file DSC_2062 because that one contains people in it. It's shot with the same body and lens, and I tested my previous commands on them.

**Comment by clanmills** [comment]
I've hopped out of bed to get your files (it's almost mid-night in England).  I'll look at them on Sunday.

```bash
556 rmills@rmillsm1:~/clanmills $ dirod ~/Downloads/ | tail -2
-rw-r--r--@   1 rmills  staff  21908478 28 Aug 23:48 DSC_2080.dng
-rw-r--r--@   1 rmills  staff  24683213 28 Aug 23:48 20210827_0017.NEF
557 rmills@rmillsm1:~/clanmills $ 
```

**Comment by clanmills** [comment]
Here's the story so far:

```bash
524 rmills@rmillsm1:~/Downloads $ exiv2 -pa -g lens/i -g Exif.Image.Make  20210827_0017.NEF 
Exif.Image.Make                              Ascii      18  NIKON CORPORATION
Exif.Nikon3.LensType                         Byte        1  D G VR
Exif.Nikon3.Lens                             Rational    4  18-55mm F3.5-5.6
Exif.Nikon3.LensFStops                       Undefined   4  5.33333
Exif.NikonLd3.LensIDNumber                   Byte        1  Nikon AF-P DX Nikkor 18-55mm f/3.5-5.6G VR
Exif.NikonLd3.LensFStops                     Byte        1  F5.3
525 rmills@rmillsm1:~/Downloads $ exiv2 -pa -g lens/i -g 'Make ' DSC_2080.dng 
Error: Directory Nikon1 with 25665 entries considered invalid; not read.
Exif.Photo.LensSpecification                 Rational    4  180/10 550/10 35/10 56/10
Exif.Photo.LensModel                         Ascii      23  18.0-55.0 mm f/3.5-5.6
Exif.Image.LensInfo                          Rational    4  180/10 550/10 35/10 56/10
Xmp.aux.LensInfo                             XmpText    25  180/10 550/10 35/10 56/10
Xmp.aux.Lens                                 XmpText    22  18.0-55.0 mm f/3.5-5.6
Xmp.aux.LensID                               XmpText     3  160
526 rmills@rmillsm1:~/Downloads $ 
```

Two observations:

1.  Lens Identification

- The .NEF Lens is recognised as 'Nikon AF-P DX Nikkor 18-55mm f/3.5-5.6G VR' by Exif.NikonLd3.LensIDNumber
- The .dng Lens is recognised as '18.0-55.0 mm f/3.5-5.6' by Exif.Photo.LensModel

2. Major difference between .NEF and .dng
- I don't recall anybody ever reporting a lens identification issue with a DNG file and I'm surprised that  Exif.NikonLd3.LensIDNumber isn't in the your DNG.
- I'm surprised that the DNG files has the ascii string for Exif.Photo.LensModel.  That's not in the .NEF.  Adobe cooked that up from thin air.

3. Warning message 'Error: Directory Nikon1 with 25665 entries considered invalid; not read.' from DNG

- I could investigate and get to the bottom of that.  However, I think that's a red herring as you are concerned about the lens identification.  

Three questions:

1.  @dfontenot Which lens is being used?
2. @kmilos Which keys does **darktable** use to drive the lens correction/lens fun magic? 
3. @kmilos Is there a way in **darktable** to say _"ignore the metadata and use lens='abc' for lens correction"_ ?

**Comment by dfontenot** [comment]
@clanmills the lens is a Nikon AF-P DX NIKKOR 18-55mm f/3.5-5.6G VR Lens

**Comment by clanmills** [comment]
We're making steady progress.

It's possible to edit Exif.Photo.LensModel to be "Nikon AF-P DX NIKKOR 18-55mm f/3.5-5.6G VR" or _as labelled in the .NEF_, "Nikon AF-P DX Nikkor 18-55mm f/3.5-5.6G VR".  You can edit with exiv2 and Milo&scaron; (@kmilos) can advise if that is possible in **darktable**.  With the metadata edited in the DNG, let's see if **darktable** does the correct lens correction.

@dfontenot Two more questions:

1. Can you confirm that your objective is to get **darktable** to do the lens correction?  So the _**error/warning**_ from the DNG is a side show.  It could of course be a symptom of the issue as we're still gathering evidence.  However the objective of this investigation is to get **darkable** to perform the lens correction.  Is that correct?

2. Does _**darktable**_ perform the correct lens correction on the .NEF?

I will investigate the mysterious _**error/warning**_ from the DNG today and report my findings.

**Comment by clanmills** [comment]
I've re-read your original bug report.  My understanding is correct, the objective of this investigation is to get lens correction to work in **darktable**.

Progress:

1. I understand the source of this issue.
2. I have a work-around for you!
3. A few more comments.

**1. The source of this issue**

I've installed **darktable** and edited DSC_2080.dng with the command:

```bash
586 rmills@rmillsm1:~/Downloads $ exiv2 -M'set Exif.Photo.LensModel Nikon AF-P DX Nikkor 18-55mm f/3.5-5.6G VR' DSC_2080.dng
Error: Directory Nikon1 with 25665 entries considered invalid; not read.
Error: Directory Nikon1 with 25665 entries considered invalid; not read.
587 rmills@rmillsm1:~/Downloads $ exiv2 -pa -g lens/i DSC_2080.dng
Error: Directory Nikon1 with 25665 entries considered invalid; not read.
Exif.Photo.LensSpecification                 Rational    4  180/10 550/10 35/10 56/10
Exif.Photo.LensModel                         Ascii      43  Nikon AF-P DX Nikkor 18-55mm f/3.5-5.6G VR
Exif.Image.LensInfo                          Rational    4  180/10 550/10 35/10 56/10
Xmp.aux.LensInfo                             XmpText    25  180/10 550/10 35/10 56/10
Xmp.aux.Lens                                 XmpText    22  18.0-55.0 mm f/3.5-5.6
Xmp.aux.LensID                               XmpText     3  160
588 rmills@rmillsm1:~/Downloads $
```
Here's a screen shot in **darktable**.  Whatever is in Exif.Photo.LensModel is displayed in the **darktable** UI.  No matter what I put into Exif.Photo.LensModel, **darktable** stubbornly displays the message "camera/model not found".  Maybe I need to install LensFun or something as I got the same message from 20210827_0017.NEF which you said was OK for you.

<img width="515" alt="screenshot_59" src="https://user-images.githubusercontent.com/529982/131244232-ad8baead-da66-41a1-9eb4-34aa6cdc2a54.png">

_**Irrelevant grumble:**_ **darktable** also seems to re-open files without re-reading the metadata, so when I edit Exif.Photo.LensModel, I have to copy and modify the DNG and ask **darktable** to open the new copy.  Some cacheing or user-friendly behaviour is getting in my way.  Let's not discuss that.
 
So the issue is that the DNG has set Exif.Photo.LensModel to a value not recognised by darktable/LensFun.

**2. The work-around**

After your run Adobe DNG Convertor, you should run `$ exiv2 -pa -g exiv2 -pa -g lensidnumber/i foo.NEF" to get the value of Exif.NikonLd3.LensIDNumber, and then `$ exiv2 -M'set Exif.Photo.LensModel lens-model-name' foo.DNG.  It should be easy to write a little bash script to perform this chore.

I believe the issue here is caused by DNG Convertor incorrectly setting Exif.Photo.LensModel and recommend that you discuss it with Adobe.  Another possibility is to ask Lens fun to recognise the lens with the string "18-55mm f/3.5-5.6 G VR AF-P".  Another possibility is for **darktable** to "tweak" the string from the metadata to suit LensFun.

**3. A few more comments:**

1. I used the latest 2021 Adobe DNG Convertor (13.4.0.872) and behaved in the same way as your experience.
2. I reproduced your experience with exiftool correctly identifying the lens as "Lens Spec" I'm sure that's a home-made generated tag in exiftool and not in the file.
```bash
614 rmills@rmillsm1:~/Downloads $ exiftool DSC_2080.dng  | grep -i lens
Lens Info                       : 18-55mm f/3.5-5.6
Lens Model                      : 18.0-55.0 mm f/3.5-5.6
DNG Lens Info                   : 18-55mm f/3.5-5.6
Lens Type                       : G VR AF-P
Lens                            : 18-55mm f/3.5-5.6
Lens Data Version               : 0204
Lens ID Number                  : 160
Lens F Stops                    : 5.33
Lens Spec                       : 18-55mm f/3.5-5.6 G VR AF-P
615 rmills@rmillsm1:~/Downloads $ exiftool 20210827_0017.NEF  | grep -i lens
Lens Type                       : G VR AF-P
Lens                            : 18-55mm f/3.5-5.6
Lens Data Version               : 0204
Lens ID Number                  : 160
Lens F Stops                    : 5.33
Lens ID                         : AF-P DX Nikkor 18-55mm f/3.5-5.6G
Lens Spec                       : 18-55mm f/3.5-5.6 G VR AF-P
616 rmills@rmillsm1:~/Downloads $ 
```

3.  I did investigate the _**error/warning**_ being emitted by the DNG.  I don't know exactly what's at the bottom of that.  tvisitor reads that file without issue.  As this _**error/warning**_ is not really the subject of this investigation, I'm not going to pursue this.  It's Sunday, the sun is shining.  I'm going to out to run.

4. Lens Recognition is guess work.  Exif only recently added Exif.Photo.LensModel to their specification (I believe v2.32 in 2019).  Prior to that, guessing the lens is difficult.  The information is stored in the Manufacturer's MakerNote using different representations for every manufacturer and even different models from the same Manufacturer.

I think we've identified the reason for this issue and I look forward to your comments.  I wish you success is using my suggested work-around, or cooperation from Adobe, or darktable, or LensFun to accept the value of the tag Exif.Photo.LensModel.

**Comment by kmilos** [comment]
I could look into dt+lensfun side of things, but will be a while until I get to it...

As far as I remember, both lens make and model need to match the entry in the lensfun database (XML that can be easily checked).

**Comment by clanmills** [comment]
Milo&scaron; @kmilos 

I think it might be good for **darktable** to use the sound-ex matching algorithm.  Exiv2 gets more issues concerning lens recognition that everything else combined.  The lens isn't in the metadata and people demand that Exiv2 **exactly** matches what LensFun needs.  Darktable, or LensFun have to be more tolerant.

If @dfontenot gets the work-around to work, I think this matter can be closed because exiv2 is reporting the correct metadata.  I see no case for Exiv2 to answer.

By the way, I haven't investigate the _**error/warning**_ with the debugger.  The message is coming from the TiffVisitor code and I'm very confident that the warning is valid.  If I spend time exploring that, it would have to be reported to Adobe for resolution.  Again, I believe that there is no case for Exiv2 to answer.

I hope you're well.  I'm enjoying retirement.  I hope you _(and the rest of Team Exiv2)_ don't mind me looking into some of those interesting puzzles.  I will never debug and write code for Exiv2.  I'm preparing for an exam with the Euphonium in November and re-engineering clanmills.com.  Life is good.

![robin_cartoon](https://user-images.githubusercontent.com/529982/131250438-022bce4a-081e-4647-ae9d-0da9726f8fde.png)

**Comment by dfontenot** [comment]
@clanmills yes, the two commands you gave me for a workaround worked. I think this can be closed. Thanks for taking a look.

**Comment by kmilos** [comment]
Glad you're enjoying your retirement Robin! You could've upped the filter on that image for even more obvious cartoon effect ;)

I'm afraid we still have work to do relating to this issue (or open a new more general one): there should be no reason exiv2 shouldn't be able to get to the original Nikon makernotes that is now embedded in the converted DNG (with Adobe's wrapper). 

Here's the snippet of the output of `exiftool -v3` on NEF (exiv2 also reads the makernotes stored in the usual Exif 0x927c):

```
  | | 14) MakerNoteNikon (SubDirectory) -->
  | |     - Tag 0x927c (161304 bytes, undef[161304]):
  | |         3494: 4e 69 6b 6f 6e 00 02 11 00 00 49 49 2a 00 08 00 [Nikon.....II*...]
  | |         34a4: 00 00 42 00 01 00 07 00 04 00 00 00 30 32 31 31 [..B.........0211]
  | |         34b4: 04 00 02 00 08 00 00 00 26 03 00 00 05 00 02 00 [........&.......]
  | |         34c4: 0d 00 00 00 2e 03 00 00 07 00 02 00 07 00 00 00 [................]
  | |         34d4: 3e 03 00 00 08 00 02 00 0d 00 00 00 46 03 00 00 [>...........F...]
  | |         [snip 161224 bytes]
  | | + [MakerNotes directory with 66 entries]
  | | | 0)  MakerNoteVersion = 0211
  | | |     - Tag 0x0001 (4 bytes, undef[4]):
  | | |         34b0: 30 32 31 31                                     [0211]
```

And here's the structure of the Adobe converted and wrapped makernotes in DNG (exiv2 fails):

```
  | 37) DNGAdobeData (SubDirectory) -->
  |     - Tag 0xc634 (161324 bytes, int8u[161324] read as undef[161324]):
  |         1d2e: 41 64 6f 62 65 00 4d 61 6b 4e 00 02 76 1e 49 49 [Adobe.MakN..v.II]
  |         1d3e: 00 00 34 94 4e 69 6b 6f 6e 00 02 11 00 00 49 49 [..4.Nikon.....II]
  |         1d4e: 2a 00 08 00 00 00 42 00 01 00 07 00 04 00 00 00 [*.....B.........]
  |         1d5e: 30 32 31 31 04 00 02 00 08 00 00 00 26 03 00 00 [0211........&...]
  |         1d6e: 05 00 02 00 0d 00 00 00 2e 03 00 00 07 00 02 00 [................]
  |         [snip 161244 bytes]
  | + [DNGAdobeData directory, 161324 bytes]
  | | MakN = II4.Nikon..II*.B...0211...&.........>....F....V........j..............ze..[snip]
  | | - Tag 'MakN' (161310 bytes):
  | |     1d3c: 49 49 00 00 34 94 4e 69 6b 6f 6e 00 02 11 00 00 [II..4.Nikon.....]
  | |     1d4c: 49 49 2a 00 08 00 00 00 42 00 01 00 07 00 04 00 [II*.....B.......]
  | |     1d5c: 00 00 30 32 31 31 04 00 02 00 08 00 00 00 26 03 [..0211........&.]
  | |     1d6c: 00 00 05 00 02 00 0d 00 00 00 2e 03 00 00 07 00 [................]
  | |     1d7c: 02 00 07 00 00 00 3e 03 00 00 08 00 02 00 0d 00 [......>.........]
  | |     [snip 161230 bytes]
  | | + [AdobeMakN directory, 161310 bytes]
  | | | + [MakerNotes directory with 66 entries]
  | | | | 0)  MakerNoteVersion = 0211
  | | | |     - Tag 0x0001 (4 bytes, undef[4]):
  | | | |         1d5e: 30 32 31 31                                     [0211]
```

It seems it's all preserved there if the first 20 bytes `Adobe.MakN..v.II..4.` are skipped...

**Comment by clanmills** [comment]
I didn't crank up the filter, because it would have made it impossible to recognise the Exiv2 log on my wall.

What I've said about Adobe creating Exif.Photo.LensModel is correct and I'm sure the **warning/error** from the DNG is valid.

I don't know what **darktable** (LensFun) actually wants.  Exif.Photo.LensModel ?

The original maker note in the NEF is copied to the DNG as Exif.Image.DNGPrivateData.  Exiv2 could parse that and find Exif.Nikon3Ld.LensIDNumber.  I think Exiv2 does not know that Exif.Image.DNGPrivateData is a MakerNote (which is an IFD with a Nikon header).

I haven't deleted the user's files.  Let me know if you need me to dig further.  Please be gentle on me, I don't want to get dragged any deeper into what is a guessing game.

```bash
746 rmills@rmillsm1:~/clanmills $ exiv2 -g private/i ~/Downloads/DSC_2080.dng | less
747 rmills@rmillsm1:~/clanmills $ ls -l ~/Downloads/*.NEF ~/Downloads/*.dng
-rw-r--r--@ 1 rmills  staff  24683213 28 Aug 23:48 /Users/rmills/Downloads/20210827_0017.NEF
-rw-r--r--@ 1 rmills  staff  21908478 29 Aug 10:00 /Users/rmills/Downloads/DSC_2080.dng
748 rmills@rmillsm1:~/clanmills $ 
```

**Comment by clanmills** [comment]
Exif.Image.DNGPrivateData is tag 0xc634.
```
749 rmills@rmillsm1:~/clanmills $ taglist ALL | grep Exif.Image.DNGPrivateData
Image.DNGPrivateData,50740,0xc634,Image,Exif.Image.DNGPrivateData,Byte,"Provides a way for camera manufacturers to store private data in the DNG file for use by their own raw converters, and to have that data preserved by programs that edit DNG files."
```
ExifTool knows to parse that:
```
37) DNGAdobeData (SubDirectory) -->
  |     - Tag 0xc634 (161324 bytes, int8u[161324] read as undef[161324]):
```

To parse that, I think you have to add that to the state/change table `groupInfo[]` in src/tags_int.cpp and tell him to parse with Nikon3MakerNote.

If you're willing to undertake that work, can you consider my comments about SubImageN and IFD2, IFD3 etc.  That architecture is suspect.  The groupId should not be restricted to 10 SubImages, or 4 IFDs.  I'm not sure there is such a thing as a SubImage.  I think really Image[n].  A tiff file can contain a sequence of Images.  Usually 1.

These are challenging code changes.  You'll need steady hands and lots of coffee.  I know your skills are up to the task if you have the time to work on this.

**Comment by kmilos** [comment]
> What I've said about Adobe creating Exif.Photo.LensModel is correct

Yep, but sometimes it works out and gives the same result as the makernote (i.e. Adobe's lens database sometimes overlaps w/ exiv2's...), see e.g. https://github.com/darktable-org/darktable/issues/9883#issuecomment-909127389

> I don't know what darktable (LensFun) actually wants. Exif.Photo.LensModel ?

It tries all the known makernote locations, and then `Exif.Photo.LensModel` if all else fails. So when Adobe messes that record up, we have a problem...

Here's the lensfun entry for this lens:

```xml
<lens>
        <maker>Nikon</maker>
        <model>Nikon AF-P DX Nikkor 18-55mm f/3.5-5.6G VR</model>
        ...
```

which [matches the exiv2 database](https://github.com/Exiv2/exiv2/blob/23dbf4f51a6a08f2ad7a76ef4af99c10d8a84f3c/src/nikonmn_int.cpp#L2137) but only when translated by exiv2 from the makernote, not when translated by Adobe into `Exif.Photo.LensModel` in this case.

**Comment by kmilos** [comment]
Yep, interesting stuff to work on, but time is an issue... :(

**Comment by clanmills** [comment]
Well, we know what to do.  You should ensure that Exif.Photo.DNGPrivateData is parsed and you do that in either groupId in src/tags_int.cpp or TiffCreator::tiffTreeStruct_ in src/tiffimage_int.cpp

SubImageN issue is not involved in this issue which is about lens recognition issue.

However, if you're going to perform brain surgery on the TiffVisitor to respect Exif.Image.DNGPrivateData, please conside consider fixing SubImageN at the same time.

**Comment by clanmills** [comment]
Time is always an issue.  Regrettably, some believe I have an unlimited amount and they are happy to waste my time investigating legal issues for which they provide no evidence.  I want to use my time to pass my Euphonium exam in November.

**Comment by kmilos** [comment]
Btw, [found the source of Adobe translation issue](https://github.com/darktable-org/darktable/issues/9883#issuecomment-910383011).

**Comment by clanmills** [comment]
Well done.  Great work on [darktable/.NEF converted with Adobe DNG Converter can't find lens data](https://github.com/darktable-org/darktable/issues/9883#issuecomment-910383011)

Adobe correctly set Exif.Photo.LensModel to type `ascii` (tiff type 2), so the _**translator**_ (prettyPrinter)_ takes no action.  I believe you added that Exif.Photo.LensModel as part of the Exif 2.32 for v0.27.4.  I'm surprised that the comment isn't in src/tags.cpp
```cpp
        TagInfo(0xa434, "LensModel", N_("Lens Model"),
                N_("This tag records the lens's model name and model number as an "
                "ASCII string."),
                exifId, otherTags, asciiString, 0, printValue),
```

As we move into the future, I hope every camera will support Exif.Photo.LensModel and the days of playing "guess that lens" will be over.  Exif.Photo.LensModel should, at that time, be the preferred Lens Identification and the mysterious, undocumented makernote tricks will be a thing of the past.

I'm always happy to help you and everybody in Exiv2.  I don't want sucked into work full time work on Exiv2 again.  And I want to pass my Euphonium Exam in November (and November 2022).

**Comment by kmilos** [comment]
> Adobe correctly set Exif.Photo.LensModel to type `ascii` (tiff type 2), so the _**translator**_ (prettyPrinter)_ takes no action.

Our translator takes no action, right, but in NEF->DNG conversion Adobe did their own translation from Nikon MakerNote's numerical "160" in `Exif.NikonLd3.LensIDNumber` into ASCII "18.0-55.0 mm f/3.5-5.6" for `Exif.Photo.LensModel` using their own database. "Correct" translation is very relative here unfortunately...

**Comment by clanmills** [comment]
@kmilos Milo&scaron;  It's not "translated".  Call it what is. It's a guess.  I agree it's a good guess, however it's non-deterministic and the source of lots of consequential issues.

I'm sure Adobe will regret adding a "translator" to their code.

Lens identification is a time swamp.  Even discovering the LensIDNumber is toublesome.  Nikon have different makernote layouts (that's what Nikon1, Nikon2, Nikon3 are about).  Every manufacturer has different makernote designs.  I believe Nikon even encrypt part of their makernote.  Sony also encrypt something.  I've documented all of this in my book.

**Comment by kmilos** [comment]
Found this old nugget as well: https://dev.exiv2.org/issues/574

**Comment by clanmills** [comment]
Great find.  Under NO circumstances should we ever modify the data in Exif.Image.DNGPrivateData. The reason it's there is to preserve and manufacturer's makernote and preserve every offset, even if it violates the Exif standard.  It's the guarantee to recover the manufacturer's data.

I had totally forgotten about Exif.Image.DNGPrivateData.  I was talking to Phil Harvey _(our exiftool friend)_ last year and said the Adobe should never have removed the makernote.  He told me about Exif.Image.DNGPrivateData.  tvisitor.cpp understands that tag and it's discussed in my book.
