### ISSUE TITLE
Lens type missing: Olympus OM-System F.Zuiko Auto-S 1:1.8 f=50mm

### ISSUE THREAD

**Issue by parasange** [Exiv2/exiv2#1904]
The above Olympus lens is not recognized by exiv2 (0.27.4 - Arch Linux):
`exiv2 -pa some.RAW | grep -i LensType` does not return anything.

`exiv2 -pa some.RAW` gives
> Exif.Photo.LensSpecification                 Rational    4  5500/100 5500/100 0/0 0/0
> Exif.Photo.LensMake                          Ascii      13  
> Exif.Photo.LensModel                         Ascii      64  
> Exif.Photo.LensSerialNumber                  Ascii      11

**Comment by postscript-dev** [comment]
Is it possible that the Olympus tags have been deleted? You can check that other Olympus tags are in the file using:
```
$ exiv2 --grep Olympus some.RAW
```
Something else to consider is that, if the image was edited then saved, this could have effected which metadata was written to the file.

If the above is of no help, then if you could post an unedited test image, this would move the problem forward.

**Comment by parasange** [comment]
There weren't any Olympus tags in the un-edited image in the first place. I am pretty sure now that my camera (Fujifilm X-T3) does not handle metadata for manual lenses correctly. Thanks anyway for your help!

**Comment by clanmills** [comment]
You are correct.  There is no lens meta-data for a manual lens.  If the camera doesn't know anything about the lens, it cannot store metadata! 

Have you tried using exiftool on your images?  If exiftool cannot identify your lens, it's unlikely that Exiv2 will either.

I'm not optimistic that anything can be done. Team Exiv2 can't investigate and/or offer advice about your files until you supply a sample/test image.

**Comment by parasange** [comment]
Yep, you are right :-) But usually there's a way to manually edit metadata for the specific lens thorugh the camera itself. Unfortunately this is not sufficiently possible with my camera. That's why I'll use exiftool now.

**Comment by clanmills** [comment]
The _**configuration file**_ `~/.exiv2` _(documented in the exiv2 man page)_ is provided to overwrite the lens recognition code in Exiv2.  Olympus probably record a LensID value such as `-1` for a manual lens.  You can use that in ~/.exiv2 to recognise your lens. 

I will look further into your situation if you provide a test image.  Can you take a photo with the lens cap on and post it here.  There's probably a camera setting to avoid huge raw files.

**Comment by postscript-dev** [comment]
I wrongly assumed that the camera was an Olympus, but it turns out to be a Fujifilm X-T3.

I looked at both Exiv2 and ExifTool and neither has any FujiFilm lens ID tags or lenses listed. This means that, at this time, neither program can output the lens names. The exiv2 configuration file doesn't work with FujiFilm cameras, as there aren't any tags to update. Sorry that this is not more help.
