### ISSUE TITLE
Exiv2 v0.27.5 RC3

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1935]
I've updated the v0.27.5 release notes https://github.com/Exiv2/exiv2/issues/1018#issuecomment-895425552 with an additional prolog.  The release note tables for RC1/RC2/RC3.  will be merged for GM.

**Exiv2 v0.27.5 RC3 2021-09-30**

Changes since RC2.

| Group    | PR     | Topic                                                       | Issue  | 
|:-        |:-      |:-                                                           |:-      |
| Withdrawn| #1858  | Fix compiler warning on Apple/M1/Clang                      | https://github.com/Exiv2/exiv2/pull/1915#pullrequestreview-758174005  |
| Withdrawn |  | Reading HEIC from iPhone images |  #1928 |
| Build    | TBD    | Fix linking libiconv on macOS with M1                       | #1903  |
| Security | TBD    | Fix out of range access                                     | #1918  |

We intend to release Exiv2 v0.27.5 RC3 and v0.27.5 on 2021-10-22.

---------------------------------

Please let me know of other changes.  Here are PRs which have been closed on 'main'.  I believe only #1918 and #1915 will be in RC3.   I'm sure @kevinbackhouse will know about other issues.

fix out of range access, minor performance improvement  bug
#1918 by rabauke was merged 5 days ago

Pass -fstack-protector-strong to linker  build  CMake
#1915 by evanmiller was merged 9 days ago

Fix quadratic loops in pentaxmn_int.cpp  bug  OSS-Fuzz
#1910 by kevinbackhouse was merged 10 days ago

Comment out bogus code in XMPUtils.cpp  bug  OSS-Fuzz
#1902 by kevinbackhouse was merged 10 days ago

Lock conan version on Windows.  forward-to-main
#1897 by kevinbackhouse was merged 20 days ago

**Comment by kevinbackhouse** [comment]
@clanmills: I would like to backport #1902 and #1910. And @kmilos has suggested that we backport #1932.

I have pull requests open for my backports: #1923, #1924, #1925. We didn't open one for #1932 yet.

**Comment by clanmills** [comment]
@kevinbackhouse @John55h @kmilos @alexvanderberkel   Has #1932 been back-ported to 0.27-maintenance?

The MacMini build-server has performed a successful build/test on the release platforms: Ubuntu, macOS, msvc2019, MinGW-msys2, Cygwin64.

Tomorrow I'll bump the revision number, update the web-site and release-notes.  On-track for RC3 on 2021-09-30.

**Comment by kevinbackhouse** [comment]
Yes: #1936 is the backport of #1932.

All the backports have been merged. Thanks everyone!

**Comment by clanmills** [comment]
Thank You, Everybody.  All going well, exiv2 v0.27.5 RC3 will be released tomorrow.

GM schedule remains: 2021-10-22 (to fit my vacation).

**Comment by clanmills** [comment]
Latest (and I hope final version of the release notes).

The CI has gone crazy on PR #1937.  It looks as if the SSL Certificate on the conan recipe server is out of date.   This effectively destroys the CI until fixed.  As I use conan to build with Visual Studio, this could also disable the MacMini until fixed.

**Exiv2 v0.27.5 RC3 2021-09-30**

Changes since RC2.

| Group       | PR     | Topic                                                       | Issue  | 
|:-           |:-      |:-                                                           |:-      |
| Build       | #1938  | Exiv2 v0.27.5 RC3                                           | #1935  |
| Lens        | #1936  | Canon EF 80-200mm f/4.5-5.6 II                              | #1906  |
| Bug         | #1925  | Fix out of range access in src/tags_int.cpp                 | #1918  |
| Bug         | #1924  | Fix quadratic loops in pentaxmn_int.cpp                     | #1910  |
| Bug         | #1923  | Remove bogus code in XMPUtils.cpp                           | #1902  |
| Build       | #1937  | Fix compiler warning on Apple/M1/Clang                      | https://github.com/Exiv2/exiv2/pull/1915#pullrequestreview-758174005  |
| Build       | #1937  | Fix linking libiconv on macOS with M1  Requires CMake 3.14+ | #1903  |
| Withdrawn   |        | Reading HEIC from iPhone images                             | #1928  |

We intend to release Exiv2 v0.27.5 on 2021-10-22.

**Comment by clanmills** [comment]
I submitted a draft PR for v0.27.3 RC3  #1938.  I've done a build using Visual Studio and that worked with issue on the Mac Mini.  The problem on the CI is impacting both #1937 and #1938.  I used to have permissions to "merge anyway".  I think we'll have to wait for the CI to be repaired.  I've tried googling this situation without learning anything.

**Comment by kevinbackhouse** [comment]
@clanmills: I think the CI failures are due to a Conan outage, as explained here: https://github.com/conan-io/conan/issues/9695
The really annoying thing is that I think we have to add [this command](https://github.com/conan-io/conan/issues/9695#issuecomment-931406912) to all of our CI scripts to fix it:
```bash
conan config install https://github.com/conan-io/conanclientcert.git
```

**Comment by clanmills** [comment]
@kevinbackhouse Thanks for this discovery.  I'm going to withdraw #1937 because it needs cmake 3.14 (for add_link_options) and one of the Linux CIs has 3.7.  It's odd that we use add_link_options on main and the CI is happy.

I have #1938 as a draft at the moment.  When I mark it ready for review, please approve it and RC3 will be done.

**Comment by clanmills** [comment]
I've built and pushed the bundles to https://pre-release.exiv2.org

I'll tag the release and publish it on GitHub later today and then close this issue.

**Comment by clanmills** [comment]
@kevinbackhouse 

I can't create a tag on GitHub. I updated .git/config to use the new remote url:  `url = https://github.com/Exiv2/exiv2.git`


From the command-line:

```
608 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance $ git push origin v0.27.5-RC3
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 164 bytes | 164.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To https://github.com/Exiv2/exiv2.git
 ! [remote rejected]   v0.27.5-RC3 -> v0.27.5-RC3 (refusing to allow an OAuth App to create or update workflow `.github/workflows/nightly_Linux_distributions.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/Exiv2/exiv2.git'
609 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance $ 
```

I did this for v0.27.5 RC2 a few weeks ago without any trouble.  Something has changed.

**Comment by kevinbackhouse** [comment]
@clanmills: I'll look at this now.

**Comment by kevinbackhouse** [comment]
@clanmills: I think it's probably because you clone from the https url, not the ssh url. I'll try creating the tag now myself.

**Comment by kmilos** [comment]
I remember there was some mail from GitHub about a month ago about some authentication changes?

**Comment by kevinbackhouse** [comment]
I think it was the https/ssh url thing. I created a tag: https://github.com/Exiv2/exiv2/tree/v0.27.5-RC3

**Comment by clanmills** [comment]
Well done, guys.

```bash
614 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance $ git ls-remote --tags origin | grep RC3
38e2fb7ca71903e801e0bd1a043633847d385c1a	refs/tags/0.27-RC3
875870a182d59e0718e3efe14e6ef94ff80c5c7f	refs/tags/v0.27.2-RC3
fd0cab155b9ab8f76a675dbd94e246a455689ab2	refs/tags/v0.27.2-RC3^{}
ed2023eabb6ab20a18e7100a387fb1a9d7cd76d8	refs/tags/v0.27.4-RC3
c4722df582015373b208aa0280c58bc01cb3ec40	refs/tags/v0.27.4-RC3^{}
7eeed00a5c690d73b2b8ba018df3c6daa04a3be1	refs/tags/v0.27.5-RC3
d3f7e92240a5e8bb827846c6094f46f9c7b53585	refs/tags/v0.27.5-RC3^{}
615 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance $ 
```

I'll take a fresh clone of the repos and hope to keep out of trouble.  I've published the release.

Good Work, Everybody.  Especially @kevinbackhouse.  You're a wizard.  Thank You.

**Comment by clanmills** [comment]
@kevinbackhouse I've been able to clone using ssh.

If you know the GitHub Engineer who wrote the ssh documentation, please tell them they made a great job.  There's no way I could have achieved that without such good documentation.
