### ISSUE TITLE
[BUG][BISECTED] exiv2 rename -T file  rename the file instead of just touching it

### ISSUE THREAD

**Issue by rgenoud** [Exiv2/exiv2#1951]
Since commit 74bc0e05359f ("Changes for cross-platform getopt")
exiv2 rename -T file.jpeg change the file name instead of only setting the file timestamp according to Exif create timestamp.

script used for git bisect run : 
NB: the script should be in the parent directory of exiv2 along with a test.jpeg file
`
#!/bin/sh
set -e

git clean -fdx
mkdir -p build
cd build
cmake -j15 .. -DCMAKE_BUILD_TYPE=Release
cmake --build . -j15
cp ../../test.jpeg .
./bin/exiv2 rename -T test.jpeg
`
The platform amd64/debian 11 

[bisect.log](https://github.com/Exiv2/exiv2/files/7310526/bisect.log)

**Comment by postscript-dev** [comment]
The exiv2 usage in Exiv2 0.27.4 is:
```
$ exiv2
exiv2: An action must be specified
exiv2: At least one file is required
Usage: exiv2 [ options ] [ action ] file ...

Manipulate the Exif metadata of images.
```
In this version, the 'action' must be used *immediately before* the 'file' and not any earlier. For example, placing the action earlier in the command:
```
$ curl --silent -O https://clanmills.com/Stonehenge.jpg
$ exiv2 --verbose rename -T Stonehenge.jpg
File 1/2: -T
-T: Failed to open the file
File 2/2: Stonehenge.jpg
Renaming file to ./20150716_153854.jpg
```
and immediately before the file:
```
$ curl --silent -O https://clanmills.com/Stonehenge.jpg
$ exiv2 --verbose -T rename Stonehenge.jpg
File 1/1: Stonehenge.jpg
Updating timestamp to 2015:07:16 15:38:54
```
The second example works in the way that you expect.

I didn't work on Exiv2 back then and don't have time to investigate if this has changed behaviour. I hope that the example is useful for you, as it provides a way to work around the problem.

**Comment by rgenoud** [comment]
Ok, I understand.
Before commit 74bc0e0 ("Changes for cross-platform getopt"), the options could be anywhere in the command.
And after this commit, the options *must* be before the action parameter, otherwise they will be treated as a filename.
I'll correct my scripts to reflect this change.
Thanks for the heads-up.
