### ISSUE TITLE
-PV option doesn't print the key

### ISSUE THREAD

**Issue by facundofc** [Exiv2/exiv2#1969]
Using an image from the test suite, you get:

```
$ exiv2 -PV -K Exif.Image.ImageDescription test/data/smiley1.jpg
set  Well it is a smiley that happens to be green
```

while according to the man page, `-PV` is supposed to:

```
V : plain data value AND the word 'set ' (for use with exiv2 -m-)
```

But the above output is unsuitable for the `-m` flag since it's missing the key.

**Comment by postscript-dev** [comment]
Thanks for contributing this.

While working on the manpage I found lots of small problems with the exiv2 sample including this one. There are several still to be addressed. Would you be interested in fixing a couple related to your issue?

When modifying, if using a non-standard XMP namespace, it needs to be registered in the [same line as the modification](https://github.com/Exiv2/exiv2/blob/main/exiv2.md#registering-an-xmp-namespace). When using `--modify cmdfile`, all the entries in the file are treated as though they are `--Modify cmd` commands on a single line.
1. Problem with `--Print Vk`
The command cannot be used to initialise all the data in a file, as it does not include the registering of non-standard namesapces. For example,
```
$ curl --silent -O https://clanmills.com/Stonehenge.jpg

# Copy the image and delete the XMP metadata
$ cp Stonehenge.jpg Stonehenge-test.jpg
$ exiv2 --verbose --delete x Stonehenge-test.jpg
File 1/1: Stonehenge-test.jpg
Erasing XMP data from the file

# Output the XMP 'set' data to a file
$ exiv2 --Print Vk --grep Xmp Stonehenge.jpg > Stonehenge-output.txt

# Add the saved 'set' data back into the file
$ exiv2 --verbose --modify Stonehenge-output.txt Stonehenge-test.jpg
Stonehenge-output.txt, line 3: Invalid key `Xmp.cm2e.Father'
exiv2.exe: Error parsing -m option arguments
Usage: exiv2.exe [ option [ arg ] ]+ [ action ] file ...

Image metadata manipulation tool.
```
The 'Stonehenge-output.txt' file is:
```
set Xmp.xmp.Rating                                0
set Xmp.xmp.ModifyDate                            2015-07-16T20:25:28+01:00
set Xmp.cm2e.Father                               Robin Mills
set Xmp.cm2e.Family                             
set Xmp.dc.description                            lang="x-default" Classic View
set Xmp.dc.Family                                 Robin
```
As the `cm2e` prefix is non-standard, an error is raised. If the line `reg cm2e http://clanmills.com/exiv2/` is added to the 'Stonehenge-output.txt' file before using the `cm2e` group, then the example works.

The usage information appears in the output as the namespace check occurs early before opening the image and executing the modify command.

2. List all the XMP namespaces in a file
Printing the built-in XMP namespaces is simple but listing all the XMP namespaces used by a file involves parsing XML. Both methods are shown [here](https://github.com/Exiv2/exiv2/blob/main/exiv2.md#78-xmp-namespaces). The namespaces in a file could be listed from the print option using the same format as the built-in namespaces.
