### ISSUE TITLE
improvable error message 

### ISSUE THREAD

**Issue by paolobenve** [Exiv2/exiv2#1977]
exiv built without `-DEXIV2_ENABLE_BMFF=1`:

```
$ exiv2 -pp "/home/paolo/image.CR3"
Exiv2 exception in print action for file /home/paolo/image.CR3:
/home/paolo/image.CR3: The file contains data of an unknown image type
```

I think that the error message is correct, but could be better: actually exiv2 cannot find the preview because it hasn't the rights to process CR3 files. A check on CR3 type would permit to add a suggestion that maybe EXIV2_ENABLE_BMFF support isn't enabled.

**Comment by clanmills** [comment]
@paolobenve I'm going to close this.  The changes required to fix this is would require v0.27.5 RC4 and a three week delay.  I'm sure you and the _**darktable**_ folks prefer to have 0.27.5 now with the CR3/preview code.

As you know, Paolo we don't always get what we want.  Team Exiv2 have worked well on your behalf and delivered CR3/preview for you.
