### ISSUE TITLE
exiv2 performance

### ISSUE THREAD

**Issue by MrDkVV** [Exiv2/exiv2#1993]
Hello, 

I've been experience issues removing a large number of tags. 

There are about 1M tags total and trying to remove approximately 90,000. Trying to remove more then about 10,000 causes the application dialog prompts to "confirm" to fail.  Not to mention the list goes off the screen.

Running v7.2.0

1. Please fix the dialog windows when removing large number of tags. 

2. Please consider moving the list of tags to be removed to a scrollable list and the action of editing the images to a sub process with a progress indicator.

Thank you.
Derek

**Comment by kmilos** [comment]
I think there might be some case of mistaken identity here - exiv2 is not a GUI application and current version is 0.27.5

**Comment by MrDkVV** [comment]
Hello @kmilos,  I see what happened. 


I will go back and see if I can get Digikam support to help identify where the latency may exist.


I was on "https://www.digikam.org/support/" and was trying to submit an issue for Digikam that uses Exiv2 for their file tag processing.  It's unclear if this is a "Software / Digikam " or "Exiv2" issue?  
Sorry for the confusion, I didn't realize they pointed their support for Exiv2 issues to here :)

![image](https://user-images.githubusercontent.com/82465898/140536277-10266c32-7ed7-4415-9318-c726b0a1ec15.png)


Thank you.
Derek

**Comment by kmilos** [comment]
> It's unclear if this is a "Software / Digikam " or "Exiv2" issue?

No problem, I figured as much. It would indeed be best if Digikam devs analyzed the issue first.
