### ISSUE TITLE
Build with C++17 possible?

### ISSUE THREAD

**Issue by Simon-12** [Exiv2/exiv2#1997]
Hey, 
i tried to build exiv2 from the last stable main branch ([#1963](https://github.com/Exiv2/exiv2/pull/1963)) with: C++17 MSVC 2019 under Windows 10.
I got no success, so bevor i deep dive to figure out what is going on, is this even possible?
Or i have to take another branch/commit?

Cheers

**Comment by Simon-12** [comment]
Okay the error was slightly different. I just destroyed my PATH variable, now i got a successful build with C++17.
Sorry for spam and @clanmills all the best in your well deserved retirement.

Cheers

**Comment by clanmills** [comment]
Thanks @Simon-12.  I'm happy to retire.  Very pleased that @kmilos @postscript-dev @alexvanderberkel and others are keeping Exiv2 alive.
