### ISSUE TITLE
Xmp file date/time changes overwritten

### ISSUE THREAD

**Issue by jim-easterbrook** [Exiv2/exiv2#1998]
I'm revisiting a bug I raised 4 years ago https://dev.exiv2.org/issues/1313

I start with a simple XMP file with just one item of metadata:
```
<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
   xmp:CreateDate="2021-02-03T12:34:56+02:00"/>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>
```

Reading this file with libexiv2 reports the following data:
```
Exif.Photo.DateTimeDigitized: 2021:02:03 10:34:56
Iptc.Application2.DigitizationDate: 2021-02-03
Iptc.Envelope.CharacterSet: 
Xmp.xmp.CreateDate: 2021-02-03T12:34:56+02:00
```
The Exif and Iptc values are synthesised in `XmpSidecar::readMetadata()` lines 110-111. (This is not the place to discuss if synthesising values is a good idea.) Note that `Iptc.Application2.DigitizationTime` is not synthesised.

If I change the Xmp time:
```
xmpData['Xmp.xmp.CreateDate'] = '2021-02-03T11:00:00+01:00'
```
it gets changed back to its original value by `XmpSidecar::writeMetadata()`. However, if I change the date as well as the time:
```
xmpData['Xmp.xmp.CreateDate'] = '2021-02-02T11:00:00+01:00'
```
then the new value is not modified by `XmpSidecar::writeMetadata()`. Looking at xmpsidecar.cpp I see line 160 detects a new date/time value by comparing the first 10 characters of the string, i.e. the date but not the time!

I don't really understand the intent behind all this. Lines 144-145 appear to copy exif and iptc data to xmp, regardless of what might already be in xmp. Lines 147-150 appear to try and put back the xmp values that have just been over-written, then lines 152-164 appear to try and restore date/time stamps. Would this even be needed if the iptc time values had been synthesised as they have time zone info anyway.

**Comment by jim-easterbrook** [comment]
Aha! Moving lines 147-150 to be after lines 152-164 solves my problem and all the unit tests still pass. I'll submit a PR.

**Comment by clanmills** [comment]
Well done, Jim.  I don't know the rationale for the convertors.  This kind of manipulation should be carried out by applications and should not be in the metadata engine.

**Comment by jim-easterbrook** [comment]
I agree, but I'm happy to live with it now I know it's there. (Using clearExifData() and clearIptcData() immediately after opening an xmp file does the job.)

I think my changes honour the intent of the authors of those bits of xmpsidecar.cpp as it makes the "restore dates if they lost their TZ info" step part of the copying back of Exif & Iptc, all of which are selectively undone by the final "restore tags which were modified by the convertors" step.

**Comment by jim-easterbrook** [comment]
I've submitted a test file now that I've understood the test system a bit.
