### ISSUE TITLE
GwenView gThumb and other crashes with Darktable JPGs

### ISSUE THREAD

**Issue by DL4MW** [Exiv2/exiv2#2011]
##### **Describe the bug**
Since the latest Ubuntu updates some KDE applications which uses libexiv2 crashes when trying to open JPGs which are exported from Darktable. It also seems that older Darktable images will not give that error, so that there must be changes too. the community reported, that older libexiv will solve the problem, but I cannot see that in general.

May be, the reason of this problem is just reported in other issues.

##### **To Reproduce**
Just open a Darktable exported JPG.
The backtrace is the following:

Application: Gwenview (gwenview), signal: Aborted
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f1829806440 (LWP 23826))]

Thread 7 (Thread 0x7f1819ffb700 (LWP 23833)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f1819ffaa10, clockid=<optimized out>, expected=0, futex_word=0x560ec850e6b0) at ../sysdeps/nptl/futex-internal.h:320
#1  __pthread_cond_wait_common (abstime=0x7f1819ffaa10, clockid=<optimized out>, mutex=0x560ec850e660, cond=0x560ec850e688) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=0x560ec850e688, mutex=0x560ec850e660, abstime=0x7f1819ffaa10) at pthread_cond_wait.c:656
#3  0x00007f182f4e0a7c in QWaitCondition::wait(QMutex*, QDeadlineTimer) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f182f4e0bcb in QWaitCondition::wait(QMutex*, unsigned long) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f182f4de171 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f182f4da9d2 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f182d875609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007f182f168293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7f181a7fc700 (LWP 23832)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f18240046c8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f1824004678, cond=0x7f18240046a0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f18240046a0, mutex=0x7f1824004678) at pthread_cond_wait.c:638
#3  0x00007f18209feb1b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007f18209fe71b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007f182d875609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f182f168293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f181affd700 (LWP 23831)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f18240046c8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f1824004678, cond=0x7f18240046a0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f18240046a0, mutex=0x7f1824004678) at pthread_cond_wait.c:638
#3  0x00007f18209feb1b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007f18209fe71b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007f182d875609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f182f168293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f181b7fe700 (LWP 23830)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f18240046c8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f1824004678, cond=0x7f18240046a0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f18240046a0, mutex=0x7f1824004678) at pthread_cond_wait.c:638
#3  0x00007f18209feb1b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007f18209fe71b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007f182d875609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f182f168293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f181bfff700 (LWP 23829)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f18240046c8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f1824004678, cond=0x7f18240046a0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f18240046a0, mutex=0x7f1824004678) at pthread_cond_wait.c:638
#3  0x00007f18209feb1b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007f18209fe71b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007f182d875609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f182f168293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f182380b700 (LWP 23828)):
#0  0x00007f182f15baff in __GI___poll (fds=0x7f181c011b70, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f182d05a36e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f182d05a4a3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f182f6fa583 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f182f6a14db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f182f4d9785 in QThread::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f182eeffefa in ?? () from /lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007f182f4da9d2 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f182d875609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007f182f168293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f1829806440 (LWP 23826)):
[KCrash Handler]
#6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#7  0x00007f182f06b859 in __GI_abort () at abort.c:79
#8  0x00007f182f2d6911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f182f2e238c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007f182f2e23f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007f182f2e26a9 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007f182f2d93ab in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007f182ec9ff49 in ?? () from /lib/x86_64-linux-gnu/libexiv2.so.27
#14 0x00007f182ec4160f in Exiv2::Xmpdatum::write(std::ostream&, Exiv2::ExifData const*) const () from /lib/x86_64-linux-gnu/libexiv2.so.27
#15 0x00007f1831137fd9 in ?? () from /lib/x86_64-linux-gnu/libgwenviewlib.so.5
#16 0x00007f1831133f23 in Gwenview::ImageMetaInfoModel::setExiv2Image(Exiv2::Image const*) () from /lib/x86_64-linux-gnu/libgwenviewlib.so.5
#17 0x00007f18310f0470 in Gwenview::Document::setExiv2Image(std::unique_ptr<Exiv2::Image, std::default_delete<Exiv2::Image> >) () from /lib/x86_64-linux-gnu/libgwenviewlib.so.5
#18 0x00007f18310ef156 in ?? () from /lib/x86_64-linux-gnu/libgwenviewlib.so.5
#19 0x00007f18310fa53c in ?? () from /lib/x86_64-linux-gnu/libgwenviewlib.so.5
#20 0x00007f182f6ce458 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f182f4e4f65 in QFutureWatcherBase::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007f18302e3a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007f18302ed0f0 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007f182f6a293a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007f182f6a55b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007f182f6faf67 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007f182d05a17d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f182d05a400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007f182d05a4a3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007f182f6fa565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007f182f6a14db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007f182f6a9246 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x0000560ec7777aaa in ?? ()
#34 0x00007f182f06d0b3 in __libc_start_main (main=0x560ec7777600, argc=2, argv=0x7ffc04632d18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc04632d08) at ../csu/libc-start.c:308
#35 0x0000560ec777804e in _start ()
[Inferior 1 (process 23826) detached]

##### **Desktop (please complete the following information):**
- OS and version: Ubuntu 20.04.3 LTS 

Images that reproduces this problem:

https://home.schueler.ws/cloud/index.php/s/kDtgBSze3brKWTW

**Comment by kmilos** [comment]
It seems this is a known issue w/ fix already in exiv2 0.27.5 and waiting to be back-ported to Ubuntu packages:

https://github.com/Exiv2/exiv2/pull/1918
