### ISSUE TITLE
Use of Exiv2 library to embed metadata in JPEG file header

### ISSUE THREAD

**Issue by htartisan** [Exiv2/exiv2#2029]
I am trying to use the EXIV2 lib to modify an encoded JPEG image buffer (not a file), to add (embed) application metadata, without decoding/re-encoding the JPEG image.  Is this possible (using this library)?

**Comment by clanmills** [comment]
Yes.  That's possible.  Normally you open images from a file.  If the JPEG is already in memory, you can create a MemIo file and the library can parse and edit the data.

Take a look at the class Exiv2::ImageFactory().  The Exiv2 sample applications usually read images from a path.  However there is an open() method which accepts a memory buffer.

https://exiv2.org/doc/classExiv2_1_1ImageFactory.html
