### ISSUE TITLE
According to release notes of 0.27.5 #1765 was included but it's not

### ISSUE THREAD

**Issue by Wormnest** [Exiv2/exiv2#2044]
##### **Describe the bug**
The release notes of 0.27.5 state that PR #1765 was included in this release, however it was never committed to this branch.

##### **To Reproduce**
1. On Windows install GIMP 2.10.30 which includes exiv2 0.27.5 from MSYS2.
2. Open any TIFF image that includes Exif.Image.PageName, e.g. (sorry, can't add tif directly and even after zipping it, it still doesn't want to add it)
3. Open the metadata viewer and see that instead it still lists Exif.Image.0x011d as tag name (GIMP gets the literal name from exiv2).

##### **Expected behavior**
The metadata viewer should show the tag Exif.Image.PageName.

##### **Desktop (please complete the following information):**
- OS and version: Windows 10 Home, 64-bit  
- Compiler and version: The version used on the GIMP release build.  
- Compilation mode and/or compiler flags: -  

##### **Additional context**
When looking at [https://github.com/Exiv2/exiv2/blob/0.27-maintenance/src/tags_int.cpp#L599](https://github.com/Exiv2/exiv2/blob/0.27-maintenance/src/tags_int.cpp#L599) in the 0.27 maintenance branch I do not see this tag around line 599, while in the main branch I do see it at [line 605](https://github.com/Exiv2/exiv2/blob/main/src/tags_int.cpp#L605).

**Comment by clanmills** [comment]
Clearly an error in the release notes _(my mistake)_.  We are continuing to maintain the 0.27-maintenance branch in case we need to produce a security release.  However feature development is now focused on branch 'main'.

Perhaps we should back port this to 0.27-maintenance.  What do you think.

**Comment by Wormnest** [comment]
This is just a minor visual issue, it personally doesn't bother me much if it wouldn't be back ported. On the other hand, it was announced as being included. As such, it might be better to include it in the next maintenance release if it can be done without too much hassle.

**Comment by clanmills** [comment]
Fix submitted: #2045
