### ISSUE TITLE
Canon RF 70-200mm F2.8 L IS USM named as Canon RF 70-200mm F4 L IS USM

### ISSUE THREAD

**Issue by PeterWem** [Exiv2/exiv2#2056]
##### **Describe the bug**

```
exiv2 -pa --grep lens/i 70-2004.CR3
 
Exif.Photo.LensSpecification                 Rational    4  70/1 200/1 0/1 0/1
Exif.Photo.LensModel                         Ascii      23  RF70-200mm F4 L IS USM
Exif.Photo.LensSerialNumber                  Ascii      11  9613000868
Exif.CanonCs.LensType                        Short       1  Canon RF 70-200mm F4L IS USM
Exif.CanonCs.Lens                            Short       3  70.0 - 200.0 mm
Exif.CanonFi.RFLensType                      SShort      1  (278)
Exif.Canon.LensModel                         Ascii     138  RF70-200mm F4 L IS USM

exiv2 -pa --grep lens/i 70-20028.CR3 
Exif.Photo.LensSpecification                 Rational    4  70/1 200/1 0/1 0/1
Exif.Photo.LensModel                         Ascii      25  RF70-200mm F2.8 L IS USM
Exif.Photo.LensSerialNumber                  Ascii      11  8000000819
Exif.CanonCs.LensType                        Short       1  **Canon RF 70-200mm F4L IS USM**
Exif.CanonCs.Lens                            Short       3  70.0 - 200.0 mm
Exif.CanonFi.RFLensType                      SShort      1  (266)
Exif.Canon.LensModel                         Ascii     138  RF70-200mm F2.8 L IS USM
macgyver@macgyver-700Z3A-700Z4A-700Z5A-700Z5B:~/Hämtningar$ exiv2 --version
```

##### **To Reproduce**
[Steps to reproduce the behavior:
I used samples from Dpreview
https://www.dpreview.com/sample-galleries/8685700048/canon-rf-70-200mm-f2-8l-is-usm/6898420290
https://www.dpreview.com/sample-galleries/7468308170/canon-rf-70-200mm-f4l-is-usm-sample-gallery/2799350001

Exiv2 0.27.5

##### **Expected behavior**
Exif.CanonCs.LensType should be named Canon RF 70-200mm F2.8 L IS USM

##### **Desktop (please complete the following information):**
Ubuntu 20.04

**Comment by clanmills** [comment]
I'm not familiar with DPreview and don't know how to download your test image(s).

The lens is not stored in the metadata and exiv2 has to "guess" the lens from other metadata.  This is frequently discussed.  For example:  #1906

You can fix this locally on your machine using the _**configuration file**_ `~/.exiv2` as described in the exiv2 man page.  If you need assistance to get that to work, please attach the test image and I'll show you how to get the lens correctly identified.

**Comment by PeterWem** [comment]
I don't own the lenses, but have created pull requests for one of them in Lensfun. I already know how to use your fantastic configuration file, but I thought this was something that manually needed to be solved because of the wrong lens. 

Btw, I do have a question for you and .exiv2, but I will ask in #1906, thanks.

**Comment by EC1000** [comment]
I should be corrected by https://github.com/Exiv2/exiv2/pull/1692 :+1: (at least, the Canon RF 50mm F1.8 version is now correctly identified while it was identified as the F1.2 version with exiv2 0.27.5)
