### ISSUE TITLE
CanonRFLensType values are wrong in canonmn_int.cpp

### ISSUE THREAD

**Issue by EC1000** [Exiv2/exiv2#2059]
##### **Describe the bug**
`canonRFLensType` values are wrong in https://github.com/Exiv2/exiv2/blob/main/src/canonmn_int.cpp#L2462-L2482 (`257` for all Canon RF lenses, while it should be a different number for each lens except Canon RF 50mm F1.2L USM). 

##### **Expected behavior**
The correct values are described here: https://exiftool.org/TagNames/Canon.html (search "RFLensType").

**Comment by postscript-dev** [comment]
@EC1000: Unlike ExifTool, Exiv2 usually adds a test image to demonstrate each of the different lenses containing that description. The `Exif.CanonFi.RFLensType` values in your post were added in #1451, but for some reason didn't include test images. @alexvanderberkel where did the lens information come from?

**Comment by alexvanderberkel** [comment]
@postscript-dev  I did notice the issue as well and started to work on correcting the issue ##1628. However, I didn't find the time to complete the pull request with test images etc. so far.

**Comment by postscript-dev** [comment]
@alexvanderberkel: No problem. As you have experience with Canon cameras, are you free to deal with this current issue?

**Comment by alexvanderberkel** [comment]
I would like to finish that pull request. It should fix the issue in version 1.0, though I'm still a bit limited timewise...
