### ISSUE TITLE
bugfixTests failed on Raspbian buster 10.10 (gcc 8.3.0)

### ISSUE THREAD

**Issue by QuietLullaby** [Exiv2/exiv2#2134]
##### **Describe the bug**
I followed the install process described in README and couldn't go through `ctest --verbose` command.
The objective is to install exiv2 on Raspbian Buster 10.10 running a gcc 8.3.0.
Tests failed (see [LastTest.log](https://github.com/Exiv2/exiv2/files/8206706/LastTest.log)):

> 1: FAIL: test_run (github.test_issue_1503.issue_1503_jxl_bmff)
> 1: FAIL: test_run (github.test_pr1475_AVIF.pr_1475_avif_avif)
> 1: FAIL: test_run (github.test_pr1475_AVIF.pr_1475_exif_xmp_avif)
> 1: FAIL: test_run (github.test_pr1475_AVIF.pr_1475_metadata2_avif)
> 1: FAIL: test_run (github.test_pr1475_HEIC.pr_1475_2021_heic)
> 1: FAIL: test_run (github.test_pr1475_HEIC.pr_1475_IMG_3578_heic)
> 1: FAIL: test_run (github.test_pr1475_HEIC.pr_1475_Stonehenge_heic)
> 1: FAIL: test_run (github.test_pr1475_HEIC.pr_1475_heic_heic)
> 1: FAIL: test_run (github.test_pr1475_HIF.pr_1475_Canon_hif)
> 1: FAIL: test_run (github.test_pr1475_HIF.pr_1475_Sony_hif)
> 1: FAILED (failures=10, skipped=10)

##### **To Reproduce**
HEAD of Branch `main` Raspbian Buster 10.10 GCC 8.3.0

Commands used :

```
git clone https://github.com/Exiv2/exiv2.git
cd exiv2
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
ctest --verbose
```

##### **Expected behavior**
All tests passed without any failures.

##### **Desktop (please complete the following information):**
- Raspbian Buster 10.10 (Armv7l  i.e. 32 bit)
- GCC 8.3.0
- Release build : -DCMAKE_BUILD_TYPE=Release

##### **Additional context**
Installation goes perfectly right on Ubuntu 20.04 (x86_64 i.e. 64 bit) with GCC 9.4.0 and same install steps

**Comment by piponazo** [comment]
Thanks for reporting this. I own a raspberry pi, and I should be able to verify this issue and hopefully have time to work on it.

**Comment by piponazo** [comment]
By the way, could you provide information about the hardware you are using? I suppose that the problem should be reproducible with any raspberry Pi, but it would be good to know exactly which model you used.

**Comment by QuietLullaby** [comment]
@piponazo I tried this on a Compute Module 4 (equivalent to raspberry pi 4)
My actual configuration is 2GB RAM 16GB eMMc with wifi

**Comment by piponazo** [comment]
Hi @QuietLullaby , I finally had some time to look at this and I can confirm that those tests are failing on ARM. I'll try to debug the problems on my RaspberryPi and fix the issues.

**Comment by piponazo** [comment]
@QuietLullaby The issues you found should be fixed now. Could you please provide feedback if these changes also fix the issues on your side?
