### ISSUE TITLE
Problems with IPTC dates containing zero for month or day

### ISSUE THREAD

**Issue by jim-easterbrook** [Exiv2/exiv2#2144]
##### **Describe the bug**

According to the IPTC standard for 2:55 Date Created: "Where the month or day cannot be determined, the information will be represented by “00”. Where the year cannot be determined, the information for century and year will be represented by “00”.

When reading a file with zero values in `Iptc.Application2.DateCreated` the string returned by `Iptcdatum.toString()` is missing its '-' separators and I get an "Unsupported date format" warning. The exiv2 command line tool (v0.26) shows the correctly formatted value.

##### **To Reproduce**

```
$ exiv2 -M"set Iptc.Application2.DateCreated 1978-09-00" copyright-free-image.jpg 
$ exiv2 -pa copyright-free-image.jpg
Iptc.Application2.DateCreated                Date        8  1978-09-00
$ python3
Python 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import exiv2
>>> im = exiv2.ImageFactory.open('copyright-free-image.jpg')
>>> im.readMetadata()
Unsupported date format

>>> im.iptcData()['Iptc.Application2.DateCreated'].toString()
'19780900'
>>> 
$ exiv2 -M"set Iptc.Application2.DateCreated 1978-09-01" copyright-free-image.jpg 
$ python3
Python 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import exiv2
>>> im = exiv2.ImageFactory.open('copyright-free-image.jpg')
>>> im.readMetadata()
>>> im.iptcData()['Iptc.Application2.DateCreated'].toString()
'1978-09-01'
>>> 
$ 
```
##### **Expected behavior**

I expect this special case to be handled the same way as normal dates.

##### **Desktop (please complete the following information):**
openSUSE Leap 15.3
libexiv2 v0.27.5 and v1.0.0.9 show the same behaviour.

**Comment by jim-easterbrook** [comment]
Correction: the v0.26 command line tool shows the date with separators, v1.0.0.9 shows the following:
```
$ ~/Documents/projects/exiv2-1.0.0.9-Linux64/bin/exiv2 -pa copyright-free-image.jpg 
Warning: Unsupported date format
Iptc.Application2.DateCreated                String      8  19780900
$
```

**Comment by piponazo** [comment]
Thanks @jim-easterbrook for reporting. I'll take a look to this issue.

**Comment by jim-easterbrook** [comment]
I think the cure may be to broaden the regexes in src/value.cpp lines 918 & 919. (I think they're being a bit over-prescriptive, not allowing for the sort of malformed stuff written by some applications I won't name here.)
