### ISSUE TITLE
Metacopy CLI tool corrupt JPEG2000 (regression with Exiv2 >= 0.27.5)

### ISSUE THREAD

**Issue by cgilles** [Exiv2/exiv2#2147]
* Context : 

Linux Mageia8
Exiv2 from 0.27-maintenance branch compiled with samples tool and installed 
One JPEG file with Exif metadata (https://drive.google.com/file/d/13n4MMb9hjUKnNuTjVcDVP7sVt0icYjTu/view?usp=sharing)
ImageMagick version 7.0.10-62 Q16 x86_64

* Steps to reproduce the bug : 

1/ I convert a JPEG containing metadata with ImageMagick:

﻿﻿[gilles@localhost JP2]$ convert 4324477432.jpg 4324477432.jp2

2/ I check if ImageMagick is able to parse JPEG2000 file.

[gilles@localhost JP2]$ identify 4324477432.jp2
4324477432.jp2 JP2 4032x3024 4032x3024+0+0 8-bit sRGB 0.000u 0:00.000

3/ ImageMagick do not copy metadata from JPEG to JPEG2000

[gilles@localhost JP2]$ exiv2 4324477432.jp2
File name       : 4324477432.jp2
File size       : 16249731 Bytes
MIME type       : image/jp2
Image size      : 4032 x 3024
4324477432.jp2: No Exif data found in the file

4/ Simple backup of JPEG2000 to compare later

[gilles@localhost JP2]$ cp 4324477432.jp2 4324477432_original.jp2

5/ I use Exiv2 metacopy CLI tool to import metadata from JPEG to JPEG2000

[gilles@localhost JP2]$ metacopy -eix 4324477432.jpg 4324477432.jp2

6/ Now ImageMagick cannot parse the JPEG2000 file:

[gilles@localhost JP2]$ identify 4324477432.jp2
identify: Stream error while reading JP2 Header box: box length is inconsistent.
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/194.
identify: unable to decode image file `4324477432.jp2' @ error/jp2.c/ReadJP2Image/347.

// ----

[gilles@localhost JP2]$ exiv2 --version
exiv2 0.27.5
[gilles@localhost JP2]$ convert --version
Version: ImageMagick 7.0.10-62 Q16 x86_64 2021-02-07 https://imagemagick.org
[gilles@localhost JP2]$ identify --version
Version: ImageMagick 7.0.10-62 Q16 x86_64 2021-02-07 https://imagemagick.org

* Important:

- I tried with other jpeg images taken with other camera, and problem is reproducible.
- With Exiv2 0.27.3, the problem is not reproducible.

**Comment by piponazo** [comment]
Thanks @cgilles for reporting this issue. I'll take a look at it.

**Comment by cgilles** [comment]
Note : i discovered this bug in digiKam primary, while i testing the file/export function to compare the regressions in different image formats. I was surprised to see the broken JPEG2000, as this format is supported since a while.

https://i.imgur.com/lrIl4ho.png

I tried also other platforms as Windows and MacOS, with exactly the same problem. After to suspect libjasper codec, i finally discovered the bug in Exiv2.

Looking in JPEG2000 code history in Exiv2, there are few changes which are candidate to introduce this regression.

Look also to my methodology to check if JPEG200 is broken, you can easily use a script in your CI to see if code work as expected in time. 

Gilles

**Comment by piponazo** [comment]
I started to investigate this issue and I am fascinated by what I am finding out. I just tried to add few unit tests to check what happens when you create a Jp2Image instance and you try to call the `printStructure` function. Just by doing that, I encountered that the function is throwing an exception. It looks like the `Jp2Blank` static data that we are adding to each Jp2Image might have some problems ... Interestingly this piece of code seems that was added by you in 2009 😅 : https://github.com/Exiv2/exiv2/commit/76a3a36e51b6b5e0fc95cda9ac578dc9c61d4421

It might also be that `Jp2Blank` is fine and what we are doing wrong if the parsing of such data.

I need to dig a bit more into the Jp2Image format to understand it properly.

**Comment by clanmills** [comment]
@piponazo JP2 is a member of the BMFF family.  `class Jp2Image::Image` in tvisitor.cpp _(in my book)_ handles JP2, HEIC, AVIF, CR3 and JXL.  During the bmff development project I decided to retain src/jp2image.cpp for the following reasons:

1.  If it's not broken, don't touch it.
2. The legal situation.   Make it easy to remove src/bmffimage.cpp.
3. The project was under significant time pressure _as always_.
4. And probably other reasons I have forgotten.

If you decide to undertake significant JP2 maintenance, please consider handling JP2 in src/bmffimage.cpp.  JP2 and BMFF are documented here:  https://exiv2.org/book/index.html#JP2  Happy to discuss this on Zoom.

**Comment by piponazo** [comment]
I am having some fun reading the JP2 standard, adding new unit tests for that class, and digging into this problem. I think I have found the bug and fixed it already. `Jp2Image::encodeJp2Header` has a mistake when writing the "Colour Specification Box" and afterwards it is impossible to read the metadata. 

By fixing this issue some other regression tests fail now, but luckily there are not so many of such cases.

For the moment I am working to bring this fix into `main`. We can decide later if we should also aim for bringing the fix to 0.27.X or not.
