### ISSUE TITLE
Compiler cannot find -lexiv2lib after apt-get install exiv2

### ISSUE THREAD

**Issue by canberkgurel** [Exiv2/exiv2#2174]
##### **Describe the bug**
First I tried to install exiv2 from the source. I followed the instructions on the README. I ran into an error upon executing `cmake --install`, then I tried to install it with `apt-get install` which worked. I'm trying to use the `exiv2/exiv2.hpp` header file in my C++ code, but the compiler still complains that it cannot find the exiv2.

##### **To Reproduce**
To reproduce, install `exiv2` with apt-get install.

```
$ sudo apt-get install -y exiv2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  exiv2
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 76.3 kB of archives.
After this operation, 249 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 exiv2 amd64 0.25-3.1ubuntu0.18.04.11 [76.3 kB]
Fetched 76.3 kB in 0s (1,046 kB/s)
Selecting previously unselected package exiv2.
(Reading database ... 772990 files and directories currently installed.)
Preparing to unpack .../exiv2_0.25-3.1ubuntu0.18.04.11_amd64.deb ...
Unpacking exiv2 (0.25-3.1ubuntu0.18.04.11) ...
Setting up exiv2 (0.25-3.1ubuntu0.18.04.11) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ... 
```

Then modify the CMakeList,txt to include `exiv2lib` in your `target_link_libraries`. 
```
target_link_libraries(<executable name> ${catkin_LIBRARIES} exiv2lib)
```

Then try to compile the code.
```
$ cd ~/catkin_ws
$ catkin build <package name>
```
This is the error:
> /usr/bin/ld: cannot find -lexiv2lib

Then if you add exiv to your find_packages in CMakeList, you should see that
```
find_package(exiv2 REQUIRED CONFIG NAMES exiv2)
```
  >Could not find a package configuration file provided by "exiv2" with any of
  the following names:
    exiv2Config.cmake
    exiv2-config.cmake
  Add the installation prefix of "exiv2" to CMAKE_PREFIX_PATH or set
  "exiv2_DIR" to a directory containing one of the above files.  If "exiv2"
  provides a separate development package or SDK, be sure it has been
  installed.

##### **Expected behavior**
I expect the compiler to find the exiv library and compile the code successfully. 

##### **Desktop (please complete the following information):**
- OS and version: Linux (Ubuntu 18.04)
- Compiler and version: 
- Compilation mode and/or compiler flags: The default is: `-DCMAKE_CXX_STANDARD=11`. I tried `-DCMAKE_CXX_STANDARD=17` but it didn't work.

**Comment by canberkgurel** [comment]
@piponazo is this something you can help with?

**Comment by piponazo** [comment]
Hi @canberkgurel . I'll try to help you. I do not think this is a bug so I removed the `bug` label for now.

Firstly, let's try to figure out why you cannot link against exiv2 when you install the system package for Ubuntu 18.04. I have a machine with the same OS, and these are the files installed with the `libexiv2-dev` package:

```
luis@myPc ~ $ dpkg -L libexiv2-dev 
/.
/usr
/usr/include
/usr/include/exiv2
/usr/include/exiv2/basicio.hpp
...
/usr/include/exiv2/exiv2.hpp
...
/usr/include/exiv2/xmpsidecar.hpp
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libexiv2.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/exiv2.pc
/usr/share
/usr/share/doc
/usr/share/doc/libexiv2-dev
/usr/share/doc/libexiv2-dev/copyright
/usr/lib/x86_64-linux-gnu/libexiv2.so
/usr/share/doc/libexiv2-dev/changelog.Debian.gz
```

As you can see, the Ubuntu package does not bring any CMake files, and therefore you cannot easily find the library with `find_package`. You could use instead **pkgconfig** for that instead.

Nonetheless, since you are installing the system package, the exiv2 folder is deployed in your system include directory (`/usr/include`) and the library in the system lib directory (`/usr/lib/x86_64-linux-gnu`). In principle, your compiler should take into account those default system paths so that if you include in your .cpp files the exiv2 headers like this:

```cpp
#include <exiv2/exiv2.hpp>
...
```
And in your CMake you do something like this:
```
target_link_libraries(myApp exiv2)  # Note that you need to use exiv2 and not exiv2lib
```

Everything should work. If not, you can always use the CMake command `target_include_directories` to add more include directories to be considered. The CMake command `find_library` can also help you to determine if one library is found in your system.

A second issue is regarding building & installing exiv2 from sources. You mentioned that `cmake --install` failed for you. If you provide more detials about this I might be able to help you :wink:

**Comment by clanmills** [comment]
There are several exiv2 related packages in apt.  The "vanilla" exiv2 installs the command-line program.   To compile and link exiv2, you'll need to install libexiv2-dev

The last time this was discussed (about 2 years ago) there was an issue with the "vanilla" exiv2.  It installed the exiv2 executable without installing the library.  I don't know if that's been fixed.

You might find downloading and installed the builds from exiv2.org is easier - _or you may not_.  I assure you that we prepare the packages and documentation with great care.  However installing and building packages can be challenging when you are not familiar with the tools involved. 

```
rmills@rmillsm1-ubuntu:~$ apt list | grep exiv2

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

exiv2/focal-updates,focal-security 0.27.2-8ubuntu2.7 arm64
gir1.2-gexiv2-0.10/focal 0.12.0-2 arm64
libexiv2-27/focal-updates,focal-security,now 0.27.2-8ubuntu2.7 arm64 [installed]
libexiv2-dev/focal-updates,focal-security 0.27.2-8ubuntu2.7 arm64
libexiv2-doc/focal-updates,focal-security 0.27.2-8ubuntu2.7 all
libgexiv2-2/focal,now 0.12.0-2 arm64 [installed]
libgexiv2-dev/focal 0.12.0-2 arm64
libgexiv2-doc/focal 0.12.0-2 all
libkf5kexiv2-15.0.0/focal 19.12.3-0ubuntu1 arm64
libkf5kexiv2-dev/focal 19.12.3-0ubuntu1 arm64
rmills@rmillsm1-ubuntu:~$
```

**Comment by canberkgurel** [comment]
@piponazo @clanmills Thanks for the help.

I already had `libexiv2-dev` installed. I solved the problem by adding

```
target_include_directories(<exe name> PUBLIC /usr/include /usr/include/exiv2/)
target_link_libraries(tower_scan_imager ${catkin_LIBRARIES} exiv2)
```
to my CMakeList.txt file. For some reason `find_package(exiv2 REQUIRED CONFIG NAMES exiv2)` still throws an error. But anyway, I am able to compile and run the code. So, I'm happy.

**Comment by piponazo** [comment]
> For some reason `find_package(exiv2 REQUIRED CONFIG NAMES exiv2)` still throws an error.

As I mentioned in my previous comment, the Ubuntu package `libexiv2-dev` is not installing the needed CMake files for CMake to be able to find the library with the `find_package` command. Probably on that version of the package (0.25-3) we were not deploying any CMake files yet.

If you would compile and install exiv2 from the sources, you would get those CMake files in the installation folder. You also have the chance to use any of the pre-compiler versions from here:
https://github.com/Exiv2/exiv2/releases?page=1

In these pre-compiled binaries, you will find the CMake files needed for CMake to find the library under `lib/cmake/*.cmake`
