### ISSUE TITLE
Out of bounds read in isValidBoxFileType (jp2image_int.cpp)

### ISSUE THREAD

**Issue by kevinbackhouse** [Exiv2/exiv2#2178]
Two bugs reported by OSS-Fuzz, both caused by the same issue:

* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46000
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45993

These are reproducible on `main` and `0.27-maintenance`, but fortunately not on v0.27.5, so they don't need a security advisory. I think the bugs were most likely introduced by #2153, which hasn't been included in an official release yet.

pocs: 
[pocs.tar.gz](https://github.com/Exiv2/exiv2/files/8388270/pocs.tar.gz)

To reproduce:

```bash
./bin/exiv2 clusterfuzz-testcase-minimized-fuzz-read-print-write-5186226698715136
./bin/exiv2 clusterfuzz-testcase-minimized-fuzz-read-print-write-5350508795133952
```

The crash happens here:

https://github.com/Exiv2/exiv2/blob/790fc465f486eb511b9bdbe2c0f53d7132256c9d/src/jp2image.cpp#L186

The problem is that there is no size check of `boxData`.

Thanks also to @mqrsv, who found this issue independently from OSS-Fuzz and reported it to us today (2022-03-31), before I opened this issue.

**Comment by piponazo** [comment]
Thanks @kevinbackhouse for reporting. I'll take a look to this ASAP

**Comment by piponazo** [comment]
Just out of curiosity, when I click in the links provided (bugs.chromium...) I cannot see any details there, I only see the message: `Permission denied.`. I have few questions about this:
- Is there a way somebody can get access to the details of those reports?
- What's the difference between that oss-fuzz and the fuzzer jobs we have in our CI? Do those fuzzers run a longer time or with different options?

**Comment by piponazo** [comment]
> @piponazo: I think I can give you access to the OSS-Fuzz results by adding your email address to [this file](https://github.com/google/oss-fuzz/blob/master/projects/exiv2/project.yaml). It looks like I just need to add a section named [`auto_ccs`](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#auto_ccs). Would you like me to do that?

Yes please, I am also interested in learning more about this things and get notified when something occurs :+1:
