### ISSUE TITLE
You

### ISSUE THREAD

**Issue by Ladcjh04** [Exiv2/exiv2#2188]
##### **Is your feature request related to a problem?**
A clear and concise description of the problem (e.g., I'm always frustrated when [...]; Exiv2 does not support XXX format [...])

##### **Describe the solution you would like**
A short description of what you want to happen.

##### **Describe alternatives you have considered**
A simple explanation of any alternative solutions or features you have considered.

##### **Additional context**
Add any other information about the feature request here (e.g. screenshots, URLs).

**Comment by piponazo** [comment]
Mmmmm ... I guess you clicked in submit accidentally 😅 . Closing it until details are given
