### ISSUE TITLE
New lens AF-S Nikkor 500mm f/5.6E PF ED VR

### ISSUE THREAD

**Issue by bilddateien** [Exiv2/exiv2#2193]
##### **Is your feature request related to a problem?**
Lens is not supported by darktable/lensfun as lens type is not decoded.

##### **Additional context**
RAW sample and EXIF attached, [content of those two files is CC0](https://creativecommons.org/publicdomain/zero/1.0/)
[exifdata-AF-S_Nikkor_500mm.zip](https://github.com/Exiv2/exiv2/files/8426236/exifdata-AF-S_Nikkor_500mm.zip)
[20220130_N5X0015.nef.zip](https://github.com/Exiv2/exiv2/files/8426244/20220130_N5X0015.nef.zip)

**Comment by hassec** [comment]
Yep looks like this lens should be added, thanks for providing the samples :+1:     
Do agree that we will add the extracted exif data from your samples to this repository to turn them into a test case?

Just FYI in case you don't know this yet: 
You can work around exiv2 not knowing this specific lens by using a configuration file.       
This is explained in the `CONFIGURATION FILE` section of the [man pages](https://exiv2.org/manpage.html)
