### ISSUE TITLE
Lens ID mismatch: Canon RF 100-500 has 2x extender added to ID

### ISSUE THREAD

**Issue by BazThomas** [Exiv2/exiv2#2202]
Hi

Using ART (a fork of RawTherapee) v1.13 on Windows 10. ART uses Exiv2.

An image taken with the Canon R5 and RF 100-500 is reported as having the RF 2x extender too - which was not used.

I reported this on the ART forum and the author found it was due to Exiv2 and the same issue appears in Darktable:

https://discuss.pixls.us/t/lens-spec-display-bug/30301/2

Sample file here: www.barrythomas.co.uk/R5BT8039.zip

Many thanks

Barry

**Comment by BazThomas** [comment]
I checked with another RF lens, the 50mm f/1.8 STM which is reported as 50mm f1.2:

![image](https://user-images.githubusercontent.com/59660057/162922007-4cd90919-bb71-4e34-9f2a-95d563679afd.png)

I guess this is all part of the same issue so not worthy of starting a new ticket.

tvm

B.

**Comment by hassec** [comment]
This is what I see using the current `main` branch:

```
❯ ../build/bin/exiv2 -pt --grep Lens R5BT8039.CR3
Exif.Photo.LensSpecification                 Rational    4  100/1 500/1 0/1 0/1
Exif.Photo.LensModel                         Ascii      30  RF100-500mm F4.5-7.1 L IS USM
Exif.Photo.LensSerialNumber                  Ascii      11  1014004270
Exif.CanonCs.LensType                        Short       1  Canon RF 100-500mm F4.5-7.1L IS USM
Exif.CanonCs.Lens                            Short       3  100.0 - 500.0 mm
Exif.CanonFi.RFLensType                      SShort      1  Canon RF 100-500mm F4.5-7.1L IS USM
Exif.Canon.LensModel                         Ascii     138  RF100-500mm F4.5-7.1 L IS USM
Exif.CanonLe.LensSerialNumber                SLong       1  1107301392
Exif.CanonAfC.USMLensElectronicMF            SLong       1  Disable in AF Mode
Exif.CanonAfC.LensDriveWhenAFImpossible      SLong       1  Continue Focus Search
```

There are main improvements on `main` that aren't in `0.27.X` so that's probably the problem you are seeing.   
You could try and download the nightly prerelease and use that version.

**Comment by BazThomas** [comment]
Thank you - good to know. My sw building days are historical now, but if the nightly build can be dropped into my version of ART I might go that route. 

Interestingly, looking in the RAW above, re the f1.2 vs f1.8 lens, ExifTool (in XnView) shows this:

![image](https://user-images.githubusercontent.com/59660057/162940145-fa028bda-8145-4e47-92b4-38a167ec0dbc.png)

So the Lens Type field is at best vague, while the individual specs of the lens below are right. Thanks Canon. I can see that someone has to do a lot of picking through the bones to get the right answer for the user on screen. I appreciate the help from authors of Exiv2 and Abverto over at ART.

B.

**Comment by BazThomas** [comment]
Thank you - good to know. My sw building days are historical now, but if the nightly build can be dropped into my version of ART I might go that route.

Interestingly, looking in the RAW above, re the f1.2 vs f1.8 lens, ExifTool (in XnView) shows this:

![Uploading image.png…]()

So the Lens Type field is at best vague, while the individual specs of the lens below are right. Thanks Canon. I can see that someone has to do a lot of picking through the bones to get the right answer for the user on screen. I appreciate the help from authors of Exiv2 and Abverto over at ART.

B.

**Comment by BazThomas** [comment]
[](https://github.com/Exiv2/exiv2/issues/2202)Thank you - good to know. My sw building days are historical now, but if the nightly build can be dropped into my version of ART I might go that route.

Interestingly, looking in the RAW above, re the f1.2 vs f1.8 lens, ExifTool (in XnView) shows this:


![image](https://user-images.githubusercontent.com/59660057/162940856-ac29eb60-8c40-4803-bb27-b174e5158f39.png)


So the Lens Type field is at best vague, while the individual specs of the lens below are right. Thanks Canon. I can see that someone has to do a lot of picking through the bones to get the right answer for the user on screen. I appreciate the help from authors of Exiv2 and Alberto over at ART.

B.

**Comment by hassec** [comment]
> So the Lens Type field is at best vague,...

yes that is unfortunately a super annoying problem because the reported Lens type has to be reconstructed from the available lens details that is found in the metadata.    
If you are interested, for canon this happens here: https://github.com/Exiv2/exiv2/blob/6c99577f1d5b6c8d6cd13d5990e789fd9adc8942/src/canonmn_int.cpp#L2520  

You can see that there is quite a bit of code trying to do its best, but the problem is unfortunately not well-defined and there are various cases where one can't differentiate between two lenses :(    

FWIW, for most users a good solution is also to just use a configuration file to overwrite the lens detection in `exiv2`. How to do that is explained in the [manpages](https://exiv2.org/manpage.html)      

So in your case, instead of trying the latest build you could continue to use the exiv2 version you have + a configuration file, which might be easier to setup :wink:

**Comment by BazThomas** [comment]
I spent 10y writing medical s/w in C and C++ a _long_ time ago and don't miss it. The layer upon layer of other people's data that you have to unpick to make this kind of app work is a nightmare. I'm going to back away from the keyboard and leave you guys to it thanks :) I can tell from the (correctly reported) lens length in the ART info panel which combo I was using at the long end, and I know I don't own an f1.2 at the short end. Also if I was really motivated I could just look at the EXIF to see what horrors Canon left there. I'm happy.

Many thanks

Barry
