### ISSUE TITLE
Problem reading metadata from a JPEG XL file

### ISSUE THREAD

**Issue by novomesk** [Exiv2/exiv2#2233]
Hello,

This is a home-made JXL file which should have Exif and XMP metadata embedded: 
[jpeg-xl-with-metadata.zip](https://github.com/Exiv2/exiv2/files/8664053/jpeg-xl-with-metadata.zip)

When I try to print metadata using `exiv2` 0.27.5 I get following error:

```
exiv2 pr jpeg-xl-with-metadata.jxl
Exiv2 exception in print action for file jpeg-xl-with-metadata.jxl:
corrupted image metadata
```

Please investigate the problem. I would like to see whether the problem is in the jpeg-xl-with-metadata.jxl file or exiv2 implementation.

**Comment by kmilos** [comment]
Actually both the Exif and XMP box handling look suspicious to me wrt to length (box header included, while expected is not?) and start address (header skipped or not)... @1div0 @kevinbackhouse 

https://github.com/Exiv2/exiv2/blob/056139269eba1ec373fe57b82c0d98d3c31a28c4/src/bmffimage.cpp#L439-L444


The file looks ok.

**Comment by kmilos** [comment]
Yep, did the box swap using `dd` and now Exif parsing fails...

[jpeg-xl-with-metadata-swap.zip](https://github.com/Exiv2/exiv2/files/8668784/jpeg-xl-with-metadata-swap.zip)

**Comment by eddiezato** [comment]
Don't know where to report this:
- take png from [here](https://file-examples.com/storage/fe6869c4db62a7ab6a021f9/2017/10/file_example_PNG_3MB.png);
- make a copy and write a comment with `exiv2`;
- the same with `exiftool`;
- trying to convert pngs with `cjxl`.

`cjxl` can see the exif for pngs processed with `exiftool`, but can't with `exiv2`.

```PowerShell
PS > cp 0.png e2.png
PS > exiv2 -M"set Exif.Photo.UserComment test-exiv2" e2.png

PS > cp 0.png et.png
PS > exiftool -UserComment="test-exiftool" et.png
    1 image files updated

PS > exiv2 -PEkv -g UserComment e2.png et.png
e2.png                Exif.Photo.UserComment                        test-exiv2
et.png                Exif.Photo.UserComment                        charset=Ascii test-exiftool

PS > .\exiftool -UserComment e2.png et.png
======== e2.png
User Comment                    : test-exiv2
======== et.png
User Comment                    : test-exiftool
    2 image files read

PS > cjxl e2.png
JPEG XL encoder v0.7.0 b7076f1 [SSE4]
libpng warning: iCCP: known incorrect sRGB profile
No output file specified.
Encoding will be performed, but the result will be discarded.
Read 2200x1467 image, 39.0 MP/s
Encoding [VarDCT, d1.000, squirrel], 4 threads.
Compressed to 124131 bytes (0.308 bpp).
2200 x 1467, 5.70 MP/s [5.70, 5.70], 1 reps, 4 threads.

PS > cjxl et.png
JPEG XL encoder v0.7.0 b7076f1 [SSE4]
libpng warning: iCCP: known incorrect sRGB profile
No output file specified.
Encoding will be performed, but the result will be discarded.
Read 2200x1467 image, 39.3 MP/s
Encoding [Container | VarDCT, d1.000, squirrel | 178-byte Exif], 4 threads.
Compressed to 124131 bytes (0.308 bpp).
2200 x 1467, 5.66 MP/s [5.66, 5.66], 1 reps, 4 threads.
Including container: 124361 bytes (0.308 bpp).
```

`exiv2`, `cjxl` - the latest git-versions (built with msys2/ucrt64)
`exiftool` - from exiftool.org

**Comment by kmilos** [comment]
Please create a separate issue, maybe after somehow establishing if this is really exiv2's "fault", or libjxl's... E.g. does it happen with some other more "standard" tag like `Copyright`, `UserComment` is a bit special as it requires that character encoding to be present...

Also, there might be a difference in where exiv2 and exiftool actually store the Exif data in a PNG - there are two possibilities, and cjxl might support only one of them:

iTXt chunk - general purpose blob storage, as the original PNG spec didn't support Exif
eXIf chunk - only added in PNG spec update 1.5 for Exif specifically and not all SW might be up to date with it.

**Comment by eddiezato** [comment]
It seems to be a `cjxl` *"fault"*, it doesn't detect exif in both cases:
```
PS > cp 0.png e2.png; exiv2 -M"set Exif.Image.Copyright test" e2.png

PS > cp 0.png et.png; .\exiftool -Copyright="test" et.png
    1 image files updated

PS > exiv2 -pS e2.png
STRUCTURE OF PNG FILE: e2.png
 address | chunk |  length | data                           | checksum
       8 | IHDR  |      13 | ............                   | 0xfe630e0c
      33 | zTXt  |      92 | Raw profile type exif..x.U.... | 0xf557d624
     137 | iCCP  |    2609 | ICC profile..x...wTS.....7.P.. | 0x39a0dbb9
    2758 | pHYs  |       9 | .........                      | 0x009a9c18
    2779 | tIME  |       7 | ......+                        | 0x2eec9677
    2798 | IDAT  |    8192 | x.....$..$.j..Y}..`..>.R.".~.. | 0x736d732c
   11002 | IDAT  |    8192 | ....'....,..........@.}(*=...B | 0xa45fd2a2
   ...

PS > exiv2 -pS et.png
STRUCTURE OF PNG FILE: et.png
 address | chunk |  length | data                           | checksum
       8 | IHDR  |      13 | ............                   | 0xfe630e0c
      33 | iCCP  |    2627 | ICC profile..x..SwX...>..e.VB. | 0x80392511
    2672 | pHYs  |       9 | .........                      | 0x009a9c18
    2693 | tIME  |       7 | ......+                        | 0x2eec9677
    2712 | tEXt  |      14 | Copyright.test                 | 0x87a4fae1
    2738 | IDAT  |    8192 | x.....$..$.j..Y}..`..>.R.".~.. | 0x736d732c
   10942 | IDAT  |    8192 | ....'....,..........@.}(*=...B | 0xa45fd2a2
   ...

PS > cjxl e2.png
JPEG XL encoder v0.7.0 b7076f1 [SSE4]
libpng warning: iCCP: known incorrect sRGB profile
No output file specified.
Encoding will be performed, but the result will be discarded.
Read 2200x1467 image, 34.8 MP/s
Encoding [VarDCT, d1.000, squirrel], 4 threads.
Compressed to 124131 bytes (0.308 bpp).
2200 x 1467, 4.86 MP/s [4.86, 4.86], 1 reps, 4 threads.

PS > cjxl et.png
JPEG XL encoder v0.7.0 b7076f1 [SSE4]
libpng warning: iCCP: known incorrect sRGB profile
No output file specified.
Encoding will be performed, but the result will be discarded.
Read 2200x1467 image, 36.1 MP/s
Encoding [VarDCT, d1.000, squirrel], 4 threads.
Compressed to 124131 bytes (0.308 bpp).
2200 x 1467, 5.21 MP/s [5.21, 5.21], 1 reps, 4 threads.
```

**Comment by kmilos** [comment]
Ah, the exiftool way didn't work this second time because it created a plain PNG Copyright text.

https://exiftool.org/TagNames/PNG.html#TextualData

To make sure it is Exif, you can maybe try `exiftool -EXIF:Copyright="test"`.

In any case, I think it is now clear - please create two new requests:

- one for exiv2 to support/prefer writing to PNG eXIf chunk (and possibly check the XMP as well)
- one for libjxl to support reading old-style tEXt/iTXt/zTXt chunks for Exif/XMP/ICC
