### ISSUE TITLE
exiv2 reports "corrupted metadata" where exiftool can extract them all

### ISSUE THREAD

**Issue by notorand-it** [Exiv2/exiv2#2237]
##### **Describe the bug**
On an Andoid-shot MP4 file exiv2 reports "corrupted metadata" while exiftool can extract them all.

##### **To Reproduce**
1. Download the attached MP4 file
2. run "exiv2 pr file.mp4"
3. run "exiftool file.mp4"

##### **Expected behavior**
Both steps output media file metadata

##### **Actual behavior**
exiv2 reports corruption error
exiftools works

##### **Desktop (please complete the following information):**
- OS and version: ArchLinux (up-to-date)
- Compiler and version: gcc (GCC) 12.1.0 (irrelevant?)
- Compilation mode and/or compiler flags: Packages come from distro repo.

##### **Additional context**
exiv2 0.27.5
exiftool 12.4

https://user-images.githubusercontent.com/5338874/168466332-67761d35-9357-4649-b001-9cf7d5219d4f.mp4

**Comment by VJSchneid** [comment]
Hi @notorand-it,
unfortunately I do not know a lot about mp4 files but after looking into the corresponding source file (``src/bmffimage.cpp``) it seems as if there is missing some code to parse all the boxes/atoms found in your video file.

The corrupted file error comes from exiv2 when it tries to read another box inside the ``meta`` box, which seems to be not present or differently formatted as expected (see [line 288](https://github.com/Exiv2/exiv2/blob/main/src/bmffimage.cpp#L288) in ``src/bmffimage.cpp``).

I made some tests and when the boxHandler in [line 295](https://github.com/Exiv2/exiv2/blob/main/src/bmffimage.cpp#L295) is just called for the ``moov``, ``iprp`` and ``ipco`` tag, no error is thrown but no metadata is found either. To find the metadata I think more boxes have to be parsed.
[This site](https://gpac.github.io/mp4box.js/test/filereader.html) can give some hints what boxes are present in your mp4 file and there are many more that exiv2 does not process...

I hope I could help a little bit

**Comment by benmccann** [comment]
I'm not that familiar with this stuff, but here's where the `creation_time` is from `mp4box.js`:

![Screenshot from 2022-08-11 19-54-15](https://user-images.githubusercontent.com/322311/184276516-0e2e36df-11a1-4fc4-be23-b39f77412ff0.png)

**Comment by hassec** [comment]
This request targets the removed video functionality, to be specific `quicktimevideo.cpp`. Please see https://github.com/Exiv2/exiv2/issues/1748 for further info

**Comment by 1div0** [comment]
@benmccann please have a l👀l at https://mediaarea.net/ tools.

Video is very complex and full of bull$#17 $0ftwar€ patents.
