### ISSUE TITLE
Exif.OlympusCs.ArtFilter not fully parsed on Olympus E-M10 Mark II

### ISSUE THREAD

**Issue by RigacciOrg** [Exiv2/exiv2#2246]
##### **Describe the bug**
The human readable label for **Exif.OlympusCs.ArtFilter** is not printed in some cases. Exiv2 parses the first two shorts and expects the second short to be always 1280, but in my case it is 4352.

##### **To Reproduce**
Execute the following command on the photo shooted in "Soft Focus":
`exiv2 -P kyctv -u print OlympusCs.PictureMode.11.jpg`

The output is (no human readable tag):
`Exif.OlympusCs.ArtFilter                     Short       4  1 4352 0 0`

At least for my E-M10 the following should be added in olympusmn_int.cpp:

```
{{1, 4352}, N_("Soft Focus")},
{{5, 4352}, N_("Pin Hole")},
{{9, 4352}, N_("Diorama")},
{{14, 4352}, N_("Gentle Sepia")},
{{20, 4352}, N_("Dramatic Tone")},
```

Tried on Debian GNU/Linux running **exiv2 0.27.3**

If required I can try all the ArtFilters on my camera and provide sample images.

**Comment by postscript-dev** [comment]
@RigacciOrg:
Thanks for looking at this yourself - you are right, the values are missing from the translation function.

If you have the time, a complete list of `Exif.OlympusCs.ArtFilter` values would help us provide better support for your camera. As the translation function is also shared with the `Exif.OlympusCs.MagicFilter` tag, I would like to know if this is set in your photos. You can display these values using:
```
$ exiv2 --Print kvt --key Exif.OlympusCs.ArtFilter --key Exif.OlympusCs.MagicFilter file.jpg
Exif.OlympusCs.ArtFilter                      0 0 0 0  Off
```
I don't have any example photos that include the `Exif.OlympusCs.MagicFilter` tag. Do you know anything about this feature?

**Comment by RigacciOrg** [comment]
I took 23 pictures with all the Picture Modes available on the OM-D E-M10 MarkII:

i-Enhance
Vivid
Natural
Muted
Portrait
Monotone
Custom
e-Portrait
Color Creator
Pop Art
Soft Focus
Pale&Light Color
Light Tone
Grainly Film
Pin Hole
Diorama
Cross Process
Gentle Sepia
Dramatic Tone
Key Line
Watercolor
Vintage
Partial Color

Then I printed with **exiv2 -P kyctv -u print** the Exif.OlympusCs.ArtFilter, Exif.OlympusCs.PictureMode and Exif.OlympusCs.MagicFilter tags, it seems that MagicFilter is missing from the photos:

```
===== Exif.OlympusCs.ArtFilter =====
Exif.OlympusCs.ArtFilter                     Short       4  0 0 0 0  Off
Exif.OlympusCs.ArtFilter                     Short       4  0 0 0 0  Off
Exif.OlympusCs.ArtFilter                     Short       4  0 0 0 0  Off
Exif.OlympusCs.ArtFilter                     Short       4  0 0 0 0  Off
Exif.OlympusCs.ArtFilter                     Short       4  0 0 0 0  Off
Exif.OlympusCs.ArtFilter                     Short       4  0 0 0 0  Off
Exif.OlympusCs.ArtFilter                     Short       4  0 0 0 0  Off
Exif.OlympusCs.ArtFilter                     Short       4  0 0 0 0  Off
Exif.OlympusCs.ArtFilter                     Short       4  0 0 0 0  Off
Exif.OlympusCs.ArtFilter                     Short       4  2 1280 0 0  Pop Art
Exif.OlympusCs.ArtFilter                     Short       4  1 4352 0 0  
Exif.OlympusCs.ArtFilter                     Short       4  3 1280 0 0  Pale & Light Color
Exif.OlympusCs.ArtFilter                     Short       4  4 1280 0 0  Light Tone
Exif.OlympusCs.ArtFilter                     Short       4  6 1280 0 0  Grainy Film
Exif.OlympusCs.ArtFilter                     Short       4  5 4352 0 0  
Exif.OlympusCs.ArtFilter                     Short       4  9 4352 0 0  
Exif.OlympusCs.ArtFilter                     Short       4  10 1280 0 0  Cross Process
Exif.OlympusCs.ArtFilter                     Short       4  14 4352 0 0  
Exif.OlympusCs.ArtFilter                     Short       4  20 4352 0 0  
Exif.OlympusCs.ArtFilter                     Short       4  25 4352 0 0  
Exif.OlympusCs.ArtFilter                     Short       4  33 4352 0 0  
Exif.OlympusCs.ArtFilter                     Short       4  36 4352 0 0  
Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 15  

===== Exif.OlympusCs.PictureMode =====
Exif.OlympusCs.PictureMode                   Short       2  5 2  i-Enhance
Exif.OlympusCs.PictureMode                   Short       2  1 2  Vivid
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  3 2  Muted
Exif.OlympusCs.PictureMode                   Short       2  4 2  Portrait
Exif.OlympusCs.PictureMode                   Short       2  256 2  Monotone
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  6 2  e-Portrait
Exif.OlympusCs.PictureMode                   Short       2  7 2  Color Creator
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural
Exif.OlympusCs.PictureMode                   Short       2  2 2  Natural

===== Exif.OlympusCs.MagicFilter =====
```

It seems also that for **Partial Color** mode {39, 4352}, the 3rd and 4th bytes represent the selected color: I got the values (0, 12), (0, 15) and (0, 4) by changing it randomly.

**Comment by postscript-dev** [comment]
Thanks for taking the pictures, I can use the values to update the tags.

> It seems also that for Partial Color mode {39, 4352}, the 3rd and 4th bytes represent the selected color: I got the values (0, 12), (0, 15) and (0, 4) by changing it randomly.

The `Exif.OlympusCs.ArtFilter` tag uses 4 `Short` values. The first is the art filter but the other 3 are still a mystery.
I looked at your camera's instruction manual and the `Partial Color` mode produces a monochrome image with a single user-selected colour in it. You may be correct about the 3rd/4th values of `Partial Color` but I am unclear how they relate to the selected colour. I can't tell from the instruction manual but are there only 256 colours to choose from in the user-selected 'Color Ring'?

**Comment by RigacciOrg** [comment]
When using the `Partial Color` mode of `Exif.OlympusCs.ArtFilter` (1st byte = 39), the **4th byte** represents **the color selected using the dial**. On my E-M10 Mark II you can select 18 different positions on the color wheel, the top (north) position is 0 and it increases by 1 at each step, turning clockwise:

```
P5303239.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 0  
P5303240.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 1  
P5303241.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 2  
P5303242.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 3  
P5303243.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 4  
P5303244.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 5  
P5303245.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 6  
P5303246.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 7  
P5303247.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 8  
P5303248.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 9  
P5303249.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 10  
P5303250.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 11  
P5303251.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 12  
P5303252.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 13  
P5303253.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 14  
P5303254.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 15  
P5303255.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 16  
P5303256.JPG          Exif.OlympusCs.ArtFilter                     Short       4  39 4352 0 17  
```

**Comment by postscript-dev** [comment]
@RigacciOrg:
> When using the Partial Color mode of Exif.OlympusCs.ArtFilter (1st byte = 39), the 4th byte represents the color selected using the dial. On my E-M10 Mark II you can select 18 different positions on the color wheel, the top (north) position is 0 and it increases by 1 at each step, turning clockwise:

This makes things clearer - sometimes you need the camera in front of you to understand how things work. I will update the tags as follows:
1. Add the missing filter values
2. Output `Partial Color` as `Partial Color (position n+1)` where `n` is the 4th vanilla value. e.g., `Partial Color (position 16)`.

Could you please donate 1 test image where `Partial Color` has been used. This needs to be released under the project's [GPL 2.0 license](https://github.com/Exiv2/exiv2/blob/main/COPYING)). Exiv2 has few Olympus test images and this will help to provide support both here and in the future. The quality of the image is unimportant as it is the metadata which we are interested in.

**Comment by RigacciOrg** [comment]
I attach an image here, it is marked
 "CC-By-SA" into the `Exif.Image.Copyright`, if you need a different licensing let me know. GPL is OK too.
Please consider also to add the missing label for `Exif.OlympusCs.ImageStabilization` and the typo into `![P5313257](https://user-images.githubusercontent.com/863803/171219805-d00020d4-0ede-449b-93ba-e3b870f6ce77.JPG)`:

- `Exif.OlympusCs.ArtFilter`: ART14 - **Partial Color (position 6)**
- `Exif.OlympusCs.ImageStabilization`: (4) - Is actually labeled "**S-IS AUTO**" into the Olympus menu
- `Exif.OlympusCs.WhiteBalance`: Auto (Keep Warm Color Off - Please add the **missing closed parenthesis**

![P5313257.JPG](https://user-images.githubusercontent.com/863803/171220007-9b481815-e493-45d1-8b19-c6312374066a.JPG)

**Comment by postscript-dev** [comment]
@RigacciOrg:

> I attach an image here, it is marked "CC-By-SA" into the Exif.Image.Copyright, if you need a different licensing let me know. GPL is OK too.

That is a nice photo. I have searched for links between "CC-By-SA" and GPL2 and can't find a simple explanation. As I only need the metadata from the image, if you agree, I can extract the metadata and this can be released under the GPL2. I can update the `Exif.Image.Copyright` tag to reflect the change in license.

> Please consider also to add the missing label for Exif.OlympusCs.ImageStabilization and the typo into Exif.OlympusCs.WhiteBalance:

As the changes are small, I can include them.

> Exif.OlympusCs.ArtFilter: ART14 - Partial Color (position 6)

I don't understand what you mean by `ART14`?

**Comment by postscript-dev** [comment]
@RigacciOrg:
Sorry for the delay.

> The CC-By-SA should be a free license compatibile with GPL (at least this is my intent), see https://www.gnu.org/licenses/license-list.en.html, but I did not find specific words about versions. Anyway feel free to use the whole image above or to extract the metadata and publish all under any GPL license.

I looked at the link but I could only find references to GPL3 rather than GPL2. However, as you have explained your consent, I have continued to make the changes.

> About ART14: the menus of the E-M10 use short labels and long ones for art filters; e.g. ART1 is also labeled Pop Art, ART2 is Soft Focus, ... and the last one ART14 is Partial Color (se the full list in my above comment). Here it is a screenshot of the menu:

Thanks for explaining but I think that I will leave adding `ART` as only some of the values have additional labels. I think that it is possible to understand the camera choices using the other text.

I see that you are currently using `Exiv2 0.27.3` but `Exiv2 0.27.5` is available to [download](https://exiv2.org/download.html) (see the [release notes](https://exiv2.org/whatsnew.html) to find out what has changed). The `main` branch has a rewritten [manpage](https://github.com/Exiv2/exiv2/blob/main/exiv2.md) which contains more information and examples. Currently, apart from a couple of small differences (see the git history), the text works with the `0.27.5` download.

As for fixing things, I have started to submit changes to the `main` branch. Once these are merged, I will look at adding them into the `0.27-maintenance` branch. It looks as though the next version of Exiv2 will be `0.27.6` although I don't know when this will be released.

**Comment by postscript-dev** [comment]
@RigacciOrg:
As you requested, I am updating the `Exif.OlympusCs.ImageStabilization` to use the `S-IS AUTO` value (`4`). I see from your camera's instruction manual that values of `S-IS1`, `S-IS2` and `S-IS1` are also available. Intuitively these labels look like they relate to values of `1`, `2` and `3` but could you please confirm this? There is no need to provide sample file, simply let me know.

**Comment by RigacciOrg** [comment]
I can confirm that the values of the `Exif.OlympusCs.ImageStabilization` tag have the following meaning in my E-M10:

- 0 => OFF - Still-I.S. Off
- 1 => S-IS1 - All Direction Shake I.S.
- 2 => S-IS2 - Vertical Shake I.S.
- 3 => S-IS3 - Horizontal Shake I.S.
- 4 => S-IS AUTO - Auto I.S.
