### ISSUE TITLE
Canon EF 35-80mm f/4-5.6 II and III are named just like the original Canon EF 35-80mm f/4-5.6

### ISSUE THREAD

**Issue by PeterWem** [Exiv2/exiv2#2247]
![EF35-80](https://user-images.githubusercontent.com/34200649/173085428-32534d0c-3345-463b-9825-d8aa37fc34e8.png)

Canon has five EF 35-80 lenses and exiv2 reports the same name for three of them for the LensType tag.

##### **To Reproduce**
Sample raw files CC0 license https://drive.google.com/file/d/1fnxPGsF_daav3ej16DKlIgfh2gBJ4_Vh/view?usp=sharing
![exiv2-pt](https://user-images.githubusercontent.com/34200649/173083640-4c772b54-3ad2-4e65-90d8-7f30dfa8a521.png)
![exiv2-pv](https://user-images.githubusercontent.com/34200649/173083663-83df5783-8acf-43c3-882e-e98af27e3ed0.png)

exiv2 version 0.27.5

##### **Expected behavior**
LensType 35 should be named Canon EF 35-80mm f/4-5.6 II
LensType 37 should be named Canon EF 35-80mm f/4-5.6 III

##### **Desktop (please complete the following information):**
- Ubuntu 20.04

**Comment by PeterWem** [comment]
Thanks!

**Comment by hassec** [comment]
Thanks for the report! :+1:

**Comment by kmilos** [comment]
Might be an idea to report this over at https://github.com/exiftool/exiftool as well: 

https://exiftool.org/TagNames/Canon.html
