### ISSUE TITLE
exiv2 rename example in the man pages doesn't work the way it says it should.

### ISSUE THREAD

**Issue by frohro** [Exiv2/exiv2#2290]
It appears that the basename option is not documented correctly or perhaps doesn't work as it should.  The manual page says:
`  $ exiv2 -r'basename_%Y%m' rename img_1234.jpg
       Renames img_1234.jpg to img_1234_200511.jpg

`
but what happens on Ubuntu 22.04 is the file name becomes 
$ ls basename_202207.jpg 
basename_202207.jpg
for this image first renamed to img_1234.jpg, taken in July 2022.

Rob

**Comment by postscript-dev** [comment]
@frohro:
You are right, the manpage is incorrect. For the `0.27.5` release, the manpage example is:

```
$ exiv2 -r'basename_%Y%m' rename img_1234.jpg
```

but should read:

```
exiv2 -r ":basename:_%Y%m" rename image.jpg
```
as the keyword needs to be surrounded by `:`s.

I am working on a different project at the moment but when I am finished I will come back and update the text.

I have rewritten the manpage on the `main` branch and already corrected your issue. The [new manpage](https://github.com/Exiv2/exiv2/blob/main/exiv2.md) is almost compatible with the `0.27.5` release (see the [history](https://github.com/Exiv2/exiv2/commits/main/exiv2.md) for differences) but contains more corrections, information and examples. It is also written in markdown which is much easier to use. You can find the `--rename fmt` flag documented [here](https://github.com/Exiv2/exiv2/blob/main/exiv2.md#rename_fmt).

**Comment by frohro** [comment]
Thank you!
Rob

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
