### ISSUE TITLE
0.27.5: broken doxygen detection

### ISSUE THREAD

**Issue by kloczek** [Exiv2/exiv2#2310]
##### **Describe the bug**
Looks like doxygen detection is failing.
cmake prints contradicting mesaages that it found doxygen anbd than it fails.
```console
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Doxygen (missing: dot) (found version "1.9.4")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindDoxygen.cmake:646 (find_package_handle_standard_args)
  cmake/generateDoc.cmake:7 (find_package)
  CMakeLists.txt:72 (include)
```

**Comment by piponazo** [comment]
I just tried and it works as expected.

Not that the error message is telling you: 

  Could NOT find Doxygen (**missing: dot**) (found version "1.9.4")

The message is a bit misleading. But what it is happening is that doxygen is being found, but you are missing the `dot` command which comes with `graphviz`.  If you install `graphviz` and run cmake again, the configuration should finish successfully.

Please let me know if this suggestion solves your problem, so that I can close this issue.

**Comment by kloczek** [comment]
I've checked with below patch
```patch
--- a/cmake/generateDoc.cmake
+++ b/cmake/generateDoc.cmake
@@ -4,7 +4,7 @@
 # target "doc" allows building the documentation with doxygen/dot on WIN32, Linux and Mac
 #

-find_package(Doxygen REQUIRED dot)
+find_package(Doxygen REQUIRED)

 macro(generate_documentation DOX_CONFIG_FILE)
     if(NOT EXISTS "${DOX_CONFIG_FILE}")
```
And looks like `dot` is not used enywhere.

**Comment by kloczek** [comment]
OK closing.
Looks like I have some issues with packages depenedencies.
Funny that doxygen uses dot but it only prints warnings.

**Comment by piponazo** [comment]
It is used. If you take a look in `cmake/Doxyfile.in` you will see in line 2140 the following:

```
# If the CLASS_DIAGRAMS tag is set to YES, doxygen will generate a class diagram
# (in HTML and LaTeX) for classes with base or super classes. Setting the tag to
# NO turns the diagrams off. Note that this option also works with HAVE_DOT
# disabled, but it is recommended to install and use dot, since it yields more
# powerful graphs.
# The default value is: YES.

CLASS_DIAGRAMS         = YES
```

It is not a strong requirement but it generates better graphs. AFAIK, we use it to generate a nice documentation for our webpage.
