### ISSUE TITLE
Canon EF 75-300 II USM named as original 75-300 USM. Canon EF 75-300 III named as original 75-300.

### ISSUE THREAD

**Issue by PeterWem** [Exiv2/exiv2#2351]
![Canon75-300-comparsion](https://user-images.githubusercontent.com/34200649/189512059-23b489cb-fe95-436b-9725-c339d65e734b.png)

Exiv2 matches wrong lens with wrong LensType for Canon EF 75-300mm f/4-5.6 II USM and Canon EF 75-300mm f/4-5.6 III.

#### **To Reproduce**
Sample raw files CC0 license.
https://drive.google.com/file/d/12g3ojYJHGT9awSICqBDmuY5AYxQm8RTw/view?usp=sharing
![Lenstype200-and-39](https://user-images.githubusercontent.com/34200649/189512082-48c3f20f-8121-4b9b-b49a-a94135793f6f.png)

#### **Expected behavior**
LensType 200 should be Canon EF 75-300mm f/4-5.6 II USM
https://global.canon/en/c-museum/product/ef326.html

LensType 39 should be Canon EF 75-300mm f/4-5.6 III
https://global.canon/en/c-museum/product/ef349.html

#### **Desktop (please complete the following information):**
exiv2 version 0.27.5
Ubuntu 20.04

**Comment by PeterWem** [comment]
What I find strange is that an older LensType nr, 39, is used for a lens from 1999 and nr 200 is used for a lens from 1995.

**Comment by PeterWem** [comment]
An update. A user who ones Canon EF 75-300mm f/4-5.6 II posted raw files. Also LensType 39. So at least EF 75-300mm f/4-5.6 II and EF 75-300mm f/4-5.6 III share the same LensType.

**Comment by kmilos** [comment]
FYI, the original labels I guess come form https://exiftool.org/TagNames/Canon.html where there is indeed aliasing present.
