### ISSUE TITLE
Lens Recognition HD PENTAX-DA* 11-18mm F2.8 ED DC AW

### ISSUE THREAD

**Issue by tuxfanx** [Exiv2/exiv2#2388]
#### **Is your feature request related to a problem?**
no automatic lens detection by lensfun / darktable 4.0.1 possible (lens type unknown)
`exiv2 -pt HD_PENTAX-DA++_11-18mm_F2.8_ED_DC_AW--11mm--5.6.DNG | grep -i lens 
Exif.PentaxDng.LensType                      Byte        4  Unknown (0x08c4)
Exif.PentaxDng.LensInfo                      Undefined 128  0 168 240 80 0 196 0 ...`

#### **Describe alternatives you have considered**
exiftool output:
`exiftool HD_PENTAX-DA++_11-18mm_F2.8_ED_DC_AW--11mm--5.6.DNG | grep -i lens
Lens Type                       : HD PENTAX-DA* 11-18mm F2.8 ED DC AW
Lens F Stops                    : 8.5
Lens Focal Length               : 11.2 mm
Lens ID                         : HD PENTAX-DA* 11-18mm F2.8 ED DC AW
`
#### **Desktop**
- Linux Debian bullseye 
- Exiv2 version 0.27.5
- lensfun / darktable 4.0.1

#### **sample raw pictures**
[find Raw sample pictures here under lenses / Pentax](https://www.dpreview.com/sample-galleries?category=lenses&sort=byBrandsAlphabetically)

**Comment by kmilos** [comment]
Indeed this ID seems to be missing from https://github.com/Exiv2/exiv2/blob/main/src/pentaxmn_int.cpp

Patches are welcome.

In the meantime, can be worked around as usual using the [config file](https://exiv2.org/manpage.html#lbAM).
