### ISSUE TITLE
Installing Exiv2 on Windows with Chocolatey

### ISSUE THREAD

**Issue by victorhqc** [Exiv2/exiv2#2411]
#### **Is your feature request related to a problem?**
No

#### **Describe the solution you would like**
As a Windows user, would be nice to find the library in [chocolatey](https://community.chocolatey.org/packages?q=exiv2) similar to how it can be found on [brew](https://formulae.brew.sh/formula/exiv2#default) for MacOSX.

Having it in a package manager would make it simpler to install in automated pipelines like Github Actions for example.

#### **Describe alternatives you have considered**
- Manually downloading each version with curl or similar, but where's the fun in that? 😄 

#### **Desktop**
- OS and version: Windows 10, Window 11
- Exiv2 version and source: any
- Any software using exiv2 and source: -

#### **Additional context**
- https://community.chocolatey.org

**Comment by kmilos** [comment]
Ok, please file a request w/ Chocolatey then.
