### ISSUE TITLE
Update to latest conan version and solve issues

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#243]
We have been observing some issues in the CI jobs with conan on different platforms:

https://travis-ci.org/piponazo/exiv2/jobs/355986434
https://travis-ci.org/piponazo/exiv2/jobs/355986435

We need to update to the latest conan version, updates the recipe versions (if needed) and try to make stable the CI jobs again.

**Comment by D4N** [comment]
Guess we can close this then?

**Comment by piponazo** [comment]
Yes!
