### ISSUE TITLE
Sony image show "corrupted image metadata"

### ISSUE THREAD

**Issue by YNBTools** [Exiv2/exiv2#2435]
#### **Describe the bug**
Running the latest version of the library, some photos are read incorrectly, and the following prompt appears:"corrupted image metadata"
![2_ZP_A1_DSC00009](https://user-images.githubusercontent.com/32679861/207208457-5eed506a-1df3-4b93-a641-529c345fd6a4.JPG)

#### **To Reproduce**
After debugging, in this sentence: 
`image->readMetadata();`

#### **Expected behavior**
Other software reads normally. I don't think the judging conditions are too strict. I hope to fix this bug. Exiv2 is very easy to use. I hope I can continue to use it.

#### **Desktop (please complete the following information):**
- OS and version: (Windows 10 )
- Exiv2 version and source: (e.g., 0.27.5 from exiv2.org)
- Compiler and version: (MSVC 2022)

#### **Additional context**
I tried to fix it with magicexif, but the problem still exists.

**Comment by kmilos** [comment]
Seems to be working ok on both `0.27-maintenance` and `main` branches.

**Comment by YNBTools** [comment]
exiv2-0.27.5-2019msvc64 and NuGet StoneSteps.Exiv2.VS2022.Static 0.27.5.5 ，All are returned with this "corrupted image metadata" error.
my OS is windows 10.Is there any support file missing from my system?
![image](https://user-images.githubusercontent.com/32679861/207271743-9304302b-8437-49d4-b21d-418091f718b9.png)

**Comment by kmilos** [comment]
See https://github.com/Exiv2/exiv2/issues/1881#issuecomment-1114261989

As said, this issue is known and fixed.
