### ISSUE TITLE
Ubuntu CI fails PRs.

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#2438]
#### **Describe the bug**
CI fails PRs.  For example: #2437

#### **To Reproduce**
Submit a PR with trivial non-code change (for example change a document).  CI will fail the Ubuntu builds

#### **Expected behavior**
CI Should succeed.

#### **Desktop (please complete the following information):**
This issue is on the CI, so no Desktop is involved.

#### **Additional context**
Example:
https://github.com/Exiv2/exiv2/actions/runs/3730282452/workflow

The error message is <pre>-- Set runtime path of "/home/runner/work/exiv2/exiv2/build-base_linux/install/bin/geotag" to "$ORIGIN/../lib"
[94]install  [error opening dir]</pre>

I believe this message is generated by the following code in the workflow file:
<pre>
      - name: Install
        run: |
          cd build
          cmake --install . 
          tree install  <--- error generated here
</pre>

**Comment by clanmills** [comment]
I believe this is related to change d2083b3190111cfac142245b36cf363719dacb8e which removed `-DCMAKE_INSTALL_PREFIX=install` from the `cmake` command and results in <pre>tree install</pre>correctly failing to find the directory `install`.

IIRC, `tree` was used help debug build issues and can be safely removed from the workflow script.

Having satisfied my curiosity about the cause, I'm not going to submit a PR/fix.

**Comment by clanmills** [comment]
I appear to have insufficient privileges:

```
refusing to allow an OAuth App to create or update workflow `.github/workflows/on_PR_linux_matrix.yml` without `workflow` scope
```

```bash
559 rmills@rmillsmm-local:/Volumes/rmills/gnu/github/exiv2/main $ git push origin fix_2438_ci_ubuntu
Enumerating objects: 27, done.
Counting objects: 100% (27/27), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 419 bytes | 0 bytes/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: This repository moved. Please use the new location:
remote:   https://github.com/Exiv2/exiv2.git
To https://github.com/exiv2/exiv2
 ! [remote rejected]   fix_2438_ci_ubuntu -> fix_2438_ci_ubuntu (refusing to allow an OAuth App to create or update workflow `.github/workflows/on_PR_linux_matrix.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/exiv2/exiv2'
560 rmills@rmillsmm-local:/Volumes/rmills/gnu/github/exiv2/main $ 
```

**Comment by piponazo** [comment]
Hi Robin! Happy to see you here. 

I think you have correctly identified where the error more or less lies, although I am not sure why this started to happen suddenly. I´ll take a look at it.

By the way, by looking to your last console snippet, it looks like you might be pointing to an old remote:
```
remote: This repository moved. Please use the new location:
remote:   https://github.com/Exiv2/exiv2.git
```

Do you have something like this when you run `git remote -v`?
```
git remote -v
origin  git@github.com:Exiv2/exiv2.git (fetch)
origin  git@github.com:Exiv2/exiv2.git (push)
```

**Comment by clanmills** [comment]
@piponazo Merry Christmas and Best Wishes for 2023.

I edited .git/config without success.  Maybe I should pull down a fresh copy of the code from `github.com:Exiv2/exiv2.git.`

Using the command line isn't easy, as `github.com` does not accept passwords.

**Comment by postscript-dev** [comment]
@clanmills
Merry Christmas Robin.
> I appear to have insufficient privileges:

I don't know if this is helpful but when I had OAuth problems in the past, it was because my token was expired or improperly configured.

**Comment by clanmills** [comment]
@piponazo Thanks.  I see you've dealt with this (and many other matters) in #2439.  That's wonderful.  I can go back to my music and leave you to deal with the code.

So I wish you and everybody a Peaceful and Prosperous 2023.
