### ISSUE TITLE
ImageFactory::open() throws error in windows forms, but not command line

### ISSUE THREAD

**Issue by SciFlyGal** [Exiv2/exiv2#2456]
#### **Describe the bug**
I am writing a piece of software with Visual Studio 2022 to read and possibly manipulate exif data for a folder full of photos. I have been having a problem with the EXIV2::ImageFactory::open("filename"); function. 

The program compiles properly, but when I try to run the routine that opens photos in a folder it gives the error
System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'

Looking at the locals feature shows that the filename is correct. The only errors show upin the image type under _Myptr, there are <memory read error>s for 
_init
PixelWidth_
PixelHeight_
  | imageType_ | <Unable to read memory> |  
  | supportedMetadata_ | <Unable to read memory> |  
  | writeXmpFromPacket_ | <Unable to read memory> |  
  | byteOrder_ | <Unable to read memory> |  

I first ported the software into windows as a command line program. I had a similar problem when compiling in debug mode, switching to release mode fixed it. Switching to release didn't work in my windows forms version. Is there some sort of .NET compatibility issue?   

#### **To Reproduce**
The full code is quite long, the routine that loads the photos is below:

int uptake(vector<EANphoto>& output, string inputfolder, string outputfolder) {
		EANphoto dummyvec;
		DIR* dr;
		int j, inum;
		double hour, minute, second;
		struct dirent* en;
		const char* incomline = inputfolder.c_str();
		/*char* comline;
		stringstream ssline;

		ssline << inputfolder;
		ssline >> comline;*/

		dr = opendir(incomline);
		std::string path1(inputfolder);
		std::string path2(outputfolder);
		dummyvec.GPSAlt = 0.0; dummyvec.GPSDirection = 0.0; dummyvec.GPSLat = 0.0; dummyvec.GPSLong = 0.0;
		j = 0;
		if (dr) {
			while ((en = readdir(dr)) != NULL) {
				std::string dummyname(en->d_name);
				//cout<<dummyname<<endl;
				if (dummyname.substr(0, 1) != ".") {
					if (dummyname.substr(strlen(en->d_name) - 4, 4) == ".JPG") {
						dummyvec.inputname = path1 + "\\" + dummyname;
						dummyvec.outputname = path2 + "\\" + dummyname;
						//cout << en->d_name << '\t' << strlen(en->d_name) << '\t';
						j += 1;
						const char* filename = dummyvec.inputname.c_str();
						Exiv2::Image::AutoPtr image;
						image= Exiv2::ImageFactory::open(filename);
						assert(image.get() != 0);
						image->readMetadata();
						Exiv2::ExifData& exifData = image->exifData();

						Exiv2::ExifData::const_iterator end = exifData.end();
						for (Exiv2::ExifData::const_iterator i = exifData.begin(); i != end; ++i) {
							const char* tn = i->typeName();
							if ((i->key() == "Exif.Image.DateTime") || (i->key() == "Exif.GPSInfo.GPSLatitude") || (i->key() == "Exif.GPSInfo.GPSLongitude") || (i->key() == "Exif.GPSInfo.GPSTimeStamp") || (i->key() == "Exif.GPSInfo.GPSDateStamp")) {
								std::string dummystr(i->toString());
								std::cout
									<< std::dec << i->toString()
									<< "\t";
								if (dummystr.empty()) { cout << "empty" << '\t'; }
							}
							if ((i->key() == "Exif.GPSInfo.GPSAltitude")) {
								std::string dummystr(i->toString());
								//cout<<dummystr.length()<<'\t';
								dummyvec.GPSAltRaw = dummystr;
								dummyvec.GPSAlt = altparse(dummystr);
							}
							if ((i->key() == "Exif.GPSInfo.GPSImgDirection")) {
								std::string dummystr(i->toString());
								cout << dummystr.length() << '\n';
								dummyvec.GPSDirectionRaw = dummystr;
								dummyvec.GPSDirection = numparse(dummystr);
							}
							if ((i->key() == "Exif.GPSInfo.GPSLatitudeRef")) {
								std::string dummystr(i->toString());
								//cout<<dummystr.length()<<'\t';
								dummyvec.GPSLatRefRaw = dummystr;
								if (dummystr == "N") { dummyvec.GPSLatRef = 1.0; }
								else if (dummystr == "S") { dummyvec.GPSLatRef = -1.0; }
							}
							if ((i->key() == "Exif.GPSInfo.GPSLongitudeRef")) {
								std::string dummystr(i->toString());
								//cout<<dummystr.length()<<'\t';
								dummyvec.GPSLongRefRaw = dummystr;
								if (dummystr == "E") { dummyvec.GPSLongRef = 1.0; }
								else if (dummystr == "W") { dummyvec.GPSLongRef = -1.0; }
							}
							if ((i->key() == "Exif.Image.DateTime")) {
								std::string dummystr(i->toString());
								dummyvec.CameraTimeRaw = dummystr;
								dummyvec.CameraTimeParsed = colonparseT(dummystr.substr(11, 8));

							}
							if ((i->key() == "Exif.GPSInfo.GPSTimeStamp")) {
								std::string dummystr(i->toString());
								dummyvec.GPSTimeRaw = dummystr;
								dummyvec.GPSTimeParsed = posparseT(dummystr, hour, minute, second);
								dummyvec.GPSTimeUseable.hour = hour;
								dummyvec.GPSTimeUseable.minute = minute;
								dummyvec.GPSTimeUseable.second = second;
							}
							if ((i->key() == "Exif.GPSInfo.GPSLatitude")) {
								std::string dummystr(i->toString());
								dummyvec.GPSLatRaw = dummystr;
								dummyvec.GPSLat = posparse(dummystr);

							}
							if ((i->key() == "Exif.GPSInfo.GPSLongitude")) {
								std::string dummystr(i->toString());
								dummyvec.GPSLongRaw = dummystr;
								dummyvec.GPSLong = posparse(dummystr);

							}
							if ((i->key() == "Exif.GPSInfo.GPSDateStamp")) {
								std::string dummystr(i->toString());
								dummyvec.GPSDateRaw = dummystr;

							}
						}
						//cout<<dummyvec.GPSLong<<'\t';
						dummyvec.GPSLat = dummyvec.GPSLat * dummyvec.GPSLatRef;
						dummyvec.GPSLong = dummyvec.GPSLong * dummyvec.GPSLongRef;
						//cout<<dummyvec.GPSLong<<'\t';
						dummyvec.targetTag = 0;
						dummyvec.colorTag = 0;
						dummyvec.DataType = 0;
						//cout << endl;
						output.push_back(dummyvec);
					}
				}

			}
			closedir(dr);
		}
		return j;
	}

It is called via

private: System::Void button3_Click(System::Object^ sender, System::EventArgs^ e) {
	int ib3;

	std::string in1 = msclr::interop::marshal_as<std::string>(textBox1->Text);
	std::string out1 = msclr::interop::marshal_as<std::string>(textBox2->Text);
	nphot=EAN::uptake(photoData, in1, out1);
	for (ib3 = 0;ib3 < nphot;ib3++) {
		dataGridView1->Rows->Add(ib3, photoData[ib3].CameraTimeParsed, photoData[ib3].GPSLat, photoData[ib3].GPSLong, photoData[ib3].GPSAlt, photoData[ib3].GPSDirection);
	}

#### **Expected behavior**
I expected the routine to move through the photos in a folder and read the metadata into a custom struct I wrote.

#### **Desktop (please complete the following information):**
- OS and version: Windows 10, MSVS 2022

#### **Additional context**
Add any other information about the problem here.

**Comment by postscript-dev** [comment]
@SciFlyGal 
I don't work specifically with .net so can be of limited help with that. I have a couple of thoughts though:
1. Although your file exists, it is worth checking that it contains well formed image data that Exiv2 can read. One way of testing this is to use the exiv2 app (available from https://exiv2.org/download.html). The following command will list all the tags available in a file:
```shell
$ exiv2 --print a filename
```
The [manpage](https://github.com/Exiv2/exiv2/blob/main/exiv2.md) on the `main` branch contains more information and is almost the same as the `0.27.5` version of the app.
2. Which version of Exiv2 are you using? If you do not know, you can display this with:
```shell
$ exiv2 --version
```
The latest release is [0.27.5](https://exiv2.org/download.html).
3. It is difficult to know why Exiv2 is failing without a specific error message. Is it possible to let us know what error Exiv2 is throwing? I am assuming that it is thrown by the line `EXIV2::ImageFactory::open("filename");`.

I don't know if it is helpful but alternatively, you could use the exiv2 app to read/write the metadata of files in a directory.

**Comment by SciFlyGal** [comment]
I have an update. In the project properties menu, under "configuration Properties"> "Advanced" if i disable debug libraries then it compiles and runs fine. The Visual Studio debug libraries seem to dislike the ImageFactory::open() function. It's a partial fix since I can move forward, but won't have debugging tools.

**Comment by postscript-dev** [comment]
@SciFlyGal 
As I said, I don't know much about .net . To output the Exiv2 exception, try changing

```cpp
image= Exiv2::ImageFactory::open(filename);
```

to

```cpp
try {
  image= Exiv2::ImageFactory::open(filename);
}
catch (Exiv2::Error& e) {
  std::cout << "Caught Exiv2 exception: '" << e.what() << std::endl;
  return -1;
}
```

**Comment by clanmills** [comment]
@SciFlyGal I suspect the issue involves linking the C runtime library with your built version of Exiv2.  Windows has 4 runtime libraries /MT /MTd /MD and /MDd.  In the good old days of MFC (I'm retired), the project Wizard would set everything up so it's effortless to switch.  CMake is less kind.  You have to build the Exiv2 libraries into different directories and manually adjust the linkage for your project.

When I retired last year, I cleaned up my Windows machine and uninstalled Visual Studio 2017 and 2019.  Windows refused to install VS 2022 Community on my Windows 10.

If you can screen share (on Zoom or something), I'll be happy to inspect your setup and together, we'll get this to work.

**Comment by piponazo** [comment]
I also thought the same as @clanmills , it must be a problem with the windows runtime libraries. @SciFlyGal From where did you get the exiv2 libraries? Did you compile them by yourself from the source code? Did you take some release from our github? Let us know which version you are using. Note that we only provide pre compiled binaries in Release mode. If you want to be able to debug your software, you'll probably need to compile exiv2 by yourself in Debug mode.

**Comment by clanmills** [comment]
@SkyFlyGal.  I'm surprised you have yet to respond to my suggestion and offer to help.  I'm going to close this issue.
