### ISSUE TITLE
darktable fails to compile on Fedora37 with the latest exiv2

### ISSUE THREAD

**Issue by lintujuh** [Exiv2/exiv2#2459]
#### **Describe the bug**
Compiling darktable on Fedora37 fails on error 'AnyError' doesn't have a type

#### **To Reproduce**
1. Build darktable with the standard build script with the latest exiv2 files
2. 
```
/home/LintuJuh/darktable/src/common/exif.cc: In function ‘void dt_exif_set_exiv2_taglist()’:
/home/LintuJuh/darktable/src/common/exif.cc:290:17: error: ‘AnyError’ in namespace ‘Exiv2’ does not name a type
  290 |   catch (Exiv2::AnyError& e)
      |                 ^~~~~~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:460: bin/CMakeFiles/lib_darktable.dir/common/exif.cc.o] Error 1
```

#### **Expected behavior**
Compile and build without errors

#### **Desktop (please complete the following information):**
- Fedora 37
- Exiv2 version and source: 1.0.0.9 from git
- Compiler and version: gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)

#### **Additional context**
Issue also created in darktable (https://github.com/darktable-org/darktable/issues/13304)

**Comment by kmilos** [comment]
dt does not compile w/ C++17, use the 0.27-maintenance branch.
