### ISSUE TITLE
No source tarball available for 0.27.6

### ISSUE THREAD

**Issue by diizzyy** [Exiv2/exiv2#2469]
Website --> https://exiv2.org/builds/exiv2-0.27.6-Source.tar.gz --> 404
No attached to release "tag" on GitHub

**Comment by kevinbackhouse** [comment]
It looks like you have the wrong url. You can get tarballs from either of these locations:

* https://exiv2.org/download.html
* https://github.com/Exiv2/exiv2/releases/tag/v0.27.6

**Comment by diizzyy** [comment]
Someone updated URL on main site and added it to GitHub, anyway fixed now.
