### ISSUE TITLE
Can not build with Ninja on MSVC

### ISSUE THREAD

**Issue by emmenlau** [Exiv2/exiv2#248]
I'd like to use Ninja (https://ninja-build.org/) as a highly parallel cross platform build backend with exiv2. It works well on MacOSX and Linux, but fails on MSVC with error:
```
-- Configuring done
-- Generating done
-- Build files have been written to: D:/tmp-MSVC-Generic-7-x64-cl19.00.24210/Debug/Shared/exiv2-0.26-x64
ninja: error: build.ninja:857: bad $-escape (literal $ must be written as $$)
  LINK_PATH = -LIBPATH:\$(ConfigurationName)

                        ^ near here
make[1]: *** [MSVC/Makefile.BDA.MSVC.exiv2:19: /d/artifacts-MSVC-Generic-7-x64-cl19.00.24210/Debug/Shared/include/exiv2/exiv2.hpp] Error 1
make[1]: Leaving directory '/d/gitlabci/local/builds/e59b7d05/0/BDAThirdparty'
make: *** [Makefile.BDA:49: debug] Error 2
clear: terminal attributes: No such device or address
```
Its not a super high priority, but would be great to have Ninja support.

**Comment by clanmills** [comment]
Thanks for reporting this.  I've heard of ninja because it's one of the Generator options in CMake.  I've never used it.  A couple of questions:

1) Have you any idea of the origin of this `LINK_PATH/LIBPATH` mystery?  It doesn't appear to come from an existing .vcproj, Makefile or CMakeLists.txt file.

2) The surest way to get something done in open-source is to submit a PR with the fix.  Would you like to join the team to contribute Ninja support?

**Comment by emmenlau** [comment]
Dear @clanmills , thanks for the quick response!

1. I'm sorry but I also do not know the `LINK_PATH/LIBPATH`, and AFAIK its not something I intentionally set. I just checked and found that `LIBPATH` is an environment variable that the Visual Studio build environment seems to define, but there is no `$` sign present there.

2. I'd be happy to contribute a fix but I don't have the slightest idea what to look for or how to continue. Also google does not really return anything. If you don't mind then its also fine for me to leave this issue dangling until someone else can provide more insight?

**Comment by D4N** [comment]
@emmenlau We use ninja to build exiv2 on Appveyor. You might be able to gain some insight from the `appveyor.yml` config file in exiv2's root directory.

**Comment by clanmills** [comment]
Gentlemen.  I'll have a look at this afternoon.  We're discussing CMake with ninja for Visual Studio and running from a Cygwin/bash shell.  Ummmm.  How would it know the version of Visual Studio (2005/8/10/12/13/15/17)?

Dan's tip concerning appveyor is interesting.  I think Luis set that up.

Here's what I have on Cygwin/bash:
```
501 rmills@rmillsmbp-w7:~ $ cmake --version
cmake version 3.9.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
502 rmills@rmillsmbp-w7:~ $ cmake --help | grep -i ninja
  Ninja                        = Generates build.ninja files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
503 rmills@rmillsmbp-w7:~ $ cmake --help | grep -i visual
504 rmills@rmillsmbp-w7:~ $
$ 
```
And on Windows 10:
```
C:\WINDOWS\system32>cmake --version
cmake version 3.9.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).

C:\WINDOWS\system32>cmake --help | grep -i visual
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
  Visual Studio 8 2005 [arch]  = Deprecated.  Generates Visual Studio 2005
C:\WINDOWS\system32>cmake --help | grep -i ninja
  Ninja                        = Generates build.ninja files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.

C:\WINDOWS\system32>
```

Let me see what I can achieve with this after lunch (it's 12:52 here in England).

**Comment by emmenlau** [comment]
It would be super great if you can give it a spin, but beware that my setup is indeed slightly special:

 - cmake should be the official binary from http://www.cmake.org
 - The Cygwin bash shell has to be started from a Visual Studio command prompt to define the build environment. Just start it from the command prompt with `bash --login`
 - To avoid confusion of `cmake`, move the PATH entries from Cygwin to the end of the PATH. This way, the Visual Studio build tools preceede the Cygwin commands of similar name (mostly `link.exe`).

Then you should be all set to run `cmake -G"Ninja"` and then `ninja`.

**Comment by emmenlau** [comment]
But on second thought, please don't spend too much time on this issue! Its at least possible that the issue is unique to this special setup, and if its unique to me then I'd prefer not to waste anyones time!

**Comment by clanmills** [comment]
Ah, you've sparked my interest.  I think the cmake/ninja generator must be use the environment strings initialised by vcvars32.bat.  I can't see how else it c ould know the version of Visual Studio.

Using the cygwin/bash is a challenge.  Our buildserver is a cygwin/bash script and has the magic code:
```
        PATH=$PATH:/cygdrive/c/Windows/System32
        cmd.exe /c "cd $(cygpath -aw .) && call contrib\\buildserver\\jenkins_build.bat"
``` 

This fires up cmd.exe to execute a dos .bat file which initialises the CL/environment and gets devenv.exe to perform the build.  I'm _**fairly**_ confident that we'll find a way to achieve your goal.

Let me see what I discover and get back to you.  I go running at 6pm with my run group.  If I haven't fixed this by 5pm, you can take up the challenge after that.

**Comment by clanmills** [comment]
Loads of issues.  On cmd.exe, I get:
```
C:\Users\rmills\gnu\github\exiv2\exiv2\build>call ..\contrib\cmake\msvc\vcvars.bat 2017 64
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26430.16
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Users\rmills\gnu\github\exiv2\exiv2\build>cmake --version
cmake version 3.10.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

C:\Users\rmills\gnu\github\exiv2\exiv2\build>cmake .. -G Ninja
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/rmills/gnu/github/exiv2/exiv2/build/CMakeFiles/CMakeOutput.log".

C:\Users\rmills\gnu\github\exiv2\exiv2\build>
```

On cygwin/bash something similar:
```
515 rmills@rmillsmbp-w7:/c/users/rmills/gnu/github/exiv2/exiv2/build $ cmake ..                                   -G Ninja
CMake Error: CMake was unable to find a build program corresponding to "Ninja".                                    CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build t                                  ool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
516 rmills@rmillsmbp-w7:/c/users/rmills/gnu/github/exiv2/exiv2/build $
```

I googled into this and found this:  https://stackoverflow.com/questions/6141608/cmake-make-program-not-found

I'm not sure why you are bothering with this.  There are other ways to build Exiv2 and we've never claimed to support CMake/Ninja on any platform.  I'm glad it's working for you on MacOS-X and Linux.

**Comment by piponazo** [comment]
Hi! I am not sure if this could be an issue with Cygwin (I have never used it) but for me it works fine in normal command prompts or the power shell. This is how I do it:

```
1. Call my vs2017.bat script to setup the Visual Studio environment. Content:

----------------
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
----------------

cd $PATH_TO_EXIV2
mkdir build
cd build
conan install .. --profile msvc2017Release # Optional
cmake -GNinja ..
ninja
```
And everything works like a charm. 

@emmenlau If these steps do not help you, please tell me exactly the version of cygwin, cmake and Visual Studio that you are using, and exactly the commands that you are running, and I will try to help you 😉

**Comment by emmenlau** [comment]
Dear @clanmills and @piponazo , thanks a lot for digging into this. I think it may really not make sense to go any deeper, I will close the issue. When I find some spare time I will check the Ninja build file to see why it pulls in an unresolved `\$(ConfigurationName)` variable.

But lets not worry about it now, I can build exiv2 with jom and thats fine too!

**Comment by emmenlau** [comment]
PS: I will reopen this issue when I find the underlying cause :-)
