### ISSUE TITLE
video support

### ISSUE THREAD

**Issue by keybraker** [Exiv2/exiv2#25]
I run `./configure`, but the output is not video supported, how can i fix this ?

`------------------------------------------------------------------`
`-- Exiv2 0.26 feature configuration summary`
`--`
`-- Build a shared library......... YES`
`-- Use symbol visibility support.. YES`
`-- PNG image support.............. YES`
`-- Native language support........ NO`

`gettext is required for native language support. Make sure the`
`gettext header files and utilities are installed. `
`You can get gettext from http://www.gnu.org/software/gettext/`

`-- Nikon lens database............ YES`
`-- XMP metadata support........... YES`
`-- Video support.................. NO`
`-- Webready support............... NO`
`------------------------------------------------------------------`

**Comment by clanmills** [comment]
Com'on buddy.  Please don't bounce every question to me.  The ./configure script is warning you that NLS (natural language support) has been disabled because you don't have the gettext library available.  However, it will build if you type:
```
$ make
$ sudo make install
$ make samples
```

There are several ways to deal with gettext not being available:

1) Install gettext using MacPorts:
```
$ sudo port install gettext
```
or
2) Build without NLS (natural language support)
```
./configure --disable-nls
```
or
3) Download the gettext source code and build/install it.

**Comment by clanmills** [comment]
To inspect build options:
```
$ ./configure --help
```

To enable video:
```
$ ./configure --enable-video
```

**Comment by keybraker** [comment]
Thank you an sorry for the Spam but it is a little overwhelming.. 

_Sent from my HUAWEI PRA-LX1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by clanmills** [comment]
The build environments for Exiv2 (autotools, CMake and Visual Studio) are typical of open-source projects.  When you know those tools, you can build most projects easily.  However, there is a learning curve.  There are tools (such as Mac Ports for MacOSX and apt for Linux) which hide details.  However, open-source is source.  This is not the world of shrink-wrapped software (such as Adobe PhotoShop or Microsoft Word).  Projects such as Exiv2 are intended for use by other open-source warriors and regretfully you'll stumble while you learn.

If you continue to encounter issues, please agree on a time when we can collaborate on FaceTime.  30 minutes together will be quicker and more effective/efficient than a series of issue reports.

**Comment by keybraker** [comment]
Ok my friend thank you very much again and kudos for an incredible project! 

_Sent from my HUAWEI PRA-LX1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
