### ISSUE TITLE
exiv2 outputs non utf-8 characters

### ISSUE THREAD

**Issue by D4N** [Exiv2/exiv2#251]
When I was porting redmine issue 444 from the old to the new test suite, I always got an error from python that it could not decode the output as utf-8. The issue can be reproduced via:
```
$ exiv2 -u -pi test/data/exiv2-bug444.jpg
Iptc.Envelope.CharacterSet                   String      4  �
Iptc.Application2.Urgency                    String      2  GT
Iptc.Application2.SuppCategory               String      8  portrait
Iptc.Application2.Caption                    String     18  Witty caption here
Iptc.Application2.Keywords                   String      3  ize
Iptc.Application2.0x007b                     String      4  n123
```
The output of the first line depends on the terminal used. `st` and `xterm` show the `�` symbol, `st+tmux` shows nothing and `urxvt` shows `Ä`.

The issue is, that for certain metadata types exiv2 just forwards all binary contents to stdout, which can contain non-utf-8 characters.

Maybe we should add a utf-8 strict mode, that will upon encountering of invalid characters output them as hex numbers instead?

**Comment by clanmills** [comment]
Dan:  I don't think we need to port all of this.  The v0.26 version is safely stored on SVN and can be downloaded on-demand.  I'll take on the chore of porting the gXX issues to the new test suite.  We're off on a trip to Wales this week to celebrate our 44th Wedding Anniversary on Tuesday 27 March.  I'll start work on this after Easter when I'm home.

**Comment by D4N** [comment]
Don't worry about the gXX issues, they are taken care off by #249. The redmine issues on the other hand are a different story.

**Comment by clanmills** [comment]
This is outstanding work, Dan.  A miracle.  Thanks very much.

We can download the redmine/svn test resources on demand.  There's no need to keep any of that on GitHub and we can obliterate test/bugfixes-test.sh and test/data/test-bugfixes.out to reduce the size of the repos.   Occasionally we will need to update those files on svn without adding a byte to GitHub.

**Comment by piponazo** [comment]
Just for completion. On windows I get this (using git-bash on a powershell):

```
$ bin/exiv2 -u -pi ../test/data/exiv2-bug444.jpg
Iptc.Envelope.CharacterSet                   String      4   ─
Iptc.Application2.Urgency                    String      2  GT
Iptc.Application2.SuppCategory               String      8  portrait
Iptc.Application2.Caption                    String     18  Witty caption here
Iptc.Application2.Keywords                   String      3  ize
Iptc.Application2.0x007b                     String      4  n123
```
I am trying to determine where we are printing those lines in the code to determine how difficult it would be what @D4N proposed in the description.

**Comment by piponazo** [comment]
I have been debugging the app and this is the block of code printing those bytes:

```
        if (Params::instance().printItems_ & Params::prTrans) {
            if (!first)
                std::cout << "  ";
            first = false;
            if (Params::instance().binary_ &&
                (md.typeId() == Exiv2::undefined ||
                 md.typeId() == Exiv2::unsignedByte ||
                 md.typeId() == Exiv2::signedByte) &&
                md.size() > 128) {
                std::cout << _("(Binary value suppressed)") << std::endl;
                return true;
            }
            bool done = false;
            if (0 == strcmp(md.key().c_str(), "Exif.Photo.UserComment")) {
                const Exiv2::CommentValue* pcv = dynamic_cast<const Exiv2::CommentValue*>(&md.value());
                if (pcv) {
                    std::cout << pcv->comment(Params::instance().charset_.c_str());
                    done = true;
                }
            }
            if (!done)
                std::cout << std::dec << md.print(&pImage->exifData());  ///// THIS IS THE CULPRIT
        }
```
Does it make sense to print there the exifData() with `std::dec` ? This is the value were are trying to print there: `"\000�\034\002"`

**Comment by piponazo** [comment]
@clanmills do you actually know the meaning of `Params::prTrans` ? It is difficult to guess the meaning of that enum value by its name 😢

**Comment by clanmills** [comment]
I don't know.  Let me look.

**Comment by clanmills** [comment]
Ah yes.  "prTrans" = Translate = -pt on the command line.

```
559 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 --help | grep trans
             t : interpreted (translated) Exif data (-PEkyct)
             t : interpreted (translated) data
560 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ 
```
The type/value of a metadatum will be one of about 7 defined in the Exif standard (Byte, Undefined, Short, Rational etc).  The meaning of a metadatum is called "Translated" by Exiv2 (meaningful to a human).  Lens metadata is a good example:
```
561 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pv --grep lens/i http://clanmills.com/Stonehenge.jpg
0x0083 Nikon3       LensType                    Byte        1  14
0x0084 Nikon3       Lens                        Rational    4  180/10 2500/10 35/10 63/10
0x008b Nikon3       LensFStops                  Undefined   4  55 1 12 0
0x000c NikonLd3     LensIDNumber                Byte        1  146
0x000d NikonLd3     LensFStops                  Byte        1  55
```
And the "translated" values are:
```
562 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pt --grep lens/i http://clanmills.com/Stonehenge.jpg
Exif.Nikon3.LensType                         Byte        1  D G VR
Exif.Nikon3.Lens                             Rational    4  18-250mm F3.5-6.3
Exif.Nikon3.LensFStops                       Undefined   4  4.58333
Exif.NikonLd3.LensIDNumber                   Byte        1  Sigma 18-250mm F3.5-6.3 DC OS Macro HSM
Exif.NikonLd3.LensFStops                     Byte        1  F4.6
563 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ 
```

**Comment by clanmills** [comment]
The code is being executed in the context of the JPEG comment.
```
std::cout << std::dec << md.print(&pImage->exifData());  ///// THIS IS THE CULPRIT
```

Maybe you should report binary when done is not set.  Something like (and localise the string):
```
if ( !done ) std::cout << _N("(Binary value suppressed)") << std::endl;
```

**Comment by piponazo** [comment]
If I do that change, then the translated values for the example you showed before will turn into this:

```
21:59 $ bin/exiv2 -pt --grep lens/i /media/caviar/Stonehenge.jpg 
Exif.Nikon3.LensType                         Byte        1  (Binary value suppressed)
Exif.Nikon3.Lens                             Rational    4  (Binary value suppressed)
Exif.Nikon3.LensFStops                       Undefined   4  (Binary value suppressed)
Exif.NikonLd3.LensIDNumber                   Byte        1  (Binary value suppressed)
Exif.NikonLd3.LensFStops                     Byte        1  (Binary value suppressed)
```
I think we should do what @D4N proposed, and inspect the metadata in these cases to check whether it contains invalid UTF-8 characters. I have been googling a bit and there seems to be some ways to check if a buffer contains invalid UTF-8 characters:

http://utfcpp.sourceforge.net/
https://stackoverflow.com/questions/1031645/how-to-detect-utf-8-in-plain-c/43338168#43338168

**Comment by clanmills** [comment]
Ah!  You're right.  Bad idea.

@D4N's close to the mark.  We want to something such as:

```
if ( !done ) {
  strstream buffer ;
  buffer << std::dec << md.print(&pImage->exifData()) ;
  if ( pureUTF8(buffer.string()) ) {
    std::cout << buffer.string() << std::endl;
  } else {
    std::cout "binary output" << std::endl;
  }
}
```

**Comment by tester0077** [comment]
I have come across the very same issue for the same data field when I use my compiled version of Exiv2 - version 0.27.99.0 with the command line exiv2 -pi testfile.jpg
using the attached test file

> Iptc.Envelope.CharacterSet                   String      3  %G   <<<<<<<<<<<<<
> Iptc.Envelope.ModelVersion                   Short       1  4
> Iptc.Application2.RecordVersion              Short       1  3
> 
![Metadata_test_file_-_includes_data_in_IIM,_XMP,_and_Exif](https://user-images.githubusercontent.com/9053628/59797729-4a8c4580-9295-11e9-926d-152551f6814d.jpg)

**Comment by clanmills** [comment]
Is this a bug?  It's a problem for the test suite to deal with it, however it appears to be the data that is the file:
```
1465 rmills@rmillsmbp:~/Downloads $ exiv2 -PIv -g Character 59797729-4a8c4580-9295-11e9-926d-152551f6814d.jpg  | od -a
0000000  esc   %   G  nl                                                
0000004
1466 rmills@rmillsmbp:~/Downloads $ 
```
The IPTC data is in the APP13 "chunk" of the jpeg:
```
1476 rmills@rmillsmbp:~/Downloads $ exiv2 -pS 59797729-4a8c4580-9295-11e9-926d-152551f6814d.jpg 
STRUCTURE OF JPEG FILE: 59797729-4a8c4580-9295-11e9-926d-152551f6814d.jpg
 address | marker       |  length | data
       0 | 0xffd8 SOI  
       2 | 0xffe1 APP1  |   13260 | Exif..II*...........3..........
   13264 | 0xffed APP13 |   13200 | Photoshop 3.0.8BIM.........,....
   26466 | 0xffe1 APP1  |   28432 | http://ns.adobe.com/xap/1.0/.<?x
   54900 | 0xffdb DQT   |     132 
   55034 | 0xffdd DRI   |       4 
   55040 | 0xffee APP14 |      14 | Adobe.d.......
   55056 | 0xffc0 SOF0  |      17 
   55075 | 0xffc4 DHT   |     293 
   55370 | 0xffda SOS  
1477 rmills@rmillsmbp:~/Downloads $ 
```
And here's the raw data:
```
1482 rmills@rmillsmbp:~/Downloads $ dd bs=1 count=80 skip=$((13264+4)) if=59797729-4a8c4580-9295-11e9-926d-152551f6814d.jpg 2>/dev/null | dmpf -
       0        0: Photoshop 3.0.8B  ->  50 68 6f 74 6f 73 68 6f 70 20 33 2e 30 00 38 42
    0x10       16: IM.........,....  ->  49 4d 03 ed 00 00 00 00 00 10 01 2c 00 00 00 01
    0x20       32: ...,......8BIM..  ->  00 01 01 2c 00 00 00 01 00 01 38 42 49 4d 04 04
    0x30       48: .....Z..Z...%G..  ->  00 00 00 00 05 5a 1c 01 5a 00 03 1b 25 47 1c 01
                                                           ** ** ** = ESC 01 G
    0x40       64: ..............7.  ->  00 00 02 00 04 1c 02 00 00 02 00 03 1c 02 37 00
1483 rmills@rmillsmbp:~/Downloads $ 
```
I don't remember the spec of IPTC data, however `-pR` decodes it as:
```
$ exiv2 -pR ~/Downloads/54a8c4580-9295-11e9-926d-152551f6814d.jpg
...
   13264 | 0xffed APP13 |   13200 | Photoshop 3.0.8BIM.........,....
  Record | DataSet | Name                     | Length | Data
       1 |      90 | CharacterSet             |      3 | .%G
       1 |       0 | ModelVersion             |      2 | ..
...
```
So exiv2 is reporting exactly what's in the file.

Question: What's the problem?   I thought this issue concerned the test suite.

**Comment by tester0077** [comment]
I have just done some more digging wrt this issue, using your test image exiv2-bug444.jpg
What it looks like to me, is that in both your picture & the one I had used, the bad output comes from a Photoshop resource of the type referred to by 
_In a JPEG file, an APP13 marker with an identifier of "Photoshop 3.0" contains Photoshop Image Resources.
Resource ID 0x0404 contains IPTC data.
See http://fileformats.archiveteam.org/wiki/Photoshop_Image_Resources
From what I can see in my debugger, this section is identified properly during the reading of the file data in jpgimage.cpp lines 432 - 437
but the output for this section is incorrect if I refer to the XMP Spec part 3, page 66, section 3.1.3
The magic string "8BIM" is not followed by anything I can interpret as a character set spec.

Still, as I am unfamiliar with the logic behind the print out, I am stuck - at least for now - with this issue.

**Comment by D4N** [comment]
@tester0077 This issue was more about how the exiv2 cli utility and the library itself should handle non-utf8 encoded strings. Specifically since most metadata strings don't mandate any encoding, we are bound to dump non-utf8 characters to the user's shell (or into our test suite, which it doesn't like).

If you are experiencing a bug in the parsing of metadata, please open a new issue.

**Comment by tester0077** [comment]
After some more digging I have come to the conclusion that it is both a bug and a bad input file.
A bad input file, because, if I can trust the XMP SDK's (version 2 from the 201607 version)  tool 'dumpfile', the contents of the file are invalid for that particular data item.
Running dumpfile on the problem file gives me the following output:
  ```
..........
Photoshop Image Resources 1
      [from JPEG Photoshop APP13, offset 34925 (0x886D), size 86]
    PSIR:IPTC
    IPTC data
        [from PSIR #1028, offset 34937 (0x8879), size 74]
      IPTC:1:90
          [offset 34937 (0x8879), size 4,offset 34925 (0x886D), size 74]
      ** invalid IPTC marker **
      ** Too little IPTC data, delta -63

```
To be sure, I checked the hex contents of the file at the indicated offset around 0x8879 and the screenshot here show that it is the same area that earlier comments seemed to identify - certainly some of the adjacent strings are the very same ones.
![exiv2--bug444-hex](https://user-images.githubusercontent.com/9053628/59891588-92d95f80-938a-11e9-955b-2a779e46cb2b.jpg)
Looking a bit further to find the potential culprit who might have created the problem, I see the creator tool in my own XMP data dump as <xmp:CreatorTool>E5700v1.0</xmp:CreatorTool> which is corroborated by locating the string "E5700v1.0" in the hex dump as well - with one of the adjacent strings being 'Nikon'. Googling for this string seems to indicate that this data was possibly created by the camera itself or some other (Nikon) software. 
Going back to the image which got me started on this thread because I got a similar 'error' or problem, I find that dumpfile does identify several 8BIM sections, but none are flagged as problematic, which supports my second conclusion, the 8BIM Photoshop 3.0 sections are not identified properly.
Chasing through the exiv2 code, I have seen references to "8BIM", but I have not had a chance to take the time to analyze this any further; 

My conclusion:
- the image file used for the test is badly formatted
- the code to detect this issue within the Exiv2 code does not catch this problem.

**Comment by clanmills** [comment]
@D4N You've expressed the scope of this discussion clearly.  We are discussing what to do with non UTF8 characters in the output stream which can create difficulties for stream readers (in Dan's case implemented in python).

@tester0077 Well done to dig so deeply into this the file exiv2-bug444.jpg.  If you want to report a bug concerning that file, please open a new issue.  It is unlikely to be investigated before we release Exiv2 v0.27.2.

**Comment by D4N** [comment]
This issue is not yet resolved.

**Comment by clanmills** [comment]
I've revisited this.  The issue is unchanged in 'main'

```bash
677 rmills@rmillsm1:~/gnu/github/exiv2/main $ exiv2 -pi test/data/exiv2-bug444.jpg  | head -1 | dmpf -
       0        0: Iptc.Envelope.CharacterSet        ->  49 70 74 63 2e 45 6e 76 65 6c 6f 70 65 2e 43 68 61 72 61 63 74 65 72 53 65 74 20 20 20 20 20 20
    0x20       32:              String      4  _...  ->  20 20 20 20 20 20 20 20 20 20 20 20 20 53 74 72 69 6e 67 20 20 20 20 20 20 34 20 20 00 c4 1c 02
                                                                                                S  t  r  i  n  g                               __ ESC STX
    0x40       64: .                                 ->  0a
678 rmills@rmillsm1:~/gnu/github/exiv2/main $ 
```
The data is correct and discussed in my book.  The tag has something to do with controlling communications.  I think it's something to control a modem or the like.  It say "when you transmit this, output 0xc4 ESC STX on the line.

I don't think this matter deserves more attention.
