### ISSUE TITLE
Make a tagged release with the changes to AutoPtr -> UniquePtr

### ISSUE THREAD

**Issue by j-warren-123** [Exiv2/exiv2#2521]
PR where this is done is here: https://github.com/Exiv2/exiv2/pull/1555

Changes are in HEAD (main), but the latest tagged release is v0.27.6 which is still using `auto_ptr`

I want to use this in vcpkg in my C++20 project without needing to make the portfiles myself. The PR was merged 2 years ago, why hasn't there been a tagged release with the changes?

**Comment by kmilos** [comment]
See https://github.com/Exiv2/exiv2/issues/2406#issuecomment-1396256682 and after. @nehaljwani
