### ISSUE TITLE
Code in main does not compile on F38

### ISSUE THREAD

**Issue by 1div0** [Exiv2/exiv2#2557]
I dared to upgrade to Fedora Linux 38 β. However, Exiv2 code in main branch does not compile cleanly neither w/ GNU Compiler nor w/ LLVM based Clang++.

Please see the logs.
[Exiv2 GCC 13 F38.log](https://github.com/Exiv2/exiv2/files/11028322/Exiv2.GCC.13.F38.log)
[Exiv2 LLVM 15.0.7 F38.log](https://github.com/Exiv2/exiv2/files/11028323/Exiv2.LLVM.15.0.7.F38.log)

On F37 it was OK.

[RFC] Anyone experienced the same issue?

**Comment by kmilos** [comment]
Probably need to include cstdint (or inttypes.h if printf macros are needed as well) in types.hpp explicitly, most recent compilers got picky about it... Surprised our CI didn't pick this up already...

**Comment by kmilos** [comment]
@1div0 Please test and feedback if this change is sufficient.

**Comment by 1div0** [comment]
@kmilos hvala.

Yes, the change is sufficient to fix the compilation with GCC 13 as well as Clang 15.
