### ISSUE TITLE
Current master fails with image

### ISSUE THREAD

**Issue by neheb** [Exiv2/exiv2#2565]
#### **Describe the bug**
```
Uncaught exception: Overflow in Exiv2::DataBuf::c_data
```
#### **To Reproduce**
1. 
![20180410_182803](https://user-images.githubusercontent.com/2918873/228048969-a223928f-c6be-4104-b6a2-ef60d6315b7e.jpg)
2. just exiv2
3. 0fa22ed55d1088eacc5ef063b7307fa1b4d031e6 . This error has been here for a while though.

#### **Expected behavior**
Output

#### **Desktop (please complete the following information):**
- OS and version:Fedora 37
- Exiv2 version and source: latest master
- Compiler and version: GCC 12
- Compilation mode and/or compiler flags: -O0 and -O3

**Comment by neheb** [comment]
```
--- a/src/types.cpp
+++ b/src/types.cpp
@@ -176,7 +176,7 @@ const byte* Exiv2::DataBuf::c_data(size_t offset) const {
   if (pData_.empty()) {
     return nullptr;
   }
-  if (offset >= pData_.size()) {
+  if (offset > pData_.size()) {
     throw std::out_of_range("Overflow in Exiv2::DataBuf::c_data");
   }
   return &pData_[offset];
```

Fixes it. @kevinbackhouse does that look sensible? Both values equal 2.

**Comment by kevinbackhouse** [comment]
I thought this code looked familiar: https://github.com/Exiv2/exiv2/pull/2209#discussion_r857744958

**Comment by kevinbackhouse** [comment]
@neheb : So, yes, I'm in favor of your first suggestion (replace `>=` with `>`).

**Comment by benmccann** [comment]
@neheb do you want to send a PR to replace `>=` with `>` so that we can get 1.0 out with this fixed?

**Comment by neheb** [comment]
no because that makes the test fail.

**Comment by benmccann** [comment]
Oh! I didn't read closely enough and missed the reference to the [`tryingToAccessTooFarElementThrows`](https://github.com/Exiv2/exiv2/blob/22b12012a67509252e8a8ecea32b57df7c30200c/unitTests/test_types.cpp) test. Though that test was added in the same change that introduced the `>=`. If you look at [the comment that @kevinbackhouse linked to](https://github.com/Exiv2/exiv2/pull/2209/files#r857744958) then [the next comment](https://github.com/Exiv2/exiv2/pull/2209/files#r861506276) mentions the same thing about this test. I'm assuming that when @kevinbackhouse suggested changing to `>` that we'd also remove that test. Might be better than adding the `+ 1` hack to [the line you referenced](https://github.com/Exiv2/exiv2/blob/971bbfac9bd4fc44131499f850f120b8a346c46d/src/types.cpp#L92)?

**Comment by neheb** [comment]
maybe @piponazo can decide as that change is a regresion.

**Comment by kevinbackhouse** [comment]
I'm in favor of replacing `>=` with `>` and updating or removing the failing test.

**Comment by mohamedchebbii** [comment]
@kevinbackhouse , @neheb ; Exuse me I'm not an expert in this part of exiv2, but I'm not seeing error in the code 
```
const byte* Exiv2::DataBuf::c_data(size_t offset) const {
  if (pData_.empty()) {
    return nullptr;
  }
  if (offset >= pData_.size()) {      <<<< Why we need to replace >= by >  ( the '>=' seems correct)
    throw std::out_of_range("Overflow in Exiv2::DataBuf::c_data");
  }
  return &pData_[offset];
}
```
std::vector<byte> pData_; so we could not acces to pData_[size] .

shouldn't size+1 in the buffer ?

I pushed here https://github.com/Exiv2/exiv2/pull/2586 a fix to add +1 to the size of the buffer, this seems to fix problem but I still have some errors in tests , If you are Ok I can go on and fix them also, otherwise I can change the ">=" by ">" and try to fix problems behind.

**Comment by benmccann** [comment]
This issue can be closed now that https://github.com/Exiv2/exiv2/pull/2586 was merged
