### ISSUE TITLE
Memory corruption in GIMP possibly caused by getPreviewProperties

### ISSUE THREAD

**Issue by Wormnest** [Exiv2/exiv2#2566]
#### **Describe the bug**
We have memory corruption in GIMP (issue [https://gitlab.gnome.org/GNOME/gimp/-/issues/8816](https://gitlab.gnome.org/GNOME/gimp/-/issues/8816)), that I believe is caused by reading preview images through `getPreviewProperties`.

Loading this issue gives two warnings in the console
```
** (file-jpeg:22744): WARNING **: 18:01:30.446: Directory OlympusCs, entry 0x0101: Strip 0 is outside of the data area; ignored.

** (file-jpeg:22744): WARNING **: 18:01:30.446: Directory Thumbnail, entry 0x0111: Data area exceeds data buffer, ignoring it.
```

Before loading of the image finishes in GIMP, the jpeg image loader crashes in the part where it is loading the metadata. More specifically it crashes when trying to unreference the metadata: `g_object_unref (metadata);`, suggesting that reference has been corrupted.

#### **To Reproduce**
1. Use the jpeg image from the above linked issue [(here).](https://gitlab.gnome.org/GNOME/gimp/uploads/b8fcf31131406556c06e511d251030b3/221101_L6038_Nik-D.jpg.gz).

According to the reporter this jpeg was exported from DxO PhotoLab.

2. Run GIMP and open the image and observe that it crashes the jpeg loader.
3. This is observed both in the latest stable 2.10.34 GIMP (using exiv2 0.27.6 through gexiv2 0.14 on Windows) as well as the latest master branch.
4. By testing and commenting parts of the code I found that:
	- When i comment `Exiv2::PreviewPropertiesList list = priv->preview_manager->getPreviewProperties();`  in gexiv2-metadata.cpp, function `gexiv2_metadata_init_internal` (see [here](https://gitlab.gnome.org/GNOME/gexiv2/-/blob/master/gexiv2/gexiv2-metadata.cpp#L383)) then we can open the image in GIMP and view the metadata.
	- When only enabling one loader at a time by adding (if id == n), it only crashes with the loader with id 22 for me. Which seems to be the LoaderTiff::getData.

#### **Expected behavior**
No crash in GIMP when loading this image.

#### **Desktop (please complete the following information):**
- OS and version: Windows 10 Home, 64-bit
- Exiv2 version and source: mingw-w64-x86_64-exiv2 0.27.6-2 (MSYS2 package), but also self-built same version.

For self-built:
- Compiler and version: cmake version 3.25.2
- Compilation mode and/or compiler flags: cmake -G "MSYS Makefiles" ../../exiv2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=d:/msys64/home/Jacob/prefix-gimp -DEXIV2_ENABLE_WIN_UNICODE=ON

#### **Additional context**
GIMP uses exiv2 indirectly through gexiv2.

**Comment by kevinbackhouse** [comment]
Please could you create reproduction steps using just exiv2?

**Comment by kevinbackhouse** [comment]
I've investigated this and found that the bug is in the gexiv2 library, not exiv2 itself. I've suggested a fix for gexiv2: https://gitlab.gnome.org/GNOME/gexiv2/-/merge_requests/74
