### ISSUE TITLE
Windows - failing to install

### ISSUE THREAD

**Issue by perdrix52** [Exiv2/exiv2#2589]
I installed python 3.11.3 and then did pip install conan which appeared to work.

I then opened a VS command prompt and navigated to d:\Exiv2-0.27.6 and created a build dir as instructed

D:\exiv2-0.27.6>cd build

D:\exiv2-0.27.6\build>conan --version
'conan' is not recognized as an internal or external command,
operable program or batch file.

D:\exiv2-0.27.6\build>

So I fall at the first hurdle 

What should i do?

**Comment by perdrix52** [comment]
Worked around this silly conan issue using CMAKE manually

**Comment by krupkat** [comment]
Cannot reproduce this:

```
> pip install conan
> conan --version
Conan version 2.0.4
```

You can check that the executables are in the PATH environment variable, for me it is:

```
C:\Users\tomas\AppData\Local\Programs\Python\Python310\Scripts\
C:\Users\tomas\AppData\Local\Programs\Python\Python310\
```

Or better, use virtual environments as suggested here: https://docs.conan.io/2/installation.html#install-with-pip-recommended

Note that Conan was recently updated to 2.0 and there might be some issues with it. You might have to install a v1 version:

```
pip install conan==1.59
```

If still having issues, consider asking in a more appropriate place, e.g.: https://github.com/conan-io/conan

Note that I haven't tested a build of Exiv2 with conan myself.

**Comment by perdrix52** [comment]
As I said above I just used CMake
