### ISSUE TITLE
Samples not built

### ISSUE THREAD

**Issue by perdrix52** [Exiv2/exiv2#2592]
CMake build of Nightly build:

Could NOT find Iconv (missing: Iconv_LIBRARY Iconv_INCLUDE_DIR) 
Install prefix:    d:/instdir
------------------------------------------------------------------
CMake Generator:   Visual Studio 17 2022
CMAKE_BUILD_TYPE:  Release
Compiler info: MSVC (C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe) ; version: 19.35.32216.1
CMAKE_CXX_STANDARD:17
 --- Compiler flags --- 
General:           /DWIN32 /D_WINDOWS /W3 /GR /EHsc
	 /MP
	 /utf-8
Extra:              
Debug:             /MDd /Zi /Ob0 /Ox /Zo
Release:           /MD /O2  /DNDEBUG
RelWithDebInfo:    /MD /Zi /O2  /DNDEBUG
MinSizeRel:        /MD /O1  /DNDEBUG
 --- Linker flags --- 
General:           /machine:x64
Debug:             /debug /INCREMENTAL
Release:           /INCREMENTAL:NO
RelWithDebInfo:    /debug /INCREMENTAL
MinSizeRel:        /INCREMENTAL:NO

Compiler Options
Warnings as errors:                 NO
Use extra compiler warning flags:   NO

------------------------------------------------------------------
Building shared library:            NO
Building PNG support:               YES
XMP metadata support:               NO
Building BMFF support:              NO
Brotli support for JPEG XL:         NO
Native language support:            NO
Building video support:             YES
Nikon lens database:                YES
Building webready support:          NO
Dynamic runtime override:           YES
Building exiv2 command:             NO
Building samples:                   YES
Building unit tests:                NO
Building fuzz tests:                NO
Building doc:                       NO
Building with coverage flags:       NO
Using ccache:                       NO
Configuring done (0.2s)
Generating done (0.1s)

does not build the samples - there's no project created to do so,

**Comment by perdrix52** [comment]
Stangely if I configured to build EXIV2 command as well, then the sample projects were also created!!!!

**Comment by kmilos** [comment]
[This is by design](https://github.com/Exiv2/exiv2/blob/b4179adab82b5cac40e9e6b3bb3967377e741774/CMakeLists.txt#L113-L125).
