### ISSUE TITLE
Unable to build doc on WIndows

### ISSUE THREAD

**Issue by perdrix52** [Exiv2/exiv2#2594]
Trying to run build of the doc under VS2022 on Windows.  I get lots of errors like:

2>CUSTOMBUILD : error : problems opening map file D:/exiv2-build/doc/html/classExiv2_1_1HttpIo_1_1HttpImpl__inherit__graph.map for inclusion in the docs!
2>If you installed Graphviz/dot after a previous failing run,
2>try deleting the output directory and rerun doxygen.

Am I missing some critical tool, or what else could be the issue.

This is from the last nightly build

**Comment by neheb** [comment]
still an issue?

**Comment by kmilos** [comment]
Closing due to lack of response.
