### ISSUE TITLE
Consider bumping CMake minimum version to 3.13 for easier build workflow

### ISSUE THREAD

**Issue by Ryanf55** [Exiv2/exiv2#2617]
#### **Is your feature request related to a problem?**

Right now, in version `0.28.0` the README recommends the following workflow to build with CMake:

```bash
$ cd ~/gnu/github/exiv2                     # Location of the project code
$ mkdir build && cd build                   # Create a build directory
$ cmake -DCMAKE_BUILD_TYPE=Release ..       # Configure the project with CMake
$ cmake --build .                           # Compile the project
$ ctest --verbose                           # Run tests
$ cmake --install .                         # Run the install target (install library, public headers, application and CMake files)
```

The CMake version of `3.11` is said to be pinned be CentOS 8, [which CentOS Linux 8.0-1905 appears to be EOL since December 31st, 2021](https://www.stackscale.com/blog/centos-linux/). Furthermore, as per the reference, `CentOS Stream 8`, which is currently maintained till `May 31st, 2024`, [appears to support 3.18](https://centos.pkgs.org/8-stream/centos-appstream-x86_64/cmake-3.18.2-9.el8.x86_64.rpm.html).

#### **Describe the solution you would like**

I would like to bump the CMake minimum version at least to 3.13, the higher the better, to support the following build process:

```bash
$ cd ~/gnu/github/exiv2                                                # Location of the project code
$ cmake -S . -B build -DCMAKE_BUILD_TYPE=Release  # Configure the project with CMake
$ cmake --build build                                                     # Compile the project
$ ctest--test-dir  build --verbose                                    # Run tests
$ cmake --install build                                                    # Run the install target (install library, public headers, application and CMake files)
```

Configure: Change to supply which directory to put the configuration in, per [here](https://cmake.org/cmake/help/latest/manual/cmake.1.html#generate-a-project-buildsystem). This was added in 3.13.

Build: Modified to specify path to build 

Test: Modified to specify path to test dir

Install: Modified to specify which folded to install, which also supports the `--prefix` option to install in a different path without root privileges for example.

This value of the new build process is one less step (no need to create a build directory). It also means if any step fails, you do not have to change directories to rebuild. It's also more familiar to more modern CMake users. 

#### **Desktop**

- OS and version: I use ubuntu 22.04
- Exiv2 version and source: (e.g., 0.28.0 from source)

#### Contribution Node

If the maintainers like the above change, please let me know. I can submit a PR. If the CMake minimum version can be bumped higher than 3.11, please share what the current platform is that is restricting upgrades, so I can update the comment from Centos:8 to something else.

Thanks!

**Comment by kmilos** [comment]
As Ubuntu 18.04 is EOLd this month, IMHO it's ok to bump minimum to 3.16 (Ubuntu 20.4) - that'll cover Centos 8 (and Debian 10 and Leap 15.3 that are already EOLd).
