### ISSUE TITLE
Wrong description for canonLiOpId HighlightTonePriority, LongExposureNoiseReduction, HighISONoiseReduction

### ISSUE THREAD

**Issue by norbertwg** [Exiv2/exiv2#2640]
It seems, the descriptions in following three tags is not correct, probably a copy-paste-error as the different tag names have same description:

     IfdId::canonLiOpId, SectionId::makerTags, signedLong, -1, EXV_PRINT_TAG(canonAutoLightingOptimizer)},
    {0x0003, "HighlightTonePriority", N_("Distortion Correction Setting"), N_("Distortion Correction Setting"),
     IfdId::canonLiOpId, SectionId::makerTags, signedLong, -1, EXV_PRINT_TAG(canonOffOn)},
    {0x0004, "LongExposureNoiseReduction", N_("Distortion Correction Setting"), N_("Distortion Correction Setting"),
     IfdId::canonLiOpId, SectionId::makerTags, signedLong, -1, EXV_PRINT_TAG(canonLongExposureNoiseReduction)},
    {0x0005, "HighISONoiseReduction", N_("Distortion Correction Setting"), N_("Distortion Correction Setting"),

Source: https://github.com/Exiv2/exiv2/blob/main/src/canonmn_int.cpp lines 1013-1018

**Comment by postscript-dev** [comment]
> It seems, the descriptions in following three tags is not correct, probably a copy-paste-error as the different tag names have same description:

The ExifTool code doesn't have any descriptions for those tags (https://github.com/exiftool/exiftool/blob/a2f26dc90ab031c687b5730cb1e6dffb35e3e029/lib/Image/ExifTool/Canon.pm#L8614).

**Comment by norbertwg** [comment]
Ok, got it. Then I suggest to enter a comment by just inserting some spaces in tag name (as it is done in other tags):
e.g. for HighlightTonePriority description will be "High light tone priority"
If this is fine, I will prepare a PR for it.

**Comment by neheb** [comment]
This was merged.
