### ISSUE TITLE
exiv2 libgexiv2 libkexiv2 are crashing almost everything what depends on them

### ISSUE THREAD

**Issue by michaelhmich** [Exiv2/exiv2#2666]
from the FAQ
Q: "I don't know why anybody would uninstall Exiv2."
A: because it actually doesn't work

major impact in KDE  on everything graphics related

thumbnails are correctly displayed in dolphin, but then clicking on any image to open it with gwenview for example it crashes
nevertheless, gwenview opens in folder view, thumbs are displayed on folder icons. but clicking any folder and it crashes too

this is Archlinux, with latest plasma 5.27.6 on Arch, gwenview 23.04..2
happens also on Kde Neon, Ubuntu and LinuxMint, just on Mint it doesn't crash. only displays the unresolved mime types errors
all related packages are upgraded

jun 29 06:05:35 hm-abang systemd[1628]: Started Gwenview - KDE Image Viewer.
jun 29 06:05:35 hm-abang gwenview[5837]: kf.i18n.kuit: "Unknown subcue ':whatsthis,' in UI marker in context {@info:whatsthis, %1 the action's text}."
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-aptus-mos"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-arq"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-bay"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-bmq"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-cap"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-cine"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-cs1"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-dc2"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-drf"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-dxo"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-epson-eip"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-epson-erf"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-fff"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-hasselblad-3fr"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-iiq"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-kodak-dcs"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-kodak-kc2"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-mamiya-mef"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-mfw"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-minolta-mdc"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-mng"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-obm"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-ori"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-ptx"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-pxn"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-qtk"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-r3d"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-raw"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-rdc"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-rwl"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-rwz"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-samsung-srw"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved mime type  "image/x-sti"
jun 29 06:05:35 hm-abang gwenview[5837]: org.kde.kdegraphics.gwenview.lib: Unresolved raw mime type  "image/x-samsung-srw"
jun 29 06:05:36 hm-abang kernel: gwenview[5837]: segfault at 0 ip 0000753429dcbc7b sp 00007ffe2ce17860 error 4 in libexiv2.so.0.28.0[753429cd3000+17c000] likely on CPU 0 (core 0, socket 0)
jun 29 06:05:36 hm-abang kernel: Code: 74 24 50 48 89 44 24 60 48 8b 44 24 08 4c 8d b4 24 a0 00 00 00 48 89 54 24 58 48 8d bc 24 90 00 00 00 48 01 f2 48 89 7c 24 38 <49> 8b 1c 24 48 89 44 24 70 48 c7 44 24 78 00 00 00 00 c6 84 24 80
jun 29 06:05:36 hm-abang systemd[1]: Started Process Core Dump (PID 5847/UID 0).

jun 29 06:05:36 hm-abang systemd-coredump[5848]: Removed old coredump core.gwenview.1000.d7305819fe8943e0b36da71d0ddd91c6.4268.1688027614000000.zst.
jun 29 06:05:37 hm-abang systemd-coredump[5848]: [🡕] Process 5837 (gwenview) of user 1000 dumped core.
                                                 
                                                 Module libnvidia-glcore.so.390.157 without build-id.
                                                 Module libnvidia-tls.so.390.157 without build-id.
                                                 Module libGLX_nvidia.so.0 without build-id.
                                                 Stack trace of thread 5837:
                                                 #0  0x0000753429dcbc7b _ZNK5Exiv28ExifData7findKeyERKNS_7ExifKeyE (libexiv2.so.28 + 0x1cbc7b)
                                                 #1  0x0000753429e4225a n/a (libexiv2.so.28 + 0x24225a)
                                                 #2  0x0000753429d68d7d n/a (libexiv2.so.28 + 0x168d7d)
                                                 #3  0x0000753429dc2c44 _ZNK5Exiv29Exifdatum5writeERSoPKNS_8ExifDataE (libexiv2.so.28 + 0x1c2c44)
                                                 #4  0x000075342abeb1f4 _ZN8Gwenview18ImageMetaInfoModel13setExiv2ImageEPKN5Exiv25ImageE (libgwenviewlib.so.5 + 0xde1f4)
                                                 #5  0x000075342abafc21 _ZN8Gwenview8Document13setExiv2ImageESt10unique_ptrIN5Exiv25ImageESt14default_deleteIS3_EE (libgwenviewlib.so.5 + 0xa2c21)
                                                 #6  0x000075342abbad8e n/a (libgwenviewlib.so.5 + 0xadd8e)
                                                 #7  0x00007534288d06a7 n/a (libQt5Core.so.5 + 0x2d06a7)
                                                 #8  0x00007534286fd4d5 _ZN18QFutureWatcherBase5eventEP6QEvent (libQt5Core.so.5 + 0xfd4d5)
                                                 #9  0x000075342957893f _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x17893f)
                                                 #10 0x000075342889b778 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x29b778)
                                                 #11 0x00007534288a06db _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2a06db)
                                                 #12 0x00007534288e6748 n/a (libQt5Core.so.5 + 0x2e6748)
                                                 #13 0x0000753426677981 g_main_context_dispatch (libglib-2.0.so.0 + 0x5a981)
                                                 #14 0x00007534266d4b39 n/a (libglib-2.0.so.0 + 0xb7b39)
                                                 #15 0x0000753426675032 g_main_context_iteration (libglib-2.0.so.0 + 0x58032)
                                                 #16 0x00007534288ea5cc _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea5cc)
                                                 #17 0x000075342889a484 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x29a484)
                                                 #18 0x000075342889b923 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x29b923)
                                                 #19 0x000057174b89ca49 n/a (gwenview + 0x35a49)
                                                 #20 0x0000753428038850 n/a (libc.so.6 + 0x23850)
                                                 #21 0x000075342803890a __libc_start_main (libc.so.6 + 0x2390a)
                                                 #22 0x000057174b89d245 n/a (gwenview + 0x36245)
                                                 
                                                 Stack trace of thread 5841:
                                                 #0  0x0000753428115571 pselect (libc.so.6 + 0x100571)
                                                 #1  0x00007534254986f9 n/a (libusbmuxd-2.0.so.6 + 0x36f9)
                                                 #2  0x00007534254993cc n/a (libusbmuxd-2.0.so.6 + 0x43cc)
                                                 #3  0x000075342809c44b n/a (libc.so.6 + 0x8744b)
                                                 #4  0x000075342811fe40 n/a (libc.so.6 + 0x10ae40)
                                                 
                                                 Stack trace of thread 5845:
                                                 #0  0x0000753428098f0e n/a (libc.so.6 + 0x83f0e)
                                                 #1  0x000075342809bab5 pthread_cond_timedwait (libc.so.6 + 0x86ab5)
                                                 #2  0x00007534286fb1f4 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xfb1f4)
                                                 #3  0x00007534286f832a n/a (libQt5Core.so.5 + 0xf832a)
                                                 #4  0x00007534286f34da n/a (libQt5Core.so.5 + 0xf34da)
                                                 #5  0x000075342809c44b n/a (libc.so.6 + 0x8744b)
                                                 #6  0x000075342811fe40 n/a (libc.so.6 + 0x10ae40)
                                                 
                                                 Stack trace of thread 5838:
                                                 #0  0x0000753428112c0f __poll (libc.so.6 + 0xfdc0f)
                                                 #1  0x00007534266d4a9f n/a (libglib-2.0.so.0 + 0xb7a9f)
                                                 #2  0x0000753426675032 g_main_context_iteration (libglib-2.0.so.0 + 0x58032)
                                                 #3  0x00007534288ea5cc _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea5cc)
                                                 #4  0x000075342889a484 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x29a484)
                                                 #5  0x00007534286f72b6 _ZN7QThread4execEv (libQt5Core.so.5 + 0xf72b6)
                                                 #6  0x0000753429ad5a9a n/a (libQt5DBus.so.5 + 0x18a9a)
                                                 #7  0x00007534286f34da n/a (libQt5Core.so.5 + 0xf34da)
                                                 #8  0x000075342809c44b n/a (libc.so.6 + 0x8744b)
                                                 #9  0x000075342811fe40 n/a (libc.so.6 + 0x10ae40)
                                                 
                                                 Stack trace of thread 5846:
                                                 #0  0x0000753428098f0e n/a (libc.so.6 + 0x83f0e)
                                                 #1  0x000075342809bab5 pthread_cond_timedwait (libc.so.6 + 0x86ab5)
                                                 #2  0x00007534286fb1f4 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xfb1f4)
                                                 #3  0x00007534286f832a n/a (libQt5Core.so.5 + 0xf832a)
                                                 #4  0x00007534286f34da n/a (libQt5Core.so.5 + 0xf34da)
                                                 #5  0x000075342809c44b n/a (libc.so.6 + 0x8744b)
                                                 #6  0x000075342811fe40 n/a (libc.so.6 + 0x10ae40)
                                                 
                                                 Stack trace of thread 5840:
                                                 #0  0x0000753428098f0e n/a (libc.so.6 + 0x83f0e)
                                                 #1  0x000075342809b7a0 pthread_cond_wait (libc.so.6 + 0x867a0)
                                                 #2  0x00007534286fb264 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xfb264)
                                                 #3  0x000075342ac0d9b6 n/a (libgwenviewlib.so.5 + 0x1009b6)
                                                 #4  0x00007534286f34da n/a (libQt5Core.so.5 + 0xf34da)
                                                 #5  0x000075342809c44b n/a (libc.so.6 + 0x8744b)
                                                 #6  0x000075342811fe40 n/a (libc.so.6 + 0x10ae40)
                                                 
                                                 Stack trace of thread 5843:
                                                 #0  0x0000753428098f0e n/a (libc.so.6 + 0x83f0e)
                                                 #1  0x000075342809bab5 pthread_cond_timedwait (libc.so.6 + 0x86ab5)
                                                 #2  0x00007534286fb1f4 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xfb1f4)
                                                 #3  0x00007534286f832a n/a (libQt5Core.so.5 + 0xf832a)
                                                 #4  0x00007534286f34da n/a (libQt5Core.so.5 + 0xf34da)
                                                 #5  0x000075342809c44b n/a (libc.so.6 + 0x8744b)
                                                 #6  0x000075342811fe40 n/a (libc.so.6 + 0x10ae40)
                                                 
                                                 Stack trace of thread 5839:
                                                 #0  0x0000753428112c0f __poll (libc.so.6 + 0xfdc0f)
                                                 #1  0x0000753426b8226b n/a (libxcb.so.1 + 0xd26b)
                                                 #2  0x0000753426b83d1d xcb_wait_for_event (libxcb.so.1 + 0xed1d)
                                                 #3  0x0000753422c3fed2 n/a (libQt5XcbQpa.so.5 + 0x62ed2)
                                                 #4  0x00007534286f34da n/a (libQt5Core.so.5 + 0xf34da)
                                                 #5  0x000075342809c44b n/a (libc.so.6 + 0x8744b)
                                                 #6  0x000075342811fe40 n/a (libc.so.6 + 0x10ae40)
                                                 
                                                 Stack trace of thread 5844:
                                                 #0  0x0000753428098f0e n/a (libc.so.6 + 0x83f0e)
                                                 #1  0x000075342809bab5 pthread_cond_timedwait (libc.so.6 + 0x86ab5)
                                                 #2  0x00007534286fb1f4 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xfb1f4)
                                                 #3  0x00007534286f832a n/a (libQt5Core.so.5 + 0xf832a)
                                                 #4  0x00007534286f34da n/a (libQt5Core.so.5 + 0xf34da)
                                                 #5  0x000075342809c44b n/a (libc.so.6 + 0x8744b)
                                                 #6  0x000075342811fe40 n/a (libc.so.6 + 0x10ae40)
                                                 ELF object binary architecture: AMD x86-64
jun 29 06:05:37 hm-abang systemd[1]: systemd-coredump@2-5847-0.service: Deactivated successfully.
jun 29 06:05:37 hm-abang systemd[1628]: app-org.kde.gwenview-a8f15bf16f1d4a6e9aab18c57e9cc5c2.scope: Consumed 1.625s CPU time.

**Comment by kevinbackhouse** [comment]
https://invent.kde.org/graphics/gwenview/-/merge_requests/207

**Comment by michaelhmich** [comment]
ok, thanks, gwenview is not crashing anymore, just logging the mime type errors

still, certain plugins have problems like this:

plasmashell[23929]: /home/hm/.config/GIMP/2.10/plug-ins/gimp-lensfun: error while loading shared libraries: libexiv2.so.27: cannot open shared object file: No such file or directory

**Comment by kmilos** [comment]
> /home/hm/.config/GIMP/2.10/plug-ins/gimp-lensfun: error while loading shared libraries: libexiv2.so.27: cannot open shared object file: No such file or directory

This is unrelated to the original problem, and also not the issue for Exiv2.

GIMP (or its plugin, or any other software) has to be rebuilt against the appropriate version of Exiv2 - in this case if you upgraded to 0.28.0 the SOVERSION bumped so it should be rebuild against `libexiv2.so.28`.

**Comment by michaelhmich** [comment]
ok, I'll check it out, thanks
