### ISSUE TITLE
Fix config/FindIconv.cmake for cmake >= 3.11

### ISSUE THREAD

**Issue by D4N** [Exiv2/exiv2#267]
`config/FindIconv.cmake` seems to be broken on Windows with a recent enough cmake (>= 3.11). Therefore that include is disabled by #266.

- [x] Find out if this is a Windows specific issue
- [x] Find a more permanent solution

**Comment by D4N** [comment]
My Fedora machines are running cmake 3.11 and `iconv.h` provided by glibc. So this probably does not occur on Linux.

**Comment by clanmills** [comment]
Thanks for discovering and reporting this.  Let me investigate this later today (or over the weekend).

I assume were discussing the CMake/Visual Studio 2017 build.

**Comment by D4N** [comment]
Afaik Appveyor uses Visual Studio 2015 & Cmake 3.11

**Comment by piponazo** [comment]
Exactly, on Linux and OSX systems it seems to work (even on travisCI). This issue was discovered on AppVeyor.

**Comment by clanmills** [comment]
Thanks, Luis.  I'm going to run in the forest this morning.  I'll look at this later today (Sunday 8/4).

**Comment by clanmills** [comment]
I'm tired and haven't solved this.    Tomorrow is another day.

**Comment by piponazo** [comment]
I can investigate the CMake integration, even check if there is already some conan recipe for it. I have never used that library, and I do not even know for what it is used for. Could you give me some hints? :)

**Comment by clanmills** [comment]
I think iconv does string conversion between UTF-8 and UCS-abc (and what not).  I think it's only used for JPEG comments which can be encoded/decoded using that library.  It's mentioned in the man page.

It's not an explicit build option.  Both CMake and autotools detect the availability of the library during the build and link it.  I've never thought about this until yesterday evening (and that's when I decided I had to sleep and think a little).

```
687 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ grep -i iconv build/exv_conf.h 
/* Define to `const' or to empty, depending on the second argument of `iconv'. */
/* #undef ICONV_ACCEPTS_CONST_INPUT */
#if defined ICONV_ACCEPTS_CONST_INPUT
#define EXV_ICONV_CONST const
#define EXV_ICONV_CONST
// Define if you have the iconv function.
#define EXV_HAVE_ICONV
```

**Comment by piponazo** [comment]
Some good news!

There is an available conan recipe for libiconv in **conan-center**:

https://bintray.com/bincrafters/public-conan/libiconv%3Abincrafters/1.15%3Astable

I will try to integrate this right now.
