### ISSUE TITLE
0.28 broke the build while using std::experimental::filesystem (Ubuntu 18.04, GCC 7.5.0)

### ISSUE THREAD

**Issue by kamiccolo** [Exiv2/exiv2#2679]
#### **Describe the bug**
After the release of 0.28 exiv2 build with mostly default flags got broken (still works with 0.27.7), complaining about missing `filesystem`:

```
build/test/exiv2-0.28.0-Source/build# cmake ..
CMake Error at cmake/FindFilesystem.cmake:246 (message):
  Cannot run simple program using std::filesystem
Call Stack (most recent call first):
  cmake/findDependencies.cmake:38 (find_package)
  CMakeLists.txt:81 (include)
  
-- Configuring incomplete, errors occurred!
```

I'm almost certain, that this is the culprit (not mentioning "Experimental" component):
https://github.com/Exiv2/exiv2/blob/main/cmake/findDependencies.cmake#L38

And excluding search for "Experimental" if it's not explicitly mentioned:
https://github.com/Exiv2/exiv2/blob/main/cmake/FindFilesystem.cmake#L133

Thus, making this temporal hack pass the build:
```
--- a/cmake/findDependencies.cmake
+++ b/cmake/findDependencies.cmake
@@ -35,7 +35,7 @@ if (NOT Python3_Interpreter_FOUND)
     message(WARNING "Python3 was not found. Python tests under the 'tests' folder will not be executed")
 endif()

-find_package(Filesystem REQUIRED)
+find_package(Filesystem COMPONENTS Experimental REQUIRED)
```

#### **To Reproduce**

1.`wget https://github.com/Exiv2/exiv2/releases/download/v0.28.0/exiv2-0.28.0-Source.tar.gz`
2. `tar -xvf ./exiv2-0.28.0-Source.tar.gz`
3. `mkdir ./exiv2-0.28.0-Source/build && cd exiv2-0.28.0-Source/build`
4. `cmake -DEXIV2_ENABLE_INIH=OFF ..`

(libinih-dev package do seem a bit broken on Ubuntu 18.04, but that's for another case)

#### **Expected behavior**
Well, despite Ubuntu 18.04 being out of CI for a while already, I would expect it to work, while there weren't that many serious compatibility changes and it used to build <=0.27.7 fine.

#### **Desktop (please complete the following information):**
- OS and version: Ubuntu 18.04
- Exiv2 version and source: 0.28 from Source tarball at https://github.com/Exiv2/exiv2/releases/tag/v0.28.0
- Compiler and version: GCC 7.5.0 (7.5.0-3ubuntu1~18.04), using CMake 3.26.3
- Compilation mode and/or compiler flags: default flags

**Comment by Ryanf55** [comment]
Do you have ability to upgrade to Ubuntu 20.04? Ubuntu 18 is deprecated.

**Comment by neheb** [comment]
meson will work

**Comment by kamiccolo** [comment]
> Do you have ability to upgrade to Ubuntu 20.04? Ubuntu 18 is deprecated.

Well, it's rather related to particular versions of GCC (and I suppose, Clang as well). Which do ship `std::filesystem` as `std::experimental::filesystem`.  Having in mind that https://github.com/Exiv2/exiv2/blob/main/cmake/FindFilesystem.cmake is not that old addition, I don't believe we're going to ditch those particular versions of C++ compilers, are we?

**Comment by neheb** [comment]
Forgot how I ended up fixing this. Overrode some CMake variables from that file to force experimental fs.

**Comment by kamiccolo** [comment]
I believe this may be related: https://github.com/Exiv2/exiv2/issues/2136

**Comment by neheb** [comment]
oh wait a minute. Ubuntu 18.04 has GCC8. Try compiling with that.

**Comment by kamiccolo** [comment]
> oh wait a minute. Ubuntu 18.04 has GCC8. Try compiling with that.

It does indeed, thanks! Only thing that it used to be some kind of weird pre-release version GCC. Not so sure how to interpret that Ubuntu-specific versioning now, though. 

But yeah, currently, specifically for 18.04 it does seem like an option. The build succeeded. Will ran a few more tests later this week.

**Comment by neheb** [comment]
Closing since this was fixed.
