### ISSUE TITLE
Warnings when exiv2 built and linked with LTO

### ISSUE THREAD

**Issue by pszemus** [Exiv2/exiv2#2680]
#### **Describe the bug**
I've built a static libexiv2.a using [LTO (Link Time Optimization)](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) and, while linking with my code, some warnings occured:

```
/home/user/projects/libs/exiv2/src/minoltamn_int.cpp:1653: warning: type ‘struct LensIdFct’ violates the C++ One Definition Rule [-Wodr]
 1653 | constexpr struct LensIdFct {
      | 
/home/user/projects/libs/exiv2/src/pentaxmn_int.cpp:1234: note: a different type is defined in another translation unit
 1234 | struct LensIdFct {
      | 
/home/user/projects/libs/exiv2/src/minoltamn_int.cpp:1654: note: the first difference of corresponding definitions is field ‘idx’
 1654 |   uint32_t idx;
      | 
/home/user/projects/libs/exiv2/src/pentaxmn_int.cpp:1235: note: a field with different name is defined in another translation unit
 1235 |   long id_;       //!< Lens id
      | 

```

#### **To Reproduce**
1. Build v0.28.0 with CMake:
```
cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
          -DBUILD_SHARED_LIBS=OFF \
          -DEXIV2_ENABLE_XMP=OFF \
          -DEXIV2_ENABLE_BROTLI=OFF \
          -DEXIV2_ENABLE_INIH=OFF
cmake --build build
cmake --install build
```
2. link with a custom code
3. observe warnings while linking (see above)

#### **Expected behavior**
no warnings

#### **Desktop**
- OS and version: Linux (Fedora 37)
- Exiv2 version and source: 0.28.0 from https://github.com/Exiv2/exiv2.git
- Compiler and version: gcc (GCC) 12.3.1 20230508 (Red Hat 12.3.1-1), CMake 3.26.4
- Compilation mode and/or compiler flags: `CMAKE_BUILD_TYPE=Release` and `CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON` add the following compiler/linker flags: `-O3 -DNDEBUG -flto=auto -fno-fat-lto-objects`

**Comment by neheb** [comment]
missing static looks like.

**Comment by neheb** [comment]
merged and backported. wait for next release.
