### ISSUE TITLE
0.28 broke the possible inclusion of the project using CMake's FetchContent

### ISSUE THREAD

**Issue by kamiccolo** [Exiv2/exiv2#2707]
#### **Describe the bug**
Using CMake's FetchContent for Exiv2 0.28 to be used as a dependency causes the build of Exiv2 itself to lose it's CMAKE_MODULE_PATH and error out:

```
$ cmake ..
-- The C compiler identification is GNU 13.1.1
-- The CXX compiler identification is GNU 13.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/bin/python3.11 (found version "3.11.3") found components: Interpreter
CMake Error at build/_deps/exiv2-src/cmake/findDependencies.cmake:38 (find_package):
  By not providing "FindFilesystem.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Filesystem", but CMake did not find one.

  Could not find a package configuration file provided by "Filesystem" with
  any of the following names:

    FilesystemConfig.cmake
    filesystem-config.cmake

  Add the installation prefix of "Filesystem" to CMAKE_PREFIX_PATH or set
  "Filesystem_DIR" to a directory containing one of the above files.  If
  "Filesystem" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  build/_deps/exiv2-src/CMakeLists.txt:81 (include)


-- Configuring incomplete, errors occurred!
```

#### **To Reproduce**

Try building sample CMake project:

```
cmake_minimum_required(VERSION 3.15)

project("SampleExiv2RDep" VERSION 0.0.1)

include(FetchContent)
FetchContent_Declare(
	exiv2
	URL https://github.com/Exiv2/exiv2/releases/download/v0.28.0/exiv2-0.28.0-Source.tar.gz
)

FetchContent_MakeAvailable(exiv2)

add_executable(main main.cpp)

# Missing "exiv2lib_export.h" goes to global BINARY_DIR as well?
target_include_directories(main PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
target_link_libraries(main exiv2lib)
```

With, let's say "empty" main.cpp:

```
#include <exiv2/exiv2.hpp>

int main(int argc, const char *argv[])
{
    return 0;
}
```

#### **Expected behavior**
Well, this kind of usage (or rather inclusion) is not documented as a recommended way, but used to work as expected with Exiv2 0.27.6 and 0.27.7

#### **Desktop (please complete the following information):**
- OS and version: ArchLinux
- Exiv2 version and source: [0.28.0](https://github.com/Exiv2/exiv2/releases/download/v0.28.0/exiv2-0.28.0-Source.tar.gz)
- Compiler and version: GCC 13.1.1, CMake 3.26.4

#### **Additional context**
I'm led to believe that the behavior in question was introduced with this commit: https://github.com/Exiv2/exiv2/commit/c334fa3ce9197c3e374536fe7228540eb378eb49

Also, I'd guess that switch from using `CMAKE_SOURCE_DIR` to `CMAKE_CURRENT_SOURCE_DIR` would make a difference here and supposed to be a preferred way.

If that seems like a proper fix, can provide a PR. For with proposed "fix":
https://github.com/Exiv2/exiv2/compare/main...kamiccolo:exiv2:bugfix/do_not_rely_on_global_source_dir_for_cmake_modules

 On the side-note, I'm still not sure if the same should be applied to all the `CMAKE(_CURRENT)_BINARY_DIR`'s as well.

**Comment by neheb** [comment]
PR would be great.

**Comment by kamiccolo** [comment]
> PR would be great.

Indeed. Will invest more time looking into it in more details. A bit too much things to break in the process :)
