### ISSUE TITLE
Inconsistency in the usage of the DEBUG compiler definitions

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#272]
In #270 it was reported an compilation error when using the `DEBUG` compiler definition. On Linux and Mac builds we are using a custom compiler definition (`DEBUG`) to activate certain pieces of code only in Debug builds. We add this compiler definition conditionally in CMake, by checking if the `CMAKE_BUILD_TYPE` if `Debug`. 

However on Windows we were not adding this compiler flag. Actually, we do not need to add such compiler flag by ourselves, since [Visual Studio adds automatically `_DEBUG`](https://github.com/Exiv2/exiv2/pull/261/commits/2f644db8d64cd4e63583707fb81037cfd4838c3e) when using the compiler switch `/MDd` or `/MTd`. 

I propose the following approach to properly allow Debug builds in all the platforms, having the same behaviour in all of them:

- Replace all occurrences of `DEBUG` in the C++ code by `NDEBUG` (and negate the preprocessor conditions). Note that the [assert](http://en.cppreference.com/w/c/error/assert) behaviour is based on `NDEBUG`.
- Remove the `DEBUG` compiler definition added for Debug builds. CMake is already adding the `NDEBUG` one for the Release builds.

**Comment by piponazo** [comment]
After the discussion we had in the PR we agreed on:

- Leave the code using DEBUG as it is.
- Remove DEBUG from the default compiler flags for Debug builds.
- Add a way in CMake to add such DEBUG definition (or just tell users to define it if they are interested in that behavior).

**Comment by D4N** [comment]
I agree with your proposal. Imho it is good enough to add `-DDEBUG` to `CXXFLAGS` manually, the debug mode is anyway only interesting for developers, so I think that is convenient enough (at least for me).

**Comment by piponazo** [comment]
Yes, I agree with you. The less options we have in the CMake code, the better :wink:
