### ISSUE TITLE
 The link interface of target "Exiv2::exiv2lib" contains: "EXPAT::EXPAT" but the target was not found. 

### ISSUE THREAD

**Issue by Ryanf55** [Exiv2/exiv2#2726]
This is the same as #2687 but for a different dependency, `expat` when consuming exiv2 with CMake config mode, when it was built with expat support.

```bash
cd /path/to/exiv2
docker run -v $(pwd):/ws -w /ws --net=host -it ubuntu:22.04 bash
apt update && apt install -y build-essential cmake libbrotli-dev libz-dev libexpat-dev
cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=Off -DEXIV2_ENABLE_INIH=Off
cmake --build build --parallel `nproc`
cmake --install build
cat /usr/local/share/cmake/exiv2/exiv2Config.cmake
```

**Comment by neheb** [comment]
these are private dependencies, no? Sounds like you're compiling statically.

**Comment by Ryanf55** [comment]
> ```shell
> cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=Off -DEXIV2_ENABLE_INIH=Off
> ```

Yea, the dependency shows here as PRIVATE: https://github.com/Exiv2/exiv2/blob/368eab01db680b0613d0e85b9c10c9257ef12c4d/xmpsdk/CMakeLists.txt#L32



On `main`, `EXPAT` is indeed linked privately, however, it still shows up as in INTERFACE_LINK_LIBRARY: 
```
cat /usr/local/share/cmake/exiv2/exiv2Export.cmake | grep -A 2 -B 3 EXPAT

set_target_properties(Exiv2::exiv2lib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:EXPAT::EXPAT>;\$<LINK_ONLY:ZLIB::ZLIB>;/usr/lib/x86_64-linux-gnu/libbrotlicommon.so;/usr/lib/x86_64-linux-gnu/libbrotlidec.so"
)
```

Relevant info: 
https://gitlab.kitware.com/cmake/cmake/-/issues/15415#note_333595
https://stackoverflow.com/questions/47534442/cmake-how-to-export-a-library-with-private-dependencies
https://stackoverflow.com/questions/73568844/what-does-my-exported-cmake-static-library-require-private-links




I'm actually not sure on the right was to solve this, even after reading the SO post on it. This needs to work for both static and shared libs. I'm taking the approach of exporting the dependency even though it was PRIVATE. It's mentioned later in the CMake issue thread a nice solution for >3.26, but we don't have that.

**Comment by Ryanf55** [comment]
I think I've found a great solution with the `BUILD_INTERFACE` generator for the linkage to `EXPAT::EXPAT`. Take a look at the PR. It works for our static library use case.

Honestly this would be a lot easier to test if exiv2 actually tested the usage in CMake. Then, it could go through both a static and shared library approach in CI for consuming.

**Comment by Ryanf55** [comment]
Ok, so going back to the steps to reproduce, using the current PR branch with `$<BUILD_INTERFACE:EXPAT::EXPAT>`, it fails with static libraries, just as @eli-schwartz said. Shared libraries build fine. 

Here's the example app to test against with both shared and static exiv2 builds: **main.cpp**
```c++
#include <exiv2/exiv2.hpp>


int main() {
        Exiv2::XmpParser::initialize();
        Exiv2::XmpData xmpData;
        return 0;
}
```

I'm going back to the original version where the private library is exported, like I did for ZLIB.

**Comment by neheb** [comment]
Was this fixed?

**Comment by Ryanf55** [comment]
Yep!
