### ISSUE TITLE
exiv2/cmake /msvc_conan_profiles/msvc2019Release64 is wrong

### ISSUE THREAD

**Issue by SCWilly** [Exiv2/exiv2#2759]
exiv2/cmake /msvc_conan_profiles/msvc2019Release64 is set to debug when it should be release

It is like this..

[build_requires]
[settings]
arch=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
arch_build=x86_64
os_build=Windows
[options]
[env]

It should be..

[build_requires]
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
arch_build=x86_64
os_build=Windows
[options]
[env]

**Comment by kmilos** [comment]
Indeed, thanks.
