### ISSUE TITLE
CANON RF 15-30 incorrectly identified as 61182

### ISSUE THREAD

**Issue by Roebie** [Exiv2/exiv2#2767]
#### **Describe the bug**
My CANON RF 15-30MM F4.5-6.3 IS STM lens wrongly identifies as 61182.

#### **To Reproduce**
1. I've run `exiv2 -pt EOSR-2023-09-09-002338.jpg |grep -i 'lens\|model\|make'`
2. I looked at the Exif.CanonCs.LensType value
3. See also attached file with the command's output

#### **Expected behavior**
The value of the Exif.CanonCs.LensType field should be CANON RF 15-30mm F4.5-6.3 IS STM

#### **Desktop (please complete the following information):**
- Latest Linux Mint 21.2 Cinnamon
- Exiv2 0.27.5-3ubuntu1 (installed through Mint Software Manager)

#### **Additional context**
[output.txt](https://github.com/Exiv2/exiv2/files/12640605/output.txt)

**Comment by kmilos** [comment]
This expected behaviour, LensType is not valid d for RF, as all RF lenses have this same LensType number.

Use LensModel instead for RF.
