### ISSUE TITLE
Please add support for reading temperature values form RAW files

### ISSUE THREAD

**Issue by cryptomilk** [Exiv2/exiv2#280]
Hello,

my camera (Sony ILCE-7M3) has temperature information stored in the exif data. Especially the CameraTemperature value is interesting for [dark frame subtraction](https://en.wikipedia.org/wiki/Dark-frame_subtraction). You can create a dark frame library for subtraction if you know the temperature value and reuse them (+/- 1°C).

```
exiftool -s _7M30305.ARW | grep Temp
ColorTemperature                : Auto
CameraTemperature               : 8 C
BatteryTemperature              : 10.0 C
```

```
exiv2 -pa _7M30305.ARW | grep Temp
Exif.Sony2.ColorTemperature                  Long        1  0
```

RAW example can be found on https://raw.pixls.us/

I guess that other camera manufactures have also temperature sensors in the camera.

**Comment by clanmills** [comment]
Yes.  Camera Temperature been discussed before.  An Astronomer at NASA was interested in this for Canon cameras.  As you can imagine, temperature in the observatory is an important input to the image post-processing.

We're having a meeting of Team Exiv2 at my home in England in May.  I've proposed that the top priority matter for v0.28 (2019) is "Improved raw image code and test".  http://dev.exiv2.org/news/3 

I'm sure you understand that Exiv2 is an open-source project with limited resources and many requests.  The sure way to get a feature added is to volunteer and submit a patch.  Your request will be discussed in May.   https://github.com/Exiv2/exiv2/issues/225

**Comment by clanmills** [comment]
Andreas:  I forgot to say "Thank You" for all your hard work on libssh.  I subscribe to your mailing list because exiv2 (optionally) uses libssh.  I know you put in a lot of effort.  Thanks for doing that.

**Comment by cryptomilk** [comment]
I didn't know that exiv2 uses libssh, but you're welcome! Thanks for working on exiv2 ;-)

**Comment by clanmills** [comment]
Andreas:  In 2013, I had a GSoc (Google Summer of Code) student in Singapore work with me to implement "WebReady".  This extends the I/O system in Exiv2 to support internet protocols such as http, ftp and so on.  So you can do stuff like this:
```
782 rmills@rmillsmbp:~/Downloads $ exiv2 -pa --grep Caption http://clanmills.com/Stonehenge.jpg
Iptc.Application2.Caption                    String     12  Classic View
783 rmills@rmillsmbp:~/Downloads $ 
```

To support ssh, we us libssh.  All versions of exiv2 support HTTP.  To use https, ftp, ssh, you can optionally link libcurl, openssl and libssh.  As I've never had a bug report concerning the ssh support, I don't think there are many folks building using those options.

I didn't connect the dots this morning and realise that cryptomilk (GitHub), Andreas S (email) and Andreas Schneider are all the same person.

Incidentally, I made a contribution to libssh in 2016.  Somebody in India wanted to build libssh on MinGW and helped him to get that to work.

I promise that your requests to support Temperature and *Balance will be discussed at the Team Meeting in England.  We have a major architecture project to be undertaken to support BigTiff (64 bit Tiff).  I expect that we will agree that this is the major priority for 2019.  This will probably involve a redesign of the some internals of Exiv2 and it's possible that we can automate the MakerNote decoders.  So, there's a good possibility that Temperature and *Balance will arrive next year as a "free bonus" thanks to BigTiff.  However, no promises.

**Comment by cryptomilk** [comment]
Robin, just for your interest libcurl uses libssh for scp and sftp support in the meantime.

https://github.com/curl/curl/pull/2036

So you can just use curl to access those files via ssh too. However the current code also supports ssh exec.

**Comment by postscript-dev** [comment]
I'm not sure if you have something particulara in mind, but I am working on adding tags for my Sony camera and made changes before seeing your request.
Here is an example of some of the tags that I have been working on.
```bash
$ exiv2 -pa DSC00680.JPG | grep -i "temperature"
Exif.Sony1.ColorTemperature                  Long        1  Auto
Exif.Sony2Fp.AmbientTemperature              SByte       1  14°C
Exif.Sony9403.CameraTemperature              SByte       1  17°C
```
I have changed lots of other tags, so this will take me a while to format into the different PRs required.
