### ISSUE TITLE
Problematic use of std:regex on Windows (MSYS2 UCRT64)

### ISSUE THREAD

**Issue by Wormnest** [Exiv2/exiv2#2831]
#### **Describe the bug**
The use of std:regex in `src/datasets.cpp` in `IptcKey::decomposeKey` causes severe slowdowns (minutes) and the use of huge amounts of memory (gigabytes).  This is called in GIMP's dev version when built on Windows under the UCRT64 profile of MSYS2 through the gexiv2 library (0.14.2).

#### **To Reproduce**
1. On Windows, under MSYS2 UCRT64, install package `mingw-w64-ucrt-x86_64-gimp3` (dev version 2.99.16) or self build current master.
2. Start gimp-2.99 and open an image that has IPTC metadata, for testing I used e.g. [https://github.com/psd-tools/psd-tools/blob/main/tests/psd_files/16bit5x5.psd](https://github.com/psd-tools/psd-tools/blob/main/tests/psd_files/16bit5x5.psd).
3. Observe the very long waiting time and with e.g. process explorer you can see huge amounts of memory being used.

#### **Expected behavior**
Expected is quick loading and a reasonable amount of memory used.

#### **Desktop (please complete the following information):**
- OS and version: Windows 10 Home, 64-bit
- Exiv2 version and source: mingw-w64-ucrt-x86_64-exiv2 0.28.1-1 from the MSYS2 repository
- Compiler and version: whatever is used by default on up-to-date MSYS2 UCRT64 repository
- Compilation mode and/or compiler flags: Release

#### **Additional context**
This issue is discussed in [this GIMP MR](https://gitlab.gnome.org/GNOME/gimp/-/merge_requests/1102) to evaluate moving from MINGW64 to UCRT64 on Windows.

As I describe there, I added print statements to verify where the slowdown occurred, which is on the following line in decomposeKey:
```
static const std::regex re(R"((\w+)(\.\w+){2})");
```

A r[eply in that issue](https://gitlab.gnome.org/GNOME/gimp/-/merge_requests/1102#note_1916367) suggests that std:regex on Windows is indeed buggy and should better not be used with references to gcc and Inkscape issues.

**Comment by kamiccolo** [comment]
mhm. Do seem like a bigger issue at hand. 

I wonder, if we could try and reduce the grammar in use a bit (do look like a sane thing to try) do to the following:
> "By default, if no grammar is specified, ECMAScript is assumed. Only one grammar may be specified." [1]

I wonder if that could/would/should change anything.

[1] https://learn.microsoft.com/en-us/cpp/standard-library/regular-expressions-cpp?view=msvc-170

**Comment by lb90** [comment]
WE may fix the issue in GCC/libstdc++ then. Taking in account the return value / errno in calls to strxfrm() should be enough.

**Comment by Wormnest** [comment]
and now it gets stuck on a different image with IPTC DateCreated/TimeCreated tags; looks like they also use regex.

**Comment by neheb** [comment]
new issue probably. would be great to find which regex causes problems.
