### ISSUE TITLE
exiv2.org expires on February 29, 2024

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#2875]
We are sending this email because we've detected that you have a domain with an upcoming expiration date.

The following domain is expiring within 60 days:

[exiv2.org](http://exiv2.org/) -- Expires in 60 days
If expired domains are not renewed, they will be deleted and made available for registration.

[Click here to log in to your account](https://www.pairdomains.com/login.html)

Note: Your registration information indicates that the Registrant Contact for a domain name mentioned in this message resides in a country with an applicable tax rate. When your domain name is renewed, you will be charged tax if you do not have an exemption. Please review our tax exemption policy [here](https://www.pairdomains.com/kb/posts/817?q=60&utm_source=customer_mail&utm_medium=email&utm_campaign=consolidated_expire_mail).

If you have any questions, please do not hesitate to contact us at [support@pairdomains.com](mailto:support@pairdomains.com).

Thank you,
[pairdomains.com](http://pairdomains.com/) Customer Care
[support@pairdomains.com](mailto:support@pairdomains.com)

You can disable expiration reminders for individual domain names by logging into your Pair Domains account, clicking on one of your domain names, and then clicking "Toggle Expiration Reminders".

* pair International is the trade name for Ryousha Kokusai, LLC. Services to our international customers are provided exclusively by pair Networks, Inc., a World Class web host and domain registrar. All domain registration services will be fulfilled by Pair Domains, a division of pair Networks, Inc. pursuant to its ICANN status and agreements with other TLD Registries.

**Comment by nehaljwani** [comment]
I've tried logging in to the Pair Domains account, but it is protected by 2FA and I don't receive the one time code as I am only listed as the technical contact and not the main contact. I reached out to their support contact in Jan and they told me that only @clanmills can make that change.

I also reached out to our contact at pixls, but haven't heard back from them so far.

**Comment by nehaljwani** [comment]
Response from Pair Domains:

>Hello,
>
>If you are not able to log in, you can submit credit >card payment
>information through our secure contact page:
>
 > 1. Go to https://www.pairdomains.com/contact.html
>  2. Select "Credit Card Payment" from the Type menu
 > 3. Enter your account name (if you know it), the domain, and email address
>  4. Enter the credit card number, expiration date, and security code
>  5. Enter the renewal length in the "Message" box
>  6. Click "Send Message"


>These are the current renewal prices:
>
>  1 year is $23.00
>  2 years are $44.00 ($22.00/year)
>  3 years are $66.00 ($22.00/year)
>  4 years are $84.00 ($21.00/year)
>  5 years are $100 ($20.00/year)
>
>Since the account lists a UK address, 20% VAT >would be added to the total.

**Comment by clanmills** [comment]
@nehaljwani I believe I can access Pair Domains and can restore the domain name using my credit card.  I thought the plan was to host exiv2.org on a server owned by pixls.us (Pat David and his friends).  Or has this already been done?  I'm a little lost about what we need to do.

**Comment by nehaljwani** [comment]
I've reminded Pat David and Alexander Esseling several times, but I haven't heard back from them.

The entire hosting is already on GitHub, it was the transfer of domain to them that we were hoping to achieve.

**Comment by kmilos** [comment]
Have you tried reaching out to them via discuss.pixls.us?

**Comment by clanmills** [comment]
@nehaljwani So, we only need to update the IP address for exiv2.org and we're done, right?  If github.com allow that, then I can pay PairDomains and we're done.  Moving forward, I'd like to have my name/address removed from ownership, and somebody else can pay the annual charge.

I agree with @kmilos that opening a topic on discuss.pixls.us is a good idea.

**Comment by nehaljwani** [comment]
@clanmills Only domain renewal is required, everything else is in place already.

I've opened a topic at https://discuss.pixls.us/t/ownership-for-exiv2-org/42586

**Comment by nehaljwani** [comment]
@clanmills Pat David is asking if we can transfer the domain to them. If you can make me the admin contact for the Pair Domains account, I can initiate the transfer. You can do that by removing all of your details and copying mine from the Technical contact section.

**Comment by clanmills** [comment]
I believe this has been resolved. Thank You, @nehaljwani, for working on this. Nehal: If you (or anybody else) know of further action on this, please reopen the issue and let me know by email if I am required to do something.
