### ISSUE TITLE
Lens Recognition for Sigma 24mm f/1.4 DG HSM Art

### ISSUE THREAD

**Issue by Macchiato17** [Exiv2/exiv2#2877]
#### **Is your feature request related to a problem?**
exiv2 doesn't recognize the lens **Sigma 24mm f/1.4 DG HSM Art** when used with a crop sensor, i.e. Nikon D7500. 
I was reproducing that issue with darktable (built from current master) and also by directly launching exiv2 from a MINGW64 shell under Windows 11.

In the meantime, the crop related calibration data was added to the lensfun database (see [lensfun issue 2126](https://github.com/lensfun/lensfun/issues/2126)), the issue related to darktable not recognizing this lens and the content of the `exiv2.ini` is decribed in [lensfun issue 2127](https://github.com/lensfun/lensfun/issues/2127).

#### **Describe the solution you would like**
Would be wonderful, if you may add recognition of this lens to exiv2. 

#### **Describe alternatives you have considered**
As a work-around I created an `exiv2.ini` linking the lens ID with the lens name string found in the lensfun database

#### **Desktop**
- Windows 11
- Exiv2 version 0.27.7 installed via pacman
- darktable built from current master

#### **Additional context**
I attached a [JPEG file](https://github.com/Exiv2/exiv2/assets/58610057/d4394060-e04d-4844-a0b1-2d6c77302b0f) that was taken with this lens. Don't get confused, it's just a "black shot" 😉.
And I wish all of you developing, maintaining or otherwise contributing to this nice piece of software a Happy New Year 😃

**Comment by kmilos** [comment]
Thanks for the sample.

**Comment by Macchiato17** [comment]
Thanks for including the lens so quickly - have a good time.
