### ISSUE TITLE
win32 build of exiv2.exe no longer includes wildcard filenames support?

### ISSUE THREAD

**Issue by ennss** [Exiv2/exiv2#290]
What am I missing?   Wildcard filenames are no longer supported in latest (0.26 version) of the win32 build compared to older (0.25) version?      Missing a link to setargv.obj or this isn't supported with the cross-compiler?

F:\TMP\cam\d\180429>c:\bin\exiv2-new.exe -m c:\bin\myexif.txt _mg_361*.*
_mg_361*.*: Failed to open the file
F:\TMP\cam\d\180429>c:\bin\exiv2-new.exe -V
exiv2 0.26 001a00 (64 bit build)
...

Older version works:

F:\TMP\cam\d\180429>c:\bin\exiv2.exe -m c:\bin\myexif.txt _mg_361*.*
F:\TMP\cam\d\180429>c:\bin\exiv2 -V
exiv2 0.25 001900 (32 bit build)
...

**Comment by clanmills** [comment]
There was a major change concerning the v0.26 binaries built for release.  Prior to v0.26, the binaries were cross-compiled for Windows and supported wild-card expansion on the command-line.

With v0.26, I was unable to get the cross compiler to work.  Instead, I built and distributed Windows builds for Cygwin/64, MinGW/32 and Visual Studio (32/64 2005,2008, 2010, 2012, 2013 and 2015).  So many more Windows builds are published.

No version of Exiv2 built with Visual Studio has ever supported wildcard expansion.  The Cygwin bash shell performs wildcard expansion.  The MinGW builds "should" support this, however it doesn't seem to be working.

I have some suggestions:
1) Install Cygwin and use exiv2 from the bash shell
2) cmd.exe supports wildcards with the syntax:`for %p in (*.jpg) do exiv2 .options. %p`
3) Use PowerShell.  This is discussed here:  https://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths
