### ISSUE TITLE
Lens Recognition for Yongnuo YN 35mm f/2

### ISSUE THREAD

**Issue by tuxfanx** [Exiv2/exiv2#2902]
#### **Is your feature request related to a problem?**
exiv2 doesn't recognize the lens [Yongnuo YN 35mm f/2](https://th.hkyongnuo.com/products/yn35mm-f2). 
The lens is recognized by exiftool as Yongnuo YN 35mm f/2 and is [included in the lensfun database](https://github.com/lensfun/lensfun/blob/master/data/db/misc.xml) under this name.

#### **Describe the solution you would like**
Would be wonderful, if you may add recognition of this lens to exiv2.

#### **Describe alternatives you have considered**
As a work-around I created an exiv2.ini

#### **Desktop**
- OS: Debian bookworm
- Exiv2 version and source: 0.27.6 and 1.00.0.9
- Any software using exiv2 and source: darktable 4.6.0

#### **Additional context**
I attached a jpeg picture taken with Canon EOS 5D Mark II. [The lens is also available with a Nikon F mount
](https://th.hkyongnuo.com/products/yn35mm-f2n)

![IMG_5121](https://github.com/Exiv2/exiv2/assets/95431163/e69ce172-7bf5-483a-b9ea-9218f132a424)

**Comment by kmilos** [comment]
Seems to be present in the Canon tables already: https://github.com/Exiv2/exiv2/blame/v0.27.6/src/canonmn_int.cpp#L1900

As there are many lenses w/ this ID, it's possible that dealiasing for Canon is broken. Please search the issues, there are several reports about this.

For Nikon, a separate sample is needed.

**Comment by kmilos** [comment]
Also, I don't see the problem on this sample w/ exiv2 0.28.1:
```
Exif.CanonCs.LensType                         198  Yongnuo YN 35mm f/2
```

**Comment by tuxfanx** [comment]
Thanks for the info!
Unfortunately, I can't provide a picture for Nikon mount.

**Comment by kmilos** [comment]
FYI: https://github.com/Exiv2/exiv2/pull/2904
