### ISSUE TITLE
Support winget installation

### ISSUE THREAD

**Issue by alanlivio** [Exiv2/exiv2#2927]
#### **Is your feature request related to a problem?**
No.

#### **Describe the solution you would like**
I would like to request a feature that would make it easier to install and update exiv2 on Windows using the winget tool, which is a command-line interface to the Windows Package Manager service, part of the App Installer. You can learn more about winget [here](https://learn.microsoft.com/en-us/windows/package-manager/winget/),[here](https://learn.microsoft.com/en-us/windows/package-manager/winget/).

[To support winget installation, you would need to create and submit a manifest file to the winget-pkgs repository](https://learn.microsoft.com/en-us/windows/package-manager/winget/)[2](https://github.com/coreybutler/nvm-windows/issues/547), which is the source for the packages available through winget. The manifest file contains the metadata and installer URLs for your software. [You can use the winget-create tool](https://learn.microsoft.com/en-us/windows/package-manager/winget/)[3](https://github.com/microsoft/winget-cli/issues/356) to help you generate or update the manifest file.

#### **Describe alternatives you have considered**
No.

#### **Desktop**
- OS and version: windows

**Comment by kmilos** [comment]
Any packaging/delivery of exiv2 is out of scope for the project.

Please feel to contact the winget project/packagers directly.

**Comment by kmilos** [comment]
Thank you for your understanding and contribution!

**Comment by alanlivio** [comment]
Thank you @kmilos It seems someone already submitted a PR. 😊
