### ISSUE TITLE
Canon Lens incorrectly identified as Sigma Lens

### ISSUE THREAD

**Issue by sans-c** [Exiv2/exiv2#2928]
#### **Describe the bug**
Canon EF100-400mm f/4.5-5.6L IS USM incorrectly identified as Sigma 100-400mm f/5-6.3 DG OS HSM in Exif.CanonCs.Lens field. Exif.Photo.LensModel shows the correct lens.

#### **To Reproduce**
1. consider this file:
![G94A1274](https://github.com/Exiv2/exiv2/assets/52868970/44995e12-71e5-4a10-8cd1-0799d61f4cd4)

which is an out-of-camera, otherwise unprocessed jpg

2. `exiv2 -P kt file | grep Sigma`
results in: Exif.CanonCs.LensType                         Sigma 100-400mm f/5-6.3 DG OS HSM

#### **Expected behavior**
The lens used was a Canon EF100-400mm f/4.5-5.6L IS USM and should be detected as such.

#### **Desktop (please complete the following information):**
- OS and version: Linux (Endeavour)
- Exiv2 version and source: exiv2 0.28.2 from Arch repo

#### **Additional context**
The EF lens was mounted to an RF mount via a genuine Canon adapter. No idea if this has any influence. Unfortunately I cannot currently test this lens on an EF-mount.

**Comment by kmilos** [comment]
Can't reproduce w/ exiv2 0.28.2 on MSYS2 UCRT64, I get different output that highlights there is aliasing:
```
$ exiv2 -Pkt -g LensType 307808061-44995e12-71e5-4a10-8cd1-0799d61f4cd4.jpg
Exif.CanonCs.LensType                         Canon EF 100-400mm f/4.5-5.6L IS USM *OR* Sigma 100-400mm f/5-6.3 DG OS HSM
Exif.CanonFi.RFLensType                       n/a

$ exiv2 -V
exiv2 0.28.2
```

**Comment by kmilos** [comment]
@sans-c Unrelated: would you mind asking the Arch exiv2 package maintainers to add the `brotli` dependency as well please?

**Comment by sans-c** [comment]
> @sans-c Unrelated: would you mind asking the Arch exiv2 package maintainers to add the `brotli` dependency as well please? It seems it's enabled anyway (via `curl`?), just not listed explicitly...

Not sure what qualifies as a dependency and what doesn't. As you mentioned, curl is listed and curl itself depends on brotli. I don't have any affiliation with Arch, nor do I have any accounts there to contribute, but that can change of course. :) I'll see what I can do.

As for the issue: that's interesting. I stumbled across this by using darktable, as so many others. I skimmed through the issue you linked but didn't get much out of it for now. If you need any more input or someone to test stuff, feel free to ping me.

> The EF lens was mounted to an RF mount via a genuine Canon adapter. No idea if this has any influence.

Can you speak to this perhaps? My gut feeling is, that mount adapters shouldn't have any influence but thats unsubstantiated. What is your take on this?

**Comment by kmilos** [comment]
> I'll see what I can do.

@sans-c Never mind, I found the package maintainers' email and contacted them directly. Thanks anyway!

**Comment by sans-c** [comment]
> @sans-c Never mind, I found the package maintainers' email and contacted them directly. Thanks anyway!

:D I just requested my account (which was granted) and was about to raise an issue since I wasn't sure if mailing directly would be frowned upon. Anyway, good to know. :)

**Comment by kmilos** [comment]
> I wasn't sure if mailing directly would be frowned upon. Anyway, good to know. :)

I might ping you back if there is no reply. Ta.

**Comment by kmilos** [comment]
@sans-c I never got a reply from the Arch maintainers, so [please open an issue in their GitLab](https://gitlab.archlinux.org/archlinux/packaging/packages/exiv2), TIA

**Comment by kamiccolo** [comment]
> > @sans-c I never got a reply from the Arch maintainers, so [please open an issue in their GitLab](https://gitlab.archlinux.org/archlinux/packaging/packages/exiv2), TIA
> 
> [done](https://gitlab.archlinux.org/archlinux/packaging/packages/exiv2/-/issues/1) :)

the update got merged: https://gitlab.archlinux.org/archlinux/packaging/packages/exiv2/-/commit/1b9e30f5403194f81dd6bed9997b5bfc95da4dd0

;)

**Comment by kmilos** [comment]
Thank you both!
