### ISSUE TITLE
Make bugfix release that includes CVE patches

### ISSUE THREAD

**Issue by Germano0** [Exiv2/exiv2#293]
Good day, I am one of Fedora package maintainers and in particular I deal with exiv2 due my co-maintaining activity of [darktable](https://github.com/darktable-org/darktable/) software.
Fedora still has not included patches for 2017 and 2018 exiv2 CVEs, like RHEL and CentOS instead [have done](https://git.centos.org/tree/rpms!exiv2.git/c7/SOURCES)
Since I am planning to do such activity in Fedora, I would like to ask you instead if you are planning to release a bugfix update that would include them, so that Linux distributions exiv2 maintainers would be helped in their packaging activity.

Best regards

**Comment by clanmills** [comment]
We're having a team meeting this weekend at my home in England and this top of the agenda.  I think we'll agree to release v0.27 later this year and will include all the security fixes.  http://dev.exiv2.org/news/3

Early next week I'll publish my notes from the meeting: https://github.com/Exiv2/exiv2/issues/225

@a17r has a branch of v0.26 with security patches.  I haven't spent any time to discover what's included.

Pascal de Bruijn is an active contributor to darktable and has cherry picked our repos for several years.  I recommend you speak with Pascal about this. 

I'm going to close this issue.  However be sure, you are not being ignored.  This matter is our top priority and receiving a lot of attention.
