### ISSUE TITLE
Access Violation in value.cpp

### ISSUE THREAD

**Issue by roflcopter4** [Exiv2/exiv2#2962]
#### **Describe the bug**
The line 374 in "value.cpp"
```
      throw Error(ErrorCode::kerInvalidIconvEncoding, encoding, "UTF-8");
```
can cause an access violation when `encoding` is NULL. This line of code has been fixed in the nightly and head but the most recent release still contains the old version. `encoding` ought to be `from`, as in the current version of the code. Since this breaks the library when used with any bad image file I'd call this bug pretty serious.

#### **To Reproduce**
The problem is in program logic and doesn't need to be reproduced. `Error` passes its argument to a function that turns it into a string via `std::ostringstream`, which must not be given a NULL `const char *` pointer.

**Comment by neheb** [comment]
I assume you're talking about https://github.com/Exiv2/exiv2/commit/d4f6c9cf40a80dc11c536d5c8399c49a1b9e62cb

**Comment by neheb** [comment]
https://github.com/Exiv2/exiv2/pull/2977 should fix this.

**Comment by neheb** [comment]
Closing this. Next minor release should fix this.
