### ISSUE TITLE
Handle XMP dependency with Conan

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#297]
As discussed in the team meeting, we would like to handle the XMP dependency with conan so that we can easily compile XMP SDK different versions (2013, 2014, 2016) for the main platforms (OS X, Linux and Windows) and compilers.

Later on, CMake would use the information provided by the Conan recipe to find properly the headers and libraries.

**Comment by D4N** [comment]
Could you make the whole thing plugable, so that package maintainers for distributions can simply provide their version of the xmpsdk from their repository and don't have to patch our cmake files?

**Comment by D4N** [comment]
Plugable was probably the wrong word here. What Linux distributions usually require is that all dependencies must be brought in via their system wide package manager. In that case, the packages manager would install the xmpsdk headers & dynamic library into the standard locations and we could include those (probably) without extra work.

So the best solution would be to have an option to turn of our bundled xmpsdk & not bring it in via conan but to use the system wide version. Would that be doable?

cc @dirkmueller @Germano0 This will probably concern your packaging efforts.

**Comment by piponazo** [comment]
From the point of view of our CMake code is totally doable. However the XMP SDK configuration code is far from being good. Basically I had to throw away big portions of their cmake code and re-write some others to make it compile on Linux and Windows (I still need to make it work on Mac). 

After spending some time trying to integrate the new XMP SDK into Exiv2, I think we will be able to work with both versions: the existing one in our repo and the new one (handled by conan). Linux distributions can still compile Exiv2 with XMP support by compiling the old XMP code available in our repository.

**Comment by D4N** [comment]
> Linux distributions can still compile Exiv2 with XMP support by compiling the old XMP code available in our repository.

I am pretty sure most distros don't actually want that or are forbidden from doing that (the Fedora packaging guidelines state that bundling is forbidden except for very rare circumstances). If it would be possible for our cmake code to also support an already installed xmpsdk, then I think that would be the easiest for package maintainers.

Just a though: conan probably installs the xmpsdk to some provided folder in the users home directory, doesn't it? Could we make this folder configurable via cmake? Then a package maintainer could simply set that directory to their system wide xmpsdk installation and it should in theory work.

**Comment by Germano0** [comment]
> cc @dirkmueller @Germano0 This will probably concern your packaging efforts.

Fedora exiv2 maintainers are Rex Dieter (rdieter) - main admin and Michel Alexandre Salim (salimma) 
https://src.fedoraproject.org/rpms/exiv2
the name between parentheses is the Fedora Account System (FAS) name. To send an e-mail to them, use the email alias fasname@fedoraproject.org
You may want to contact Jan Grulich too, which is the maintainer for RHEL / CentOS

**Comment by piponazo** [comment]
> Just a though: conan probably installs the xmpsdk to some provided folder in the users home directory, doesn't it? Could we make this folder configurable via cmake? Then a package maintainer could simply set that directory to their system wide xmpsdk installation and it should in theory work.

Yes, if we provide a proper CMake finder for XMP, it should easy to find it wherever it is.
