### ISSUE TITLE
exiv2 --grep does not work in 0.26

### ISSUE THREAD

**Issue by lysium** [Exiv2/exiv2#298]
exiv2 v0.25 allowed grepping for keys, which does not seem to work anymore for exiv2 v0.26:

```
$ ~/.root/bin/exiv2 --version
exiv2 0.25 001900 (64 bit build)
Copyright (C) 2004-2015 Andreas Huggel.
[...license snipped...]
$ ~/.root/bin/exiv2 --grep DateTime Masters/2018//05/01/20180501-182913/IMG_6977.JPG
Exif.Image.DateTime                          Ascii      20  2018:05:01 16:45:09
Exif.Photo.DateTimeOriginal                  Ascii      20  2018:05:01 16:45:09
Exif.Photo.DateTimeDigitized                 Ascii      20  2018:05:01 16:45:09
$ /opt/local/bin/exiv2 --version
exiv2 0.26 001a00 (64 bit build)
Copyright (C) 2004-2017 Andreas Huggel.
[...license snipped...]
$ /opt/local/bin/exiv2 --grep DateTime Masters/2018//05/01/20180501-182913/IMG_6977.JPG
File name       : Masters/2018//05/01/20180501-182913/IMG_6977.JPG
File size       : 2900818 Bytes
MIME type       : image/jpeg
Image size      : 3264 x 2448
[...other keys snipped...]
White balance   : Auto
Thumbnail       : image/jpeg, 13941 Bytes
Copyright       :
Exif comment    :
```

I expected v0.26 to work as v0.25 with regard to `--grep`.
I checked if the issues has been reported previously, to no avail.
I observe the behavior with any other image file, so I haven't attached a particular one.

**Comment by clanmills** [comment]
I am not aware that this has been previously reported.  My usual way of to work with exiv2 is to use the command @$ exiv2 -pa --grep foo image@ and that behaviour is unchanged in v0.26.  It would appear that there is a change in the grep behaviour of the default command @$ exiv2 --grep foo image@ and I will investigate.

There are a couple of changes to the grep code in v0.26.  In v0.25 and earlier, --grep was a simple sub-string match.  In v0.26, it will use the system regular expression engine if available.  Additionally and argument such as @--grep date/i@ will match the substring while ignoring case.

**Comment by clanmills** [comment]
I've decided to do nothing about this.  When the grep code was reworked for v0.26, I believe it does not apply to the default `$ exiv2 foo` command.  There's a lot of work to be done for v0.27 and spending time on this could be a time/resource trap.  I don't think this feature is worth the trouble that changing the code could cause.
