### ISSUE TITLE
[Testsuite] Debug mode of the testsuite fails when the terminal does not support utf-8

### ISSUE THREAD

**Issue by D4N** [Exiv2/exiv2#313]
Some of the commands & outputs include non-ascii characters which result in errors due to `print()` which uses the default encoding of the shell.

It would be probably the best to issue a warning to the user, if their shell does not support utf-8 but they try to use the debug mode with non-ascii commands & outputs.

**Comment by piponazo** [comment]
The redmine issue 1242 is affected by this issue.

**Comment by D4N** [comment]
Actually all issues which have unicode escapes in them are. I think the only solution for that is to print out the raw bytes (which will look ugly here and there). But that shouldn't be that much of a problem, as it only affects the debug mode.

**Comment by clanmills** [comment]
I think we should "let this go".  @1div0 has agree to take on development of the python test harness for v1.00 #1550.
