### ISSUE TITLE
Fix the error codes

### ISSUE THREAD

**Issue by D4N** [Exiv2/exiv2#323]
In #109 we discussed some inconsistencies in the error codes (`include/exiv2/error.hpp` and `src/error.cpp`) and how to fix them but then did not implement the fix.

Here is the list from that PR:
- [x] change error message of `Exiv2::kerInvalidTypeValue` to "invalid type in tiff structure"
- [x] merge `Exiv2::kerInvalidIccProfile` and `Exiv2::kerInvalidXMP` to `Exiv2::kerInvalidIccProfile`
- [ ] change `kerCorruptedMetadata` to `kerTiffParsingError`
- [ ] fix invalid usage of `kerTiffDirectoryTooLarge` in the webready code => add a new error code for that (e.g. `kerServerError` or `kerWebError`)
- [ ] merge `kerTooManyTiffDirectoryEntries` and `kerTiffDirectoryTooLarge`? I am actually unsure if they should be merged. `kerTooManyTiffDirectoryEntries` aka `Error 49` is used only once in the whole code in `src/tiffcomposite.cpp:1093` (which was indeed last edited by Andreas in 2010) however it is used in the context of writing too many Tiff directories to a file. `kerTiffDirectoryTooLarge` (aka `Error 55`) is actually only once used correctly (I assume) in `Image::printIFDStructure` (the other uses are in the network code and look like this: `Error(55, "Server", serverCode)`, so I assume that is wrong) where it reports that a Tiff directory is larger than `500`. In my opinion these are two different errors.

**Comment by clanmills** [comment]
#1045 has been merged and closed.  I believe this has been resolved and should be closed.
