### ISSUE TITLE
Support for TAMRON SP 24-70mm F/2.8 Di VC USD G2 A032

### ISSUE THREAD

**Issue by bzobl** [Exiv2/exiv2#330]
Hi,

is it possible to support the Tamron lens mentioned in the subject? It currently is detected as "Canon EF 300mm f/2.8L IS II USM", so I suspect a clash in lens IDs.
Is there a way to detect the lens anyways? The focal length, as well as the model text is read correctly

> $ exiv2 -pt ./3P2A5930.CR2 | grep -ai lens
> Exif.CanonCs.LensType                        Short       1  Canon EF 300mm f/2.8L IS II USM
> Exif.CanonCs.Lens                            Short       3  24.0 - 70.0 mm
> Exif.Canon.LensModel                         Ascii      74  TAMRON SP 24-70mm F/2.8 Di VC USD G2 A032
> Exif.Photo.LensSpecification                 Rational    4  24/1 70/1 0/1 0/1
> Exif.Photo.LensModel                         Ascii      42  TAMRON SP 24-70mm F/2.8 Di VC USD G2 A032
> Exif.Photo.LensSerialNumber                  Ascii      11  0000000000

Full exiv2 output attached.

Thanks,
Bernd

[exiv2.txt](https://github.com/Exiv2/exiv2/files/2046114/exiv2.txt)

**Comment by D4N** [comment]
Hi Bernd,

could you attach the image that you are extracting the metadata from? You can upload the metadata only version that you get via `exiv2 -ex` to keep the filesize down and the actual image private.

Can't unfortunately promise a swift resolution, as there is a lot of other stuff to fix.

Cheers,
Dan

**Comment by bzobl** [comment]
Hi Dan,

thanks for the fast response, I'm attaching a sample taken with the lens on my 7D Mark II.

![3p2a5931](https://user-images.githubusercontent.com/9977167/40629451-79ed0742-62cb-11e8-8729-84e695b01659.JPG)
