### ISSUE TITLE
config/config.h.cmake and EXV_HAVE_UNISTD_H

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#344]
I've been experiencing difficulties with CMake builds on MSVC having EXV_HAVE_UNISTD_H set.  No version of MSVC provides <unistd.h>

There's suspicious code in config/config.h.cmake.  I think the "1" typos are harmless, however let's fix them.

```
/* Define if you have the <unistd.h> header file. */
#cmakedefine EXV_HAVE_UNISTD_H 1

#if !defined( EXV_HAVE_UNISTD_H) && defined(__CYGWIN__)
#define EXV_HAVE_UNISTD_H 1
#endif
```

I have discovered this error by using Cygwin and MSVC to build in the same source tree.  The Cygwin build correctly detects <unistd.h> and sets EXV_HAVE_UNISTD_H in  include/exiv2/exv_conf.h.  A subsequent build of MSVC uses this rogue file instead of build/exv_conf.h   I believe this is a collision between autotools and CMake.  As we are now removing autotools, this will not occur again.

The block should be removed. 
```
#if !defined( EXV_HAVE_UNISTD_H) && defined(__CYGWIN__)
#define EXV_HAVE_UNISTD_H 1
#endif
```

Let's fix the typos in config/config.h.cmake and remove the Cygwin/unistd_h test.

**Comment by piponazo** [comment]
I agree with your analysis. I'll clean those things ;)

**Comment by piponazo** [comment]
Fixed in #348

**Comment by clanmills** [comment]
I've discovered another instance of CMake/Visual Studio getting its include path wrong by finding stuff in cygwin directories.  FindIntl can add `c:\cygwin64\usr\include` to the front of the include search path with awful consequences.

In README-CONAN.md I've recommended temporarily renaming `c:\cygwin64\usr\include\` as `c:\cygwin64\usr\uncle` while building with CMake/Visual Studio.  Brutal fix.

I have `c:\cygwin64\bin` on my PATH.  Perhaps that's the culprit.  Who knows!

**Comment by piponazo** [comment]
I'm sure that you are finding those issues because of your PATH environment variable. I do not have anything about cygwin in my PATH, and I never had problems building on Windows with CMake + Visual Studio.

I do not think it's a good idea to put this kind of notes in the README-CONAN.md document. It has nothing to do with conan.

**Comment by clanmills** [comment]
You are right.  It has nothing to do with conan.  However if somebody is following that document, they will have no idea what's wrong.  It's better to mention this than leaving the user puzzled.

Let's leave it like this.  If I have more time, I'll revisit it.  It's puzzling the FindIntl is doing this.  I don't understand the code in FindIntl, however it looks boiler plate.  Other FindXxxx modules don't do this.
