### ISSUE TITLE
Broken master

### ISSUE THREAD

**Issue by TernaK** [Exiv2/exiv2#345]
I've tested installation on macOS & Ubuntu with `make config && ./configure && make` and this was the result:
```
g++: error: cr2image_int.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
make[1]: *** [cr2image_int.o] Error 1
```

**Comment by piponazo** [comment]
Hi @TernaK . The autotools and msvc files are not receiving support lately and we are putting all our efforts  in improving the CMake code to make it compatible with the main platforms and toolchains. In fact, we are planning to drop the the autotools and msvc files for the next release:

https://github.com/Exiv2/exiv2/pull/338

Would you mind to try to configure and compile the project with CMake and tell us if it works for you ?

**Comment by TernaK** [comment]
@piponazo I normally use cmake but didn't even think to use it here because it's failed me in the past. I guess that's been resolved and it worked for me this time. It was able to build, thanks.

**Comment by piponazo** [comment]
Thanks for your quick reply. I'm happy to see that this time the CMake worked for you :smile: .

I'm closing this.
