### ISSUE TITLE
MAKE build and install also fail..

### ISSUE THREAD

**Issue by kooscode** [Exiv2/exiv2#355]
Tried using the "auto" make and build tools.. 

After doing a ./configure (and no errors) the make command fails with this error:

make[1]: Entering directory '/media/koos/data/sources/exiv2/src'
libtool: compile:  g++ -O2 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wcast-align -Wpointer-arith -Wformat-security -Wmissing-format-attribute -Woverloaded-virtual -W -MMD -I../src -I../include/ -I../include/exiv2 -std=c++98 -DEXV_LOCALEDIR=\"/usr/local/share/locale\" -I../xmpsdk/include -c -DEXV_BUILDING_LIB=1 cr2image_int.cpp  -fPIC -DPIC -o .libs/cr2image_int.o
g++: error: cr2image_int.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
Makefile:200: recipe for target 'cr2image_int.o' failed
make[1]: *** [cr2image_int.o] Error 1
make[1]: Leaving directory '/media/koos/data/sources/exiv2/src'
Makefile:59: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by D4N** [comment]
Hi,
we are currently deprecating autotools, which will be removed by #338. Therefore we will not fix any bugs in autotools any more. We'll of course take a look at your other issue #354, as cmake is our prefered build system.
