### ISSUE TITLE
Provide a Config-file package with CMake

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#359]
Currently exiv2 can be only found by a consumer via a pkg-config file. Since CMake is now the main configuration system, we started providing a Config-file package that should ease the integration of Exiv2 in other C/C++ projects configured via CMake:

https://cmake.org/cmake/help/v3.3/manual/cmake-packages.7.html#config-file-packages

We need to update the documentation related to this point and make sure it is working for all the platforms.

**Comment by clanmills** [comment]
I will start working on the release next week.  I will do some maintenance on README.md concerning _Linking your own code with Exiv2_ which refers to the pkg-config file.   And there are other changes needed to that file such as removing the discussion of the commercial license.
