### ISSUE TITLE
create directory if it doesnt exist

### ISSUE THREAD

**Issue by koryphaee** [Exiv2/exiv2#372]
I want to sort some photos using the rename option.
I want to move all files of one day to it's own subdirectory using this command:

`exiv2 -r "%Y-%m-%d/%H-%M-%S" mv *`

However since the directory doesn't exist, the operation fails.
I get the error:

`exiv2: Failed to rename file.jpg to ./2014-07-25/12-21-55.jpg: No such file or directory (errno = 2)`

If I create the directory manually and run the same command again it works.

**Comment by D4N** [comment]
To be honest I don't think this is something exiv2 should do, I'd prefer if exiv2 would touch the filesystem as little as possible. @piponazo @clanmills what are your opinions?

**Comment by exiftool** [comment]
This is something that ExifTool does.  It is a widely used, very useful feature.

**Comment by clanmills** [comment]
Remarkably, I replied to a question about 'rename' earlier today.  http://dev.exiv2.org/boards/3/topics/3158  I think this topic (and the earlier question) may be the  only questions that have arisen about 'rename' in the 10 years during which I've contributed to Exiv2. 

Andreas, the founder of Exiv2, established the philosophy that "Exiv2 does depth, not area".  So, we do image processing technology and we are not an image processing application.  

My recommendation to you (and the earlier topic concerning sub-seconds) is to write a script.

The exiv2 application is primarily intended to be used by our test suite and, while it has impressive capability, it is not a command-line photo organiser.

There are many demands on Team Exiv2 to develop "core" technology.  For example, Canon have a new .CR3 image format.  We can't deal with this in a script and will require Team Exiv2 to write C++ code.

There is a user contributed application for organising photos contrib/organize/ which you may find suitable.  Most of the code in contrib/ is unsupported by Team Exiv2, although I helped a user with a build issue concerning organize a few years ago.

**Comment by D4N** [comment]
I agree with @clanmills, imho this is something that should be performed by a different utility. But since two people find this to be a useful addition, I'd mark this as a feature request and leave it open.

**Comment by clanmills** [comment]
As nobody else has requested this in the 4 years since this discussion, I'm going to close this issue.

**Comment by oliwarner** [comment]
Well I've just run into this problem, trying to sort a pile of NEFs for archival.

exiv2 clearly already "touches the filesystem" with its `-r` option so I'm not sure why you're showing such enthusiasm for neutering what would be a useful feature. Not implementing a `mkdir -p` equivalent? [Seems like a long-solved issue in C++](https://stackoverflow.com/questions/20358455/cross-platform-way-to-make-a-directory-including-subfolders).

The alternative —the alternative I have to choose now— is to not use exiv2.  
This might not come up very often, but I do wonder how many other people have gone through the cycle I've just been on: found exiv2's rename feature, found it hobbled and have crawled off to exivtool or another.
