### ISSUE TITLE
[bug] print incompleted in Jupyter notebook by python3.6

### ISSUE THREAD

**Issue by SmithPeng** [Exiv2/exiv2#399]
I used exiv2 in my linux , it run well on command line ,in ipython ,and in Jupyter notebook  by python3.4 ,but in Jupyter notebook  by python3.6 , run following code:

cmd =  'exiv2 -pa xxx.tif '
os.system(cmd)

only print Exif.Image ,  parts as Exif.Photo, Exif.GPSInfo, Xmp.Camera and etc haven't print, and error present.
Error:
exiv2: symbol lookup error: exiv2: undefined symbol: _Z11_exvGettextPKc

**Comment by clanmills** [comment]
There's something wrong with your build of the library as I will explain.

Before you execute exiv2 from python, use the terminal and you'll see the same error message.  You can use the command `c++filt` to discover that exiv2 is searching (unsuccessfully) for the entry `_exvGettext(char const*)`

```
2011 rmills@ubuntu:~ $ c++filt _Z11_exvGettextPKc
_exvGettext(char const*)
```
This entry is unsatisfied and must be provided by a library:
```
2012 rmills@ubuntu:~ $ nm -g --demangle $(which exiv2) | grep exvGettext
                 U _exvGettext(char const*)
```
You can discover the location of the libraries with the command `ldd`
```
2033 rmills@ubuntu:/Home/Downloads/dist/linux/bin $ ldd $(which exiv2)
        linux-vdso.so.1 =>  (0x00007fff919fe000)
        libexiv2.so.26 => /usr/local/lib/libexiv2.so.26 (0x00007f1358f62000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1358be0000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f13589ca000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1358600000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f13583e6000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f13581bd000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1357fb9000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1357d9c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1357a93000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1359439000)
2034 rmills@ubuntu:/Home/Downloads/dist/linux/bin $ 
```

On my Linux machine, it's in libexiv2.so:
```
2013 rmills@ubuntu:~ $ nm -g --demangle /usr/local/lib/libexiv2.so | grep exvGet
000000000017c600 T _exvGettext(char const*)
000000000017c640 T Exiv2::exvGettext(char const*)
```

```
2014 rmills@ubuntu:~ $ ls -alt /usr/local/lib/libexiv2.so
lrwxrwxrwx 1 root root 18 Oct 14  2017 /usr/local/lib/libexiv2.so -> libexiv2.so.26.0.0
2015 rmills@ubuntu:~ $ ls -alt /usr/local/lib/libexiv2.so.26.0.0
-rw-r--r-- 1 root root 3363064 Oct 14  2017 /usr/local/lib/libexiv2.so.26.0.0
2016 rmills@ubuntu:~ $
```

How did you obtain exiv2?  Did you build this yourself, or download it from exiv2.org?  http://www.exiv2.org/download.html

**Comment by clanmills** [comment]
I'm closing this.  Without user feedback, no progress can be made.

@SmithPeng I'll reopen this when you provide more information.
