### ISSUE TITLE
Unable to run with arm64 architecture / ios

### ISSUE THREAD

**Issue by ingviso** [Exiv2/exiv2#405]
I'm trying to use exiv2 as a metadatawriter in a ios app that is written in react-native framework. 
I have made a bridge using djinni to call c++ code which is where I intend to use exiv2. In Xcode I have set the header search paths to exiv2 and it can be found.  

Running this code is fine:
`Exiv2::ExifData exifData;`

But when I start using it more like this code

`exifData["Exif.Image.VersionApp"] = 'TestingVersion';                     // AsciiValue`
`  Exiv2::Image::AutoPtr image = Exiv2::ImageFactory::open(uri);`
`    assert(image.get() != 0);`
`    image->setExifData(exifData);`
`    image->writeMetadata();`

Then I get 

`Undefined symbols for architecture arm64:`
`  "Exiv2::ImageFactory::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)", referenced from:`
 `     ExifdataHandler::exifdataProcess(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in exifdataHandler.o`
`ld: symbol(s) not found for architecture arm64`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Any ideas on what is needed to run this ?

**Comment by ingviso** [comment]
I'm using macOS High Sierra / Xcode 9.4.1
Installed exiv2 using brew 


In Build Settings -> Search Paths -> Header Search Paths  I have the paths:
/usr/local/Cellar/exiv2/0.26
/usr/local/bin/exiv2
/usr/local/include/exiv2
I was gettings issues when including the exiv2 library in the header file thats why I have 3 paths.

Valid architectures are arm64, I took out armv7 and armv7s because glib wouldnt run if they where on.

The code is basic same as the example the hpp file is 

`#include <exiv2/exiv2.hpp>`
`class ExifdataHandler {`
`  public:`
`    ExifdataHandler();`
`    int exifdataProcess(const string uri);`
`};`

And the cpp file is
#include "exifdatahandler.hpp"

`ExifdataHandler::ExifdataHandler()`
`{`
`}`

`int ExifdataHandler::exifdataProcess(const string uri){`
`          Exiv2::ExifData exifData;`
`            Exiv2::Image::AutoPtr image = Exiv2::ImageFactory::open(uri);`
`    exifData["Exif.Image.Model"] = "Test 1";                     // AsciiValue`
`    assert(image.get() != 0);`
`     image->setExifData(exifData);`
`    image->writeMetadata();`
`    return 0;`
`}`

**Comment by D4N** [comment]
> I'm using macOS High Sierra / Xcode 9.4.1
> Installed exiv2 using brew

Eh, does homebrew provide builds for ARM64? If they don't then that's the root of the problem.

**Comment by ingviso** [comment]
When you ran this on arm64 how did you install exiv2 ?

**Comment by D4N** [comment]
> When you ran this on arm64 how did you install exiv2 ?

I compiled it from source. But that was on Linux that was running on an arm64 machine, so no cross compilation was required.

**Comment by clanmills** [comment]
I agree with @D4N.  When you install with brew, it installs libraries for use on the desktop.

I've never programmed for iOS, however I don't believe you can use shared libraries and have to use static linking to build your application as monolith.

Team Exiv2 do not build/support iOS and Android platforms.  We'd like to and hope that one day an iOS Engineer will join us.  It could be you!

**Comment by D4N** [comment]
@ingviso You could build exiv2 with a suitable cross compiler for iOS and get the dependencies via conan (https://docs.conan.io/en/latest/systems_cross_building/cross_building.html). Note that I've never tried that, so your mileage may vary (cross compiling is unfortunately often quite painful).

**Comment by clanmills** [comment]
I'm going to close this.  Team Exiv2 does not provide support for mobile platforms.  One day we'll recruit an Engineer to provide this support, however for now we're (regrettably) unable to provide assistance.
