### ISSUE TITLE
Wrong values in GPS tags: negative number for seconds of latitude or longitude

### ISSUE THREAD

**Issue by RigacciOrg** [Exiv2/exiv2#432]
Hi, I have a problem tagging jpeg images using the pexif Python library, but I can reproduce the bug with exiv2 tool alone.

I set the following value of latitude:
`exiv2 -n UTF-8 -k -M "set Exif.GPSInfo.GPSLatitude 43/1 51/1 2576100059/50000000"  image.jpg`

With **exiv2 -PExgnycv** I can confirm that the rationale for seconds of latitude is correct:
`0x0002 GPSInfo  GPSLatitude   Rational    3  43/1 51/1 2576100059/50000000`

but if I check with **exiv2 -Pkyct** I see a wrong number:
`Exif.GPSInfo.GPSLatitude  Rational    3  43deg 51' -34.377"`

It seems that Exiv2 consider the numerator of the rationale as a signed long integer (so the overflow to negative number when the value is above 2^32/2). As far as I can understand, the Exif standard says that the rationale should be two unsigned long  integer instead.

 I tried exiv2 version 0.25, on a Debian 9 (Stretch), someone shoul check the new 0.26 version...

**Comment by D4N** [comment]
The issue appears to be fixed on master, I have tested it and obtain
with exiv2 -Pkyct:
Exif.GPSInfo.GPSLatitude                     Rational    3  43deg 51' 51.522"

which looks like the correct value to me.

Is this the behavior that you expect?

**Comment by RigacciOrg** [comment]
Yea! Thank you very much, 51.522"  is the correct value!
Happy to read that **the bug is corrected** in master . Unfortunately there are many GPS related sofware compiled against libexiv2 (eg. the image viewer Geeqie), which show the bug.
May be it is a little crazy by the Python library to use a **so huge denominator** (50000000!). To avoid triggering the overflow the maximum denominator is 35791394 :-)

**Comment by clanmills** [comment]
Gentlemen:

The Exif Standard defines Rational and SRational and we declare them in include/exiv2/types.hpp
```
    enum TypeId {
        unsignedByte       = 1, //!< Exif BYTE type, 8-bit unsigned integer.
        asciiString        = 2, //!< Exif ASCII type, 8-bit byte.
        unsignedShort      = 3, //!< Exif SHORT type, 16-bit (2-byte) unsigned integer.
        unsignedLong       = 4, //!< Exif LONG type, 32-bit (4-byte) unsigned integer.
        unsignedRational   = 5, //!< Exif RATIONAL type, two LONGs: numerator and denumerator of a fraction.
        signedByte         = 6, //!< Exif SBYTE type, an 8-bit signed (twos-complement) integer.
        undefined          = 7, //!< Exif UNDEFINED type, an 8-bit byte that may contain anything.
        signedShort        = 8, //!< Exif SSHORT type, a 16-bit (2-byte) signed (twos-complement) integer.
        signedLong         = 9, //!< Exif SLONG type, a 32-bit (4-byte) signed (twos-complement) integer.
        signedRational     =10, //!< Exif SRATIONAL type, two SLONGs: numerator and denumerator of a fraction.
        tiffFloat          =11, //!< TIFF FLOAT type, single precision (4-byte) IEEE format.
        tiffDouble         =12, //!< TIFF DOUBLE type, double precision (8-byte) IEEE format.
        tiffIfd            =13, //!< TIFF IFD type, 32-bit (4-byte) unsigned integer.
        unsignedLongLong   =16, //!< Exif LONG LONG type, 64-bit (8-byte) unsigned integer.
        signedLongLong     =17, //!< Exif LONG LONG type, 64-bit (8-byte) signed integer.
        ...
   }
```
With my Nikon 5300 (with embedded GPS), GPS is stored as Rational (not Signed Rational) and xxxRef defines N/S for Latitude E/W for Longitude and Above/Below sea-level for Altitude

```
958 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pv --grep GPS http://clanmills.com/Stonehenge.jpg
0x8825 Image        GPSTag                      Long        1  4060
0x0000 GPSInfo      GPSVersionID                Byte        4  2 3 0 0
0x0001 GPSInfo      GPSLatitudeRef              Ascii       2  N
0x0002 GPSInfo      GPSLatitude                 Rational    3  51/1 106969/10000 0/1
0x0003 GPSInfo      GPSLongitudeRef             Ascii       2  W
0x0004 GPSInfo      GPSLongitude                Rational    3  1/1 495984/10000 0/1
0x0005 GPSInfo      GPSAltitudeRef              Byte        1  0
0x0006 GPSInfo      GPSAltitude                 Rational    1  97/1
0x0007 GPSInfo      GPSTimeStamp                Rational    3  14/1 38/1 5588/100
0x0008 GPSInfo      GPSSatellites               Ascii       3  09
0x0012 GPSInfo      GPSMapDatum                 Ascii      17  WGS-84          
0x001d GPSInfo      GPSDateStamp                Ascii      11  2015:07:16
959 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ 
```

Exiv2 isn't a metadata policeman.  The data associated with a key can be of any type.  The choice of 50*10**6 seems bizarre and invites overflow.  You can see that the Nikon firmware uses 10000 for Latitude and Longitude.

Is there a case to answer?  If it's fixed on 'master' it will flow in time to applications which use libexiv2.
