### ISSUE TITLE
Sigma 24-105mm F4 DG HSM ART not properly recognised

### ISSUE THREAD

**Issue by swesemeyer** [Exiv2/exiv2#45]
I recently purchased the above lens and exiv2(git  master as of today) is not identifying it correctly.
I needed to add 
        { 143, "Sigma 24-105mm F4 DG OS HSM [Art 013]"                      }, // 2
to the current canonmn.cpp file to have it detected correctly.

Note that there is another lens type at 255 which appears to be the same lens but mine provides a different identifier for some reason...

Adding the following to ~/.exiv2 worked as well:
[canon]
143=Sigma 24-105mm F4 DG HSM ART changed by me

I have attached a sample image which contains the relevant tags.

![20170826_173544](https://user-images.githubusercontent.com/6536807/29841068-fe6cc404-8cfb-11e7-8b14-8f83cbbed4d5.jpg)

Thanks,
 Steve

**Comment by clanmills** [comment]
Steve

Thanks for reporting this.  I added the ~/.exiv2 feature to Exiv2 to enable you to fix this immediately yourself.  I'll add your change to src/canonmn.cpp.  Beautiful photo, by the way!

**Comment by clanmills** [comment]
I've extracted the metadata from your image to test/data/exiv2-g45.exv and updated our test suite to inspect that file as a regression detector.  Here's the impact of your change:
```
531 rmills@rmillsmbp:~/gnu/exiv2/0.26 $ exiv2 -pa --grep lens/i 45.exv 
Exif.CanonCs.LensType                        Short       1  143
Exif.CanonCs.Lens                            Short       3  24.0 - 105.0 mm
Exif.CanonCf.LensAFStopButton                Short       1  0
Exif.Canon.LensModel                         Ascii      74  24-105mm F4 DG OS HSM | Art 013
532 rmills@rmillsmbp:~/gnu/exiv2/0.26 $ cd ~/gnu/github/exiv2/exiv2
533 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ makes 2>/dev/null
make
      8      76     718
sudo make install
    108     614    8307
534 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pa --grep lens/i 45.exv 
Exif.CanonCs.LensType                        Short       1  Sigma 24-105mm F4 DG OS HSM [Art 013]
Exif.CanonCs.Lens                            Short       3  24.0 - 105.0 mm
Exif.CanonCf.LensAFStopButton                Short       1  0
Exif.Canon.LensModel                         Ascii      74  24-105mm F4 DG OS HSM | Art 013
535 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $
```
