### ISSUE TITLE
CMake tests (ctest) do not work with Visual Studio (on Windows)

### ISSUE THREAD

**Issue by mmatrosov** [Exiv2/exiv2#467]
Run CMake with Visual Studio generator (tested with Visual Studio 2013 and Visual Studio 2017). Try running tests:

```
>ctest -C Release
Test project E:/dev/packages/exiv2/0.27-1/aligntech/stable/build/b76c459f2beaee629c93c8b89349fd8a04f10ba5
No tests were found!!!

>cmake --build . --config Release --target RUN_TESTS
Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: RUN_TESTS.vcxproj
```

Tested with this revision: https://github.com/Exiv2/exiv2/commit/11e66c6c9eceeddd2263c3591af6317cbd05c1b6

**Comment by D4N** [comment]
That is unfortunately to be expected, as we do not use ctest (yet).

You have to run the tests manually with (see for instance Appveyor.yml for a concrete example on Windows).

**Comment by piponazo** [comment]
I would like to have this issue open as a reminder to add CTest support in the project. We can also label this issue as "good first issue" so that somebody can try to provide a patch to add this support ;)

**Comment by clanmills** [comment]
We do not support ctest at this time.

Our test suite is in a state of transition from bash scripts (which for Visual Studio require MinGW/msys2) to python.

The procedure to run the test suite on MSVC builds is documented on the **RC1** branch in the file `README.md` under `5.2 Running tests on Visual Studio builds`

**Comment by mmatrosov** [comment]
@clanmills thanks for the clarification! I'm currently using the latest released version - 0.26. If I understood correctly, the best way for me to run tests, is to use bash, set appropriate env variables, and run all shell scripts in the `test` dir. It already works for me, just want to make sure this is a proper way.

**Comment by mmatrosov** [comment]
@clanmills 

> The procedure for running the test suite on v0.26 is documented on the Exiv2 Wiki. http://dev.exiv2.org/projects/exiv2/wiki/How_do_I_run_the_test_suite_for_Exiv2

Yes, I've seen this page, it is helpful. However, it is not completely clear what do I do in my case. I'm building the library (including test apps) with CMake->Visual Studio. The page suggests me to run tests with CMake->Makefile. Is it possible to plug executables compiled with Visual Studio into "make tests"?

**Comment by clanmills** [comment]
There's a Cygwin bash script test/testMSVC.sh that will set up the correct environment variable and run the test suite.  The syntax is:
```
$ cd <exivdir>/test
$ ./testMSVC.sh [build-dir]
```
The script uses the command `find . -name build-dir exiv2.exe` to locate exiv2.exe and set EXIV2_BINDIR.

---------

For Exiv2 v0.26, the MSVC builds were performed with the script `contrib/cmake/msvc/cmakeBuild.cmd` for which one of the options is **`--test`**

`cmakeBuild.cmd` not only performs the build, it also downloads the builds dependencies (expat, zlib)

A typical command for cmakeBuild.cmd is:

```
xxxx> cmd/c "vcvars 2015 64 && cmakeBuild.cmd --build --test"
```
There are lots of options which are documented in contrib/cmake/msvc/ReadMe.txt

For Exiv2 v0.27 we now support conan which does a wonderful job of downloading and building dependencies.

**Comment by mmatrosov** [comment]
I was able to run many tests. I'm actually writing a conan recipe for Exiv2, so I used `self.run()` with `win_bash=True`, and I used git bash as Windows bash. 

I noticed thought that many tests fail because they simply cannot find tests data! At least `test/data/eps` and `test/data/video` are missing.

**Comment by piponazo** [comment]
@mmatrosov In case you are interested, I also started to write a conan recipe for exiv2 some time ago:
https://github.com/piponazo/conan-exiv2

My idea is to create a "official" conan recipe for Exiv2 after we release the 0.27 version.

**Comment by mmatrosov** [comment]
@piponazo 
> My idea is to create a "official" conan recipe for Exiv2 after we release the 0.27 version.
This is a great idea! Concerning the recipe that you have so far, it does not run tests, which for me was actually the trickiest part. Building and packaging was a pice of cake since you guys provided great CMake support. Really appreciated!

**Comment by clanmills** [comment]
@mmatrosov If you'd like to join the team and support ctest, I'd be delighted to welcome you on board.  @D4N has made a great job of moving test/bugfixes.sh into a new python test harness.  There are lots more tests to be transferred into python: see test/*.sh

The test data for video and eps files are stored in SVN and downloaded on demand.  You'll see the code in test/Makefile.  However, I'd like to remove support for video and EPS from Exiv2 for reasons I can discuss if you're interested. 

@piponazo has done a great job of getting our CMake and conan support 100% ready for prime time.  We've removed the autotools and msvc sln/project build environment.

As we move forward, both @D4N and @piponazo want to do C++ feature development and it would be wonderful to have another engineer work on our test and build infrastructure.  I've been work on Exiv2 for more that 10 years and would like to retire (I'm 67).  I hope to release v0.27 by the end of 2018 and next year I'd like to only deal with user correspondence and leave the code to the Team.

**Comment by clanmills** [comment]
It's possible to run both the "new" python test suite and the "old" bash scripts on all supported platforms (MacOS-X, Linux, Cygwin, MinGW/msys2 and Visual Studio).  It's documented in README.md.  Our Jenkins buildserver builds and runs the tests every night.  I think we'll get a student from Google Summer of Code to work with us in 2019 to port all our tests to the "new" python based test suite and to integrate with CTest.
