### ISSUE TITLE
Exiv2 0.27 - cppcheck static analyzer HTML reports

### ISSUE THREAD

**Issue by cgilles** [Exiv2/exiv2#474]
cppcheck is a very important tool to detect quickly some internal dysfunctions. It's very configurable and very fast. The HTML report is very easy to review.

I use this static analyzer over whole digiKam implementation (around 1.5 M lines of code), and we clean and stabilize the application with a lots of true errors detected.

I recommend to review the right light annotated reports from the front page.

Gilles Caulier

[Exiv2-0.27-cppcheck-reports.tar.gz](https://github.com/Exiv2/exiv2/files/2467417/Exiv2-0.27-cppcheck-reports.tar.gz)

**Comment by tbeu** [comment]
Anything left to do? Otherwise close this issue.

**Comment by piponazo** [comment]
There were still some issues reported by the tool, but none of them is critical. At some point I would like to add something in CI running this tool or pvs-studio, but I do not see myself doing it soon. Let's close the issue.
