### ISSUE TITLE
Exiv2 0.27 - Clang scan-build static analyzer HTML reports

### ISSUE THREAD

**Issue by cgilles** [Exiv2/exiv2#475]
clang scan-build  is another very important tool to detect quickly some internal dysfunctions. It's very configurable but slower than cppcheck as it require a code compilation. The HTML report is very easy to review and can give different feedbacks than cppcheck.

I use also this static analyzer over whole digiKam implementation (around 1.5 M lines of code), and we clean and stabilize the application with a lots of true errors detected.

Gilles Caulier

[exiv2-0.27-clang-scan-build-reports.tar.gz](https://github.com/Exiv2/exiv2/files/2467499/exiv2-0.27-clang-scan-build-reports.tar.gz)

**Comment by D4N** [comment]
scan-build is on the todo list (right next to clang-tidy, infer, coverity, cppcheck & pwsstudio)

**Comment by clanmills** [comment]
I'm going to close this as "historical trouble" and no long relevant.
