### ISSUE TITLE
Feature Req:  modify/update/remove preview images in RAW files

### ISSUE THREAD

**Issue by whatdoineed2do** [Exiv2/exiv2#48]
_[ feature request / query ]_

RAW files contain preview images of various sizes; for Nikon NEFs there's a small tiff + 1 medium jpg and then 1 full sized jpg that are generated at the time of capture.

I would like the ability to remove/update the preview images in a RAW file - is this technically possible and functionality make available?

**The use case:**
RAW files will get processed by tools like Adobe Lightroom, (old and retired) CaptureNX2 etc.  Edits are made to generate a final image:  tiff or jpeg for final output.

However, when archiving the RAW files to DVD or NAS I want to store the final tiff/jpeg *embedded in the RAW file* - this has the benefits:

- simplifies archival content management;  one file archived (the RAW file which includes the final processed jpg/tif) and jpeg/tif can be extracted at any time
- removes dependency on RAW processor meta/sidecar files (Lightroom) that may change in future
- preview tools (GUI file explorers that extract thumbnails from RAW files) can reflect RAW image processed contents

Nikon's CaptureNX2 had functionality to  remove all previews and leave a small thumbnail in their NEFs but this is slightly different to others since it was writing edit tags in the meta for CaptureNX2 to read/process (no sidecars)

**Comment by clanmills** [comment]
Last week, I was surprised to discover that Exiv2 does not have code to remove/modify preview images.  I think it must be difficult to do this.  When Andreas wrote the preview manager, he would have added that code if it were simple.  I suspect this is a very challenging request and unlikely to be implemented.
