### ISSUE TITLE
There is no PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP on FreeBSD

### ISSUE THREAD

**Issue by lantw44** [Exiv2/exiv2#497]
Exiv2 currently doesn't compile on FreeBSD:
```
*** Building exiv2 *** [39/228]
ninja
[24/86] Building CXX object src/CMakeFiles/exiv2.dir/actions.cpp.o
FAILED: src/CMakeFiles/exiv2.dir/actions.cpp.o
/usr/bin/clang++  -B/home/lantw44/.local/bin  -DEXV_HAVE_DLL -DEXV_HAVE_STDINT_H -DEXV_LOCALEDIR=\"share/locale\" -I/home/lantw44/gnome/source/exiv2/src -I/home/lantw44/gnome/source/exiv2/include -I/home/lantw44/gnome/source/exiv2/include/exiv2 -I. -I/home/lantw44/gnome/source/exiv2/xmpsdk/include -I/usr/local/include -Isrc -march=corei7 -B/home/lantw44/.local/bin -pipe -g3 -O0 -gz -fdebug-macro -std=gnu++98 -MD -MT src/CMakeFiles/exiv2.dir/actions.cpp.o -MF src/CMakeFiles/exiv2.dir/actions.cpp.o.d -o src/CMakeFiles/exiv2.dir/actions.cpp.o -c /home/lantw44/gnome/source/exiv2/src/actions.cpp
/home/lantw44/gnome/source/exiv2/src/actions.cpp:2063:32: error: use of undeclared identifier 'PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP'
  static pthread_mutex_t cs =  PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP;
                               ^
1 error generated.
[29/86] Building CXX object src/CMakeFiles/exiv2lib.dir/convert.cpp.o
ninja: build stopped: subcommand failed.
```
The `_NP` suffix of `PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP` suggests it is a non-portable macro. FreeBSD supports recursive mutex, but it does not define a static initializer for it. FreeBSD pthread.h only defines two mutex initializers, `PTHREAD_MUTEX_INITIALIZER` and `PTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP`, and neither of them is equivalent to `PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP` used here. If the recursive behavior is needed, is it possible to use `pthread_mutexattr_settype` instead of allocating it statically?

**Comment by clanmills** [comment]
There's something familiar about this issue.  I think it may have arisen in MinGW or Cygwin and there are macros already in the code deal with this.
```
 /* Unix/Linux/Cygwin/MacOSX */
 #include <pthread.h>
 /* This is the critical section object (statically allocated). */
 #if defined(__APPLE__)
  #if defined(PTHREAD_RECURSIVE_MUTEX_INITIALIZER)
    static pthread_mutex_t cs =  PTHREAD_RECURSIVE_MUTEX_INITIALIZER;
   #else
    static pthread_mutex_t cs =  PTHREAD_MUTEX_INITIALIZER;
  #endif
 #else
  #if defined(PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP)
    static pthread_mutex_t cs =  PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP;
   #else
    static pthread_mutex_t cs =  PTHREAD_MUTEX_INITIALIZER;
  #endif
 #endif
```

Can you find the Compiler symbol for FreeBSD and we'll update the code.  It'll be something like \_\_FREEBSD\_\_  You can see the symbols with:
```
echo '' > /tmp/empty.cpp
gcc -E -dM /tmp/empty.cpp
```
Regrettably, we can't support every flavour of Linux.  The buildserver uses Ubuntu 18.04 LTS and we use GitHub to build lots of flavours.  @D4N is our GitHub Enthusiast.

**Comment by clanmills** [comment]
To answer your question about can we use a Mutex?

I hate the lock code.  No library code should use a lock.  I only agreed to take this code from a user to make him happy and because it's not in the library.  It's in src/actions.cpp which is in the exiv2(.exe) command-line application.  Incidentally, having accepted that code, I've been plagued with build issues on every platform.  I should have said "No!".

**Comment by lantw44** [comment]
Sorry, I didn't notice I wasn't on master branch but on 0.26 branch. The problem I described above is already fixed by commit d775683f579543c35463ab2a8d9425da10d2f016.

> Can you find the Compiler symbol for FreeBSD and we'll update the code. It'll be something like __FREEBSD__ You can see the symbols with:

Yes, there is a symbol. It is `__FreeBSD__` and it is defined to be the major version of FreeBSD.

> ```
> echo '' > /tmp/empty.cpp
> gcc -E -dM /tmp/empty.cpp
> ```

Most supported architectures of FreeBSD already move to Clang several years ago, so we usually use clang to compile and test.

> Regrettably, we can't support every flavour of Linux. The buildserver uses Ubuntu 18.04 LTS and we use GitLabs to build many flavours. @D4N is our GitLabs Enthusiast.

FreeBSD is not a flavor of Linux. It has a different kernel which is not based on Linux. Linux cannot run FreeBSD executables.

It seems the only remaining problem of exiv2 is the installation. It fails because there is no ReadMe.txt file for FreeBSD:
```
*** Installing exiv2 *** [1/1]
ninja  install
[0/1] Install the project...
-- Install configuration: ""
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/samples/exifprint.cpp
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/vms
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/vms/README.md
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/vms/Vagrantfile
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/vms/setup.sh
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/vms/setup_user.sh
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/vms/utils.source
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/buildserver
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/buildserver/ReadMe.txt
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/buildserver/build.sh
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/buildserver/categorize.py
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/coverity.sh
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/createEpsTestfiles
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/diffeps
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/MD5.cpp
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/MD5.h
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/Makefile
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/README
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/boost.mk
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/helpers.cpp
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/helpers.hpp
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/organize.cpp
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/work
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/work/exiv2
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/work/exiv2/contrib
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/work/exiv2/contrib/organize
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/contrib/organize/work/exiv2/contrib/organize/organize.cpp
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/./README.md
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/./README-CONAN.md
-- Installing: /home/lantw44/gnome/devinstall/_jhbuild/root-exiv2/home/lantw44/gnome/devinstall/./license.txt
CMake Error at cmake_install.cmake:56 (file):
  file INSTALL cannot find
  "/home/lantw44/gnome/source/exiv2/releasenotes/FreeBSD/ReadMe.txt".


FAILED: CMakeFiles/install.util 
cd /home/lantw44/gnome/build/exiv2 && /usr/local/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

The path `samples`, `contrib`, `.` also look wrong. If I use `/usr/local` as the prefix, this means I will have `/usr/local/samples`, `/usr/local/contrib`, `/usr/local/README.md`, `/usr/local/license.txt` on my systems, which is not an expected behavior.

**Comment by lantw44** [comment]
I just found that exiv2.pc no longer exists and the name of the shared library changes. gexiv2 is unable to find the newly-installed exiv2 0.27 because there is no .pc file.

**Comment by clanmills** [comment]
Ah yes, FreeBSD is Unix.  I forgot.

We've deprecated exiv2.pc in v0.27.  We've totally rewritten our build system in CMake and no longer need/generate exiv2.pc.  I think you'll have to rebuild gexiv2 with the v0.27 RC1 headers and stuff.

Incidentally, we deliberately changed the library from exiv2.dll to exiv2lib.dll and digiKam complained.  We're investigating/considering reverting to exiv2.dll #498

That's interesting about the INSTALL/FreeBSD.  You'll need a link in release notes:

```
$ ln -s releasenotes\Linux releasenotes\ FreeBSD
```

I can put a fix in cmake\packaging.cmake to copy the Linux/ReadMe.txt by default.

**Comment by clanmills** [comment]
About the installation.  On Linux, I do `$ sudo make install` or `$ cmake --build . --config Release --target install` to populate `/usr/local/....` (the prefix tree).

The notes in releasenotes/Linux/ReadMe.txt say how to copy the library, headers and other stuff from the bundle into `/usr/local/...`.  If there's something wrong, let's get that fixed before it pollutes more machines.

**Comment by lantw44** [comment]
> We've deprecated exiv2.pc in v0.27. We've totally rewritten our build system in CMake and no longer need/generate exiv2.pc. I think you'll have to rebuild gexiv2 with the v0.27 RC1 headers and stuff.

What is the expected way for projects depending on exiv2 to find the library without a .pc file? I think cmake files are not useful for projects using other build systems.

> That's interesting about the INSTALL/FreeBSD. You'll need a link in release notes:
> 
> ```
> $ ln -s releasenotes\Linux releasenotes\ FreeBSD
> ```

Yes, it will be nice if it can be done in the upstream repository, as other *BSD systems will also find this problem when installing or packaging exiv2.

> The notes in releasenotes/Linux/ReadMe.txt say how to copy the library, headers and other stuff from the bundle into `/usr/local/...`. If there's something wrong, let's get that fixed before it pollutes more machines.

Thr README says only bin, include, lib should be copied, which is more correct than the current `ninja install` behavior. Is it possible to make `make install` or `ninja install` work for installation instead of asking users or packagers to copy files manually?

**Comment by clanmills** [comment]
I don't know anything about ninja.  Never used it.

I'll fix the package issue when it's looking for FreeBSD/ReadMe.txt  I've opened an issue about this and will fix it.  #499  Perhaps you could test/verity my fix next week.  It will be on the branch `0.27-RC2`

`releasenotes/Linux/ReadMe.txt` has commands to compile and link exiv2lib.so without using exiv2.pc or cmake.  Can you try those commands on FreeBSD and confirm that they work.

**Comment by clanmills** [comment]
@lantw44 Can you put the following into cmake/packaging.cmake and confirm that all is well on FreeBSD.
```
set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_CONTACT "Luis Díaz Más <piponazo@gmail.com>")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})

set(CPACK_SOURCE_GENERATOR TGZ)
set(CPACK_SOURCE_IGNORE_FILES "build.*;\.git/;\.DS_Store;")

if ( MINGW OR MSYS )
    if ( CMAKE_SIZEOF_VOID_P EQUAL 8 )
        set (PACKNAME MinGW-64)
    else()
        set (PACKNAME MinGW-32)
    endif()
    set (PACKDIR MinGW)
elseif ( MSVC )
    set (PACKNAME MSVC)
    set (PACKDIR  MSVC)
elseif ( APPLE OR LINUX OR CYGWIN )
    set (PACKNAME ${CMAKE_SYSTEM_NAME}) # Darwin or Linux or CYGWIN
    set (PACKDIR  ${PACKNAME})
else()
    set (PACKNAME Linux      ) # unsupported systems such as FreeBSD
    set (PACKDIR  ${PACKNAME})
endif()

if ( MSVC )
    set(CPACK_GENERATOR ZIP)  # use .zip - less likely to damage bin/exiv2.dll permissions
else()
    set(CPACK_GENERATOR TGZ)  # MinGW/Cygwin/Linux/MacOS-X etc use .tar.gz
endif()

set(CPACK_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${PACKNAME})

# https://stackoverflow.com/questions/17495906/copying-files-and-including-them-in-a-cpack-archive
install(FILES     "${PROJECT_SOURCE_DIR}/samples/exifprint.cpp" DESTINATION "samples")
install(DIRECTORY "${PROJECT_SOURCE_DIR}/contrib/"              DESTINATION "contrib")

# Copy top level documents (eg README.md)
# https://stackoverflow.com/questions/21541707/cpack-embed-text-files
set( DOCS
     README.md
     README-CONAN.md
     license.txt
)
foreach(doc ${DOCS})
    install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/${doc} DESTINATION .)
endforeach()

# Copy releasenotes.txt and appropriate ReadMe.txt (eg releasenotes/${PACKDIR}/ReadMe.txt)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/releasenotes/${PACKDIR}/ReadMe.txt DESTINATION .)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/releasenotes/releasenotes.txt      DESTINATION .)

include (CPack)
```

**Comment by lantw44** [comment]
> `releasenotes/Linux/ReadMe.txt` has commands to compile and link exiv2lib.so without using exiv2.pc or cmake. Can you try those commands on FreeBSD and confirm that they work.

The command works, but it isn't the point. pkg-config is a well-known tool which is very easy to use in build systems such as autotools and meson. In autotools you only need single line of `PKG_CHECK_MODULES` to find a library, and in meson you just need to write `dependency`. pkg-config also provides an easy way to check version and describe dependencies. Removing exiv2.pc is likely to make it more complex for other projects to find exiv2 and generate .pc files. It also means projects which currently use pkg-config to find exiv2 will stop working without changing build files.

> @lantw44 Can you put the following into cmake/packaging.cmake and confirm that all is well on FreeBSD.

Yes, it can now be installed successfully. However, there are many files installed on non-standard paths. Here is the list of installed files recorded by JHBuild:

```
samples/exifprint.cpp
contrib/vms/README.md
contrib/vms/Vagrantfile
contrib/vms/setup.sh
contrib/vms/setup_user.sh
contrib/vms/utils.source
contrib/buildserver/ReadMe.txt
contrib/buildserver/build.sh
contrib/buildserver/categorize.py
contrib/coverity.sh
contrib/createEpsTestfiles
contrib/diffeps
contrib/organize/MD5.cpp
contrib/organize/MD5.h
contrib/organize/Makefile
contrib/organize/README
contrib/organize/boost.mk
contrib/organize/helpers.cpp
contrib/organize/helpers.hpp
contrib/organize/organize.cpp
contrib/organize/work/exiv2/contrib/organize/organize.cpp
README.md
README-CONAN.md
license.txt
ReadMe.txt
releasenotes.txt
lib/libxmp.a
lib/libexiv2lib.so.0.27.0.1
lib/libexiv2lib.so.0
lib/libexiv2lib.so
include/exiv2/asfvideo.hpp
include/exiv2/basicio.hpp
include/exiv2/bmpimage.hpp
include/exiv2/config.h
include/exiv2/convert.hpp
include/exiv2/cr2image.hpp
include/exiv2/crwimage.hpp
include/exiv2/datasets.hpp
include/exiv2/easyaccess.hpp
include/exiv2/epsimage.hpp
include/exiv2/error.hpp
include/exiv2/exif.hpp
include/exiv2/exiv2.hpp
include/exiv2/futils.hpp
include/exiv2/gifimage.hpp
include/exiv2/http.hpp
include/exiv2/image.hpp
include/exiv2/ini.hpp
include/exiv2/iptc.hpp
include/exiv2/jp2image.hpp
include/exiv2/jpgimage.hpp
include/exiv2/matroskavideo.hpp
include/exiv2/metadatum.hpp
include/exiv2/mrwimage.hpp
include/exiv2/orfimage.hpp
include/exiv2/pgfimage.hpp
include/exiv2/preview.hpp
include/exiv2/properties.hpp
include/exiv2/psdimage.hpp
include/exiv2/quicktimevideo.hpp
include/exiv2/rafimage.hpp
include/exiv2/riffvideo.hpp
include/exiv2/rw2image.hpp
include/exiv2/rwlock.hpp
include/exiv2/slice.hpp
include/exiv2/tags.hpp
include/exiv2/tgaimage.hpp
include/exiv2/tiffimage.hpp
include/exiv2/types.hpp
include/exiv2/utilsvideo.hpp
include/exiv2/value.hpp
include/exiv2/version.hpp
include/exiv2/webpimage.hpp
include/exiv2/xmp_exiv2.hpp
include/exiv2/xmpsidecar.hpp
include/exiv2/exv_conf.h
include/exiv2/exiv2lib_export.h
include/exiv2/pngimage.hpp
share/exiv2/cmake/exiv2Config.cmake
share/exiv2/cmake/exiv2Config-noconfig.cmake
bin/exiv2
bin/addmoddel
bin/convert-test
bin/easyaccess-test
bin/exifcomment
bin/exifdata-test
bin/exifdata
bin/exifprint
bin/exifvalue
bin/ini-test
bin/iotest
bin/iptceasy
bin/iptcprint
bin/iptctest
bin/key-test
bin/largeiptc-test
bin/mmap-test
bin/mrwthumb
bin/prevtest
bin/stringto-test
bin/taglist
bin/tiff-test
bin/werror-test
bin/write-test
bin/write2-test
bin/xmpparse
bin/xmpparser-test
bin/xmpprint
bin/xmpsample
bin/xmpdump
bin/metacopy
bin/path-test
bin/exiv2json
bin/geotag
man/man1/exiv2.1
man/man1/exiv2samples.1
```

I think non-standard files, including contrib, samples, releasenotes.txt, ReadMe.txt, should be moved to share/exiv2.

**Comment by clanmills** [comment]
I'll ask @piponazo to comment concerning exiv2.pc.  I believe we only have to restore one line in CMakeLists.txt to achieve that.  If we do that, I'll also update releasenotes/platform/ReadMe.txt to say that is available and discuss it in README.md 

I agree that the contrib stuff and the 5 documents (README.md etc) should not be in the prefix tree.  I can fix that in cmake/packaging.cmake

Thank You for your effort on this today.  Very good feedback.

**Comment by clanmills** [comment]
@piponazo Can you comment on:
1) the exiv2.pc file.  I agree with @lantw44 as a courtesy to autotools users we should generate that file.
2) We shouldn't be installing those files (contrib etc) in the prefix tree.  However I want them in the package and that's why I have those `install` commands in `cmake/packaging.cmake`.  Presumably `install` is the wrong command.  Should it be `copy` or possibly `configure_file` or `file(COPY ...)`  Any suggestions?

**Comment by clanmills** [comment]
Thanks to @piponazo, I believe we have everything fixed.  We have:
1) Restored the name of the library to exiv2.dll (not exiv2lib.dll)
2) The packaging is hidden behind the option -DEXIV2_TEAM_PACKAGING=On and reserved for building our binary bundles on the build server
3) Restored `lib/pkgconfig/exiv2.pc` in the bundle
4) Updated the bundle ReadMe.txt appropriately.

These fixes will appear in Exiv2 v0.27 RC2 which will be released mid-November.

I'll mark this issue as closed as we've moved a long way from the initial topic of PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP.  Very happy with your input on all those matters.  Thank You for your help.

**Comment by lantw44** [comment]
> 3\. Restored `lib/pkgconfig/exiv2.pc` in the bundle

I just tested 0.27-RC2 branch, but I still could not find `exiv2.pc` file after `ninja install`. It seems the .pc file template is restored, but related code in cmake files are not.

**Comment by clanmills** [comment]
I'll have to ask @piponazo to fix this one for us.  I restored src/exiv2.pc.in file system.  There's no code in any CMakeLists.txt file to deal with it.

**Comment by piponazo** [comment]
@lantw44 You are right. We added the file to be generated in the BUILD directory, but we are not installing it. Furthermore I have to take care of assigning the proper paths depending on `CMAKE_INSTALL_PREFIX`. Sorry for the inconveniences. I'll fix it today and merge it into master.

**Comment by clanmills** [comment]
I documented this in README.md this morning.  In autotools days, I believe it goes into `/usr/local/lib/pkgconfig/exiv2.pc`
