### ISSUE TITLE
Changelog for 0.26

### ISSUE THREAD

**Issue by sqrt** [Exiv2/exiv2#5]
Hi @clanmills,

the Changelog at [doc/ChangeLog](/Exiv2/exiv2/blob/v0.26/doc/ChangeLog) still shows Changes from version 0.24 to 0.25. I assume you're still preparing the changelog for v0.26?

Thanks for your great work!

**Comment by clanmills** [comment]
Ah, your sharp eyes have spotted something that I didn't know.  v0.26 is the first time that for which I have been the release engineer and mistakes are inevitable.  The Changelog for v0.26 is website/var/__ChangeLog__ and published here:  http://www.exiv2.org/changelog.html#v0.26

I'll fix this in GitHub.
