### ISSUE TITLE
IPTC metadata not saved unless `setIptcData()` is called

### ISSUE THREAD

**Issue by mardy** [Exiv2/exiv2#502]
Hi there!
  I'm using libexiv 0.25 on Ubuntu 16.04, and I've noticed a behaviour which is unexpected to me: I've got a Jpeg file on which I call `image.iptcData()`, and then:

- if I assign some fields such as `Iptc.Application2.Caption`, this metadata gets properly saved;
- if I use the `IptcData::add()` method to add multiple values to the `Iptc.Application2.Keywords` field, then this works *only if I call `image.setIptcData()`* afterwards.

It looks like the iptcData pointer in the image changes by itself, in the second case. But by looking at the code of libexiv2, I cannot find any explanation for it.

I can try to provide a simple test case, if needed (will require some time, though).

**Comment by mardy** [comment]
OMG, it was a silly mistake on my part: I was doing:

    auto data = image.iptcData()

instead of

    auto &data = image.iptcData()

So indeed I was modifying a local copy of the metadata. :-)

**Comment by clanmills** [comment]
@mardy Thanks for reporting this and finding a fix.  Really appreciate you closing the issue as that saves our time to investigate.
