### ISSUE TITLE
infinite loop in getopt.cpp 

### ISSUE THREAD

**Issue by cool-tomato** [Exiv2/exiv2#510]
There is a bug in  function int getopt(int argc, char * const argv[], const char *optstring) in /src/getopt.c, while the incorrect parameters are processed, the value of optind should plus one, and the program should exit , but not continue to process the other parameters.

`./exiv2 -A 20:00:00 -Y 2018 -O 11 -D 01 ad  ./test/data/Reagan.tiff`
```
In file: /home/pwd/fuzz/fuzz-exiv2/exiv2/src/getopt.cpp
   56 			optopt = arg[optpos];
   57 			if (!opt) {
   58 				if (opterr && *optstring != ':')
   59 					fprintf(stderr, "%s: illegal option: %c\n", argv[0], optopt);
   60 				return '?';
 ► 61 			} else if (opt[1] == ':') {
   62 				if (arg[optpos + 1]) {
   63 					optarg = (char *)arg + optpos + 1;
   64 					optind++;
   65 					optpos = 1;
   66 					return optopt;

```

**Comment by clanmills** [comment]
Thanks for reporting this.  You're correct.  It's looping.

I haven't understood your fix: _the value of optind should plus one_?  Can you provide a patch?

**Comment by clanmills** [comment]
I agree that the program is looping and should be fixed.  I believe getopt() is correctly returning '?' to indicate distress and this is being ignored by the calling code:
```
    int Getopt::getopt(int argc, char* const argv[], const std::string& optstring)
    {
        progname_ = Util::basename(argv[0]);
        Util::optind = 0; // reset the Util::Getopt scanner

        for (;;) {
            int c = Util::getopt(argc, argv, optstring.c_str());
            if (c == -1) break;
            errcnt_ += option(c, Util::optarg == 0 ? "" : Util::optarg, Util::optopt);
            // What about c == '?' ? 
        }
        for (int i = Util::optind; i < argc; i++) {
            errcnt_ += nonoption(argv[i]);
        }

        return errcnt_;
    }
```

**Proposed fix:**

```
510 rmills@rmillsmm:~/gnu/github/exiv2/exiv2 $ git diff src/getopt.cpp 
diff --git a/src/getopt.cpp b/src/getopt.cpp
index ee38ab4b..9eef3b03 100644
--- a/src/getopt.cpp
+++ b/src/getopt.cpp
@@ -107,6 +107,7 @@ namespace Util {
             int c = Util::getopt(argc, argv, optstring.c_str());
             if (c == -1) break;
             errcnt_ += option(c, Util::optarg == 0 ? "" : Util::optarg, Util::optopt);
+            if ( c == '?' ) break;
         }
         for (int i = Util::optind; i < argc; i++) {
             errcnt_ += nonoption(argv[i]);
511 rmills@rmillsmm:~/gnu/github/exiv2/exiv2 $ 
```

**Result**

Test Suite passes.  So this has no downside.

```
511 rmills@rmillsmm:~/gnu/github/exiv2/exiv2 $ build/bin/exiv2 -A 20:00:00 -Y 2018 -O 11 -D 01 ad ./test/data/Reagan.tiff
exiv2: Unrecognized option -A
Usage: exiv2 [ options ] [ action ] file ...

Manipulate the Exif metadata of images.
512 rmills@rmillsmm:~/gnu/github/exiv2/exiv2 $ 
```

**Observation**

I have my doubts about the loop `for ( int i ...` I think it may be safer to test `( i < argc && errcnt_ == 0)`.  This also passes the test suite.  However it does modify the program behaviour.
```
521 rmills@rmillsmm:~/gnu/github/exiv2/exiv2 $ build/bin/exiv2 -A 20:00:00 -Y 2018 -O 11 -D 01 ad ./test/data/Reagan.tiff
exiv2: Unrecognized option -A
exiv2: An action must be specified
exiv2: At least one file is required
Usage: exiv2 [ options ] [ action ] file ...

Manipulate the Exif metadata of images.
522 rmills@rmillsmm:~/gnu/github/exiv2/exiv2 $ 
```

**Comment by cool-tomato** [comment]
I mean ,
```
if (!opt) {
   58 				if (opterr && *optstring != ':')
   59 					fprintf(stderr, "%s: illegal option: %c\n", argv[0], optopt);
   60 			       optind++;
           			       optpos = 1;
                                       return '?';
```
In this way, the output will be correct:
```
fish@ubuntu:~/Desktop/2018-10-10/exiv2/past_done_job_analysis$ ../debug/debug/bin/exiv2 -A 20:00:00 -Y 2999 -O 98 -D 21 ad Reagan.tiff
exiv2: Unrecognized option -A
Usage: exiv2 [ options ] [ action ] file ...

Manipulate the Exif metadata of images.
fish@ubuntu:~/Desktop/2018-10-10/exiv2/past_done_job_analysis$ ../debug/debug/bin/exiv2 -a 20:00:00 -Y 2999 -O 98 -D 21 ad Reagan.tiff
fish@ubuntu:~/Desktop/2018-10-10/exiv2/past_done_job_analysis$ ../debug/debug/bin/exiv2 -a 20:00:00 -y 2999 -O 98 -D 21 ad Reagan.tiff
exiv2: Unrecognized option -y
Usage: exiv2 [ options ] [ action ] file ...

Manipulate the Exif metadata of images.

```

**Comment by clanmills** [comment]
Thanks.  I'll have a look at this your way.  Perhaps I should put in both your fix in getopt() and mine in  Getopt::getopt().

**Comment by clanmills** [comment]
@cool-tomato I'm very please to say that @piponazo has fixed this.  #516 

We plan to remove that code in v0.28.  The history of this file is that the code was windows related in v0.26 and earlier.
```
618 rmills@rmillsmbp:~/gnu/exiv2/v0.26 $ wc src/getop*
     512    1928   13265 src/getopt_win32.c
      84     432    2868 src/getopt_win32.h
     596    2360   16133 total
619 rmills@rmillsmbp:~/gnu/exiv2/v0.26 $ 
```
Linux (MacOS-X, Cygwin, and MinGW/msys2) were using the platform getopt().  We discovered semantic differences between getopt() on different platforms (in libc or somewhere)  We agreed to stop using the platform getopt() and to adopt the windows code as we are consistent on different platforms (same bugs everywhere).

The top feature planned for Exiv2 v0.28 is to "modernise" the code which will involve only using C++11 (or later) and removing all legacy "C" code.  The files `localtime.c` and `tzfile.h` are retained for MinGW in v0.27, however they'll be removed after we release Exiv2 v0.27 GM (at the end of 2018). 

Thank You very much for bringing this to our attention.  I suspect that issue has been there in the Visual Studio builds for about 10 years and nobody has ever reported it.
