### ISSUE TITLE
Generating pkg-config file exiv2.pc from CMake build environment.

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#512]
In investigating #497 we were requested to support the pkg-config utility by generating the file exiv2.pc  @piponazo implemented this in #509

**Action**

1) No action is required in the code.
2) The platform notes releasenotes/platform/ReadMe.txt should be updated appropriately.
3) The "User Manual" README.md should be updated to discuss exiv2.pc.

**Analysis**

The v0.26 legacy code config/exiv2.in.cmake is:
```
522 rmills@rmillsmbp:~/gnu/exiv2/v0.26 $ cat config/exiv2.pc.cmake 
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: exiv2
Description: Exif and IPTC metadata library and tools
Version: @PACKAGE_VERSION@
URL: @PACKAGE_URL@
Libs: -L${libdir} -lexiv2 @EXV_LIB_STATIC@
Cflags: -I${includedir}
523 rmills@rmillsmbp:~/gnu/exiv2/v0.26 $ 
```

This has morphed in v0.27 into cmake/exiv2.pc.in
```
524 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ cat cmake/exiv2.pc.in 
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=${prefix}
libdir=@CMAKE_INSTALL_FULL_LIBDIR@
includedir=@CMAKE_INSTALL_FULL_INCLUDEDIR@

Name: exiv2
Description: Exif and IPTC metadata library and tools
Version: @PACKAGE_VERSION@
URL: @PACKAGE_URL@
Libs: -L${libdir} -lexiv2
Cflags: -I${includedir}
525 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ 
```

The legacy file contains the symbol @EXV_LIB_STATIC@ which we believe is a relic of autotools and no longer relevant.  I've looked at this in several different ways:

1) Does Exiv2 v0.27 exiv2.pc file work correctly for applications built with static and dynamic libraries.  Answer: **Yes**
2) What does exiv2 v0.26 CMake code (CMakeLists.txt and config/*.cmake) do with EXV_LIB_STATIC?  Answer: **Nothing**
```
533 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ cd ../../../exiv2/v0.26
534 rmills@rmillsmbp:~/gnu/exiv2/v0.26 $ find config -name "*" -type f -exec grep -H EXV_LIB_STATIC {} \;
config/configure.ac:    EXV_LIB_STATIC=$LTLIBICONV
config/configure.ac:    EXV_LIB_STATIC=
config/configure.ac:AC_SUBST(EXV_LIB_STATIC)
config/exiv2.pc.cmake:Libs: -L${libdir} -lexiv2 @EXV_LIB_STATIC@
config/autom4te.cache/traces.0:m4trace:configure.ac:310: -1- AC_SUBST([EXV_LIB_STATIC])
config/autom4te.cache/traces.0:m4trace:configure.ac:310: -1- AC_SUBST_TRACE([EXV_LIB_STATIC])
config/autom4te.cache/traces.0:m4trace:configure.ac:310: -1- m4_pattern_allow([^EXV_LIB_STATIC$])
config/autom4te.cache/output.0:EXV_LIB_STATIC
config/autom4te.cache/output.0:    EXV_LIB_STATIC=$LTLIBICONV
config/autom4te.cache/output.0:    EXV_LIB_STATIC=
config/exiv2.pc.in:Libs: -L${libdir} -lexiv2 @EXV_LIB_STATIC@
535 rmills@rmillsmbp:~/gnu/exiv2/v0.26 $ find . -name CMakeLists.txt -type f -exec grep -H EXV_LIB_STATIC {} \;
536 rmills@rmillsmbp:~/gnu/exiv2/v0.26 $
```
3) What's the difference between the v0.26 CMake exiv2.pc file and v0.27? Answer: **None**
```
531 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ diff exiv2.pc ../../../../exiv2/v0.26/build/exiv2.pc
3,4c3,4
< libdir=/usr/local/lib
< includedir=/usr/local/include
---
> libdir=${prefix}/lib
> includedir=${prefix}/include
8,10c8,10
< Version: 
< URL: 
< Libs: -L${libdir} -lexiv2
---
> Version: 0.26
> URL: http://www.exiv2.org
> Libs: -L${libdir} -lexiv2 
532 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $
```
4. Is the autotools generated exiv2.pc file different for static/shared builds.  Answer: **No**

5.  What does v0.26 autotools and CMake generate in exiv2.pc?
```
make config; ./configure --disable-shared --enable-static
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: exiv2
Description: Image metadata library and tools
Version: 0.26
Libs: -L${libdir} -lexiv2 -liconv
Libs.private:    -L/usr/local/lib -lintl -liconv -lc -R/usr/local/lib -Wl,-framework -Wl,CoreFoundation -liconv -lz   -lexpat
Cflags: -I${includedir}

512 rmills@rmillsmbp:~/gnu/exiv2/v0.26/build $ cat exiv2.pc
prefix=/usr/local
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: exiv2
Description: Exif and IPTC metadata library and tools
Version: 0.26
URL: http://www.exiv2.org
Libs: -L${libdir} -lexiv2 
Cflags: -I${includedir}
513 rmills@rmillsmbp:~/gnu/exiv2/v0.26/build $ 
```

6 Anything else?

I'm not happy that in v0.27 we are installing exiv2.pc into **`{prefix}/shared/exiv2.pc`** as that probably requires the user to modify PKG_CONFIG_PATH.  I believe it's more conventional (and v0.26 behaviour) to installing exiv2.pc into **`{prefix}/lib/pkgconfig/exiv2.pc`** which the user probably has already set up on their machine.

**Comment by piponazo** [comment]
Great investigation @clanmills . I agree with you on the point 6. We should install the file in `{prefix}/lib/pkgconfig/exiv2.pc` where pkg-config will look by default:

https://linux.die.net/man/1/pkg-config

I fix it today.

**Comment by piponazo** [comment]
I leave this open until you update the documentation. Please, remember to close the issue once you have updated the doc 😉

**Comment by lantw44** [comment]
It seems the generated .pc file is broken. This is master branch, commit afc1a1e5263e894360f80d9316e00d7668760079.
```
$ cat ~/gnome/devinstall/lib/pkgconfig/exiv2.pc 
prefix=/home/lantw44/gnome/devinstall
exec_prefix=${prefix}
libdir=/home/lantw44/gnome/devinstall/lib
includedir=/home/lantw44/gnome/devinstall/include

Name: exiv2
Description: Exif and IPTC metadata library and tools
Version: 
URL: 
Libs: -L${libdir} -lexiv2
Cflags: -I${includedir}
```

gexiv2 fails to configure because it cannot find the version number:
```
The Meson build system
Version: 0.48.1
Source dir: /home/lantw44/gnome/source/gexiv2
Build dir: /home/lantw44/gnome/build/gexiv2
Build type: native build
WARNING: Unknown options: "build_man, disable_gtkdoc, doc, docbook, docs, documentation, enable-doc, enable-man, enable_docs, enable_gtk_doc, enable_valadoc, gtk-doc, gtk_doc, gtkdoc, man, man-pages, manpage, with_docs"
Project name: gexiv2
Project version: 0.10.8
Appending CFLAGS from environment: '-march=corei7-avx -B/usr/local/bin -pipe -g -O3 -gz'
Appending LDFLAGS from environment: '-L/home/lantw44/gnome/devinstall/lib -L/usr/local/lib -B/usr/local/bin -Wl,--compress-debug-sections=zlib'
Native C compiler: clang -B/usr/local/bin (clang 6.0.0 "FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)")
Appending CXXFLAGS from environment: '-march=corei7-avx -B/usr/local/bin -pipe -g -O3 -gz'
Appending LDFLAGS from environment: '-L/home/lantw44/gnome/devinstall/lib -L/usr/local/lib -B/usr/local/bin -Wl,--compress-debug-sections=zlib'
Native C++ compiler: clang++ -B/usr/local/bin (clang 6.0.0 "FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/local/bin/pkg-config (1.5.4)
Dependency exiv2 found: NO unknown version, but need: ['>= 0.21']
Dependency exiv2 found: NO 

meson.build:5:0: ERROR:  Unknown version of dependency 'exiv2', but need ['>= 0.21'].

A full log can be found at /home/lantw44/gnome/build/gexiv2/meson-logs/meson-log.txt
```

**Comment by lantw44** [comment]
It is also recommended to define all variables in .pc file with `${prefix}` instead of hardcoding the prefix value multiple times, so users can easily override it with `pkg-config --define-variable=prefix=<value>` when it is needed.

**Comment by clanmills** [comment]
@lantw44 Thanks for those observations.  I'm very happy with the great feedback that you are providing.  If you can hand edit exiv2.pc to succeed on your machine, could you show us the code that's working for you.

**Observations**

1) I failed to notice (in the diff in point 3 above) that the version isn't in exiv2.pc
2) I did notice the `{prefix}` and `/usr/local` difference and mistakenly thought that was cosmetic.

I was under the impression that file *more or less* amounts to generating `-L/usr/local/include` for the compiler and `-lexiv2 -L/usr/local/lib` for the linker.  Clearly the version is of great importance.  The messages in your transcript about `docbook, docs,` are presumably from your build and not the concern of Exiv2.

**Progress**

Today, I have extensively reworked the documentation in README.md and releasenotes/platform/ReadMe.txt to respect exiv2.pc and those changes are on branch 0.27-RC2.

**Question**

In several locations, I have documented the compiler flag `-std=c++98` on the command-line.  Is this required in exiv2.pc?

**Comment by clanmills** [comment]
I updated this issue and renamed it.  My most recent comments have been lost.

Thank You @lantw44 for this very useful feedback.  Can you edit manually `exiv2.pc` on your machine to satisfy your build.  We'll update our generated file appropriately.

**Comment by clanmills** [comment]
Ah the GitHub Gods are smiling and my comments have reappeared.  It's been another long day (sigh).

**Comment by piponazo** [comment]
Thanks @lantw44 for your feedback. I will take care of this more carefully.

**Comment by lantw44** [comment]
> @lantw44 Thanks for those observations. I'm very happy with the great feedback that you are providing. If you can hand edit exiv2.pc to succeed on your machine, could you show us the code that's working for you.

Yes, this one works for me.
```
prefix=/home/lantw44/gnome/devinstall
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: exiv2
Description: Exif and IPTC metadata library and tools
Version: 0.27.0.1
URL: http://www.exiv2.org/
Libs: -L${libdir} -lexiv2
Cflags: -I${includedir}
```

> The messages in your transcript about `docbook, docs,` are presumably from your build and not the concern of Exiv2.

They are unrelated to Exiv2. These messages appeared because I passed a lot of unknown -D options to meson. It doesn't affect the build other than causing warnings to be shown.

> In several locations, I have documented the compiler flag `-std=c++98` on the command-line. Is this required in exiv2.pc?

No, flags changing the behavior of the compiler should not appear in .pc files. If a project using Exiv2 is written in a different version of C++ standard and uses a conflicting flag such as `-std=c++14`, the compiler will throw an error. Although the field is called `Cflags` (C compiler flags) in .pc, it should really be called `Cppflags` (C preprocessor flags) if we can design the format of .pc file again. The output of `pkg-config --cflags` is expected to only include flags which are meaningful to the preprocessor, such as `-I` and `-D`, so it won't conflict with other projects.

**Comment by clanmills** [comment]
Thank you @lantw44 for your feedback, especially concerning `-std=c++98`.  I discussed this with @piponazo on Slack and we thought this should not be in `exiv2.pc`.

I see that this is closed and the fix is on `master`.  I expect it'll arrive soon on branch `0.27-RC2` (0.27.0.2)
```
513 rmills@rmillsmbp:~/gnu/github/exiv2/master/build $ grep -i version exiv2.pc 
Version: 0.27.0.1
514 rmills@rmillsmbp:~/gnu/github/exiv2/master/build $
```
