### ISSUE TITLE
Debian build broken on GitLab

### ISSUE THREAD

**Issue by D4N** [Exiv2/exiv2#519]
On the weekend the Debian builds on GitLab started failing, see for instance: for https://gitlab.com/D4N/exiv2/-/jobs/116275047. It complains about the cmake variable `CMAKE_DESCRIPTION_COMPILER_ENV_VAR` being unset.

@piponazo have you ever heard of that?

**Comment by piponazo** [comment]
O_O ... it seems that the `DESCRIPTION` variable can be only used from CMake 3.9. I'll revert that change.
