### ISSUE TITLE
How to remove XMP Region tag from JPEG ?

### ISSUE THREAD

**Issue by cgilles** [Exiv2/exiv2#521]
See the JPEG sample face-tagged with Mylio photo manager : 

https://bugs.kde.org/attachment.cgi?id=114448

The XMP  contents is this one : 

[gilles@localhost Téléchargements]$ exiv2 -px DSC_3079.jpg   
Xmp.MY.DateConfidence                        XmpText     4  Full
Xmp.exifEX.PhotographicSensitivity           XmpText     2  64
Xmp.mwg-rs.Regions                           XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:w XmpText     3  540
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:h XmpText     3  960
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:unit XmpText     5  pixel
Xmp.mwg-rs.Regions/mwg-rs:RegionList         XmpText     0  type="Seq"
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]      XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Type XmpText     4  Face
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Name XmpText     7  America
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:x XmpText     8  0.825794
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:y XmpText     8  0.379665
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:w XmpText     8  0.110064
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:h XmpText     8  0.077389
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:unit XmpText    10  normalized
Xmp.dc.subject                               XmpBag      1  America

The Xmp.mwg-rs.Regions define the data structure to host regions of image.
I want to remove these region data. I tried to remove this tag as well : 

[gilles@localhost Téléchargements]$ exiv2 -v -M"del Xmp.mwg-rs.Regions" DSC_3079.jpg
File 1/1: DSC_3079.jpg
Del Xmp.mwg-rs.Regions
[gilles@localhost Téléchargements]$

No error, no warning, all sound good, but not in fact : 

[gilles@localhost Téléchargements]$ exiv2 -px DSC_3079.jpg 
Xmp.MY.DateConfidence                        XmpText     4  Full
Xmp.exifEX.PhotographicSensitivity           XmpText     2  64
Xmp.mwg-rs.Regions                           XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:w XmpText     3  540
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:h XmpText     3  960
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions/stDim:unit XmpText     5  pixel
Xmp.mwg-rs.Regions/mwg-rs:RegionList         XmpText     0  type="Seq"
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]      XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Type XmpText     4  Face
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Name XmpText     7  America
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area XmpText     0  type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:x XmpText     8  0.825794
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:y XmpText     8  0.379665
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:w XmpText     8  0.110064
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:h XmpText     8  0.077389
Xmp.mwg-rs.Regions/mwg-rs:RegionList[1]/mwg-rs:Area/stArea:unit XmpText    10  normalized
Xmp.dc.subject                               XmpBag      1  America

[gilles@localhost Téléchargements]$ exiv2 --version
exiv2 0.27.0.1
...

What's wrong ?

Gilles Caulier

**Comment by clanmills** [comment]
I think I know what's causing this. I'm very surprised this has never been reported years ago.

Exiv2 stores metadata in an array and you can add/delete/update any member.  That's OK for Exif and IPTC metadata, however it's not a valid concept for XMP in which the metadata is stored in a hierarchy.  It's not possible to delete an XmpBag (a struct) or XmpSeq (an array) without deleting all the data in the composite structure.  So we need a recursive "delete" to take care of deleting the contents of Xmp data structures.  I have the recursive code in samples/exiv2json.cpp.

It's possible to work-around this by extracting the XML, using an xml tool such as xmllint to manipulate the XML, and then insert into the image:

<pre>$ exiv2 -pX image | xmllint some-xslt-magic | exiv2 -iXi image-path</pre> 

I'm not certain about this, as I'm still working on it.  I was working on this yesterday evening.  This morning, the machine has died will take hours to reload from TimeMachine.

So, I'm believe I understand this puzzle and I'm working on it.

**Comment by clanmills** [comment]
Good News.  I've got a work around in **`actions.cpp`**.  However the fix will need to be "deeper" in the code to work inside the library and not in the exiv2 command-line application.

We don't need a recursion to deal with this.  I noticed that when XMPdata "children" of an XmpBag or XmpSeq with keys that match their parent.  For example:
```
Xmp.mwg-rs.Regions XmpText 0 type="Struct"
Xmp.mwg-rs.Regions/mwg-rs:AppliedToDimensions XmpText 0 type="Struct"
```

So the fix is to delete the key requested **`-M"del Xmp.mwg-rs.Regions"`**, then continue to delete keys of matching children.

The correct fix should be in `XmpData::iterator XmpData::erase`, however when I put the code there, it segfaults because it has to return an iterator and I'm causing an auto_ptr to be incorrectly deleted.  Tomorrow, I figure this out. 
  
```
557 rmills@rmillsmm:~/gnu/github/exiv2/exiv2/cmake-build-debug $ git diff
diff --git a/src/actions.cpp b/src/actions.cpp
index a52145cf..8ce3b137 100644
--- a/src/actions.cpp
+++ b/src/actions.cpp
@@ -1615,8 +1615,19 @@ namespace Action {
         if (modifyCmd.metadataId_ == xmp) {
             Exiv2::XmpData::iterator pos;
             Exiv2::XmpKey xmpKey = Exiv2::XmpKey(modifyCmd.key_);
-            while((pos = xmpData.findKey(xmpKey)) != xmpData.end()) {
+
+            while((pos = xmpData.findKey(xmpKey)) != xmpData.end() ) {
+                std::string key = xmpKey.key();
                 xmpData.erase(pos);
+                // https://github.com/Exiv2/exiv2/issues/521
+                // delete 'children' of XMP composites (XmpSeq and XmpBag)
+                while ( pos != xmpData.end() ) {
+                    if ( pos->key().find(key)==0 ) {
+                        xmpData.erase(pos);
+                    } else {
+                        break ;
+                    }
+                }
             }
         }
     }
558 rmills@rmillsmm:~/gnu/github/exiv2/exiv2/cmake-build-debug $ 
```

**Comment by clanmills** [comment]
I'm going to close this.  It's been dealt with and the file DSC_3079.jpg has been added to the test harness.  Last Friday, I spend time deleting items on the  array (XmpSeq), structures (XmpBag) and individual fields in a structure (XmpBag).  Everything is working as I would expect.

**Comment by devingfx** [comment]
Hi!
I've got troubles to delete some XmpSeq elements too with CLI, as this seems to be an old issue maybe I'm not doing this right, can someone help ?

I added several time the same info by mistake, and am trying to get rid of some elements with no effect !

Here is what I tested:

```bash
$ exiv2 -pa tests/test7.png
Xmp.dc.creator                               XmpSeq      DiGreg.art, DiGreg.art, DiGreg.art, DiGreg.art
$ exiv2 -M 'del Xmp.dc.creator[2]' tests/test7.png
$ exiv2 -pa tests/test7.png
Xmp.dc.creator                               XmpSeq      DiGreg.art, DiGreg.art, DiGreg.art, DiGreg.art
$ exiv2 -M 'del Xmp.dc.creator[5]' tests/test7.png
$ exiv2 -pa tests/test7.png
Xmp.dc.creator                               XmpSeq      DiGreg.art, DiGreg.art, DiGreg.art, DiGreg.art
```
