### ISSUE TITLE
c++11: Remove rwlock.hpp and use std::lock_guard 

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#525]
Once we migrate to C++11 we could remove the existing the file `rwlock.hpp`and use `std::lock_guard` to achieve the same goal.

**Comment by clanmills** [comment]
I totally agree with this.  I accepted that from a user (in Estonia I think) and it created lots of build/platform issues.

I think the code is only in the exiv2 application and not in the library.

We should never put a lock into the library.  If we ever need a lock in the library, we provide an API so the client/host code can tell us how to get it.  The library mustn't lock without consent.  Locking leads to dead-locking.

**Comment by D4N** [comment]
There is a todo list in #214, with all the stuff that can be done for C++11. I'd suggest that we add this to the list and close this issue.

**Comment by piponazo** [comment]
Yes, I knew about that list, but I thought it could be a good idea to create a separate issue and mark it as "**good first issue**" so that a random contributor could take it at some point.

The other day I investigated a bit about the difference of Github **projects** and **milestones**:
https://stackoverflow.com/questions/39591795/what-is-the-difference-relationship-between-github-projects-and-milestones

It seems that **projects** are well suited to describe big "Stories" or "Epics". We could create a project named "C++11 Migration" and assign different issues to it (instead of having all the details in a single issue).

**Comment by clanmills** [comment]
I agree.  I've opened a new Milestone v0.28 and assigned #214 to that.

**Comment by tbeu** [comment]
I am afraid for a proper rwlock (shared read and exclusive write) we need to wait for C++14 to use `std::shared_timed_mutex` or even C++17 to use the untimed `std::shared_mutex`. However, the current Win implementation of `class RWLock` in rwlock.hpp is not a rwlock at all.
