### ISSUE TITLE
Issue compiling samples/taglist.cpp in Xcode 10

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#528]
This was reported to Apple:
https://bugreport.apple.com/web/?problemID=45223696

I documented the issue in releasenotes/releasenotes.txt for v0.27 RC1

I've had a response from Apple.  I think they are saying "Can't reproduce".  I'll install a fresh MacOS-X VM with Xcode 10 and try again.  

_Engineering has requested the following information in order to further investigate this issue:_

_Can you please tell at what revision the problem should be reproducible? It looks like there were changes made to work around the problem, so, maybe that’s why it’s not reproducible anymore. In our testing revisions 12d44f8f17bb541d5ce0c05e6020bc5d79a03e34 and afc1a1e5263e894360f80d9316e00d7668760079 were built successfully and resulting ./bin/taglist runs without crashing._

**Comment by cgilles** [comment]
Just for info, git/master code compile fine with XCode 9.1 (last version updated), under my Macbook pro with Mojave 10.14.1

Gilles Caulier

**Comment by clanmills** [comment]
Thanks, Gilles.  Yes.  I am building successfully with Xcode 9.4 on my laptop and buildserver.  I see Apple released Xcode 10.1 on Oct 30.  I'm downloading and installing that now on the laptop.

**Comment by clanmills** [comment]
Apple are correct.  The issue is resolved with Xcode 10.1.  Odd because I'm sure it's the same version of the clang compiler as Xcode 10.0.  Anyway, good news.  Another matter closes.  I'll thank Apple for their response.
