### ISSUE TITLE
Cache FileIo::size()

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#530]
This matter has arisen from this discussion:  https://github.com/Exiv2/exiv2/issues/515

BasicIo::eof() returns BasicIo::tell() == BasicIo::size() and, as explained in #515 has slightly different semantics from `::feof()`  As FileIo::size() calls ::stat() this can cause a large number of system calls in a large PNG.

In the discussion, I experimented with cacheing within FileIo::size() while reading files.  The performance gain seems valuable (about 30%-40% better).  However my patch failed the test suite in many places and would require more work before being ready for release. 

Cacheing FileIo::size() is worthy of more investigation in Exiv2 v0.28.

**Comment by piponazo** [comment]
Changes merged into 0.27 (#1178) & master (#1179)
