### ISSUE TITLE
TAMRON SP 15-30mm F/2.8 Di VC USD A012 len recognition

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#532]
http://dev.exiv2.org/issues/1306

**Comment by piponazo** [comment]
It seems that the fix was already merged in #20 . Is there something missing ?

**Comment by piponazo** [comment]
We even have a test case in the python suite (file: `tests/bugfixes/github/test_issue_20.py`).

**Comment by clanmills** [comment]
I "moved" it here from Redmine.  Looks as though it really is closed.
