### ISSUE TITLE
Issues with localisation on 'master' (on 2018-11-11)

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#537]
@piponazo I know that localisation support is "work-in-progress".  Here are my observations:

1) On MacOS-X, the build fails when linking the exiv2 command line program.  I manually fixed this by editing build/src/exiv2.dir/link.dir to mention /usr/local/lib/libexiv2.dylib.

```
[ 39%] Linking CXX executable ../bin/exiv2
Undefined symbols for architecture x86_64:
  "_libintl_bindtextdomain", referenced from:
      bindtextdomain(char const*, char const*) in exiv2.cpp.o
  "_libintl_setlocale", referenced from:
      _main in exiv2.cpp.o
  "_libintl_textdomain", referenced from:
      textdomain(char const*) in exiv2.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/exiv2] Error 1
make[1]: *** [src/CMakeFiles/exiv2.dir/all] Error 2
make: *** [all] Error 2
565 rmills@rmillsmbp:~/gnu/github/exiv2/master/build $ 
```

I believe the fix is in src/CMakeLists.txt
```
595 rmills@rmillsmbp:~/gnu/github/exiv2/master/build $ git diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 9ab270d0..d6a2ee8d 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -334,6 +334,9 @@ if(EXIV2_BUILD_EXIV2_COMMAND)
     )
 
     target_link_libraries( exiv2 PRIVATE exiv2lib )
+    if( EXIV2_ENABLE_NLS )
+        target_link_libraries( exiv2 PRIVATE  ${LIBINTL_LIBRARIES} )
+    endif()
 
     # modify source lists to suit environment
     target_include_directories(exiv2 PRIVATE ${CMAKE_SOURCE_DIR}/include/)
596 rmills@rmillsmbp:~/gnu/github/exiv2/master/build $ 
```

2) I have to install the .mo files to use them from the installed exiv2.  They are never used by build/bin/exiv2.

```
583 rmills@rmillsmbp:~/gnu/github/exiv2/master/build $ env LC_ALL=fr_FR bin/exiv2
exiv2: An action must be specified
exiv2: At least one file is required
Usage: exiv2 [ options ] [ action ] file ...

Manipulate the Exif metadata of images.
584 rmills@rmillsmbp:~/gnu/github/exiv2/master/build $ env LC_ALL=fr_FR exiv2
exiv2: Une action doit être spécifié
exiv2: Au moins un fichier est nécessaire
Utilisation : exiv2  [ options ] [ action ] fichier ...

Manipulation des métadonnées EXIF issues des images.
585 rmills@rmillsmbp:~/gnu/github/exiv2/master/build $ 
```

3) I'm not sure that libintl should be linked with libexiv2 as I believe it's only used by applications such as the exiv2 command-line program. 

4) Perhaps we should add localisation to every sample application by calling a new API Exiv2::loadLocalisation().  This API would understand when it's called in build/bin and load appropriately.  Of course, if we do this we must link libintl with libexiv2.

5) I think we're building the .mo files during install.  We should build the .mo files in the build directory and copy them during install.  I need them to be built in the build/share directory so they can be copied from a binary build into share.  In releasenotes/platform/ReadMe.txt, I've documented the following:

```
To install for use by all users
-------------------------------
$ for i in bin include lib ; do
   sudo mkdir -p /usr/local/$i ; sudo cp -R $i/* /usr/local/$i ;
done
```
This can only work if the .mo files are created by the build itself.

**Comment by piponazo** [comment]
Hi Robin, please find attached few comments regarding each point:

1. It's strange that you had a linking problem, the changes were tested in all the platforms with the CI jobs and it is working on OSX Images provided by travis: https://travis-ci.org/Exiv2/exiv2/jobs/453535170. However I tried in your OSX machine with my user and I had the same problem. We can fix the issue with the patch you provided, or this one:

```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 9ab270d0..039a5a34 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -293,7 +293,7 @@ if( EXIV2_ENABLE_PNG )
 endif()
 
 if( EXIV2_ENABLE_NLS )
-    target_link_libraries( exiv2lib PRIVATE  ${LIBINTL_LIBRARIES} )
+    target_link_libraries( exiv2lib PUBLIC  ${LIBINTL_LIBRARIES} )
 endif()
 
 if( ICONV_FOUND )
```

I think I would chose yours, since mine is saying: "Any consumer of exiv2lib will need to link with LIBINTL" and that should not be not true, it should be optional. 

2. Yes, it is necessary to install the **.mo** files to use the translations (as with any other application having translations). Do you think there is something to improve regarding this point?

3. At the moment I think it is mandatory to link **exiv2lib** against **libintl** since we have code in `src/types.cpp` (which is part of the library) making use of **libintl** functions. We also have a custom function called `exvGettext()` which is being used in many places of **exiv2lib**. 

4. I like the idea of having a API function `Exiv2::loadLocalisation(const std::string& language)` and use it in the **exiv2** application (also other consumers of exiv2 like digikam could use it). However I would not use it in the sample applications we provide. The samples are small applications that should be focused in some specific cases. I do not think it is necessary or appropriate to add the localisation feature for such sample applications.

**Comment by clanmills** [comment]
Thanks for the update, Luis.  I thought of a fifth issue and edited the issue report.  We need to build the .mo files during the build and not during install.  I need those files in the build bundles.

I'm happy that you prefer my patch for the libintl issue.  There's nothing special about the build machine.  I discovered this on my laptop.  So the mystery is why Travis passes (don't investigate).

I agree that we should not call Exiv2::loadLocalisation() from samples/*.cpp.

I wasn't aware that  types.cpp uses libintl.  However, that's fine.  We link libintl with the library and use Exiv2::loadLocalisation() to load the files at run time.  If you want to have an argument loadLocalisation(language), could you use loadLocalisation("") to mean default and fall back on the system to respect LC_ALL, LANG etc.  We don't need to know/understand/implement those rules.

About point (2) using localisation from the build/bin directory.  Let's discuss another time.  For sure, I don't need this for RC2.  I'll be home on Monday evening.  

Alison is asking the question "do you two never stop working?".  She knows the answer.

**Comment by piponazo** [comment]
Regarding your 5th point, the .mo files are generated right now at build time, but I also noticed that during the install step we are also repeating some stuff. It's true that there is room of improvement over there, and I think these problems will be solved once we deal with #536. 

I am not sure if I could address these issues during the next weeks. But anyways, I think they are not critical for releasing 0.27.

**Comment by clanmills** [comment]
1) Build is creating .gmo file (and that's fine)
I built on Linux this morning and was surprised that the build created .gmo files.  The install copies and renames them.  A little inconvenient, however that's how it is.
```
build/po/fr.gmo  => /usr/local/share/locale/fr/LC_MESSAGES/exiv2.mo 
```

2) Localisation doesn't seem to work on Ubuntu:

localeDir is correct!
```
rmills@rmillmbp-ubuntu:~/gnu/github/exiv2/master$ exiv2 -vV --grep date --grep time 2>/dev/null
localeDir = /usr/local/bin/../share/locale
exiv2 0.27.0.1
date=Nov 12 2018
time=06:36:37
have_gmtime_r=1
xmlns=mediapro:http://ns.iview-multimedia.com/mediapro/1.0/
rmills@rmillmbp-ubuntu:~/gnu/github/exiv2/master$ env LC_ALL=fr_FR exiv2
localeDir = /usr/local/bin/../share/locale
exiv2: An action must be specified
exiv2: At least one file is required
Usage: exiv2 [ options ] [ action ] file ...

Manipulate the Exif metadata of images.
rmills@rmillmbp-ubuntu:~/gnu/github/exiv2/master$ 
```

3) Building localisation is very verbose
The build is producing a great deal of output (from msgfmt or something).  Perhaps there's a --quiet option to make him less verbose, or filter the output through `wc`.

**Comment by piponazo** [comment]
I just noticed another problem with the localisation and cmake setup. By calling `make clean` in the build directory the original **.po** files get deleted. This should not happen.

**Comment by clanmills** [comment]
Four further issues:

1) We need **`$ env LANG=fr_FR exiv2`** on Linux
2) Localisation isn't working on Cygwin and MinGW/msys2 because Exiv2::getProcessPath() returns **`"unknown"`**
3) README.md doesn't document needing gettext-devel to build localisation MinGW
4) Update documentation to recommend LANG=fr_FR for localisation on all platforms

**Comment by clanmills** [comment]
I'm going to close this.  This is an "umbrella" collection of observations concerning localisation for v0.27 RC2.  I believe every topic discussed has been addressed and solved.  If any of those matters reappear, I will open new issues to track them individually.

@piponazo I'm not sure if it's right or wrong to remove the exiv2.mo files during make clean.  If the user has an earlier version of exiv2 on their machine, it's rather brutal to remove the localisation files which (unlike the library) are not stored by version.  If you feel this is a "must fix", please open a new issue.
