### ISSUE TITLE
Do we need CMake 3.12 to build?

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#543]
I got errors from cmake 3.10 on msvc concerning **add_compile_definitions**.  I updated CMake to 3.12.4 on the buildserver and everything's working.  Comment?

**Comment by D4N** [comment]
We should not require a too recent version of Cmake, otherwise we'll
make packaging needlessly hard.

Also we should be using target_compile_definitions instead (which is
available in older cmake versions).

**Comment by clanmills** [comment]
@D4N.  It's likely that there's nothing of concern here and @piponazo will close simply this.  He did a "CMake Cleanup" #540 yesterday and may have used a recent CMake feature without realising.  There was something similar last week concerning **DESCRIPTION** #520

**Comment by cgilles** [comment]
Just for info, KDE project limit the minimal version of cmake to 3.0.1 for the moment...
Gilles Caulier

**Comment by clanmills** [comment]
I think I'm mistaken here.  I'm able to build on my laptop with CMake 3.10.3.  I'll leave this open to be sure the @piponazo has seen this, however I expect he'll close it.

**Comment by piponazo** [comment]
My bad, I did not notice that `add_compile_definitions` is just available from CMake 3.12, and it did not fail on CI because the AppVeyor Images are providing CMake 3.12.

I will change it to use `target_compile_definitions` as @D4N suggested.

**Comment by piponazo** [comment]
In #546 I replaced `add_compile_definitions` by `add_definitions`. `target_compile_definitions` could have been also used, and in most of the cases it is recommended. However in this particular case we would need to add those definitions for many targets (libraries, apps, samples) conditionally only for windows, and I think it is cleaner to just use `add_definitions` in one place.
