### ISSUE TITLE
Exiv2 from git/master : make install miss header files

### ISSUE THREAD

**Issue by cgilles** [Exiv2/exiv2#551]
From git/master today : 

[gilles@localhost build]$ su
Mot de passe : 
[root@localhost build]# make install/fast
Install the project...
-- Install configuration: ""
-- Installing: /usr/lib64/pkgconfig/exiv2.pc
-- Installing: /usr/lib64/libxmp.a
-- Installing: /usr/lib64/libexiv2.so.0.27.0.2
-- Installing: /usr/lib64/libexiv2.so.27
-- Up-to-date: /usr/lib64/libexiv2.so
-- Set runtime path of "/usr/lib64/libexiv2.so.0.27.0.2" to "$ORIGIN/../lib64"
-- Old export file "/usr/share/exiv2/cmake/exiv2Config.cmake" will be replaced.  Removing files [/usr/share/exiv2/cmake/exiv2Config-noconfig.cmake].
-- Installing: /usr/share/exiv2/cmake/exiv2Config.cmake
-- Installing: /usr/share/exiv2/cmake/exiv2Config-noconfig.cmake
-- Installing: /usr/bin/exiv2
-- Set runtime path of "/usr/bin/exiv2" to "$ORIGIN/../lib64"
-- Up-to-date: /usr/share/man/man1/exiv2.1
[root@localhost build]# 

If i switch to git RC1 tag, make install copy the header files as expected. So, it's a regression.

Gilles Caulier

**Comment by piponazo** [comment]
oh god ... it was my bad while refactoring CMake code. Thanks a lot for reporting. I'll fix it in few minutes and I'll add some check in the CI for this.

**Comment by clanmills** [comment]
Thanks you @gilles for letting us know.
