### ISSUE TITLE
Exiv2 from git/master : DataBuf symbol not found

### ISSUE THREAD

**Issue by cgilles** [Exiv2/exiv2#552]
Scanning dependencies of target digikamcore
[ 55%] Building CXX object core/app/CMakeFiles/digikamcore.dir/utils/digikam_debug.cpp.o
[ 55%] Building CXX object core/app/CMakeFiles/digikamcore.dir/digikamcore_automoc.cpp.o
[ 55%] Linking CXX shared library libdigikamcore.so
../libs/metadataengine/CMakeFiles/dmetadata_src.dir/engine/metaengine_exif.cpp.o: dans la fonction « Digikam::MetaEngine::getExifThumbnail(bool) const »:
/home/gilles/devel/6.X/core/libs/metadataengine/engine/metaengine_exif.cpp:884: référence indéfinie vers « Exiv2::DataBuf::DataBuf(Exiv2::DataBufRef) »
../libs/metadataengine/CMakeFiles/dmetadata_src.dir/engine/metaengine_exif.cpp.o: dans la fonction « Exiv2::ValueType<unsigned int>::dataArea() const »:
/usr/include/exiv2/value.hpp:1740: référence indéfinie vers « Exiv2::DataBuf::DataBuf(Exiv2::DataBufRef) »
collect2: erreur : ld a retourné 1 code d'état d'exécution
core/app/CMakeFiles/digikamcore.dir/build.make:2109 : la recette pour la cible « core/app/libdigikamcore.so.6.0.0 » a échouée
make[2]: *** [core/app/libdigikamcore.so.6.0.0] Erreur 1
CMakeFiles/Makefile2:9006 : la recette pour la cible « core/app/CMakeFiles/digikamcore.dir/all » a échouée
make[1]: *** [core/app/CMakeFiles/digikamcore.dir/all] Erreur 2
Makefile:138 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

Not reproducible with RC2 tag...

Gilles Caulier

**Comment by piponazo** [comment]
It seems like you have some old header installed in `/usr/include/exiv2/value.hpp:1740` the signature of `Exiv2::DataBuf::DataBuf(Exiv2::DataBufRef)` has changed slightly and now it is `Exiv2::DataBuf::DataBuf(const Exiv2::DataBufRef&)`. 

By having in **/usr/include/exiv2/** the latest version of the headers and linking against the latest version of the library the issue should be gone.

**Comment by cgilles** [comment]
The error come from a computer freshly installed without any Exiv2. I just copie all public headers by hand on the system. Strange...

Gilles

**Comment by piponazo** [comment]
Humm, really strange. I'm going to merge #553 in few minutes that is solving the issue with the installation. If you could try later with master to check if this issue is gone, we would appreciate it :wink:

**Comment by piponazo** [comment]
I can also try to add some unit tests for this function to see if I can reproduce the issue inside exiv2.

**Comment by cgilles** [comment]
Yes, your last commit to fix install headers close this problem...
