### ISSUE TITLE
Question: is it possible to extract metadata from INDD and PDF file using this library?

### ISSUE THREAD

**Issue by subbagudipalli** [Exiv2/exiv2#567]
XMP (and also custom XMP attributes) and IPTC

**Comment by clanmills** [comment]
Support for PDF has been on our wish-list for years.  It's a big job!  I worked at Adobe in San Jose, California for more than 10 years.  So, I'm motivated.  However it's quite an undertaking.

XMP and IPTC are supported.

I don't know what INDD is.
