### ISSUE TITLE
Issues with clang

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#574]
I think we should only support clang >= 5 on Linux.

I've given up trying to get clang to work on Cygwin/MinGW/DOS.  And clang-4 on ubuntu-14.04.  It can't compile hello.cpp:
```
#include <iostream>
int main(int argc,const char* argv[])
{
	std::cout << "hello world" << std::endl;
	for ( int i = 0 ; i < argc ; i++ ) {
		std::cout << argv[i] << std::endl;
    }
	return 0;
}
```

I've encountered issues with Clang 3.4 on Ubuntu 14.04 with -DEXIV2_TEAM_ENABLE_SANITERS=On which uses the option -fno-sanitize-recover=all.  This option was added in GCC5, I believe.

**Comment by D4N** [comment]
The 
`fno-sanitize-recover=all` option is being added via a version check against the used clang version.  However, I only guessed which version of clang added that flag, so adjusting it should fix a part of the issue.

**Comment by clanmills** [comment]
I will document that we support Clang 5 and up.  We could put something into the code to refuse to build with Clang < 5, however let's not do that.  I was able to build and run the test suite with Clang 3.4.  OK -DEXIV2_TEAM_USE_SANITIZERS doesn't work on Clang 3.4.  Not a problem.

I'll assign this to Luis.  He can touch the code and close this.  Or just close this.

We will reach RC3 tomorrow (2018-11-30).  We're done.  The branch 0.27 will be created and we hope the only change in there will be the revision number.  

Both you and Luis are starting new jobs next week.  I'm going to stop working on the computer 12 hours/day.  I'll run 10k and play the Euphonium every day.  Life is wonderful.

**Comment by piponazo** [comment]
To use clang on windows is not yet a common practice and therefore, I think we should not do anything about it (not even mention it in any of our document).

As you mentioned you can use clang-3.4 although not with the SANITIZERS option enabled. 

As you can see in this document, starting from clang 3.3, they have c++11 complete support:
https://clang.llvm.org/cxx_status.html

So, in principle, in Linux/OSX any version starting from clang 3.3 it should be good for 0.28. I suspect that for 0.27 even later versions should be ok. However I do not think we should research up to which specific we support. Right now we have a job in travis CI which is compiling with clang-3.5. If somebody opens an issue about a clang related compilation issue we will investigate it.
