### ISSUE TITLE
Investigation into building unit_tests without conan

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#575]
I'm putting these notes for my benefit and this issue will be closed in a couple days.

I'm very pleased that we can build and run the unit_tests on msvc builds thanks to conan.  And they build OK on MacOS-X without using conan.  I've been unable to build Exiv2 with conan on Cygwin and/or MinGW and I've said in the docs that we don't support this.

Thanks to Dan's wonderful script ci/install_dependencies.sh, setting up on Linux is easy and is documented in README.md.

1) Building and installing static gtest libraries from https://github.com/google/googletest/archive/release-1.8.0.tar.gz

```
$ mkdir -p ~/gnu/gtest
$ cp release-1.8.0.tar.gz ~/gnu/gtest
$ cd ~/gnu/gtest
$ tar xzf release-1.8.0.tar.gz
$ cd googletest-release-1.8.0
$ mkdir build
$ cd build
$ cmake .. -DBUILD_SHARED_LIBS=0
$ make
$ sudo make install
```

2) Building exiv2 with unit_tests

```
$ mkdir -p <exiv2dir>/build
$ cd <exiv2dir>/build
$ cmake .. -DEXIV2_BUILD_UNIT_TESTS=1
$ make
$ bin/unit_tests.exe
```

**Comment by D4N** [comment]
Getting gtest to run should be very simple on Linux. Take a look at ci/install_dependencies.sh, that should get the job done on the major distros.

**Comment by clanmills** [comment]
Thanks Dan.  At the moment, I'm trying to get it to work on MinGW and CYGWIN.  I'm confident that I'll get it working.  It worked effortlessly on the Mac and MSVC (using conan).

I didn't get to RC3 yesterday.  However I'm really close.

Good Luck with the new job.  Luis starts his new job on Monday.  Excited for both of you.

**Comment by clanmills** [comment]
Thanks Dan.  At the moment, I'm trying to get it to work on MinGW and CYGWIN.  I'm confident that I'll get it working.  It worked effortlessly on the Mac and MSVC (using conan).

I didn't get to RC3 yesterday.  However I'm really close.

Good Luck with the new job.  Luis starts his new job on Monday.  Excited for both of you.
