### ISSUE TITLE
[FR] `-T` without rename

### ISSUE THREAD

**Issue by RichiH** [Exiv2/exiv2#578]
I need to restore local mtime from EXIF regularly, but maintain original file names. `exiv2 rename` is a destructive operation, `exiv2 rename -T` is benign.

Would you be willing to either introduce a new keyword just for c/mtime editing, or allow `exiv2 adjust -T`?

**Comment by clanmills** [comment]
This is a very old issue and nobody else has requested this.  The exiv2 command-line program is a useful utility and it's primary aim is to test the code in the exiv2 library.  c/mtime editing is platform dependant.  This is an image handling/work-flow issue and should be handled elsewhere.  For example in a script, or a image browsing application.
