### ISSUE TITLE
ci/install_dependencies.sh ubuntu 14.04.5 error

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#581]
This script is recommended in README.md, so it's important that it works smoothly.

Perhaps we should have a ReadMe.txt in the ci/ directory to explain what the different script do.  I've found `sudo ./install.sh` is great for installing conan.  However I have to `$ sudo cp conan/bin/conan /usr/local/bin` to get conan on the path.

Anyway, let's focus on install_dependencies.sh
 
```
$ cd <exiv2dir>/ci
$ sudo ./install_dependencies.sh
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
~/gnu/github/exiv2/exiv2/ci ~/gnu/github/exiv2/exiv2/ci
CMake Error: The source directory "/usr/src/googletest/googletest" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
rmills@ubuntu:~/gnu/github/exiv2/exiv2/ci$ 
```

Indeed, /usr/src/googletest/googltest does not exist:
```
rmills@ubuntu:~/gnu/github/exiv2/exiv2/ci$ ls -l /usr/src
total 20
drwxr-xr-x  4 root root 4096 Dec  3 11:35 gmock
drwxr-xr-x  4 root root 4096 Dec  3 11:35 gtest
drwxr-xr-x 27 root root 4096 Aug  3  2016 linux-headers-4.4.0-31
drwxr-xr-x  7 root root 4096 Aug  3  2016 linux-headers-4.4.0-31-generic
drwxr-xr-x  6 root root 4096 Dec  3 11:07 parallels-tools-14.1.0.45387
rmills@ubuntu:~/gnu/github/exiv2/exiv2/ci$ 
```

The reference to googletest is from **`contrib/vms/utils.source`**:

```
rmills@ubuntu:~/gnu/github/exiv2/exiv2/ci$ grep -Hn googletest ../contrib/vms/*
../contrib/vms/utils.source:8:# Debian & derivatives don't provide binary packages of googletest
../contrib/vms/utils.source:11:# This script builds a shared library of googletest (not googlemock!) inside
../contrib/vms/utils.source:17:    cmake -DBUILD_SHARED_LIBS=1 /usr/src/googletest/googletest
rmills@ubuntu:~/gnu/github/exiv2/exiv2/ci$ cat ../contrib/vms/utils.source 
#!/bin/sh

function get_distro_id() {
    local distro_id=$(grep '^ID=' /etc/os-release|awk -F = '{print $2}'|sed 's/\"//g')
    echo "$distro_id"
}

# Debian & derivatives don't provide binary packages of googletest
# => have to build them ourselves
#
# This script builds a shared library of googletest (not googlemock!) inside
# gtest_build and copies it to /usr/lib/
function debian_build_gtest() {
    pushd .
    [ -d gtest_build ] || mkdir gtest_build
    cd gtest_build
    cmake -DBUILD_SHARED_LIBS=1 /usr/src/googletest/googletest
    make
    cp libgtest* /usr/lib/
    popd
}
rmills@ubuntu:~/gnu/github/exiv2/exiv2/ci$ 
```

I hacked the code to work.  I suspect we need a more robust test such as `if [ -d /usr/scr/googletest/googlest ] ..` 

```
rmills@ubuntu:~/gnu/github/exiv2/exiv2$ git diff contrib/vms/utils.source
diff --git a/contrib/vms/utils.source b/contrib/vms/utils.source
index ddeef60..916b258 100644
--- a/contrib/vms/utils.source
+++ b/contrib/vms/utils.source
@@ -14,7 +14,7 @@ function debian_build_gtest() {
     pushd .
     [ -d gtest_build ] || mkdir gtest_build
     cd gtest_build
-    cmake -DBUILD_SHARED_LIBS=1 /usr/src/googletest/googletest
+    cmake -DBUILD_SHARED_LIBS=1 /usr/src/gtest
     make
     cp libgtest* /usr/lib/
     popd
rmills@ubuntu:~/gnu/github/exiv2/exiv2$ 
```

**Comment by clanmills** [comment]
This fix is insufficient.  On a clean machine, it doesn't install the gtest header files and cmake complains about GTEST not found.  I've submitted a fix that uses wget to fetch the code, then builds and installs it.  It's important to build SHARED to avoid a change to unitTests/CMakeLists.txt to target_link_libraries to reference`${CMAKE_THREAD_LIBS_INIT}` in addition to `${GTEST_BOTH_LIBRARIES}`.

**Comment by clanmills** [comment]
I'm restoring Dan's scripts and closing this.  I've removed all mention of those scripts from README.md

**Comment by D4N** [comment]
Although this has been closed a while ago, just a little clarification: the `ci/install_dependencies.sh` script is used by the continous integration infrastructure on gitlab only. I wouldn't recommend it at all for users! It does a lot of nasty and dangerous stuff that **really** shouldn't be done on any machine that you don't mind bricking.

The only thing that one can recommend to end users is to extract the list of packages from that script.
