### ISSUE TITLE
msvc compiler warning with -DEXIV2_ENABLE_VIDEO=On

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#602]
There are ugly compiler warnings coming from msvc (2017 and 2015, possibly others) from quicktimevideo.cpp and riffvideo.cpp  The built code is OK and passes the test suite.

```
  riffvideo.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xutility(3161): warning C4244: 'argument': conversion from 'const int64_t' to 'long', possible loss of data (compiling source file C:\Users\rmills\gnu\github\exiv2\buildserver\src\quicktimevideo.cpp) [C:\Users\rmills\gnu\github\exiv2\buildserver\build\src\exiv2lib.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xutility(3180): note: see reference to function template instantiation '_InIt std::_Find_unchecked1<_InIt,_Ty>(_InIt,_InIt,const _Ty &,std::false_type)' being compiled
          with
          [
              _InIt=const Exiv2::Internal::TagDetails *,
              _Ty=int64_t
          ] (compiling source file C:\Users\rmills\gnu\github\exiv2\buildserver\src\quicktimevideo.cpp)
```

One fix is to cast `(uint32_t)` in quicktimevideo.cpp#1333
```
            switch(i) {
            case GraphicsMode:
                td = find(graphicsModetags, (uint32_t) returnBufValue(buf,2));
                if(td)
                    xmpData_["Xmp.video.GraphicsMode"] = exvGettext(td->label_);
                break;
            case OpColor:
                xmpData_["Xmp.video.OpColor"] = returnBufValue(buf,2);
                break;
            default:
                break;
            }
``` 
and in riffvideo.cpp#1269
```
    const char* RiffVideo::printAudioEncoding(uint64_t i)
    {
        const TagDetails* td;
        td = find(audioEncodingValues ,(uint32_t) i);
        if(td)
            return exvGettext(td->label_);

        return "Undefined";
    } // RiffVideo::printAudioEncoding
```

**Comment by D4N** [comment]
Robin Mills <notifications@github.com> writes:

> There are ugly compiler warnings coming from msvc (2017 and 2015, possibly others) from quicktimevideo.cpp and riffvideo.cpp  The built code is OK and passes the test suite.
>
> ```
>   riffvideo.cpp
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xutility(3161): warning C4244: 'argument': conversion from 'const int64_t' to 'long', possible loss of data (compiling source file C:\Users\rmills\gnu\github\exiv2\buildserver\src\quicktimevideo.cpp) [C:\Users\rmills\gnu\github\exiv2\buildserver\build\src\exiv2lib.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xutility(3180): note: see reference to function template instantiation '_InIt std::_Find_unchecked1<_InIt,_Ty>(_InIt,_InIt,const _Ty &,std::false_type)' being compiled
>           with
>           [
>               _InIt=const Exiv2::Internal::TagDetails *,
>               _Ty=int64_t
>           ] (compiling source file C:\Users\rmills\gnu\github\exiv2\buildserver\src\quicktimevideo.cpp)
> ```

The problem here is that MS decided that long being 32 bit wide is a
sensible value (and not 64 bit). We should move to fixed size integers,
where possible.
We should use a static_cast<long>() here, preferably with a check for
overflows first (signed integer overflow is UB and on Windows we don't
have UBSAN to warn us).

**Comment by piponazo** [comment]
After what it has been discussed in #603 and #611 about having a proper deprecation cycle and dropping support to relics, I think the best we can do is to mark this code as deprecated in the branch 0.27 and remove it from master (in few months).

Note that in the PR #617 I am already marking this code as deprecated.

**Comment by piponazo** [comment]
Gentleman, I am closing this since I do not think we invest effort in deprecated code (which it has been actually removed already from master). If you think differently, please feel free to reopen the issue.
