### ISSUE TITLE
samples/conntest.cpp and -DEXIV2_ENABLE_CURL=1 is broken

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#604]
There are several issues with this:

1) We need to use #include <curl/curl.h> when EXIV2_ENABLE_CURL is set
2) We need to link CURL_LIBRARIES to conntest when EXIV2_ENABLE_CURL is set
3) There's a typo in the comment at the top of samples/conntest.cpp

The work-around is to not use CURL and we'll fix this in v0.27.1.

```
605 rmills@rmillsmm:~/gnu/github/exiv2/exiv2/build $ git diff
diff --git a/samples/CMakeLists.txt b/samples/CMakeLists.txt
index a3e491e..46aaa53 100644
--- a/samples/CMakeLists.txt
+++ b/samples/CMakeLists.txt
@@ -90,6 +90,9 @@ endif()
 # ******************************************************************************
 # connection test application
 add_executable(conntest conntest.cpp)
+if ( EXIV2_ENABLE_CURL )
+target_link_libraries( conntest PRIVATE ${CURL_LIBRARIES} )
+endif()
 list(APPEND APPLICATIONS conntest)
 
 # ******************************************************************************
diff --git a/samples/conntest.cpp b/samples/conntest.cpp
index 22fce2c..bcef8d1 100644
--- a/samples/conntest.cpp
+++ b/samples/conntest.cpp
@@ -1,5 +1,5 @@
 // ***************************************************************** -*- C++ -*-
-// con-test.cpp
+// conntest.cpp
 // Tester application for testing the http/https/ftp/ssh/sftp connection
 
 #include <exiv2/exiv2.hpp>
@@ -7,6 +7,10 @@
 #include <iostream>
 #include <cstdlib>
 
+#ifdef EXV_USE_CURL
+#include <curl/curl.h>
+#endif
+
 void httpcon(const std::string& url, bool useHttp1_0 = false) {
     Exiv2::Dictionary response;
     Exiv2::Dictionary request;
606 rmills@rmillsmm:~/gnu/github/exiv2/exiv2/build $ 
```

**Comment by piponazo** [comment]
Good catch @clanmills . I had to do the following to reproduce the issue:

- Uninstall curl-dev package from my system.
- conan: `conan install -o webready=True ../`
- cmake: `cmake  -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DCMAKE_BUILD_TYPE=Release ..`
- `make conntest`

**Comment by piponazo** [comment]
I have this issue almost solved in the branch `master_fix604`. However I am getting some linker issues on OSX:

https://api.travis-ci.org/v3/job/470952228/log.txt

```
AssertionError: 'dyld: Library not loaded: libcurl.4.dylib[198 chars].0\n' != ''

- dyld: Library not loaded: libcurl.4.dylib

-   Referenced from: /Users/travis/build/Exiv2/exiv2/build/bin/tiff-test

-   Reason: Incompatible library version: tiff-test requires version 10.0.0 or later, but libcurl.4.dylib provides version 7.0.0

 : Standard error does not match
```

I'll try to dig a bit more into this issue and if I do not find a solution, I will enable the CURL feature only for Linux and Windows.

**Comment by piponazo** [comment]
Note that in that branch I am bringing libcurl with conan (I also did some changes in travis to tell the nodes to bring libssh with conan). If this is causing problems we could just recommend to install the libssh package on OSX if somebody wants to use the feature.

**Comment by clanmills** [comment]
It built on the mac-mini and uses /usr/local/lib/libcurl.4.dylib.   It couldn't compile geotag.cpp because of something to do with Image::UniquePtr (lines 600, 626 and 901).  So, I used -DEXIV2_BUILD_SAMPLES=0 to only build exiv2.

I think I build curl from source about a year ago (curl-7.50.3).  When you use `bin/exiv2 -vVg curl` it lists protocols supported (http, https etc). ssh isn't listed.
