### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by paolocosmo** [Exiv2/exiv2#609]
Hi,
I am a beginner and I have no clear idea how to proceed with the installation of exiv2.
Following the instructions:
I download the zip exiv2-master and I unzip it

I open the powershell of Windows and I open the directory in which power exiv2-master in this way:
cd D:\Download\exiv2-master

Then I create the folder build and I open it in this way:
mkdir build
cd build

Then I run this command:
 cmake .. -G "Unix Makefiles"

and it returns me this message: 

-- The CXX compiler identification is unknown
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Check for working C compiler: C:/cygwin64/bin/cc
-- Check for working C compiler: C:/cygwin64/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Configuring incomplete, errors occurred!
See also "D:/Download/exiv2-master/build/CMakeFiles/CMakeOutput.log".
See also "D:/Download/exiv2-master/build/CMakeFiles/CMakeError.log".

I have no idea of what I have to do now to solve this problem. I tried to find something on google about the C++11 compiler but I didn't undestand what I have to do.
Someone can help me please? 

Thank you very much for your help!

**Comment by clanmills** [comment]
Good News.  It's already build for you.  Download the msvc64 bundle from http://exiv2.dyndns.org/download.html  Unzip it, and you'll find some documentation and binaries.  The file "ReadMe.txt" explains how to execute exiv2.exe from the command-line.

**Comment by paolocosmo** [comment]
Doesn't work the link : 
http://exiv2.dyndns.org/builds/exiv2-0.27.0-msvc64.zip 

Do you have some suggestions more?

**Comment by paolocosmo** [comment]
clanmills thanks a lot for your help!

**Comment by clanmills** [comment]
I'm going to close this issue.  If you have further questions, please ask.  Thank You for using Exiv2.
