### ISSUE TITLE
Support Sony DSC-RX100M5A

### ISSUE THREAD

**Issue by mikaelstaldal** [Exiv2/exiv2#612]
Sony DSC-RX100M5A is a new compact camera (non-interchangeable lens).

Seems like it can be detected by `Exif.Sony2.SonyModelID` = 369.

Relevant output from `exiv2 -pt`:
```
Exif.Image.Make                            Ascii       5  SONY
Exif.Image.Model                           Ascii      13  DSC-RX100M5A
Exif.Image.Software                      Ascii      19  DSC-RX100M5A v1.00
Exif.Sony2.SonyModelID                 Short       1  (369)
```

File: ![sonyrx100m5a](https://user-images.githubusercontent.com/716104/50385931-e28de580-06dd-11e9-8a37-6ca3a2f121a6.JPG)

**Comment by clanmills** [comment]
What's the issue?  The camera is being recognised!

```
Exif.Image.Model                           Ascii      13  DSC-RX100M5A
```

**Comment by mikaelstaldal** [comment]
No, not properly recognized. That is just the model name string from EXIF data.

A Sony DSC-RX100 is properly recognized:
```
Exif.Sony1.SonyModelID                       Short       1  DSC-RX100
```

**Comment by clanmills** [comment]
So, what's the problem?  It has indentified the camera.  And it's reporting the value 369 in Exif.Sony2.SonyModelID.

**Comment by mikaelstaldal** [comment]
I came from here: https://www.darktable.org/2015/02/on-lens-detection-and-correction/
And looked here: http://dev.exiv2.org/projects/exiv2/repository/entry/trunk/src/sonymn.cpp
and concluded that a line like:
```
        { 369, "DSC-RX100M5A"            }
```
is missing after line 133.

**Comment by clanmills** [comment]
Please submit a PR with your change.

**Comment by mikaelstaldal** [comment]
PR: https://github.com/Exiv2/exiv2/pull/613
