### ISSUE TITLE
The '--quiet' option does not silence errors

### ISSUE THREAD

**Issue by nur0n0** [Exiv2/exiv2#64]
For example: when I run `exiv2 --quiet cabin.jpg`, I get 
`
File name       : cabin.jpg
File size       : 142852 Bytes
MIME type       : image/jpeg
Image size      : 705 x 837
cabin.jpg: No Exif data found in the file
`

The last line is printing on stderr, so I expected `--quiet` to silence it. I am running GalliumOS(which is based on Ubuntu 16.04) on 64-bit x86 hardware, exiv2 version 0.26.

**Comment by clanmills** [comment]
The message is coming from the exiv2(.exe) application and not the library. 
```
574 rmills@rmillsmbp:~/gnu/exiv2/0.26 $ grep 'No Exif data found in the file' src/actions.cpp 
                      << _("No Exif data found in the file\n");
            if (noExif) std::cerr << path_ << ": " << _("No Exif data found in the file\n");
                      << ": " << _("No Exif data found in the file\n");
                      << ": " << _("No Exif data found in the file\n");
                      << ": " << _("No Exif data found in the file\n");
                      << ": " << _("No Exif data found in the file\n");
                      << ": " << _("No Exif data found in the file\n");
575 rmills@rmillsmbp:~/gnu/exiv2/0.26 $
```
Perhaps the application should also respect the log level of the library.  It the library has been silenced, perhaps applications should also keep silent.

How much pain is this causing?  Can you just use exiv2 --quiet cabin.jpg 2>/dev/null

If you want me to investigate further, can you attach cabin.jpg so that I reproduce your use case.

**Comment by nur0n0** [comment]
I just assumed the expected behavior would be a clear stderr under the `--quiet` option. I'm not sure of the utility of the current behavior when using the CLI. Overall, I just wanted to bring it to your attention since the workaround (redirecting to /dev/null) is straightforward. (Slightly tangential question: if the library is being silenced, does this mean something else is writing the error messages?)

**Comment by clanmills** [comment]
Yes. The message is being written by the Exiv2 cli application.  The library has been silenced.

**Comment by clanmills** [comment]
I'll reopen this issue if you wish to discuss this further.
