### ISSUE TITLE
Linker warning on MacOS-X (after fixing 644)

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#648]
Fixing 644 produces linker warnings on MacOS-X.  644 is a build-breaker for Suse.   The linking message is ugly and probably benign.

```
[ 50%] Linking CXX shared library ../lib/libexiv2.dylib
ld: warning: direct access in function 'Exiv2::Internal::CiffEntry::doAdd(std::__1::auto_ptr<Exiv2::Internal::CiffComponent>)' from file 'CMakeFiles/exiv2lib_int.dir/crwimage_int.cpp.o' to global weak symbol 'typeinfo for Exiv2::BasicError<char>' from file 'CMakeFiles/exiv2lib.dir/basicio.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

We've seen this message before (around the time of Exiv2 v0.27 RC3) and didn't know what it meant.

**Comment by clanmills** [comment]
Good Morning @piponazo.  The build failure involves EXIV2API on setMsg() on line 306 in error.hpp.  The library builds and links, then the sample applications don't build.   

We might need to do:
```
#ifndef _MSC_VER
class EXIV2API BasicError ...
#else
class BasicError ...
#endif
```

Ugly?  Pass me the barf bag!

**Comment by D4N** [comment]
I agree with @piponazo that #644 does not look like the correct way how to fix this, template classes should not be exported.

**Comment by piponazo** [comment]
I'm taking the freedom of closing this, now that #652 have been merged.
