### ISSUE TITLE
exiv2-0.27.0a hardcodes pkgconfig/exiv2.pc libdir with ${prefix}/lib

### ISSUE THREAD

**Issue by ikelos** [Exiv2/exiv2#651]
Compiling exiv2-0.27.0a works fine, but then packages linking against it using `pkg-config` can fail, because the exiv2.pc generation does not determine the correct `libdir`, but instead sets it to [`${prefix}/lib`](https://github.com/Exiv2/exiv2/blob/master/cmake/exiv2.pc.in#L3).

Distributions (such as Gentoo) that use `/usr/lib64` for example will either not be able to find, or end up using libraries for the wrong architecture.  The previous version used `@libdir@` to ensure the correct library directory and that successfully allows other programs to be built against it.

**Comment by ikelos** [comment]
The following patch resolves the issue:

[exiv2-0.27.0-pkgconfig.patch](https://github.com/Exiv2/exiv2/files/2751377/exiv2-0.27.0-pkgconfig.txt).

**Comment by ikelos** [comment]
Hmmm, it seems it doesn't reliably solve it.  Some systems produce bad exiv2.pc files with the patch (with no values at all for things like `libdir`).  5:\

**Comment by clanmills** [comment]
Thanks for reporting this and providing a patch.

For v0.27, we took the brave decision to adopt CMake as our only build tool and to discontinue auto tools and other build tools. 

When we published Exiv2 v0.27 RC1, a user requested _**`exiv2.pc`**_ and that was done.  However, it's very possible that more work is required to test the boundary.

In releasenotes/Linux/ReadMe.txt, I've documented what I believe is the correct way in which to use the file:

```
Method 2: Use pkg-config to set include and linking options
$ cd <bundle>
$ export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
$ export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
$ g++ -std=c++98 samples/exifprint.cpp -o exifprint $(pkg-config exiv2 --libs --cflags)
$ ./exifprint
``` 

Here's that I have on my MacOS-X:
```
549 rmills@rmillsmm:~/Downloads/exiv2-0.27.0-Source $ cat /usr/local/lib/pkgconfig/exiv2.pc 
prefix=/usr/local
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: exiv2
Description: Exif and IPTC metadata library and tools
Version: 0.27.0
URL: http://exiv2.dyndns.org
Libs: -L${libdir} -lexiv2
Cflags: -I${includedir}
550 rmills@rmillsmm:~/Downloads/exiv2-0.27.0-Source $ pkg-config exiv2 --libs --cflags
-I/usr/local/include -L/usr/local/lib -lexiv2 
551 rmills@rmillsmm:~/Downloads/exiv2-0.27.0-Source $ 
```

I can install a Gentoo VM and investigate further.  However, before embarking on that journey, may I ask you to confirm that you are using _**`exiv2.pc`**_  as documented.  Remember it's also possible that the documentation is also incorrect.

So, can we start at Gentoo and define what you believe is needed in _**`exiv2.pc`**_ and how it should be used.

**Comment by ikelos** [comment]
Thanks for the quick reply!  The packages that use pkg-config that I'm aware of are gexiv2 and gnome-color-manager.  They do so in their configure systems, and the same versions works fine with 0.26 from 2018-08-11.  Since they worked correctly previously, I'm fairly certain it's not the way that pkg-config is being used.

I don't think you'll need to install Gentoo for this, I should be able to explain more clearly what's going on: Gentoo allows a system to be multi-lib, with a kernel that supports using both 64-bit and 32-bit binaries, which means it can have libraries for both.  32-bit libraries live under `/usr/lib` and 64-bit libraries live under `/usr/lib64`.  Because of the `libdir=${prefix}/lib` line, the version compiled for 64-bit says that its `libdir` is actually `/usr/lib` meaning that it attempts to link 64-bit programs against `/usr/lib` because it isn't aware that the correct directory is actually `/usr/lib64`, it just makes the assumption that it will *always* live under the `lib` directory under the prefix.  This will result in a 64-bit library attempting to link against a 32-bit one, and throws an error.

@piponazo Thanks for the link, it appears as though the original version of the exiv2.pc file from that bug would have used the correct library directory (by using the `@CMAKE_INSTALL_LIBDIR@` variable), but that this got hardcoded when the discussion around using `${prefix}` was introduced (I suspect during implementation of comment **https://github.com/Exiv2/exiv2/issues/512#issuecomment-435555116**).

I've now produced a new patch that takes this requirement into account using the appropriate cmake variables:

[exiv2-0.27.0a-pkgconfig-2.patch](https://github.com/Exiv2/exiv2/files/2751913/exiv2-0.27.0a-pkgconfig2.txt)

Please let me know if there's any further information that could help?

**Comment by clanmills** [comment]
Thanks very much for doing more work on this.  And thank for your explanation concerning gentool/multilib.

I'm a little surprised that our friends at GExiv2 haven't mentioned this as we're currently working with @phako on a Darwin (MacOS-X) 0.27 build issue.  Perhaps you are ahead of him and solved a puzzle that he has not yet seen.  Another user has reported something concerning our support for GNUInstallDirs.  Your patch is effectively:

<img width="782" alt="exiv2 pc in diff" src="https://user-images.githubusercontent.com/529982/51072794-dd79e180-165e-11e9-9abf-f66247bc464a.png">

I google'd a conversation about CMAKE_INSTALL_LIBDIR.  

> The relatively new cmake module GNUInstallDirs sets CMAKE_INSTALL_LIBDIR
> to lib or lib64.  Other projects like tkimg appear to use this convention.

Your patch seems good to me.  @piponazo is our CMake Expert and I'm interested to hear his thoughts.

**Comment by piponazo** [comment]
Hi guys. The patch looks perfect. I did not consider to use the GnuInstallDirs variables in the .pc file, but it makes total sense. We are already using those variables inside our CMake code, but I did not propagated their usage everywhere. I'll apply your patch to both 0.27 and master.

Thanks a lot!
