### ISSUE TITLE
Request: For future milestone releases, please make it possible to easily distinguish between initial release (eg. 0.27) and a branch for that version(eg. 0.27)

### ISSUE THREAD

**Issue by phako** [Exiv2/exiv2#661]
The build error after merging #617 was not caught on my side because the flatpak-based builder keeps on checking out the tag 0.27 instead of the branch 0.27.

For 0.28 it would be nice if the branch would be 0.28 and the initial version tagged with 0.28.0 or something like that

**Comment by piponazo** [comment]
Good point. I also noticed this issue when rebasing branches, and instead of doing:

```
git rebase 0.27
```
I have to do:
```
git rebase upstream/0.27
```

We'll have it into account for the future.

**Comment by clanmills** [comment]
@piponazo I'm changing this to Milestone 0.27.1 although it applies to v0.28 as well of course.

**Comment by piponazo** [comment]
I am thinking about changing the 0.27 tag to 0.27.0 and then the next release would be 0.27.1. However this is a bad practice and it could annoy to other projects consuming **exiv2**. What do you think guys about this proposal ? \cc @D4N

**Comment by phako** [comment]
Please don't change the existing tag. Just remember it for 0.28 cycle

**Comment by D4N** [comment]
I find the branch & tag names annoying, too and I agree with @phako that we **really** shouldn't change the name of the 0.27 tag. What we however can do is to change the name of the 0.27 branch to 0.27-maintenance (or something like that), as it describes that branch more accurately.

**Comment by phako** [comment]
I think renaming the branch is equally bad. It will break many of the automatic build scripts that live out there (e.g. flatpak, CIs, ...)

**Comment by clanmills** [comment]
I think we should "take the hit" and change this once and forever.  If possible, can we avoid changing any existing tag.  We can make the change when v0.27.1 is released.  Scheduled 2019-03-31.  

I intend a "preview" for v0.27.1 in early March.  I'll mention this change prominently in the release notes _**AND**_ discuss this on https://discuss.pixls.us and invite feedback.

Could somebody (@D4N or @piponazo) define exactly what we intend to do as I don't want to add to the confusion!

**Comment by D4N** [comment]
@clanmills: We intend to drop the branch `0.27` and instead call it `0.27-maintenance` (or something like that). The tag `0.27` will stay. The advantage is, that when you checkout `0.27` you'll get the exact version `0.27` and with `0.27-maintenance`, you get the current state of `0.27`. The problem is, that if anyone has an active script pulling from `0.27`, then we'll break their workflow, as they are either going to get an error or the tag (not sure what is going to happen). If it's announced, it's fine imho.

**Comment by D4N** [comment]
> Is it possible to have tags 0.27 and 0.27.0 with identical content?

Sure, you can probably have as many as you like.

> Perhaps we should rename the tag 0.27 as 0.27.0. This change will upset somebody, however it's a "once-and-for-always" change.

I don't think that we should change the name of the tag. I would consider changing the name of the 0.27 branch though. That will also upset some people, but imho that is a lot less intrusive than changing the name of the tag (which is supposed to be a constant pointer to a specific commit).

**Comment by D4N** [comment]
We have renamed the 0.27 branch to 0.27-maintenance, as it caused issues with mergify.
