### ISSUE TITLE
Old issue tracker is being spammed.

### ISSUE THREAD

**Issue by junkyardsparkle** [Exiv2/exiv2#664]
This is the one I noticed, but there could be others:

 http://dev.exiv2.org/users/9462

If it's no longer in use, maybe new signups should be disabled?

**Comment by clanmills** [comment]
I have been able to find a way to make Redmine ReadOnly.  This would preserve the valuable information and prevent spammers.  I haven't been able to find a setting to disable signups.

I didn't set up Redmine and only know how to configure with using the web-interface.  I feel there should be a configuration file somewhere to make Redmine ReadOnly.  If you know about this, I would be very appreciative to have your help.

**Comment by junkyardsparkle** [comment]
My only experience with Redmine is via the web front end, but if I manage to dig up any information I'll report back.

**Comment by D4N** [comment]
@clanmills This is a very dirty hack, but how about doing this:
```
chmod -R -w /path/to/redmine/db
```
Unfortunately you'll probably get errors when doing just about anything and maybe redmine won't even start, but posting should become just about impossible ;-)

In the long run we should save everything from redmine as plain html via a crawler (e.g. https://www.httrack.com/) and put that as a static website onto apache/nginx/`$your_favorite_httpd`.

**Comment by lillolollo** [comment]
@clanmills http://www.redmine.org/projects/redmine/wiki/RedmineProjects read Closing a project

**Comment by clanmills** [comment]
I believe redmine is using MySql to manage the database.  And I believe the following command will do what we want.
```
SET GLOBAL READ_ONLY=1;
```
However, I don't seem to have the privileges required:
```
root@redmine redmine/config# mysql --user=user --password=password                              
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 5378
Server version: 5.5.60-0+deb7u1 (Debian)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SET GLOBAL READ_ONLY=1;
ERROR 1227 (42000): Access denied; you need (at least one of) the SUPER privilege(s) for this operation
mysql> exit  
Bye
root@redmine redmine/config# 
```

I have several different user/passwords and all are blocked from using the read_only command.  MySql has a GRANT command.  It may be possible to lock the database tables individually.  I've never used MySql.

I don't want to discuss this in such a public space.  If anybody would like to help with this, please send your public key and I'll grant you root/ssh access to exiv2.org

**Comment by clanmills** [comment]
Very pleased to let you know that Nehal Wani has offered to help with this.  Assigning to 27.1

**Comment by clanmills** [comment]
Thanks to @nehaljwani we have disabled new sign-ups.

Somebody in February registered several hundred new users with Russian email accounts and I have started to delete them.  The UI to delete a user is very tedious and takes about 15 seconds/user.  As spam arrives, I will delete the spam and "Lock" the user from making further submissions.

I think I can get a list of the email address of bandits and write a script to get curl to remove them one at a time, or enable the REST API, or use SQL, or (most likely), use the dentist's method (pull them out painfully one at a time with the UI).

**Comment by nehaljwani** [comment]
Couple of lines in ruby + a few queries in SQL = A lot of spam accounts gone.

I targeted any email having 'yandex' in it and any ending in 'mail.ru'

**Comment by nehaljwani** [comment]
This was helpful: http://www.redmine.org/boards/2/topics/41831

**Comment by clanmills** [comment]
Thank You, Nehal @nehaljwani  for dealing with this.  Wonderful!

**Comment by clanmills** [comment]
I'm going to close this as we have taken firm action.  I receive email notification of all correspondence on Redmine, so I am always aware of the bandits and usually take action within an hour or two.

I am very appreciative of the efforts of @nehaljwani to help with this.  The number of registered users on Redmine yesterday was about 2100.  Today's it's 934 (or so).  Great Job, Nehal.

I'm looking forward to getting exiv2.org moved to England and hope I can achieve that, and release 0.27.1, by the end of March.
