### ISSUE TITLE
Does not recognize Sigma 50mm F1.4 DG HSM | Art 014

### ISSUE THREAD

**Issue by piratenpanda** [Exiv2/exiv2#671]
I don't know if the lens firmware update or my 5D Mark 4 is reporting this lens incorrectly but it started some time ago that the lens is not being recognized automatically anymore. When checking the ID the output is the following:

0x0016 CanonCs      LensType                    Short       1  368

So I assumed adding:

[canon]
368=Sigma 50mm f/1.4 DG HSM | A

or
[canon]
368 = Sigma 50mm f/1.4 DG HSM [A]

to the .exiv2 file would change that but all I get is still LensType 368. Is there something I am doing wrong?

**Comment by piratenpanda** [comment]
Ok so with -pv it still shows the 368 and with -pa it shows the new name. I guess this is just user error then. Sorry for the spam

**Comment by clanmills** [comment]
The option -pv shows the value (368), the option -pt shows the "translated = human meaningful".  In the man page, -pa is:
```
a : print Exif, IPTC and XMP metadata (shortcut for -Pkyct)
```
So, it uses 't' = translated.
