### ISSUE TITLE
Remove relics from master

### ISSUE THREAD

**Issue by D4N** [Exiv2/exiv2#675]
Apply #617 to master, but instead of deprecating the code, delete it.

**Comment by tbeu** [comment]
What about file eps-preview-test.out, eps-test.sh or sshiotest.sh?

**Comment by D4N** [comment]
tbeu <notifications@github.com> writes:

> What about file eps-preview-test.out, eps-test.sh or sshiotest.sh?

These can go too. If we ever need them again, we have the git history
for that.

**Comment by Kicer86** [comment]
I guess it can be closed now.
Any objections?
