### ISSUE TITLE
Reading complex structured tags

### ISSUE THREAD

**Issue by megibyan** [Exiv2/exiv2#681]
For complex structured tags like "LensSpecification" or "MakeNote", where we know that the value is expected to be a list of values (rational, byte, integer, etc...), is there a way to read the data into appropriate container, instead of reading the data into a string and then parsing?

Thanks,
Mikayel

**Comment by clanmills** [comment]
Metadata is parsed from the image into an instance of the class `Exiv2::Metadatum`  http://www.exiv2.org/doc/classExiv2_1_1Metadatum.html

There are methods such as toFloat() which will decode the data into C types.  Or you can cast the value.

MakerNote is a complex of data.  It's typically stored in a tiff structure which Exiv2 will decode into groups.  For example:
```
520 rmills@rmillsmbp:~/clanmills $ exiv2 -pe --grep nikon/i Stonehenge.jpg | cut -d' ' -f 1 | cut -d'.' -f 2 | sort | uniq
Nikon3
NikonAf2
NikonCb2
NikonFi
NikonIi
NikonLd3
NikonMe
NikonPc
NikonVr
NikonWt
521 rmills@rmillsmbp:~/clanmills $ 
```
This file contains a maker note (Nikon3) and contains groups Af2, Cb2b etc.  These "Groups" are single binary tags in the MakerNote.  We don't provide an API to read a group.  You have to read them using the `Exiv2::Metadatum::toXXX()` methods.

I have to go for breakfast now.  I'll write more (and some code) concerning this later.

**Comment by clanmills** [comment]
We are hoping to recruit a student from Google Summer of Code to work with us.  We've submitted an application to Google.  We've done this 3 times before, so I expect we will get somebody.  Here's the discussion:  https://github.com/Exiv2/exiv2/issues/659

One of the items on the list is:
> 8 Better web documentation concerning makernotes For example #646

I have a drawing to explain the structure of TIFF files.  Exif metadata is a tiff structure that embedded in the image.  It's a very recursive because the Makernote is also a tiff structure embedded in the Exif data.  Tiff consists of a tag (16 bit integer), a type (ASCII, SIGNED, RATIONAL etc) a count and data.  So the data in a tag is always an array of the same type.  A tag is 12 bytes.  To save space, the manufacturers often have binary data.  So NikonAf2 is a single binary tag in the maker note.  We've documented it here:  http://www.exiv2.org/tags-nikon.html  That documentation is machine generated from the code in Exiv2.

Exiv2 presents the data to the user as though every field of the Af2 structure is genuine tiff tag.  This is a good and valid abstraction, however that's not what's really in the file.

```
530 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pa --grep af2/i ~/Stonehenge.jpg 
Exif.NikonAf2.Version                        Undefined   4  1.00
Exif.NikonAf2.ContrastDetectAF               Byte        1  Off
Exif.NikonAf2.AFAreaMode                     Byte        1  8
Exif.NikonAf2.PhaseDetectAF                  Byte        1  On (39-point)
Exif.NikonAf2.PrimaryAFPoint                 Byte        1  11
Exif.NikonAf2.AFPointsUsed                   Byte        7  105 5 128 0 16 0 0
Exif.NikonAf2.AFImageWidth                   Short       1  0
Exif.NikonAf2.AFImageHeight                  Short       1  0
Exif.NikonAf2.AFAreaXPosition                Short       1  0
Exif.NikonAf2.AFAreaYPosition                Short       1  0
Exif.NikonAf2.AFAreaWidth                    Short       1  0
Exif.NikonAf2.AFAreaHeight                   Short       1  0
Exif.NikonAf2.ContrastDetectAFInFocus        Short       1  0
531 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ 
```

It's hard to explain this in words and I'd like to do more work on our documentation concerning makernotes. 

[Tiff.pdf](https://github.com/Exiv2/exiv2/files/2828670/Tiff.pdf)

**Comment by clanmills** [comment]
The TiffReader is a class (derived from TiffVisitor) which recursively reads Tiff structures in the image.  The following code defines Nikon Tag 0x00b7 as AFInfo2:

```
866 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ grep 00b7 src/*.cpp
src/nikonmn_int.cpp:633:        TagInfo(0x00b7, "AFInfo2", "AF Info 2", N_("AF info 2"), nikon3Id, makerTags, undefined, -1, printValue),
src/tiffimage_int.cpp:935:        { Tag::root, nikonAf2Id,       nikon3Id,         0x00b7    },
src/tiffimage_int.cpp:1277:        {    0x00b7, nikon3Id,         EXV_BINARY_ARRAY(nikonAf2Cfg, nikonAf2Def)},
867 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ 
```
When the TiffReader finds this, he creates a binary array with the following specification in nikonmn_int.cpp
```
    const TagInfo Nikon3MakerNote::tagInfoAf2_[] = {
        TagInfo(  0, "Version", N_("Version"), N_("Version"), nikonAf2Id, makerTags, undefined, 4, printExifVersion),
        TagInfo(  4, "ContrastDetectAF", N_("Contrast Detect AF"), N_("Contrast detect AF"), nikonAf2Id, makerTags, unsignedByte, 1, EXV_PRINT_TAG(nikonOffOn)),
        TagInfo(  5, "AFAreaMode", N_("AF Area Mode"), N_("AF area mode"), nikonAf2Id, makerTags, unsignedByte, 1, printValue),
        TagInfo(  6, "PhaseDetectAF", N_("Phase Detect AF"), N_("Phase detect AF"), nikonAf2Id, makerTags, unsignedByte, 1, EXV_PRINT_TAG(nikonPhaseDetectAF)),
        TagInfo(  7, "PrimaryAFPoint", N_("Primary AF Point"), N_("Primary AF point"), nikonAf2Id, makerTags, unsignedByte, 1, printValue),
        TagInfo(  8, "AFPointsUsed", N_("AF Points Used"), N_("AF points used"), nikonAf2Id, makerTags, unsignedByte, 7, printValue),
        TagInfo( 16, "AFImageWidth", N_("AF Image Width"), N_("AF image width"), nikonAf2Id, makerTags, unsignedShort, 1, printValue),
        TagInfo( 18, "AFImageHeight", N_("AF Image Height"), N_("AF image height"), nikonAf2Id, makerTags, unsignedShort, 1, printValue),
        TagInfo( 20, "AFAreaXPosition", N_("AF Area X Position"), N_("AF area x position"), nikonAf2Id, makerTags, unsignedShort, 1, printValue),
        TagInfo( 22, "AFAreaYPosition", N_("AF Area Y Position"), N_("AF area y position"), nikonAf2Id, makerTags, unsignedShort, 1, printValue),
        TagInfo( 24, "AFAreaWidth", N_("AF Area Width"), N_("AF area width"), nikonAf2Id, makerTags, unsignedShort, 1, printValue),
        TagInfo( 26, "AFAreaHeight", N_("AF Area Height"), N_("AF area height"), nikonAf2Id, makerTags, unsignedShort, 1, printValue),
        TagInfo( 28, "ContrastDetectAFInFocus", N_("Contrast Detect AF In Focus"), N_("Contrast detect AF in focus"), nikonAf2Id, makerTags, unsignedShort, 1, printValue),
        // End of list marker
        TagInfo(0xffff, "(UnknownNikonAf2Tag)", "(UnknownNikonAf2Tag)", N_("Unknown Nikon Auto Focus 2 Tag"), nikonAf2Id, makerTags, unsignedByte, 1, printValue)
    };
```
We can see that tag in the file:
```
865 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pR ~/Stonehenge.jpg | grep b7 
           634 | 0x00b7                              | UNDEFINED |       30 |      2918 | 0100....i....................
```
So, there is a tag (0x00b7) with 30 bytes of binary data.  The binary decoder creates the tags listed in the output above.

**Comment by megibyan** [comment]
Hi Robin,

Thank you for your elaborate answer. 

I think if using ```Exiv2::Metadatum``` or something else I could iterate over all available MakerNote keys in the file, that would have made my day.

Is there any sample code I could have a look how is ```Exiv2::Metadatum``` used to read out MakerNote tags?

Thanks,
Mikayel
