### ISSUE TITLE
Support for Tamron 28-75mm F/2.8 Di III RXD A036 (Sony E Mount)

### ISSUE THREAD

**Issue by zecoj** [Exiv2/exiv2#693]
Hi team,

Is it possible to add support to the the said lens? 
```
$> **exiv2 -pt 20190208-112238.ARW | grep -ai lens**
Exif.Sony2.LensID                            Long        1  Manual lens
Exif.Photo.LensSpecification                 Rational    4  280/10 750/10 28/10 28/10
Exif.Photo.LensModel                         Ascii      19  E 28-75mm F2.8-2.8
```
Attached is the zip file containing the output of `exiv2 -ex 20190208-112238.ARW`
[20190208-112238.exv.zip](https://github.com/Exiv2/exiv2/files/2845634/20190208-112238.exv.zip)

Manufacture's [webpage for the lens](http://www.tamron-usa.com/product/lenses/a036.html)

Please let me know if you need anything else.

Thanks and regards,

**Comment by clanmills** [comment]
Thanks for getting in touch.  You can usually fix this for yourself using the file ~/.exiv2.  Lots of similar discussions such as:   http://dev.exiv2.org/issues/1370

Thanks for posting your .exv file.  This doesn't seem to contain much metadata.  Can I ask you to send the .ARW.  I realise that Redmine has a file 20mb limit.  Take a photo at minimum resolution with the lens cap ON.  Or post on a cloud service such as DropBox.  

```
1141 rmills@rmillsmbp:~/clanmills $ ls -l ~/Downloads/*.exv
-rw-r--r--@ 1 rmills  staff   2.4K  8 Feb 22:12 /Users/rmills/Downloads/20190208-112238.exv
1142 rmills@rmillsmbp:~/clanmills $ exiv2 -pa --grep lens/i /Users/rmills/Downloads/20190208-112238.exv 
1143 rmills@rmillsmbp:~/clanmills $ exiv2 -pa /Users/rmills/Downloads/20190208-112238.exv 
Xmp.xmp.Rating                               XmpText     1  0
1144 rmills@rmillsmbp:~/clanmills $ 
```

**Comment by zecoj** [comment]
Hi Robin,

Thanks for getting back to me. I don't have access to my camera at the moment but I have uploaded an old ARW file here:

https://www.dropbox.com/s/2n8w25by7vtkihy/20190202-181333.ARW?dl=1

Please let me know if you need anything else.

Regards,

**Comment by clanmills** [comment]
Thanks for the file.  I've fixed this using the config file ~/.exiv2
```
553 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ ls -l ~/Downloads/*.ARW
-rw-r--r--@ 1 rmills  staff  24767232 12 Feb 10:11 /Users/rmills/Downloads/20190202-181333.ARW

554 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pa --grep lens/i ~/Downloads/*.ARW
Exif.Sony2.LensID                            Long        1  Manual lens  <--- Exiv2 doesn't understand
Exif.Photo.LensSpecification                 Rational    4  280/10 750/10 28/10 28/10
Exif.Photo.LensModel                         Ascii      19  E 28-75mm F2.8-2.8

555 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pv --grep lens/i ~/Downloads/*.ARW
0xb027 Sony2        LensID                      Long        1  65535     <---- This is the LensID
0xa432 Photo        LensSpecification           Rational    4  280/10 750/10 28/10 28/10
0xa434 Photo        LensModel                   Ascii      19  E 28-75mm F2.8-2.8

556 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ cat ~/.exiv2 
[sony]
65535=Tamron 28-75mm F/2.8 Di III RXD A036 (Sony E Mount)                <---- Define it

557 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pa --grep lens/i ~/Downloads/*.ARW
Exif.Sony2.LensID                            Long        1  Tamron 28-75mm F/2.8 Di III RXD A036 (Sony E Mount)
Exif.Photo.LensSpecification                 Rational    4  280/10 750/10 28/10 28/10
Exif.Photo.LensModel                         Ascii      19  E 28-75mm F2.8-2.8
558 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ 
```

I'm going to close this as I think we've dealt with this.  However I'll reopen the case if you think there is something to discuss.

**Comment by zecoj** [comment]
Thanks for that. Does this mean the fix will be included in future releases?

**Comment by clanmills** [comment]
Yes and no.

Yes:  Once you modify ~/.exiv2, your definition will be respected when libexiv2 is updated.

No:  I would like to get Exiv2 out of the lens recognition.  The metadata doesn't contain the lens type.  However, we can often guess the lens from other metadata.  The metadata contains data such as Exif.Sony2.LensID which in your case (65535) == -1.  This is a common value when the manufacturer doesn't recognise your lens.  And if he doesn't know, Exiv2 also does not know.  To compound the issue, it's not unusual for some LensID values to be used by up to 20 different lenses.

It's a pity that Exiv2 got involved in lens recognition.  About 50% of email and issues are about this.

**Comment by zecoj** [comment]
Right! Understood and appreciate your assistance!
