### ISSUE TITLE
Darktable2.6:lens Tamron 100-400mm not recognized=>Canon300mm instead

### ISSUE THREAD

**Issue by andreilabato** [Exiv2/exiv2#719]
I use a Lens TAMRON 100-400mm F/4.5-6.3 Di VC USD A035.
It is recognized in Darktable as Canon EF 300mm f/2 8L IS II USM and it is wrong.
Information in RAW is correct as Canon Digital Photo Professional software recognizes it as TAMRON 100-400mm F/4.5-6.3 Di VC USD A035.

**Comment by D4N** [comment]
Can you upload a sample image please?

Also, which exiv2 version are you using?

**Comment by andreilabato** [comment]
1) Sure I can. how can I upload 20Mb? first time I use this site...
2)I use DarkTable 2.6. I do not know how to see version used. I could I?

**Comment by D4N** [comment]
> Sure I can. how can I upload 20Mb? first time I use this site...

Either try to drag & drop it into the issue field or upload it to an external file hoster.

> I use DarkTable 2.6. I do not know how to see version used. How could I?

I don't use darktable so neither do I know: try to search for exiv2 or libexiv2.so or something like that inside the installation root of darktable (if you find exiv2, run `exiv2 --version`). How did you install darktable? And which platform are you on?

**Comment by andreilabato** [comment]
Canon raw file is available here: https://framadrop.org/r/g1rF_-jgqC#k2sqHjaCBzWfoXJ5qPdSzSzvglq//377jMSyRXxIOeM=
I did instal dark table 2.6 using one of these links https://darktable.fr/installation/

**Comment by D4N** [comment]
> I did instal dark table 2.6 using one of these links https://darktable.fr/installation/

Which platform are you using?

Anyway, this issue appears to be fixed on master:
``` shell
$ exiv2 -p v --grep LensModel IMG_9291.CR2
0x0095 Canon        LensModel                   Ascii      74  TAMRON 100-400mm F/4.5-6.3 Di VC USD A035
0xa434 Photo        LensModel                   Ascii      42  TAMRON 100-400mm F/4.5-6.3 Di VC USD A035
```

That is the correct lens right?

**Comment by andreilabato** [comment]
I am using windows 10 platform.  I confirm it is the right lens: TAMRON 100-400mm F/4.5-6.3 Di VC USD A035.
What should I do then?

**Comment by D4N** [comment]
> What should I do then?

Your best bet is to ask the darktable developers when they'll release a new build with an updated version of exiv2 for Windows. You can of course rebuild everything from source, but unless you have experience with that on Windows, I'd rather wait.

Unfortunately, that's all I can do about this.
