### ISSUE TITLE
www.exiv2.org is gone

### ISSUE THREAD

**Issue by jwilk** [Exiv2/exiv2#736]
```console
$ wget http://www.exiv2.org/
--2019-03-04 09:22:21--  http://www.exiv2.org/
Resolving www.exiv2.org (www.exiv2.org)... failed: Name or service not known.
wget: unable to resolve host address ‘www.exiv2.org’
```

**Comment by clanmills** [comment]
I don't know what has happened.  It's hosted somewhere on AWS.  This happened in July 2018 and Amazon emailed Andreas.  Amazon restored it from backup.  I have asked Andreas several times to transfer the domain registration so that I can host this elsewhere.  An ISP in England have offered to host when I have the domain registration.  Can anybody can suggest how to progress?

I believe it's a co-incidence that I discussed making Redmine Read only with Nehal Wani who applied for GSoC 2013.  I added Nehal's public key to exiv2.org on Friday and the whole site disappeared on Saturday.  I trust Nehal.   However I emailed him this morning about this.  No reply yet.

**Comment by clanmills** [comment]
Nehal has done some detective work.  The site can be accessed at http://54.72.225.196

I have emailed support@pairdomains.com as follows:

_I would like to renew this domain registration.  It was registered to Mr Andreas Huggel who lives in Kuala Lumpur, Malaysia.  I maintain the content.  Regrettably, Mr Huggel no longer communicates with the Exiv2 Community who require access to this valuable resource.  The site is currently hosted:  http://54.72.225.196_

_I would like to renew the registration and transfer it to an ISP/host in England.  Can you help me, please?_

_Robin Mills_
_... my postal address ..._

To say this is frustrating is an understatement.  I anticipated this would happen and tried to move the registration when we released v0.26 in April 2017 and again in December 2018 when v0.27 was released.

Let's hope for a happy ending.  We'll get the registration and host the site in England and make Redmine Read-only.  The hosting company have also offered a VM on which to run Jenkins and SVN (for legacy code).  Perhaps we'll be able to make Jenkins secure.  Then I would like to release Exiv2 v0.27.1 by 2019-03-31.  

Thanks very much to Nehal for assisting with this.

**Comment by clanmills** [comment]
Here's the relevant section of the reply from the pairdomains.com:

_However, if you would like to transfer either the ownership or the 
registration of exiv2.org, this action would have to be done in 
co-ordination with the current owner._

I've emailed @ahuggel and have not _yet_ received a reply.

I've had more email with @nehaljwani and he has disabled new-user registration on Redmine.  He's confident about making Jenkins secure when our new server is up and running.  So, almost everything is in place to "pull the plug" on AWS and get everything transferred to the new server.

Ideally, we should renew the domain registration immediately to bring exiv2.org back on-line.  We can move the project resources to the new server and "Go Live" when we're confident that everything's working correctly on the new host.  

I will pay the changes involved in making this change.

Exiv2 has made a lot of progress in 15+ years and we now have 5 regular contributors and 10-15 "friends" who contribute from time to time in different ways.  Now is a good time change our server.

**Comment by nehaljwani** [comment]
I am so happy that exiv2 finally moved on to github and left the old SVN repo ✌️ 

Please tag me or email me if any assistance is required. My turn around time is anywhere b/w 1-24 hours :-)

**Comment by clanmills** [comment]
Thanks, Nehal.  What a splendid fellow you are.  I hope Andreas allows me to pay for the domain registration and we get exiv2.org back on-line.

I have an ISP in England willing to host the site and provide an Ubuntu VM (for Jenkins and SVN).
We should keep SVN for a couple of reasons:
1) Many existing discussions have links that make reference to SVN.
2) There is a top-level SVN branch called "team" which has resources (such an the project graphics and web-site which are not in GitHub.  

I've sent you an invitation to Slack for off-line time discussion.  Most Exiv2 correspondence concerning is public on https://github.com/exiv2/exiv2.  However chats about vacations and family are discussed privately on Slack.  If you don't want to join Slack, that's your choice and fine with me.

**Comment by clanmills** [comment]
Thanks to @ahuggel, the website is now back on-line.

I will work with Andreas and @nehaljwani to establish a new web-site with https://hostpresto.com  Andreas has asked that we try to get this done by the end of March and I will do my best to make that happen.

Nehal accepted my invitation to join Team Exiv2 on Slack.  I will discuss details the details of the move with him on Slack or by one-to-one email.

Very happy that we are making progress with this. Very appreciative of everything that Andreas has done over the years to bring Exiv2 to life and to the Open Source Community.

I'm going to close this issue.
