### ISSUE TITLE
CMake unconditionally builds Exiv2 0.27.0 with PIC

### ISSUE THREAD

**Issue by natewoodfb** [Exiv2/exiv2#738]
When building the 0.27.0 source for our service, we try to build once with PIC enabled and another time without it enabled for debug and production builds. The readme mentions setting `BUILD_SHARED_LIBS` to `OFF` to build exiv2lib as static.

However, in [src/CMakeLists.txt](https://github.com/Exiv2/exiv2/blob/master/src/CMakeLists.txt#L131) the flag `POSITION_INDEPENDENT_CODE` is unconditionally set for exiv2lib.

I fixed our build by modifying the source to check the `BUILD_SHARED_LIBS` flag, similar to how it's already done in [xmpsdk/CMakeLists.txt](https://github.com/Exiv2/exiv2/blob/master/xmpsdk/CMakeLists.txt#L54):

```
if (BUILD_SHARED_LIBS)
    set_target_properties( exiv2lib_int PROPERTIES
        POSITION_INDEPENDENT_CODE ON
        COMPILE_DEFINITIONS exiv2lib_STATIC
    )
endif()
```

I'm submitting this issue to bring awareness to the problem, in case the change should be made in the source code or if someone else has a similar problem.

**Comment by D4N** [comment]
I believe the PIC setting is intended.

What issue are you encountering due to position independent code?

**Comment by natewoodfb** [comment]
We want to have both a libexiv2.so and libexiv2.a, so we run cmake once with `-DBUILD_SHARED_LIBS=ON` and again with it `OFF`.

We are running all of this in a wrapper script to build everything and verify the result, which is checking for libexiv2.a to exist for the PIC version. The root cause may just be the wrapper script itself, however as I said making the change to Exiv2's CMakeLists.txt did fix the problem.

**Comment by D4N** [comment]
> We want to have both a libexiv2.so and libexiv2.a, so we run cmake once with -BUILD_SHARED_LIBS=ON and again with it OFF.

This should work if you use different build directories.

> We are running all of this in a wrapper script to build everything and verify the result, which is checking for libexiv2.a to exist for the PIC version. The root cause may just be the wrapper script itself, however as I said making the change to Exiv2's CMakeLists.txt did fix the problem.

Now you lost me: do you want -fPIC or not for the static library? And what is the **actual** problem or is it that you don't want position independent code in a static library?

**Comment by natewoodfb** [comment]
> This should work if you use different build directories.

Now I feel stupid, this was the correct solution and it build fine when I made this change.

> Now you lost me: do you want -fPIC or not for the static library? And what is the actual problem or is it that you don't want position independent code in a static library?

Yes, we wanted -fPIC for the static library.

Sorry for taking your time, building in separate directories fixed the problem without needing the CMakeLists change. Thank you!

**Comment by D4N** [comment]
natewoodfb <notifications@github.com> writes:

>> This should work if you use different build directories.
>
> Now I feel stupid, this was the correct solution and it build fine when I made this change.
>
>> Now you lost me: do you want -fPIC or not for the static library? And what is the actual problem or is it that you don't want position independent code in a static library?
>
> Yes, we wanted -fPIC for the static library.
>
> Sorry for taking your time, building in separate directories fixed the problem without needing the CMakeLists change. Thank you!
>

No problem at all, that was quite an easy fix ;-)

Glad your problem is now solved!
