### ISSUE TITLE
Regression in detected lens

### ISSUE THREAD

**Issue by codingdave** [Exiv2/exiv2#754]
Hi,

I have installed the current master version and face a regression of my Samyang 14mm lens. It now is wrongly identified as a 10mm lens. I am aware of the ~/.exiv2 file that can be used to tune the lens but I decided to file this bugreport because it is a regression as it is working fine in version .25. 

----------------
Correct information:

    dave@matebook:~$ /usr/bin/exiv2 --version
    exiv2 0.25 001900 (64 bit build)
    
    dave@matebook:~$ /usr/bin/exiv2 -pa --grep LensIDNumber ~/Schreibtisch/106ND750/DSC_4754.NEF
    Exif.NikonLd3.LensIDNumber                   Byte        1  Samyang AE 14mm f/2.8 ED AS IF UMC

----------------
Incorrect information:

    dave@matebook:~$ exiv2 --version
    exiv2 0.27.99.0

    dave@matebook:~$ exiv2 -pa --grep LensIDNumber ~/Schreibtisch/106ND750/DSC_4754.NEF
    Exif.NikonLd3.LensIDNumber                   Byte        1  Samyang 10mm f/2.8 ED AS NCS CS

For completeness I have added this information:

    dave@matebook:~$ exiv2 -pv --grep focal/i --grep lens/i --grep mcu/i ~/Schreibtisch/106ND750/DSC_4754.NEF
    0x920a Photo        FocalLength                 Rational    1  140/10
    0x0083 Nikon3       LensType                    Byte        1  2
    0x0084 Nikon3       Lens                        Rational    4  140/10 140/10 28/10 14/10
    0x008b Nikon3       LensFStops                  Undefined   4  72 1 12 0
    0x000b NikonLd3     FocalLength                 Byte        1  36
    0x000c NikonLd3     LensIDNumber                Byte        1  74
    0x000d NikonLd3     LensFStops                  Byte        1  72
    0x000e NikonLd3     MinFocalLength              Byte        1  36
    0x000f NikonLd3     MaxFocalLength              Byte        1  36
    0x0010 NikonLd3     MaxApertureAtMinFocal       Byte        1  36
    0x0011 NikonLd3     MaxApertureAtMaxFocal       Byte        1  12
    0x0012 NikonLd3     MCUVersion                  Byte        1  77
    0xa405 Photo        FocalLengthIn35mmFilm       Short       1  14

I can also send a caps-on, complete black image soon if you need it.

Kind regards
Dave

**Comment by D4N** [comment]
This might have been introduced by 7eb67aabe4b428f096d3b286a54e82af0461234f

**Comment by codingdave** [comment]
I also have the wrong result with
    git reset --hard 7eb67aabe4b428f096d3b286a54e82af0461234f~

Am So., 24. März 2019 um 14:25 Uhr schrieb D4N <notifications@github.com>:

> This might have been introduced by 7eb67aabe4b428f096d3b286a54e82af0461234f
>

**Comment by D4N** [comment]
Would you mind bisecting the issue and uploading the test image? Or only the latter, so that I can bisect it?

**Comment by codingdave** [comment]
I can create a black-full-non-edited raw in the evening but I have created a 1x1 px with dt and from testing exiv2 -pa / -pv I have verified that the issue appears also in that image. I hope you can work with that. If not, I will be able to upload a unmodified one in the evening when I'm back home. 
![DSC_4751](https://user-images.githubusercontent.com/3075641/54881910-392dcb80-4e55-11e9-9fd4-a22c837ce020.jpg)

**Comment by D4N** [comment]
You can create an image which only contains the extracted metadata via `exiv2 -ex $image`, that one contains no image data at all. It should be sufficient to reproduce the issue.

**Comment by codingdave** [comment]
Ok. Here it is. Btw, I had to zip it because .exv files are not allowed to upload. Going to bisect now ...
[DSC_4751.zip](https://github.com/Exiv2/exiv2/files/3000906/DSC_4751.zip)

**Comment by codingdave** [comment]
dave@matebook:~/workspace/exiv2.git$ git bisect bad
7eb67aabe4b428f096d3b286a54e82af0461234f is the first bad commit
commit 7eb67aabe4b428f096d3b286a54e82af0461234f
Author: Freddie Witherden <freddie@witherden.org>
Date:   Sat Mar 31 14:11:05 2018 +0100

    Update Nikon lens database.


Seems I have done something wrong before. Your first guess was correct. Sorry for the false notice. I am now absolutely sure it is introduced by this commit:

    git reset --hard 7eb67aabe4b428f096d3b286a54e82af0461234f
    HEAD ist jetzt bei 7eb67aab Update Nikon lens database.
    cmake ..; sudo make install -j8
-> Exif.NikonLd3.LensIDNumber                   Byte        1  Samyang 10mm f/2.8 ED AS NCS CS
-------
    git reset --hard 7eb67aabe4b428f096d3b286a54e82af0461234f~
    HEAD ist jetzt bei 2bc1c249 Merge pull request #607 from piponazo/NullptrAndNoexcept
    cmake ..; sudo make install -j8
-> Exif.NikonLd3.LensIDNumber                   Byte        1  Samyang AE 14mm f/2.8 ED AS IF UMC

**Comment by FreddieWitherden** [comment]
This is a known issue.  From nikonmn_int.cpp:
```
// Eight misidentified lenses due to double LensIDs:
//
// [snip]
//
// 4A 48 24 24 24 0C 4D 02.1: Samyang AE 14mm f/2.8 ED AS IF UMC
// 4A 48 24 24 24 0C 4D 02.2: Samyang 10mm f/2.8 ED AS NCS CS
```
Based on the current lens table data there is no means of disambiguating the two lenses.

Saying this (and in contrast with the seven other misidentified lenses) it is possible to resolve this issue by using the focal length.  Patches welcome.

**Comment by codingdave** [comment]
I agree that this could be fixed. The commit 7eb67aa however is a regression. So the first fix is a revert of this commit. I wonder why this has not happened yet, because it fixes the regression.

In a second step the focal lenght should be added into the detection of the lens, I agree with that. I was looking in the code and for me it looks like it is already checked. From nikonmn_int.cpp:
`if (   raw[0] == fmountlens[i].lid
                // stps varies with focal length for some Sigma zoom lenses.
                &&(raw[1] == fmountlens[i].stps || strcmp(fmountlens[i].manuf, "Sigma") == 0)
                && raw[2] == fmountlens[i].focs
                && raw[3] == fmountlens[i].focl
                && raw[4] == fmountlens[i].aps
                && raw[5] == fmountlens[i].apl
                && raw[6] == fmountlens[i].lfw
                && raw[7] == fmountlens[i].ltype) {
                // Lens found in database
                return os << fmountlens[i].manuf << " " << fmountlens[i].lensname;`

**Comment by FreddieWitherden** [comment]
> First off, the commit [7eb67aa](https://github.com/Exiv2/exiv2/commit/7eb67aabe4b428f096d3b286a54e82af0461234f) is a regression. So the fix is to revert this commit. I wonder why this has not happened yet, because it clearly fixes the regression.

Reverting the commit would not fix the regression.  All it would do is cause someone with a Samyang 10mm lens to complain that it is being identified as a Samyang 14mm lens.  Moreover, reverting would also remove support for many other (unambiguously identifiable) lenses.  Within the context of the current identification code there is no perfect solution and as such a call had to be made.  (And from the perspective of Exiv2 this call is to adopt the curation of Robert Rottmerhusen.)

> Anyhow, I was looking in the code and for me it looks like it is already checked. From nikonmn_int.cpp:
> 
> ```
>     if (raw[0] == fmountlens[i].lid
>     // stps varies with focal length for some Sigma zoom lenses.
>     &&(raw[1] == fmountlens[i].stps || strcmp(fmountlens[i].manuf, "Sigma") == 0)
>     && raw[2] == fmountlens[i].focs
>     && raw[3] == fmountlens[i].focl
>     && raw[4] == fmountlens[i].aps
>     && raw[5] == fmountlens[i].apl
>     && raw[6] == fmountlens[i].lfw
>     && raw[7] == fmountlens[i].ltype) {
>     // Lens found in database
>     return os << fmountlens[i].manuf << " " << fmountlens[i].lensname;  
> ```

The lens bytes are somewhat difficult to interpret.  To get the 'actual' focal length one would probably want to inspect

```
0x920a Photo        FocalLength                 Rational    1  140/10
```

although we would of course need confirmation from someone with the 10mm lens that it indeed reports its focal length correctly.

**Comment by codingdave** [comment]
If we have a regression A due to a patch and reverting that patch leads in a regression B then, since A was before B, A has a higher priority to be fixed. If you do it like you argue, keeping the commit to not have a regression in B would allow commits to be accepted when they improve 1 but break n things, so a diversion from "working fine" would happen continuously. Thats why in my opinion this arguments about the regression for the samyang 10mm does not hold.

You mentioned that the commit did a lot of things. You are right. So reverting the commit is not the solution, but the 2 lines in question can be reverted instead. I still think that this is the best way to stay consistent and fight regressions.

I dont have a 10mm samyang lens, nor do I have a picture of one. I only can help out with the 2.8 14mm ED AS IF UMC and I would like to contribute to this great project. Unfortunately I dont know where to start and I dont understand what you recommend to inspect.

I have been asking someone who has access to the raw.pixls.us database and unfortunately there is also no image from the required Samyang 10mm lens.

**Comment by FreddieWitherden** [comment]
> If we have a regression A due to a patch and reverting that patch leads in a regression B then, since A was before B, A has a higher priority to be fixed. If you do it like you argue (keeping the commit to not have a regression in B) would allow commits to be accepted when they improve 1 but break n things, so a diversion from "working fine" would happen continuously.

The point is that this is *not* strictly a regression; the previous code is broken (10mm identified as 14mm) and the current code is broken (14mm identified as 10mm).  Going from one broken state to another broken state is not a regression. 

The lens table itself is proved by Robert Rottmerhusen.  Thus whilst changing two lines would be relatively simple it would impose an ongoing burden every time we rebase the list.  And, perhaps more importantly, it would not resolve the issue (some people would still be unhappy).  Finally, it would also put us in the position of having to make calls about which group of people we annoy (for instance what if the misidentified lens outsold the currently identified lens by 50:1, would it be right to change our identification as it works for more people?).

To this end it may be worth removing support for all ambiguous lenses entirely, especially now that users can override it.  @clanmills what do you think?  At least this way everyone is equally unhappy.

**Comment by clanmills** [comment]
Ah, Freddie.  You know a President of the USA said: "You can please some of the people all of the time, all of the people some of the time.  However you can't please all of the people all of the time.".

I wish Exiv2 had never become involved with lens recognition.  However, it's there and folks want it to work.  I believe the lens recognition is used to a drive workflows to adjust image for "lens correction".  Perhaps that's what lensfun does.  I don't know.  I'm not a photographer.  

I added the ~/.exiv2 mechanism to make it easy/instant for folks to modify the lens recognition in Exiv2.  Folks say "we want something that's 100% reliable,  knows every lens (past, present and future) and is automatically kept up to date when I acquire/use a new lens and with every version of exiv2.  I believe ~/.exiv2 achieves those goals.

**Comment by clanmills** [comment]
I'm closing this matter.  We provide the ~/.exiv2 feature to deal with this.

The Lens is not explicitly identified in the metadata.  We have to "guess" the lens from other metadata such as LensIDNumber.  Not only is that tag in the Nikon MakerNotes (and therefore only valid for Nikon cameras, the same LensIDNumber can be used by more than one lens).  As @FreddieWitherden said: 

> the previous code is broken (10mm identified as 14mm) and the current code is broken (14mm identified as 10mm). Going from one broken state to another broken state is not a regression.

It's hard to believe how much work is demanded from the volunteers working on Exiv2 (and presumably other open-source projects).  Effectively this bug report is saying "I know you've dealt with this, however I want a different solution".  To this I respond "If you want a different solution, please submit a PR with appropriate updates to the test suite.".  While you're working on that, I'm going to continue the work to release Exiv2 v0.27.2 on schedule on 2019-06-30.
