### ISSUE TITLE
Failed to read specific pdf file with error "unknown image type"

### ISSUE THREAD

**Issue by t246246** [Exiv2/exiv2#762]
I tried with the latest MinGW version binary:

```
$ exiv2.exe -V |& head -1
exiv2 0.27.0

$ exiv2.exe test5p.pdf
Exiv2 exception in print action for file test5p.pdf:
test5p.pdf: The file contains data of an unknown image type
```

That file will be found via ImageMagick forum:
https://imagemagick.org/discourse-server/viewtopic.php?f=3&t=35171#p164630

They say the file is created by Microsoft Word.

**Comment by t246246** [comment]
I had thought exiv2 support PDF, but it is not included in man page.
So, please close this issue.

**Comment by clanmills** [comment]
Exiv2 has never supported PDF and there is no plan to implement that.  I would be a large undertaking.
