### ISSUE TITLE
Tag/Release 0.27.1 RC1 in git

### ISSUE THREAD

**Issue by imsodin** [Exiv2/exiv2#766]
According to https://discuss.pixls.us/t/exiv2-v0-27-1-rc1-is-ready/11963 a new RC was bundled and released - please tag the corresponding commit as well. And if possible please change the policy to use a fourth `.x` element for RCs, all versioning systems I know consider e.g. `0.27.1.1` (RC1 in your scheme) as newer than `0.27.1` (final release). It looks like you already do that for git tags (e.g. `v0.27.0-RC1`), but not for bundles.

As always, thanks everyone for your hard work!

**Comment by clanmills** [comment]
I'll change the version name if you can suggest how.  CMake seems to restrict the names to (non negative) numbers of the form: Major.Minor.Patch.Tweak.  https://cmake.org/cmake/help/latest/command/project.html

So 0.27.1 = "Dot 1".  (and GM will be so labelled).  So how do I handle RC1 in the "tweak"?

```
617 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ head -10 ../CMakeLists.txt 
cmake_minimum_required( VERSION 3.3.2 )

project(exiv2
    VERSION 0.27.1.RC1
    LANGUAGES CXX C
)

include(cmake/mainSetup.cmake  REQUIRED)

# options and their default values
618 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ cmake ..
CMake Error at CMakeLists.txt:3 (project):
  VERSION "0.27.1.RC1" format invalid.


-- Configuring incomplete, errors occurred!
See also "/Users/rmills/gnu/github/exiv2/0.27-maintenance/build/CMakeFiles/CMakeOutput.log".
See also "/Users/rmills/gnu/github/exiv2/0.27-maintenance/build/CMakeFiles/CMakeError.log".
619 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

I've modified the scripts which generate the web-site to massage "0.27.1.1" into "0.27.1 RC1".  I've put "Pre-release" on the background of every page.

I'll happily modify the numbering convention if you can help me with a practical suggestion.

**Comment by imsodin** [comment]
Looks like it isn't possible within cmake: https://gitlab.kitware.com/cmake/cmake/issues/16716 Looks like the only option would be to use the release version (0.27.1) in cmake and rename the bundle, but I see how that's ugly. In the end this was mostly a nitpick that someone might stumble over, I don't think it's very important. My main request was the git tag.

Maybe @cryptomilk has some advice concerning release candidates and cmake/cpack?

**Comment by cgilles** [comment]
Hi,

in digiKam and everywhere as i know from open source world, we use : 
"Major.Minor.Patch-Tweak" release naming.

At final release tweak is removed and "Major.Minor.Patch". This permit to not break the version scheme in packaging script '.' for offcial releases, '-' for pre-releases.

Gilles Caulier

**Comment by cryptomilk** [comment]
Example:

samba-4.8.0rc1
samba-4.8.0rc2
samba-4.8.0rc3
samba-4.8.0rc4
samba-4.8.0
samba-4.8.1
samba-4.8.2

**Comment by clanmills** [comment]
Thanks, Simon.  I wonder if we should tag RCs for "dots".  The plan for 2019 and 2020 is to have quarterly "dots" while the v0.28 "modernisation" project is in progress. The purpose of the "dots" is to provide security updates and to give the team more breathing space if v0.28 takes a while.

`$ git clone; git fetch...` reveals every tag.  If we have a lot of tags, somebody may complain __*AND*__ request back-ports of security fixes to every tag!
```
628 rmills@rmillsmbp:~/gnu/github/exiv2/foo $ git clone https://github.com/exiv2/exiv2 --depth 1
Cloning into 'exiv2'...
remote: Enumerating objects: 1034, done.
...
629 rmills@rmillsmbp:~/gnu/github/exiv2/foo $ cd exiv2
630 rmills@rmillsmbp:~/gnu/github/exiv2/foo/exiv2 $ git fetch --unshallow
remote: Enumerating objects: 38527, done.
...
From https://github.com/exiv2/exiv2
 * [new tag]           0.27-RC2   -> 0.27-RC2
 * [new tag]           0.27-RC3   -> 0.27-RC3
 * [new tag]           v0.26      -> v0.26
 * [new tag]           v0.27-RC1  -> v0.27-RC1
631 rmills@rmillsmbp:~/gnu/github/exiv2/foo/exiv2 $ 
```

With the web-site labelling the version as "Exiv2 v0.27.1 RC1" and the tags of the form "v0.27-RC1", the "human" labels are good.  So we're discussing the CMake/Project values which I believe flow into the SONAME.  Feedback from @cryptomilk or anybody else is welcome.

The command `$ exiv2 --verbose --version` displays a lot of build settings and runtime information.  I could massage that to convert `0.27.1.1` into `0.27.1 RC1`, however I prefer to continue to display "raw" CMake/Project data.

**Comment by imsodin** [comment]
@cryptomilk Looking at sambas git they don't seem to use cmake. The question isn't what versioning scheme to use, but how to produce source tarballs for release candidates when cmake/cpack restricts version to numerical characters. And avoiding the situation where `0.27.1.1` (RC) > 0.27.1 (final release).

@cgilles digiKam doesn't set it's version in the `project()` function and I can't see it doing it anywhere else in cmake code. You probably use a custom script to generate the source tarballs taking the version string from a file or tag (or KDE sysadmins do)?

@clanmills Don't worry about tags and backports - that's not what they are for. Maintenance branches are where backports happen and what you support there is up to you. As far as I can see the official policy is to maintain and release fixes (backports) for the latest release (currently 0.27) and some community efforts happen on backporting selected security fixes to 0.25. That seems totally fine to me and isn't impacted by how many tags you have. However some downstream packagers integrate your git repo in the process, where tags for releases (and release candidates) help a lot.

**Comment by cryptomilk** [comment]
You could use:

0.26.91 = rc1
0.26.92 = rc2
...

**Comment by imsodin** [comment]
> ==> Are you sure ? (:=)))

No, that's why I asked ;)  
However that's not used for cmake's `PROJECT_VERSION`, so it is a custom solution indeed.

> 0.26.91 = rc1
> 0.26.92 = rc2
> ...

That's just replacing one non-ideal solution with another. From all I see non-standard version handling is the only way to get it "right".

However we are digressing, I actually just wanted to get a git tag with this issue, the rest was a related side-thought :)

**Comment by clanmills** [comment]
I think we're good as we are.  With "the dots", I hope "code for RC1" == "code for GM" (only documentation changes), and don't need tags for "dot RCs".  We will tag v0.27.1, v0.27.2 etc.

@cgilles The tarball filenames are derived from the version information in the CMake/Project.

**Comment by imsodin** [comment]
> However we are digressing, I actually just wanted to get a git tag with this issue, the rest was a related side-thought :)

I'd still like to request an `0.27.1-RC1. This serves the same purpose as releasing the pre-release tarballs: Getting attention that a release is imminent and thus hopefully getting some people (e.g.  packagers) to do testing and thus potentially discover important problems before the release.

**Comment by clanmills** [comment]
@imsodin  Are you requesting that the code in the pre-release tarballs be tagged "0.27.1-RC1"?

I see we haven't been totally consistent in the past.
```
 * [new tag]           0.27-RC2   -> 0.27-RC2
 * [new tag]           0.27-RC3   -> 0.27-RC3
 * [new tag]           v0.26      -> v0.26
 * [new tag]           v0.27-RC1  -> v0.27-RC1
```
Let's call this v0.27.1-RC1.  If we need another, it'll be v0.27.1-RC2.  When we release the GM, let's call it "v0.27.1"

@piponazo Can you do that, please?  The code used is the current state of branch "Changes_for_v0.27.1.1"

**Comment by piponazo** [comment]
@clanmills Let's merge then #752 into `0.27-maintenance` and I'll create the tag afterwards. It seems that there is a typo in the documentation that you promised to fix beforehand. I'll wait for that change to merge the branch and create the tag.

**Comment by piponazo** [comment]
Here you have guys!
https://github.com/Exiv2/exiv2/releases/tag/v0.27.1-RC1

Can we close this ticket?

**Comment by imsodin** [comment]
Yep - thanks.

One minor comment about the release process (triggered by merging #752 after releasing tarballs and before tagging), which might not work as I have no idea how you do it: I'd propose to tag first, to make sure that the published source tarballs are made from the same files. Currently they seem to be identical except for one "typo":  
```diff
--- exiv2-0.27.1.1-Source/README.md     2019-03-29 14:14:01.000000000 +0100
+++ exiv2/README.md     2019-04-04 11:25:39.910387541 +0200
@@ -46,7 +46,7 @@
 |:------                      |:----     |
 | Project Homepage            | [https://github.com/Exiv2/exiv2](https://github.com/Exiv2/exiv2) |
 | Downloads and Documentation | [https://exiv2.org](https://exiv2.org) |
-| Prereleases:                | [https://prerelease.exiv2.org](https://prerelease.exiv2.org) |
+| Prereleases:                | [https://pre-release.exiv2.org](https://pre-release.exiv2.org) |
 | License (GPLv2)             | [COPYING](COPYING) |
 | CMake Downloads             | [https://cmake.org/download/](https://cmake.org/download/) |
```
