### ISSUE TITLE
installing exiv2 from head with vcpkg

### ISSUE THREAD

**Issue by B4rtware** [Exiv2/exiv2#777]
Hi,
I am trying to install exiv2 with `vcpkg install exiv2:x64-windows --head`. Unfortunately, the build fails with an error: 

`Error: Building package exiv2:x64-windows failed with: BUILD_FAILED`

Installing via normal install worked flawlessly. I was wondering if there is something I missed.
The latest release does not include the fix for c++11 where `auto_ptr` got renamed to `unique_ptr` and since I am using c++17 where `auto_ptr` was finally removed v0.27 does not work for me.

However, using conan to build after I have manually cloned the repo will work so it must have to do something with the usage of vcpkg + exiv2 I guess.

I would really appreciate any help because I would like to use vcpkg instead of doing it manually.

Here is the full error:

```
D:\$USER\Documents\git\vcpkg>vcpkg install exiv2:x64-windows --head
The following packages will be built and installed:
    exiv2[core]:x64-windows (from HEAD)
Starting package 1/1: exiv2:x64-windows
Building package exiv2[core]:x64-windows from HEAD...
-- Purging cached D:/$USER/Documents/git/vcpkg/downloads/Exiv2-exiv2-master.tar.gz to fetch latest (use --no-downloads to suppress)
-- Downloading https://api.github.com/repos/Exiv2/exiv2/git/refs/heads/master...
-- Skipping hash check for D:/$USER/Documents/git/vcpkg/downloads/temp/Exiv2-exiv2-master.tar.gz.version.
-- Downloading https://github.com/Exiv2/exiv2/archive/master.tar.gz...
-- Skipping hash check for D:/$USER/Documents/git/vcpkg/downloads/temp/Exiv2-exiv2-master.tar.gz.
-- Extracting source D:/$USER/Documents/git/vcpkg/downloads/Exiv2-exiv2-master.tar.gz
-- Applying patch iconv.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Using source at D:/$USER/Documents/git/vcpkg/buildtrees/exiv2/src/head/master-a5eaf86002
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:45 (message):

  'D:/$USER/Documents/git/vcpkg/packages/exiv2_x64-windows/debug/share/exiv2/cmake'
  does not exist.
Call Stack (most recent call first):
  ports/exiv2/portfile.cmake:32 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:71 (include)


Error: Building package exiv2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: exiv2:x64-windows
  Vcpkg version: 2018.11.23-nohash-external

Additionally, attach any relevant sections from the log files above.
```

**Comment by B4rtware** [comment]
Thanks for your both insanely fast replies :). Conan worked for me but I thought someone from here is responsible for the repo (port file) at vcpkg. I will post it in in their repo.

**Comment by clanmills** [comment]
I recall vcpkg being discussed by @jasjuang and perhaps he can assist.

The members of Team Exiv2 like responding quickly to users.  Insanely fast?  Maybe!
