### ISSUE TITLE
access violation vs 2017 msvc

### ISSUE THREAD

**Issue by ableade** [Exiv2/exiv2#783]
After building the most current version of exiv from source, I am running into issues using exiv in vs2017.
I am able to build the library with both debug and release DLLs. However attempting to use exiv with visual studio in release mode is causing an access violation reading error. 
```
#include <iostream>
#include <cassert>
#include <string>
#include <stdexcept>
#include <exiv2/exiv2.hpp>

using std::string;
using std::cerr;
int main() {
    try
    {
        const std::string imagepath = "capture4.png";
        auto image = Exiv2::ImageFactory::open(imagepath);
        //assert(image.get() != 0);
    }
    catch (const std::exception& e)
    {
        cerr << "Error: " << e.what() << '\n';
    }
    catch (...)
    {
        cerr << "Error, unknown exception caught.\n";
        
    }
}
```
The same code works fine in debug mode. In release mode, the image path string appears to be getting mangled when viewing through the debugger. Visual studio is reporting an "Error reading characters of string" I am also using c++ 17.

**Comment by clanmills** [comment]
You're building the branch 'master' (or 0.27-maintenance)?

This looks so "tame", it's hard to believe it's causing trouble.  Is there a reason to use C++17.  Can you try C++11?  I'm not sure I've understood how visual studio reports "error.....".

Are you linking release application with release library, (and debug application with debug library).

I'm not sure how best to help you.  Can you zip your project so we can be "on the same page".  Talk on Skype?  (clanmills).

**Comment by ableade** [comment]
I checked the visual studio solution folder where I build exiv and it does create two libraries in debug and release folders. However comparing the two, it appears there is no difference between them, I am suspecting that only the debug library is actually built. Perhaps, I did something wrong in the cmake configuration?

Here is the output of git reflog for the commit that was built

`
    4598ea93 (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: checkout: moving  from 
    3ec6aeb96f6d1c41b1880e46a7fc7cec2e42e5c4 to master                         3ec6aeb9 (origin/0.27) 
    HEAD@{1}: checkout: moving from master to origin/0.27     4598ea93 (HEAD -> master, origin/master, 
    origin/HEAD) HEAD@{2}: pull: Fast-forwa rd                                                                               
    e62aebd9 HEAD@{3}: clone: from https://github.com/Exiv2/exiv2.git
`

**Comment by clanmills** [comment]
Sola:  I'll confess.  I don't understand git.

We need to "get on the same page".  Talk on Skype or phone.  Best to screen-share.  Or zip your project and send it to me.

**Comment by piponazo** [comment]
Hi @ableade , I added your example in my **exiv2Consumer** repository and I could not reproduce your issue with VS 2017. It works fine for me:

```
pipon@DesktopWin10 MINGW64 /f/projects/exiv2Consumer/buildRelease (master)
$ cp /d/Images/goku.png capture4.png
$ ./issue783.exe
F:/projects/exiv2Consumer/buildRelease/issue783.exe: error while loading shared libraries: exiv2.dll: cannot open shared object file: No such file or directory

pipon@DesktopWin10 MINGW64 /f/projects/exiv2Consumer/buildRelease (master)
$ ls ../../exiv2/buildReleaseMaster/bin/*.dll
../../exiv2/buildReleaseMaster/bin/exiv2.dll*    ../../exiv2/buildReleaseMaster/bin/libeay32.dll*
../../exiv2/buildReleaseMaster/bin/libcurl.dll*  ../../exiv2/buildReleaseMaster/bin/ssleay32.dll*

pipon@DesktopWin10 MINGW64 /f/projects/exiv2Consumer/buildRelease (master)
$ cp ../../exiv2/buildReleaseMaster/bin/*.dll .

pipon@DesktopWin10 MINGW64 /f/projects/exiv2Consumer/buildRelease (master)
$ ./issue783.exe
Working like a charm!
```

Could you try to clone that repository and compile and run that executable? 
https://github.com/piponazo/exiv2Consumer

The only tricky thing I had to do was to copy the DLLs from the exiv2 installation folder to the build folder where I compiled the exiv2Consumer project.

**Comment by clanmills** [comment]
I'm going to set the Milestone for this to v0.27.2 which is schedule to be released at the end of June.  When we arrive at Exiv2 v0.27.2 RC1 (probably about June 10) this issue will be closed if we have made no further progress.
