### ISSUE TITLE
msvs 2015 x86 build

### ISSUE THREAD

**Issue by eadluru** [Exiv2/exiv2#787]
Can you please provide the pre-compiled library for visual studio 2015 x86. Its kinda difficult to build it using cmake for x86.

**Comment by D4N** [comment]
As per https://exiv2.org/download.html:

> The builds provided are those most likely to be of immediate use. If you require a 32 bit build or static libraries, or special configurations, you have to build from source.

I'd suggest to follow the build steps from [appveyor.yml](https://github.com/Exiv2/exiv2/blob/master/appveyor.yml) and also take a look at [README-CONAN.md](https://github.com/Exiv2/exiv2/blob/master/README-CONAN.md) which covers how to setup conan.

If there's something specific that is unclear or doesn't work, please tell us.

**Comment by eadluru** [comment]
i tried all those its kinda not woking.
Is there a easier way to make the files for Visual studio 2015 Win86

**Comment by eadluru** [comment]
i got 2 warnings and 7 errors. I am not quite sure why are there some files in 64 bit.
Attached is the snapshot of the messages. Please help me with this.

![image](https://user-images.githubusercontent.com/46500901/56587707-f8d68000-65af-11e9-8cde-45a5479d31fd.png)

**Comment by D4N** [comment]
Please start from a clean new exiv2 workspace and a clean conan config, then write down the steps you did, otherwise I'm hardly able to help you just from a screenshot of an error message.

**Comment by eadluru** [comment]
I downloaded the windows version of conan from https://conan.io/downloads and followed the steps from the github link you gave me https://github.com/Exiv2/exiv2/blob/master/README-CONAN.md#1-1

**Comment by eadluru** [comment]
everything went fine i got all the outputs as expected but the last Build Exiv2 gave me those 2 warnings and  17 errors

**Comment by D4N** [comment]
Try it with a different `arch` and `arch_build` setting in step [1-4](https://github.com/Exiv2/exiv2/blob/master/README-CONAN.md#1-4). Same applies for any invocations of `conan` with `--profile`, where you should use the non 64 bit variant and with `cmake -G` (again don't use the Visual Studio 64 bit version here, just the ordinary one).

**Comment by eadluru** [comment]
i did not include the profile when i did it earlier

**Comment by D4N** [comment]
Then please do so, conan will otherwise probably use a 64 bit profile by default.

**Comment by clanmills** [comment]
I've built 'master' with MSVC 2015 32 bits.  Let me know if you need something else built such as v0.27.1 which I expect to release tomorrow.

I am surprised you're having any difficulty with this.  I'll be happy to meet with you 1-to-1 on Skype ('clanmills') and together we'll get this built on your machine.
[exiv2-0.27.99.0-2015msvc32-2019:04:23_17:34:07.zip](https://github.com/Exiv2/exiv2/files/3108886/exiv2-0.27.99.0-2015msvc32-2019.04.23_17.34.07.zip)

**Comment by eadluru** [comment]
thank you very much i was able to build it myself

**Comment by clanmills** [comment]
Happy Users, that's what we like.
