### ISSUE TITLE
writing metadata

### ISSUE THREAD

**Issue by eadluru** [Exiv2/exiv2#792]
i ma working on writing metadata to a tiff image as xmp file.

I use the following code:
//Writing Metadata into image
	
         Exiv2::Image::AutoPtr image = Exiv2::ImageFactory::open(filename.toStdString());
	assert(image.get()!=0);
	image->setExifData(exifData);
	image->writeMetadata();

but i am getting a error saying AutoPtr not a member og Exiv2::Image

**Comment by clanmills** [comment]
I'm haven't understood your issue.  A message concerning "AutoPtr not a member of Exiv2::Image" sounds like a compiler error.  Are you building with 'master' or released code?

The team are "modernising" the code for v0.28 to C++11.  AutoPtr is being replaced with UniquePtr on 'master'

```
548 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ git status
On branch 0.27-maintenance
Your branch is up-to-date with 'origin/0.27-maintenance'.
549 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ grep ImageFact samples/exifprint.cpp 
    Exiv2::Image::AutoPtr image = Exiv2::ImageFactory::open(file); <--- AutoPtr
550 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ 
550 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ 
550 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
551 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ grep ImageFact samples/exifprint.cpp 
    Exiv2::Image::UniquePtr image = Exiv2::ImageFactory::open(file); <--- UniquePtr
552 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ 
```

**Comment by clanmills** [comment]
I'm going to mark this as "Closed".  @eadluru If you wish to discuss this further, I'm happy to reopen the issue.

**Comment by yarmoliq** [comment]
[This sample program](https://exiv2.org/doc/exifprint_8cpp-example.html#_a9) uses `AutoPtr`. That's why I encountered the sample problem. Thanks for helping and clearing things out!
