### ISSUE TITLE
twin include

### ISSUE THREAD

**Issue by maddin200** [Exiv2/exiv2#80]
/src/webpimage.cpp)  (line 47): 
included twice
#include "tags_int.hpp"

**Comment by clanmills** [comment]
Well spotted.  Fixed: d43cd820

Here's a little puzzle.  Write a bash script to detect this in all the Exiv2 files.  For bonus points, detect any file that has been recursively included.

**Comment by maddin200** [comment]
some kind of reuse:
http://gernotklingler.com/blog/open-source-tools-examine-and-adjust-include-dependencies/

**Comment by clanmills** [comment]
Thanks for the pointers.  Google's "include-what-you-use" tool sounds great.
