### ISSUE TITLE
twin include

### ISSUE THREAD

**Issue by maddin200** [Exiv2/exiv2#83]
here is another:

/src/pngimage.cpp) (line 40): (image_int.hpp)  

so far all I found

**Comment by clanmills** [comment]
Ah maddin200, you're entertaining me.  (This is more fun that what I'm actually working on at the moment).

**Comment by maddin200** [comment]
found with an internal tool :-)

**Comment by clanmills** [comment]
Well done, Martin.  If you're bored over the weekend, have a look at Google's tool.  Maybe we'll learn something interesting.  There are 100,000 lines of code in Exiv2 and I'm sure there are lots of curious things that nobody knows.  You know how it is, code is added to do something.  It builds, passes the test suite and lives forever in the code base.  I have plenty of work to keep the product stable, building/testing on 18 platforms, answering user queries and developing new features.  I don't have a lot of time to ask the question "could we speed up the build by removing some include files?”.
