### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by jasjuang** [Exiv2/exiv2#85]
I am trying to make a [vcpkg ](https://github.com/Microsoft/vcpkg/) port for exiv2 and currently the v0.26 release does not compile with the standard

``````
cd exiv2
mkdir build
cd build
cmake -A x64 ..
msbuild exiv2.sln /p:Configuration=Release
``````

However, the current master does compiles successfully. Therefore, could you make a new release with the current master for vcpkg users? Thank you very much.

**Comment by a17r** [comment]
@jasjuang work is under way for a .1 point release. meanwhile you are invited to take a look at the patches Gentoo does apply to get it going: https://github.com/gentoo/gentoo/tree/master/media-gfx/exiv2/files

**Comment by jasjuang** [comment]
@a17r while the .1 point release is underway is it possible to release a intermediate 0.27 release with the current master?

**Comment by clanmills** [comment]
There is currently considerable work in progress to create the v0.26.1 release.  The release of Visual Studio 2017 including vcpkg coincided with v0.26 in April 2017.  I'm reluctant to create a myriad of releases of Exiv2.  Perhaps you could work with me to ensure that Exiv2 v0.26.1 is compatible with vcpkg.

**Comment by jasjuang** [comment]
@clanmills I can for sure work with you to ensure that Exiv2 v0.26.1 is compatible with vcpkg.

**Comment by clanmills** [comment]
Jason

I'm going to close this for now.  I believe @piponazo has made the appropriate changes.  Later in the development cycle (before RC1), I ask you to reconfirm that everything is working as you expect.
