### ISSUE TITLE
error: no type named 'Error' in namespace 'Exiv2'

### ISSUE THREAD

**Issue by Dembalulua** [Exiv2/exiv2#893]
I'm the maintainer of the Python-3 binding of exiv2.

The version 0.27 of exiv2 had introduced an issue into the binding with the error codes.

Then I've changed my code like this:

#if EXIV2_MAJOR_VERSION >= 1 || (EXIV2_MAJOR_VERSION == 0 && EXIV2_MINOR_VERSION >= 27)
#define HAVE_EXIV2_ERROR_CODE
#endif

#ifdef HAVE_EXIV2_ERROR_CODE
// version >= 0.27
#define CHECK_METADATA_READ \
    if (!_dataRead) throw Exiv2::Error(Exiv2::kerErrorMessage, "metadata not read");
#else
// version < 0.27
#define CHECK_METADATA_READ \
    if (!_dataRead) throw Exiv2::Error(METADATA_NOT_READ);
#endif

That's solved the problem. (compiled on Linux with g++ and on OS X with clang)

But today, on OS X with the latest exiv2-0.27.2 the compilation failed with:

src/exiv2wrapper.cpp:150:12  error: no type named 'Error' in namespace 'Exiv2'
Exiv2::Error error = Exiv2::Error(Exiv2::kerSuccess);
~~~~~~~^

Is there a new change in 0.27.0 ?

**Comment by Dembalulua** [comment]
Sorry, there is a typo is not the version 0.27.2 but 0.27.1.

**Comment by clanmills** [comment]
Thanks for getting in touch about this.  And thank you for your work on py3exiv2.  About a year ago, somebody asked about building pyexiv3 on CentOS and I got v0.26 to build and documented:   https://dev.exiv2.org/projects/exiv2/wiki/BuildingPy3Exiv2onCentos

Last week, the maintainer of gexiv2 has asked about API stability of the Exiv2 v0.27.N APIs: https://github.com/Exiv2/exiv2/issues/890 Exiv2 v0.27.2 is scheduled for 2019-06-30 and I hope there will be no visible changes to the API between v0.27.1 and v0.27.2.  

There's a macro `EXIV2_TEST_VERSION` in `include/exiv2/version.cpp` for testing the version of Exiv2. 

There was a change in v0.27.1 concerning Error.  I wasn't involved, however I think it had something to do with the template for `Exiv2::Error::setMsg(std::wstring&)`.

I'm not too sure that I've understood what you are discussing, however I added your code `Exiv2::Error error = Exiv2::Error(Exiv2::kerSuccess);` to samples/exifprint.cpp and it compiles on MacOS-X:
```
746 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ git diff
diff --git a/samples/exifprint.cpp b/samples/exifprint.cpp
index 5f4d5da1..c0f42d3e 100644
--- a/samples/exifprint.cpp
+++ b/samples/exifprint.cpp
@@ -32,6 +32,9 @@ try {
     const _tchar* prog = argv[0];
     const _tchar* file = argv[1];
 
+    Exiv2::Error error = Exiv2::Error(Exiv2::kerSuccess);
+    std::cout << "error " << error << std::endl;
+
     if (argc != 2) {
         std::_tcout << _t("Usage: ") << prog << _t(" [ file | --version || --version-test ]") << std::endl;
         return 1;
747 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

I'm very happy to work with you to deal with this.

When I worked on the getting py3exiv2 to run on CentOS, I wasn't able to build on MacOS-X (nor with Visual Studio on Windows).  I've forgotten the details, however I think there's a python script (setup.py) that compiles the wrapper and that worked fine on CentOS (and Ubuntu) and needed more platform specific work.  As my user only asked about CentOS, I didn't pursue the other platforms.  Are you now supporting MacOS-X with py3exiv2?

**Comment by clanmills** [comment]
I've installed `boost_1_70_0` on my MacBook Pro and your code `py3exiv2-0.7.0`.

I had to make a couple of changes to get your code to compile:
```
849 rmills@rmillsmbp:~/gnu/py3exiv2-0.7.0/src $ diff exiv2wrapper.hpp  ~/Downloads/py3exiv2-0.7.0/src/exiv2wrapper.hpp 
31c31,34
< #include <exiv2/exiv2.hpp>
---
> 
> #include "exiv2/image.hpp"
> #include "exiv2/preview.hpp"
> 
850 rmills@rmillsmbp:~/gnu/py3exiv2-0.7.0/src $ diff exiv2wrapper_python.cpp  ~/Downloads/py3exiv2-0.7.0/src/exiv2wrapper_python.cpp 
29c29,31
< #include <exiv2/exiv2.hpp>
---
> #include "exiv2/exv_conf.h"
> #include "exiv2/version.hpp"
> 
31d32
< #include <iostream>
851 rmills@rmillsmbp:~/gnu/py3exiv2-0.7.0/src $ 
```
It now compiles.  However setup.py doesn't seem to work on MacOS-X.

```
853 rmills@rmillsmbp:~/gnu/py3exiv2-0.7.0 $ sudo python3 setup.py install
running install
running bdist_egg
running egg_info
writing src/py3exiv2.egg-info/PKG-INFO
writing dependency_links to src/py3exiv2.egg-info/dependency_links.txt
writing top-level names to src/py3exiv2.egg-info/top_level.txt
reading manifest file 'src/py3exiv2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/py3exiv2.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
running build_ext
building 'libexiv2python' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/exiv2wrapper.cpp -o build/temp.macosx-10.9-x86_64-3.7/src/exiv2wrapper.o -g
src/exiv2wrapper.cpp:1848:28: warning: unused variable 'ns' [-Wunused-variable]
        const std::string& ns = Exiv2::XmpProperties::ns(prefix);
                           ^
src/exiv2wrapper.cpp:1879:28: warning: unused variable 'ns' [-Wunused-variable]
        const std::string& ns = Exiv2::XmpProperties::ns(prefix);
                           ^
src/exiv2wrapper.cpp:1910:37: warning: unused variable 'info' [-Wunused-variable]
            const Exiv2::XmpNsInfo* info = Exiv2::XmpProperties::nsInfo(prefix);
                                    ^
3 warnings generated.
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/exiv2wrapper_python.cpp -o build/temp.macosx-10.9-x86_64-3.7/src/exiv2wrapper_python.o -g
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    extra_compile_args=['-g']
```

I know I investigated this last year and it was some platform issue concerning the path to python on MacOS-X. 

The point is that the code compiles and I don't see any issue with Exiv2::Error.

Concerning the changes I made to the header files, the preferred way to include exiv2 into C++ code is:
```
#include <exiv2/exiv2.hpp>
```

Exiv2 users are discouraged from including exiv2 files individually for several reasons:

1) `#include <exiv2/exiv2.hpp>` is simpler
2) we have the freedom to change code inside our header files without worrying about how it could impact users.  All our samples/ code uses this.
3) `#include <exiv2/exiv2.hpp>` includes installed files from a system path such as /usr/local/include

Perhaps you could make the change the include files, build your code and share you results.

**Comment by Dembalulua** [comment]
Thinks are often more clear after one night.

With some minor changes, I can now compile for OS X.

I've add #include "exiv2/exiv2.hpp" in exiv2wrapper.hpp and modified the setup.py to find libboost_python3* 

The packages available here: http://www.py3exiv2.tuxfamily.org/downloads are updated but not yet on PyPI.

PS. I see your last post now, it seems we have made the same changes.

**Comment by clanmills** [comment]
Good Stuff.  Great Minds Think Alike!

I'm closing this now.  Always happy to be of help to you.  Thank You for promoting the use of Exiv2.
