### ISSUE TITLE
Let's go to LGM 2020 in Rennes, France

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#911]
Libre Graphics Meeting is a conference on Graphics Open Source Developers.  Typically 100 Engineers spend a long week-end (Thursday -> Sunday) to attend presentations, workshops, meet each other, relax and drink beer.  It's wonderful to spend time together and get to know each other.

When I attended for one day in 2016, I met folks from Darktable, Gimp and other projects that use Exiv2.

This global event has been held on several continents since its inception about 2000.  Recent conferences were held in the spring (April or May)
2016 London, UK (I attended for one day)
2017 Rio, Brazil (I gave a presentation remotely)
2018 Seville, Spain
2019 Saarbrücken, Germany @cryptomilk gave a 5 minute presentation about Exiv2.
2020 Rennes, France

Let's have a Team Exiv2 meeting next year in Rennes.  The organisers take care to manage cost by holding the conference in a university and student accomodation.  However, as Exiv2 has no revenue, we'll have to travel and pay our own expenses.  Your boss (in my case Alison) may be sympathetic and allow you to submit an expense claim.

@boardhead Perhaps the University will consider this worthy of their support.  I think your attendance would deserve an invitation to give a "key-note" on one day of the conference. 

I would like to run an "Exiv2 Architecture" Workshop and we could spend half a day discussing the internals of Exiv2.  How does the TiffParser actually work?  Let me explain and I hope you won't fall asleep.

I'll update this issue as I learn more about the arrangements.  Who's interested in attending?

**Comment by clanmills** [comment]
@boardhead  I intended to copy you on this.

@boardman Apologies for dragging you into this (and some other Exiv2 discussions).

**Comment by boardhead** [comment]
@clanmills Thanks for the invite, but the ExifTool project is not part of my university job description, so I would be on my own here.  Plus, I think you may be underestimating just how boring a key-note talk from me would be.  :P

**Comment by clanmills** [comment]
University politics (splutter, cough, vomiting).  I'm sure you'd be wonderful and I'm confident that the audience will be full of your fans.

I'd like to give a talk entitled "Git is a load of crap", but I'd be boo-ed off.  It's amazing how some technology (for example MacOS-X) is loved by users, while other similar things (Windows) is detested.  Oh well, that's the world and it ain't gonna change.

I was running in the D-Day Marathon in Normandy on Sunday with a guy who is a plastic surgeon.  When he told me, I said "Goodness me" and he said "Nobody's Perfect!".  We could do a double-act "Images:  What do they mean?" (or something clever and witty).

(Dr Daniel is the guy on the right with the red skull-cap).
![IMG_3714](https://user-images.githubusercontent.com/529982/59920888-e9df4300-9423-11e9-8ba9-a21960f96678.jpg)

**Comment by clanmills** [comment]
Folks

I'm going to write a book about Exiv2 Architecture and I will offer a "Metadata and Exiv2 Architecture" workshop at LGM 2020.

The book will be about 12 chapters and I'm thinking to write about 1 chapter/month, so it'll take about 1 year.  The chapters will be topics such as:

1) Image File Formats
2) Tiff

**Comment by piponazo** [comment]
Great news @clanmills . I'll be happy to review the chapters :wink:

**Comment by clanmills** [comment]
@piponazo That'll be great.  I want to create a "road map" to the architecture of Exiv2 __*and*__ to explain how metadata is stored in images.  To my knowledge, nobody has written a book about metadata.

**Comment by clanmills** [comment]
I've had a reply from Timothée:

> Good to see the Exiv2 team is interested to attend LGM next year.
> However, as we announced in Saarbrucken, it is indeed on that week that
we are planning to have the event (May 28th to 31st).

It's our son's Wedding Reception on Friday 28 May.  I believe I can come on Saturday 29 and stay for the weekend.

LGM in 2021 will be in Sri Lanka.  I don't intend to attend.  I've decided to only fly when I believe the journey is essential.  So, I would get a ferry to St Malo to go to Rennes.  Perhaps I'll fly to save time.  However, I will not go to Colombo.

**Comment by clanmills** [comment]
I submitted the following proposal about 2019-12-08.  I received no acknowledgment.

———————————
Talk Proposal:  What has Open Source Done for Us?
By: Robin Mills (exiv2.org)

_You may be aware of the scene in Monty Python's "Life of Brian" entitled: "What have the Roman's ever done for us."_  https://www.youtube.com/watch?v=Y7tvauOJMHo

_I have worked on Exiv2 for 12 years and contributed more than 10,000 hours.  I've been the maintainer for the past 5 years.  I'm 69 and very happy to have retired (from Adobe in 2014) and Exiv2 (in 2019).  Delighted that Luis and Dan have taken on the challenge to maintain Exiv2.  New volunteers are always welcome._

_What does it take to maintain an open-source project?  More than you would believe!  Yet some folks (such as me) are mad enough to make the effort._

_This talk is a light-hearted discussion about the trials, tribulations, and triumphs endured to bring open-source to the world._
———————————

LGM is 28-31 May 2020.  My son’s Wedding Reception in England is 29 May.  If my paper is accepted, I will go to LGM. The Wedding was in Phuket, Thailand on 2019-12-18.  Beautiful.

![DSC_9848](https://user-images.githubusercontent.com/529982/71719405-2bf73180-2e16-11ea-960c-e9b3eb356106.jpg)

**Comment by clanmills** [comment]
I'm going to close this issue as there's nothing further to discuss.
