### ISSUE TITLE
Unable to checkout v0.27.2-RC1

### ISSUE THREAD

**Issue by imsodin** [Exiv2/exiv2#915]
I just wanted to have a look at the most recent RC for packaging but was unable to check it out in my local repo. `git fetch upstream` (where upstream is my local alias for github.com/Exiv2/exiv) does not download the tag `v0.27.2-RC1`. Explicitly fetching that results in

```
$ git fetch upstream v0.27.2-RC1
From https://github.com/Exiv2/exiv2
 * tag                 v0.27.2-RC1 -> FETCH_HEAD
``` 

However the tag is still not listed by `git tag` and can't be checked out. Neither is the commit ba3bb9ae0f27b62149815371238bad9d115faaa1 available. Looking at the commit log of the tag (https://github.com/Exiv2/exiv2/commits/v0.27.2-RC1) shows that it diverged from the `0.27-maintenance` branch (https://github.com/Exiv2/exiv2/commits/0.27-maintenance). That in itself is not good in my opinion, as it just makes the history harder to follow, but it shouldn't be a reason why the tag can't be checked out.

Could someone please check whether they are able to check tag `v0.27.2-RC1` out.

And I do request for release tags to happen in a branch, not any "free" commit. I would just do it directly in the `0.27-maintenance` branch or then split off a release branch for 0.27.2 (but that seems a bit too much for a simple point release).

**Comment by clanmills** [comment]
Simon:  I put the tag on to avoid getting this message from you.  I've never applied a git tag before and was setting off on vacation immediately after making the release.  On Thursday night, I made the release and applied the tag.  Everything in git is impossibly difficult to understand, so I didn't expect it to work and you are confirming that the tag is not correct.

Perhaps somebody else on Team Exiv2 can deal with this while I'm on vacation.

Would you like to join Team Exiv2 and be "tag man".  I'll let you know when I make a release and you can tag the damn thing.

**Comment by imsodin** [comment]
@clanmills I am sorry to have reached you in vacation with this - please don't pay any further attention to it and enjoy your vacation!

Joining the team just to tag releases seems a bit much. @piponazo already created previous releases on Github, I am sure he is ok with also taking care of setting the tag in the process.

**Comment by clanmills** [comment]
I'm sure @piponazo will do something about this.  The RC1 isn't on the 0.27-maintenance branch.  It's on origin/v0.27.2.1 (which is branched from 0.27-maintenance).

If I could understand git, I would write a paper "Reasons to hate git".  Until, then I will simply hate git.

**Comment by clanmills** [comment]
I am very upset about this issue.  I tried to avoid hearing from you.  I'm sure we'll get the tag fixed in the next few days and I will enjoy my vacation.  If note that you have refused to help.  Very upset by your behaviour.

**Comment by imsodin** [comment]
There has clearly been a misunderstanding here. I sympathize with your struggle with git and even more so not wanting to deal with this on your vacation. And you shouldn't. This is not time critical. I simply want to help this project by checking the RC and eventually maybe package it for Debian. I haven't refused anything, I have simply stated that making me a team member, with all the assossiated organisational overhead and permissions, seems a bit disproportionat to simply setting a tag. If you and your fellow maintainers really want that, I could definitely do it. However I hope you reevaluate your opinion about "my behaviour", I see no reason whatsover for it.

**Comment by clanmills** [comment]
I apologise for over-reacting.  To say that git has caused me trouble is quite insufficient to describe the difficulties it has created.  Two years of total misery.  I don't even know what problem 'git' is addressing. For sure, it has created problems that never existed with SVN (or perforce at work).  I haven't discovered any feature of 'git' that leads me to think "this is worth the pain".  Even the name 'git' is bizarre.  'git' is english slang for a very stupid person.  

When we adopted 'git', the first issue raised was about tags.  https://github.com/Exiv2/exiv2/issues/1

We'll get this fixed.

**Comment by piponazo** [comment]
Hi guys. I just removed the previous tag (which was created in a development branch) and created the tag in the proper place (in the `0.27-maintenance branch). You can find the release page here:

https://github.com/Exiv2/exiv2/releases/tag/v0.27.2-RC1

I am sorry if the delay have caused some issues. Lately I do not have much spare time.

Cheers!
