### ISSUE TITLE
XMP SDK version

### ISSUE THREAD

**Issue by tester0077** [Exiv2/exiv2#919]
As I am very unfamiliar with Conan and its process, I am unsure of how to even phrase my question.
After downloading & compiling the Widows 32-bit version, I see that the XMP SDK version I have as part of the exiv2 is 4.4.0 while the most recent version I have directly from the Adobe 5.6.0 & 5.7.0 for Core/File versions.
Is this an issue with Conan, Exiv2 or ..... ??

**Comment by clanmills** [comment]
You can build Exiv2 with the 2016 edition of Adobe's XMPsdk. This is documented in README-CONAN.md

We provide support in Exiv2 v0.27 for users wishing to use both Exiv2 and XMPsdk in an application.  The 4.4.0 source code provided in the code base is recommended for almost every user as it has been in service for about 10 years and given excellent service.  If you have no special reason to require newer Adobe code, I recommend you build Exiv2 with the embedded XMPsdk.

**Comment by tester0077** [comment]
As I recall from my earlier work (several years ago) with the Adobe XMP SDK, I had issues with the earlier version when some of the metadata strings were UTF-8 encoded. The specifics of the SDK version which gave me trouble are hazy, but I do not have those issues when I use the latest 2016.07 SDK.
Looking through the change log in XMP-Toolkit-SDK-Overview.pdf for the 2016.07 version I do see a number of changes since version 4.4.2 related to UTF-8.
Fortunately, Exiv2 keeps the XMP SDK separate so I can pick and chose.
If I get the opportunity (i.e. I find the file with UTF-8 data), I will see if I can try both versions and verify one way or the other and then provide feedback for you.
