### ISSUE TITLE
Retain msvc/ solution and project files

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#95]
I am very concerned about the criticism of my desire to retain the msvc/ solution and project files.  It is my opinion that CMake/Visual Studio struggles to build Exiv2.  And while there is a case to consider this matter, there is strong evidence that Visual Studio Users do not like CMake.  I could discuss subjects such as the zlib/zlibstatic issue, concerns about static linking and other matters.  However I want to focus on something that we never discuss "The Visual Studio User Experience".

Visual Studio users like Visual Studio.  You open the solution and build.  They effortless switch between 64 and 32 bit builds, debug/release, static/dll.  It has a great debugger and object browser.  The UI enables tweaks to build settings.  It's a very nice place in which Windows Developers are productive and happy.

CMake destroys all of this.  Instead of opening the solution, you have to run this strange tool which doesn't understand how to find or link dependencies.  If you tweak any setting in the Visual Studio UI, CMake will silently undo your changes and enforce his strong will on your project.  Trying to discuss this with CMake Lovers results in abusive comments and pointless criticism of Windows by folks who clearly do not know Visual Studio.

As the msvc/ solution files have been in production with Exiv2 for almost 10 years, I don't see any reason to remove them.  They work.  I am not asking for other team members to be involved in the support of those files.

In 2014, I invested 200 hours in contrib/cmake/msvc/cmakeBuild.cmd.  I have tried hard to make CMake/Visual Studio work well.  And indeed the nightly build of Exiv2 is performed by that script. 

I will support the removal of msvc/ when I am convinced that CMake/Visual Studio with conan or vcpkg is a genuine replacement for msvc/.  Until then, I ask other team members to support my contribution and stop discussing this matter.  After all, I use msvc/ and I'm not asking anybody else to do any work to support msvc/

**Comment by tbeu** [comment]
Please keep and maintain the working VS projects. We raised this discussion last year at a team meeting and should not give them up in favour of CMake tool. I can give enough more reasons (if you like and once I am able to see my mails archive.)

**Comment by piponazo** [comment]
Even being one of these CMake lovers I understand this good reasoning for maintaining the Visual Studio project/solutions.

**Comment by clanmills** [comment]
@piponazo I appreciate your love of CMake and I have worked hard in the past to discover how to make CMake and Visual Studio work well together.  Perhaps one day, with your help, I'll come to share your enthusiasm.  Not yet. 

Thanks to Thomas for getting involved in this discussion.  I know he shares my doubts that CMake is a replacement for solution+project files. 

I'm going to close this as I believe that we agree to retain msvc/ until CMake is a demonstrable replacement.
