### ISSUE TITLE
Build fails on MacOS-X when /usr/local/lib/libintl.dylib is missing

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#966]
I was working on the phone with a user in Little Rock, Arkansas.  He doesn't have libintl.dylib on his machine.  The MacOS-X bundle would not run because he doesn't have /usr/local/lib/libintl.dylib  I made a private build on 0.27.1 for him with EXIV2_ENABLE_NLS=Off and sent it to him and that was fine.

Later in our discussion, I got him to build from source.  The build failed while building the exiv2 command-line application complaining about libintl.dylib being missing.

I haven't understood what libintl does.  I don't even know how/why it's on my machine.

It's not on Linux.  I think it's built into the C Library.
https://stackoverflow.com/questions/11370684/what-is-libintl-h-and-where-can-i-get-it

I'd like to take two actions from this:
1) Ensure that public packages never use libraries from /usr/local/lib
I've done this on the build server for expat and zlib.
Build MacOSX packages with EXIV2_ENABLE_NLS=Off

2) Discover what's really wrong with the detection of libintl. 

The code in `cmake/findDependencies.cmake` is:
```
if (EXIV2_ENABLE_NLS)
    find_package(Intl REQUIRED)
endif( )
```

I removed libintl.dylib and libintl.a from my machine from /usr/local, /opt (macports installed that) and /sw (brew installed that).  Now pgk-config and uname are broken!  CMake still reports:
```
-- Native language support:            YES
```

Confused?  

@piponazo Please don't spend time on this.  Let me do the detective work to really understand what is going on here.

**Comment by piponazo** [comment]
I just want to point you to this CMake documentation page about FindIntl:

https://cmake.org/cmake/help/latest/module/FindIntl.html

Note that for example on Linux with GNU libc, the support is for the gettext functions are there.

**Comment by clanmills** [comment]
Thanks, Luis.  Yes.  I should have mentioned gettext in the bug report.  

For years, I never build Exiv2 on MacOS-X with NLS because I just ran into trouble and there was no documentation about how to use NLS.  So I closed my eyes and pretended there was nothing wrong.  I'm going to explore this matter.

Those libraries on my lpatop in /sw (brew) and /opt (MacPorts) probably exist efforts to build NLS.

**Comment by clanmills** [comment]
Gosh, this is a horrible matter.  I've uninstalled gettext:
```
740 rmills@rmillsmm-local:/usr/local $ cd ~/gnu/gettext/gettext-0.19.2
741 rmills@rmillsmm-local:~/gnu/gettext/gettext-0.19.2 $ sudo make uninstall
```

FindIntl reports we're linked with Mono (which I think is .Net/Unix).
```
-- Found Intl: /Library/Frameworks/Mono.framework/Headers 
```

And bin/exiv2 is still linked to /usr/local/lib:
```
736 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 -vVg lib --grep nls
exiv2 0.27.2.2
library=/usr/local/lib/libexiv2.27.dylib
library=/usr/local/lib/libintl.8.dylib
...
enable_nls=1
737 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

Deleting /usr/local/lib/libintl.8.dylib on the machine creates huge problems because I have coreutils built and installed on the machine.  Most of the unix commands are in /usr/local/bin and linked to libintl.8.dylib.  That's why `uname` and `pkg-config` are displaying errors during the build!

I'm going to install a fresh MacOS-X VM and test the bundles on that.  In future, MacOS-X bundles will be build on that VM and not on the build-server's MacOS-X instance.

**Comment by clanmills** [comment]
I've installed a new MacOS-X VM on the buildserver.  There's good news.  The default build fails because /usr/local/include/libintl.h is missing.  John's machine (the user in Little Rock, Arkansas) has a slightly mixed up machine.  It error off and does not.

It used to be that NLS would be disabled when this occurred.  So now the default build fails on the build server.

I'm going to disable NLS for the build bundles.  This inflicts the unnecessary complication on the user of having to install/build gettext just to use our bundle.

I've also looked at the libraries on Linux, Cygwin and MinGW.  When get text is built into libc, we don't need libintl.   There's another complexity.  I think they expect libiconv to be installed.

I'm going to make -EXIV2_ENABLE_NLS=Off the default for building the bundles.

I'll revisit libiconv on every platform when I have build without NLS.

**Comment by clanmills** [comment]
I've email John and asked him to run the following command.

Here are shared objects on different platforms.  I'm wondering if I should create a zip file for each platform with those objects.  Not sure.  It's easy to say "Not our issue".  Or perhaps we should use static linking.

### MinGW

```
library=C:\msys64\usr\bin\msys-gcc_s-seh-1.dll                                                                                                                                                              
library=C:\msys64\usr\bin\msys-stdc++-6.dll                                                                                                                                                                 
library=C:\msys64\usr\bin\msys-2.0.dll                                                                                                                                                                      
library=C:\msys64\usr\bin\msys-expat-1.dll                                                                                                                                                                  
library=C:\msys64\usr\bin\msys-iconv-2.dll                                                                                                                                                                  
library=C:\msys64\usr\bin\msys-z.dll                                                                                                                                                                        
```

### Cygwin

```
library=C:\cygwin64\bin\cyggcc_s-seh-1.dll                                                                                                                                                                  
library=C:\cygwin64\bin\cygwin1.dll                                                                                                                                                                         
library=C:\cygwin64\bin\cygstdc++-6.dll                                                                                                                                                                     
library=C:\cygwin64\bin\cygexpat-1.dll                                                                                                                                                                      
library=C:\cygwin64\usr\local\bin\cygiconv-2.dll                                                                                                                                                            
```

### 2017msvc

Nothing.  expat and lib must be statically linked.

### Ubuntu

```
library=/lib/x86_64-linux-gnu/libm-2.27.so
library=/lib/x86_64-linux-gnu/libpthread-2.27.so
library=/lib/x86_64-linux-gnu/libexpat.so.1.6.7
library=/lib/x86_64-linux-gnu/libz.so.1.2.11
library=/lib/x86_64-linux-gnu/libc-2.27.so
library=/lib/x86_64-linux-gnu/libgcc_s.so.1
library=/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
library=/lib/x86_64-linux-gnu/ld-2.27.so   ** Why is this linked ?? **
```

**Comment by clanmills** [comment]
John replied to my email.  Thank You, John, for working with me.

This is being caused by /Library/Frameworks/Mono.framework being installed on his machine.  The Mono Framework is .Net for Unix.  My guess is that it was installed to support another application that has been installed on the Mac.

I used the following script to clean this up.  https://gist.github.com/powerumc/e80bb475117582d7e842

Early in this investigation, I said: 
> FindIntl reports we're linked with Mono 

I've updated cmake/findDepenancies.cmake with the following code:
```
if (EXIV2_ENABLE_NLS)
    find_package(Intl REQUIRED)
    message(STATUS Intl_FOUND        ${Intl_FOUND})
    message(STATUS Intl_INCLUDE_DIRS ${Intl_INCLUDE_DIRS})
    message(STATUS Intl_LIBRARIES    ${Intl_LIBRARIES})
endif( )
```

And it reports:
```
Intl_FOUNDTRUE
Intl_INCLUDE_DIRS/Library/Frameworks/Mono.framework/Headers
Intl_LIBRARIES
```

FindIntl.cmake has failed to set Intl_LIBRARIES.  I'll report a bug to Kitware.
```
222 rmills@rmillsmm-macosx:/Library/Frameworks/Mono.framework $ find . -name libintl.8.dylib -o -name libintl.h
./Versions/5.18.1/include/libintl.h
./Versions/5.18.1/lib/libintl.8.dylib
223 rmills@rmillsmm-macosx:/Library/Frameworks/Mono.framework $ 
```
For the moment, the obvious work-around it to build without NLS support:
```
225 rmills@rmillsmm-macosx:~/gnu/github/exiv2/0.27-maintenance/build $ rm -rf CM*
226 rmills@rmillsmm-macosx:~/gnu/github/exiv2/0.27-maintenance/build $ cmake .. -DEXIV2_ENABLE_NLS=Off 
```

**Comment by clanmills** [comment]
This is a known CMake bug: https://gitlab.kitware.com/cmake/cmake/issues/18921

Case closed.  We know the cause.  There are two work-arounds:
1) cmake .. -DEXIV2_ENABLE_NLS=Off
2) Uninstall Mono with  https://gist.github.com/powerumc/e80bb475117582d7e842

Work-around 1 was provided to John several days ago.
Work-around 2 has been discovered by this investigation.

**Comment by clanmills** [comment]
Another couple of work-arounds:
3.  $ cmake -DCMAKE_FRAMEWORK_PATH=NEVER ..
4. In `cmake/findDepedancies.cmake`:
```
if (APPLE)
     set (CMAKE_FIND_FRAMEWORK NEVER)
endif()
```

I'm going to re-open this case and submit a PR for this and ask @piponazo to review.

I've also observed that we link `-ldl` the dynamic linker for src/version.cpp.  This is no long required.  I'll also submit a PR for that.
