### ISSUE TITLE
Enhancement: Add support for embedded thumbnails in AFPHOTO (Affinity Photo) files

### ISSUE THREAD

**Issue by Bluetopia** [Exiv2/exiv2#986]
The Affinity Photo (AFPHOTO) format, while proprietary, contains an embedded preview that many applications are able to use when displaying a thumbnail for a file. 

With Adobe's move to subscription, a lot of people have been jumping ship to applications like Affinity Photo which offer similar functionality for a reasonable price.

Sample file for testing is attached.

[RedTrillium_01.zip](https://github.com/Exiv2/exiv2/files/3512455/RedTrillium_01.zip)

**Comment by clanmills** [comment]
There are other formats, such as Canon's CR3, waiting to be implemented.  If you're offering to implement this, I'll mentor you.

**Comment by clanmills** [comment]
I'm closing this issue as we don't have the resources to undertake this work.  If a volunteer comes forward, this will be reopened.
