### ISSUE TITLE
Consider using a different regression test suite

### ISSUE THREAD

**Issue by D4N** [Exiv2/exiv2#99]
The current regression test script has some problems for managing it with git:

1. The regressions are added into a single file
2. The test results are added into a single binary file

Both make cherry-picking new commits onto old ones to backport changes quite cumbersome, especially the binary file, as git can't diff binary files. It would be a lot better if we would split the test file into lots of single files where each of them tests one single issue. This would make backporting very easy.

**Comment by clanmills** [comment]
Gosh, this could be tough.  We should ensure that all "reference" files (such as bugfixes-test.out) is ascii.  The main "culprit" here is bugfixes-test.sh which is monolithic monster.  It would be better to have little scripts for every fix: bugfix-1234.sh with their own reference file bugfix-1234.out

So bugfixes-test.sh would drive individual scripts.  Easy stuff.  You can imagine why I've never given this priority.

**Comment by D4N** [comment]
I'll see if there is an easy way how to split the monolithic monster.

We could also try to use the unit test suite for regression tests.

**Comment by D4N** [comment]
Fixed by #155.
