### ISSUE TITLE
exiv2 doesn't show metadata

### ISSUE THREAD

**Issue by sguillia** [Exiv2/exiv2#996]
Hi

I have a simple PNG file and I'd like to get the orientation metadata of it on an UNIX system.

With exiv2, doesn't work
```
$ exiv2 index.png 
...
index.png: No Exif data found in the file
```

With identify, doesn't work
```
$ identify -verbose index.png | grep Orientation
Orientation: Undefined
```

With exiftool, works
```
$ exiftool index.png | grep Orientation 
Orientation                     : Rotate 270 CW
```

Not sure if it is a bug, but isn't exiv2 supposed to give mo the metadata the same way as exiftool does?

If it's not a bug, why is it so?

**Bug description**
exiv2 doesn't show metadata

**To Reproduce**
Steps to reproduce the behaviour:
1. Build exiv2 from source as described [here](https://github.com/Exiv2/exiv2#21-build-install-use-exiv2-on-a-unix-like-system)
2. Test exiv2 and exiftool on an image with non-horizontal orientation

**Expected behavior**
exiv2 should show metadata, in my case I wanted orientation

**Desktop**
 - OS: Linux
 - Compiler & Version: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)
 - Compilation mode and/or compiler flags: as described in your README

**Additional context**
- I use exiftool 10.10
- The default for `EXIV2_ENABLE_PNG` is `On`

**Comment by clanmills** [comment]
Can you attach the file index.png and I will investigate.

My reaction is say "it's not Exif".  There is a metadata protocol supported by ImageMagick that embeds metadata in PNG files.  However it's distinct from the Exif/XMP/IPTC standards supported by Exiv2.  A user volunteered to implement it a couple of years ago, however it hasn't been done yet!

**Comment by sguillia** [comment]
I can't attach index.png because it's a private image I'm not allowed to share, and I can't "reproduce" the same king of image.

Here is another one which is similar, demo.png:
![demo](https://user-images.githubusercontent.com/15984272/64420653-08a6ba80-d0a0-11e9-9939-7e577a50c3eb.png)

The difference is that exiv2 says there is metadata, but doesn't tell about orientation. This is opposed to index.png where exiv2 says there is no metadata at all.

I took a random PNG file with no metadata
```
$ exiv2 demo.png
demo.png: No Exif data found in the file

$ exiftool demo.png | grep Orien
[nothing]
```

And added metadata with exiftool
```
$ exiftool "-Orientation=Rotate 270 CW" demo.png              
Warning: [minor] Creating non-standard EXIF in PNG - demo.png
    1 image files updated
```

exiv2 says there is metadata, but doesn't tell about orientation.
```
exiv2 demo.png                                
File name       : demo.png
File size       : 2453 Bytes
MIME type       : image/png
Image size      : 229 x 79
Camera make     : 
Camera model    : 
Image timestamp : 
Image number    : 
Exposure time   : 
Aperture        : 
Exposure bias   : 
Flash           : 
Flash bias      : 
Focal length    : 
Subject distance: 
ISO speed       : 
Exposure mode   : 
Metering mode   : 
Macro mode      : 
Image quality   : 
Exif Resolution : 
White balance   : 
Thumbnail       : None
Copyright       : 
Exif comment    : 
```

If I get it right, the orientation here is stored in something that is not EXIF metadata? Is there a name for this "standard"?

Thanks for super fast reply!

**Comment by clanmills** [comment]
Thanks for demo.png.  My "reaction" was correct.  This image doesn't contain Exif/IPTC/Xmp data.  Here's a discussion about this:  https://github.com/Exiv2/exiv2/issues/147

If you're interested in working on this feature, I'm happy to mentor and @tester0077 will test it for you (won't you, Arnold?).

You can inspect the structure of an image with the option _**-pS**_
```
543 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ exiv2 -pS ~/Downloads/64420653-08a6ba80-d0a0-11e9-9939-7e577a50c3eb.png 
STRUCTURE OF PNG FILE: /Users/rmills/Downloads/64420653-08a6ba80-d0a0-11e9-9939-7e577a50c3eb.png
 address | chunk |  length | data                           | checksum
       8 | IHDR  |      13 | .......O....                   | 0x9b2c95c9
      33 | sBIT  |       3 | ...                            | 0xdbe14fe0
      48 | tEXt  |      25 | Software.gnome-screenshot      | 0xef03bf3e
      85 | IDAT  |    2202 | x....P......kO...; ..rH.D"._JJ | 0x21aafbf2
    2299 | IEND  |       0 |                                | 0xae426082
544 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ 
```
A PNG file is a linked list of "Chunks".  Exif metadata is usually stored in a `tEXt` Chunk which is identified with the header `Raw profile type exif`.  Here's a "good" file from our test suite:
```
545 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ exiv2 -pS test/data/imagemagick.png 
STRUCTURE OF PNG FILE: test/data/imagemagick.png
 address | chunk |  length | data                           | checksum
       8 | IHDR  |      13 | ...@........                   | 0x7f775da4
      33 | iCCP  |    1404 | icc..x...i8........af\...w_3.. | 0x363e2409
    1449 | sBIT  |       3 | ...                            | 0xdbe14fe0
    1464 | zTXt  |      87 | Software..x...A.. ......B....} | 0xcd30861a
    1563 | tEXt  |   24482 | Raw profile type exif..exif.   | 0x81743ec0  <--- Exif
   26057 | tEXt  |     471 | Raw profile type iptc..iptc.   | 0x2db5653b  <--- IPTC
   26540 | IDAT  |    8192 | x...Y.$Wv&v.{.{l.T.......[w.=m | 0x1b2c97be
...
  144754 | IEND  |       0 |                                | 0xae426082
546 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ 
```
I don't think there's any orientation data in demo.png:
```
551 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ exiftool ~/Downloads/64420653-08a6ba80-d0a0-11e9-9939-7e577a50c3eb.png  | grep -i orient
552 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ 
```
You can use the exiftool -v3 option on index.png to discover how it knows about Orientation
```
546 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ exiftool -v3 ~/Downloads/64420653-08a6ba80-d0a0-11e9-9939-7e577a50c3eb.png 
  ExifToolVersion = 11.20
...
  MIMEType = image/png
PNG IHDR (13 bytes):
      0010: 00 00 00 e5 00 00 00 4f 08 02 00 00 00          [.......O.....]
  + [BinaryData directory, 13 bytes]
  | ImageWidth = 229
...
PNG sBIT (3 bytes):
      0029: 08 08 08                                        [...]
  SignificantBits = ...
  - Tag 'sBIT' (3 bytes):
      0000: 08 08 08                                        [...]
PNG tEXt (25 bytes):
      0038: 53 6f 66 74 77 61 72 65 00 67 6e 6f 6d 65 2d 73 [Software.gnome-s]
      0048: 63 72 65 65 6e 73 68 6f 74                      [creenshot]
  | Software = gnome-screenshot
  | - Tag 'Software' (16 bytes):
  |     0000: 67 6e 6f 6d 65 2d 73 63 72 65 65 6e 73 68 6f 74 [gnome-screenshot]
PNG IDAT (1 chunk, total 2202 bytes)
PNG IEND (end of image)
547 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ 
```

I'm going to close this issue.  However I'll reopen this if you wish to discuss it further.
