### ISSUE TITLE
Add lens support for Sigma 17-70mm F2.8-4 Contemporary

### ISSUE THREAD

**Issue by kiekerjan** [Exiv2/exiv2#998]
Please add an entry for the "Sigma 17-70mm F2.8-4 DC Macro HSM Contemporary" lens to the minoltamn_int.cpp file. Yes, I know there is already an entry for the "Sigma 17-70mm F2.8-4 DC Macro HSM" but these are different lenses. For instance the elements/groups count is different. Also, lensfun has a different set of corrections for each lens.

Unfortunately, both lenses use id 128 :(  This probably means the [exiv file](https://dev.exiv2.org/projects/exiv2/wiki/Lens_Recognition_in_Exiv2_v026_(and_later)/) needs to be used.

**Comment by D4N** [comment]
kiekerjan <notifications@github.com> writes:

> Please add an entry for the "Sigma 17-70mm F2.8-4 DC Macro HSM Contemporary" lens to the minoltamn_int.cpp file. Yes, I know there is already an entry for the "Sigma 17-70mm F2.8-4 DC Macro HSM" but these are different lenses. For instance the elements/groups count is different. Also, lensfun has a different set of corrections for each lens.
>
> Unfortunately, both lenses use id 128 :(  This probably means the
> [exiv
> file](https://dev.exiv2.org/projects/exiv2/wiki/Lens_Recognition_in_Exiv2_v026_(and_later)/)
> needs to be used.

So you have a solution for your problem?

We'd need to add **another** workaround for a lens, which we try to
avoid as lens recognition is turning into a nightmare.

**Comment by D4N** [comment]
kiekerjan <notifications@github.com> writes:

> I'm sorry. Did I misread the wiki link? I was under the impression that for that mechanism to work, an entry needed to be present in the lens database. Are you saying that the contents of the .exiv2 file can be completely customized?
>

You put this file into your home directory and that's it.

**Comment by clanmills** [comment]
Put this into ~/.exiv2 and you should be good.
```
$ cat ~/.exiv2 
[minolta]
128=Sigma 17-70mm F2.8-4 DC Macro HSM Contemporary
```

If that doesn't fix it, please provide sample image (lens cap on, any resolution) and I will investigate.

**Comment by clanmills** [comment]
Did this work for you?  Can I close this issue?

**Comment by kiekerjan** [comment]
Yes, this will work. I was mistakenly under the impression that a lensid entry was still necessary. Thank you for your work.

**Comment by clanmills** [comment]
Great.  Thanks for getting back to me.

Lens recognition has caused pain because the lens definition isn't stored in the metadata!  There are clues (such as LensID in the MakerNote), however even that is often ambiguous.  The same LensID can be used by more than one lens.
